package com.pltfm.cms.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.pltfm.cms.dao.CmsAppManageDAO;
import com.pltfm.cms.vobject.CmsAppManage;
import com.pltfm.cms.vobject.CmsAppManageExample;

import org.springframework.stereotype.Component;

import java.sql.SQLException;
import java.util.List;

import javax.annotation.Resource;

/**
 * 手机端应用管理DAO实现类
 *
 * @author cjm
 * @since 2014-4-18
 */
@Component(value = "cmsAppManageDAO")
public class CmsAppManageDAOImpl implements CmsAppManageDAO {

    /**
     * 数据库操作对象
     */
    @Resource(name = "sqlMapClient")
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    public int countByExample(CmsAppManageExample example) throws SQLException {
        Integer count = (Integer) sqlMapClient.queryForObject("CMS_APP_MANAGE.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    public int deleteByExample(CmsAppManageExample example) throws SQLException {
        int rows = sqlMapClient.delete("CMS_APP_MANAGE.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    public int deleteByPrimaryKey(Integer appmanageId) throws SQLException {
        CmsAppManage key = new CmsAppManage();
        key.setAppmanageId(appmanageId);
        int rows = sqlMapClient.delete("CMS_APP_MANAGE.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    public void insert(CmsAppManage record) throws SQLException {
        sqlMapClient.insert("CMS_APP_MANAGE.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    public void insertSelective(CmsAppManage record) throws SQLException {
        sqlMapClient.insert("CMS_APP_MANAGE.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    public List selectByExample(CmsAppManageExample example) throws SQLException {
        List list = sqlMapClient.queryForList("CMS_APP_MANAGE.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    public CmsAppManage selectByPrimaryKey(Integer appmanageId) throws SQLException {
        CmsAppManage key = new CmsAppManage();
        key.setAppmanageId(appmanageId);
        CmsAppManage record = (CmsAppManage) sqlMapClient.queryForObject("CMS_APP_MANAGE.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    public int updateByExampleSelective(CmsAppManage record, CmsAppManageExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("CMS_APP_MANAGE.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    public int updateByExample(CmsAppManage record, CmsAppManageExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("CMS_APP_MANAGE.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    public int updateByPrimaryKeySelective(CmsAppManage record) throws SQLException {
        int rows = sqlMapClient.update("CMS_APP_MANAGE.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    public int updateByPrimaryKey(CmsAppManage record) throws SQLException {
        int rows = sqlMapClient.update("CMS_APP_MANAGE.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * 窗口数据信息总数量
     *
     * @param cmsWindowData 窗口数据信息实体
     * @throws SQLException 异常
     * @return 返回值
     */
    @Override
    public Integer countByCmsAppManage(CmsAppManage cmsAppManage)
            throws SQLException {
        Integer count = (Integer) sqlMapClient.queryForObject(
                "CMS_APP_MANAGE.abatorgenerated_countByCmsAppManage", cmsAppManage);
        return count;
    }

    /**
     * 查询同一应用名称、版本名、版本号 记录数
     */
    @Override
    public Integer countByNameAndVer(CmsAppManage cmsAppManage) throws SQLException {
        Integer count = (Integer) sqlMapClient.queryForObject(
                "CMS_APP_MANAGE.abatorgenerated_countByNameAndVer", cmsAppManage);
        return count;
    }

    @Override
    public List queryForPage(CmsAppManage cmsAppManage) throws SQLException {
        return sqlMapClient.queryForList("CMS_APP_MANAGE.abatorgenerated_pageByAppManage", cmsAppManage);
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    private static class UpdateByExampleParms extends CmsAppManageExample {
        private Object record;

        public UpdateByExampleParms(Object record, CmsAppManageExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    public SqlMapClient getSqlMapClient() {
        return sqlMapClient;
    }

    public void setSqlMapClient(SqlMapClient sqlMapClient) {
        this.sqlMapClient = sqlMapClient;
    }


}