package com.pltfm.app.vobject;

import java.math.BigDecimal;
import java.util.Date;
/**
 * 
 * @author Administrator
 *回复咨询审核表
 */
public class FilterField implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 5064283861949105976L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FILTER_FIELD.FIELD_ID
     *
     * @ibatorgenerated Tue Aug 06 09:09:03 CST 2013
     */
    private BigDecimal fieldId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FILTER_FIELD.FIELD_NAME
     *
     * @ibatorgenerated Tue Aug 06 09:09:03 CST 2013
     */
    private String fieldName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FILTER_FIELD.LAST_UPDATE_PERSON
     *
     * @ibatorgenerated Tue Aug 06 09:09:03 CST 2013
     */
    private String lastUpdatePerson;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column FILTER_FIELD.LAST_UPDATE_DATE
     *
     * @ibatorgenerated Tue Aug 06 09:09:03 CST 2013
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FILTER_FIELD.FIELD_ID
     *
     * @return the value of FILTER_FIELD.FIELD_ID
     *
     * @ibatorgenerated Tue Aug 06 09:09:03 CST 2013
     */
    public BigDecimal getFieldId() {
        return fieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FILTER_FIELD.FIELD_ID
     *
     * @param fieldId the value for FILTER_FIELD.FIELD_ID
     *
     * @ibatorgenerated Tue Aug 06 09:09:03 CST 2013
     */
    public void setFieldId(BigDecimal fieldId) {
        this.fieldId = fieldId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FILTER_FIELD.FIELD_NAME
     *
     * @return the value of FILTER_FIELD.FIELD_NAME
     *
     * @ibatorgenerated Tue Aug 06 09:09:03 CST 2013
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FILTER_FIELD.FIELD_NAME
     *
     * @param fieldName the value for FILTER_FIELD.FIELD_NAME
     *
     * @ibatorgenerated Tue Aug 06 09:09:03 CST 2013
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FILTER_FIELD.LAST_UPDATE_PERSON
     *
     * @return the value of FILTER_FIELD.LAST_UPDATE_PERSON
     *
     * @ibatorgenerated Tue Aug 06 09:09:03 CST 2013
     */
    public String getLastUpdatePerson() {
        return lastUpdatePerson;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FILTER_FIELD.LAST_UPDATE_PERSON
     *
     * @param lastUpdatePerson the value for FILTER_FIELD.LAST_UPDATE_PERSON
     *
     * @ibatorgenerated Tue Aug 06 09:09:03 CST 2013
     */
    public void setLastUpdatePerson(String lastUpdatePerson) {
        this.lastUpdatePerson = lastUpdatePerson;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column FILTER_FIELD.LAST_UPDATE_DATE
     *
     * @return the value of FILTER_FIELD.LAST_UPDATE_DATE
     *
     * @ibatorgenerated Tue Aug 06 09:09:03 CST 2013
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column FILTER_FIELD.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for FILTER_FIELD.LAST_UPDATE_DATE
     *
     * @ibatorgenerated Tue Aug 06 09:09:03 CST 2013
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}