package com.pltfm.app.vobject;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;


public class ProductDraftExample implements java.io.Serializable {
	public String userId;
	//用于模糊查询的品牌名
	private String searchBrandName;

	//用于所属商家的查询
	private String supplierNameForSearch;
	
	private Long mCategoryId;
	
	private Long bCategoryId;
	
	
	private String categoryAudit;
    /**
	 * 
	 */
	private static final long serialVersionUID = 7879072555030719686L;

	 /**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table PRODUCT_DRAFT
	 * @ibatorgenerated  Tue Dec 03 08:55:29 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table PRODUCT_DRAFT
	 * @ibatorgenerated  Tue Dec 03 08:55:29 CST 2013
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_DRAFT
	 * @ibatorgenerated  Tue Dec 03 08:55:29 CST 2013
	 */
	public ProductDraftExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_DRAFT
	 * @ibatorgenerated  Tue Dec 03 08:55:29 CST 2013
	 */
	protected ProductDraftExample(ProductDraftExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_DRAFT
	 * @ibatorgenerated  Tue Dec 03 08:55:29 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_DRAFT
	 * @ibatorgenerated  Tue Dec 03 08:55:29 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_DRAFT
	 * @ibatorgenerated  Tue Dec 03 08:55:29 CST 2013
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_DRAFT
	 * @ibatorgenerated  Tue Dec 03 08:55:29 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_DRAFT
	 * @ibatorgenerated  Tue Dec 03 08:55:29 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_DRAFT
	 * @ibatorgenerated  Tue Dec 03 08:55:29 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table PRODUCT_DRAFT
	 * @ibatorgenerated  Tue Dec 03 08:55:29 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table PRODUCT_DRAFT
	 * @ibatorgenerated  Tue Dec 03 08:55:29 CST 2013
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List dateList = new ArrayList();
			Iterator iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(((Date) iter.next()).getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andProductIdIsNull() {
			addCriterion("PRODUCT_ID is null");
			return this;
		}

		public Criteria andProductIdIsNotNull() {
			addCriterion("PRODUCT_ID is not null");
			return this;
		}

		public Criteria andProductIdEqualTo(Long value) {
			addCriterion("PRODUCT_ID =", value, "productId");
			return this;
		}

		public Criteria andProductIdNotEqualTo(Long value) {
			addCriterion("PRODUCT_ID <>", value, "productId");
			return this;
		}

		public Criteria andProductIdGreaterThan(Long value) {
			addCriterion("PRODUCT_ID >", value, "productId");
			return this;
		}

		public Criteria andProductIdGreaterThanOrEqualTo(Long value) {
			addCriterion("PRODUCT_ID >=", value, "productId");
			return this;
		}

		public Criteria andProductIdLessThan(Long value) {
			addCriterion("PRODUCT_ID <", value, "productId");
			return this;
		}

		public Criteria andProductIdLessThanOrEqualTo(Long value) {
			addCriterion("PRODUCT_ID <=", value, "productId");
			return this;
		}

		public Criteria andProductIdIn(List values) {
			addCriterion("PRODUCT_ID in", values, "productId");
			return this;
		}

		public Criteria andProductIdNotIn(List values) {
			addCriterion("PRODUCT_ID not in", values, "productId");
			return this;
		}

		public Criteria andProductIdBetween(Long value1, Long value2) {
			addCriterion("PRODUCT_ID between", value1, value2, "productId");
			return this;
		}

		public Criteria andProductIdNotBetween(Long value1,
				Long value2) {
			addCriterion("PRODUCT_ID not between", value1, value2, "productId");
			return this;
		}

		public Criteria andCategoryIdIsNull() {
			addCriterion("CATEGORY_ID is null");
			return this;
		}

		public Criteria andCategoryIdIsNotNull() {
			addCriterion("CATEGORY_ID is not null");
			return this;
		}

		public Criteria andCategoryIdEqualTo(Long value) {
			addCriterion("CATEGORY_ID =", value, "categoryId");
			return this;
		}

		public Criteria andCategoryIdNotEqualTo(Long value) {
			addCriterion("CATEGORY_ID <>", value, "categoryId");
			return this;
		}

		public Criteria andCategoryIdGreaterThan(Long value) {
			addCriterion("CATEGORY_ID >", value, "categoryId");
			return this;
		}

		public Criteria andCategoryIdGreaterThanOrEqualTo(Long value) {
			addCriterion("CATEGORY_ID >=", value, "categoryId");
			return this;
		}

		public Criteria andCategoryIdLessThan(Long value) {
			addCriterion("CATEGORY_ID <", value, "categoryId");
			return this;
		}

		public Criteria andCategoryIdLessThanOrEqualTo(Long value) {
			addCriterion("CATEGORY_ID <=", value, "categoryId");
			return this;
		}

		public Criteria andCategoryIdIn(List values) {
			addCriterion("CATEGORY_ID in", values, "categoryId");
			return this;
		}

		public Criteria andCategoryIdNotIn(List values) {
			addCriterion("CATEGORY_ID not in", values, "categoryId");
			return this;
		}

		public Criteria andCategoryIdBetween(Long value1,
				Long value2) {
			addCriterion("CATEGORY_ID between", value1, value2, "categoryId");
			return this;
		}

		public Criteria andCategoryIdNotBetween(Long value1,
				Long value2) {
			addCriterion("CATEGORY_ID not between", value1, value2,
					"categoryId");
			return this;
		}

		public Criteria andCategoryNameIsNull() {
			addCriterion("CATEGORY_NAME is null");
			return this;
		}

		public Criteria andCategoryNameIsNotNull() {
			addCriterion("CATEGORY_NAME is not null");
			return this;
		}

		public Criteria andCategoryNameEqualTo(String value) {
			addCriterion("CATEGORY_NAME =", value, "categoryName");
			return this;
		}

		public Criteria andCategoryNameNotEqualTo(String value) {
			addCriterion("CATEGORY_NAME <>", value, "categoryName");
			return this;
		}

		public Criteria andCategoryNameGreaterThan(String value) {
			addCriterion("CATEGORY_NAME >", value, "categoryName");
			return this;
		}

		public Criteria andCategoryNameGreaterThanOrEqualTo(String value) {
			addCriterion("CATEGORY_NAME >=", value, "categoryName");
			return this;
		}

		public Criteria andCategoryNameLessThan(String value) {
			addCriterion("CATEGORY_NAME <", value, "categoryName");
			return this;
		}

		public Criteria andCategoryNameLessThanOrEqualTo(String value) {
			addCriterion("CATEGORY_NAME <=", value, "categoryName");
			return this;
		}

		public Criteria andCategoryNameLike(String value) {
			addCriterion("CATEGORY_NAME like", value, "categoryName");
			return this;
		}

		public Criteria andCategoryNameNotLike(String value) {
			addCriterion("CATEGORY_NAME not like", value, "categoryName");
			return this;
		}

		public Criteria andCategoryNameIn(List values) {
			addCriterion("CATEGORY_NAME in", values, "categoryName");
			return this;
		}

		public Criteria andCategoryNameNotIn(List values) {
			addCriterion("CATEGORY_NAME not in", values, "categoryName");
			return this;
		}

		public Criteria andCategoryNameBetween(String value1, String value2) {
			addCriterion("CATEGORY_NAME between", value1, value2,
					"categoryName");
			return this;
		}

		public Criteria andCategoryNameNotBetween(String value1, String value2) {
			addCriterion("CATEGORY_NAME not between", value1, value2,
					"categoryName");
			return this;
		}

		public Criteria andProductNameIsNull() {
			addCriterion("PRODUCT_NAME is null");
			return this;
		}

		public Criteria andProductNameIsNotNull() {
			addCriterion("PRODUCT_NAME is not null");
			return this;
		}

		public Criteria andProductNameEqualTo(String value) {
			addCriterion("PRODUCT_NAME =", value, "productName");
			return this;
		}

		public Criteria andProductNameNotEqualTo(String value) {
			addCriterion("PRODUCT_NAME <>", value, "productName");
			return this;
		}

		public Criteria andProductNameGreaterThan(String value) {
			addCriterion("PRODUCT_NAME >", value, "productName");
			return this;
		}

		public Criteria andProductNameGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NAME >=", value, "productName");
			return this;
		}

		public Criteria andProductNameLessThan(String value) {
			addCriterion("PRODUCT_NAME <", value, "productName");
			return this;
		}

		public Criteria andProductNameLessThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NAME <=", value, "productName");
			return this;
		}

		public Criteria andProductNameLike(String value) {
			addCriterion("PRODUCT_NAME like", value, "productName");
			return this;
		}

		public Criteria andProductNameNotLike(String value) {
			addCriterion("PRODUCT_NAME not like", value, "productName");
			return this;
		}

		public Criteria andProductNameIn(List values) {
			addCriterion("PRODUCT_NAME in", values, "productName");
			return this;
		}

		public Criteria andProductNameNotIn(List values) {
			addCriterion("PRODUCT_NAME not in", values, "productName");
			return this;
		}

		public Criteria andProductNameBetween(String value1, String value2) {
			addCriterion("PRODUCT_NAME between", value1, value2, "productName");
			return this;
		}

		public Criteria andProductNameNotBetween(String value1, String value2) {
			addCriterion("PRODUCT_NAME not between", value1, value2,
					"productName");
			return this;
		}

		public Criteria andProductNoIsNull() {
			addCriterion("PRODUCT_NO is null");
			return this;
		}

		public Criteria andProductNoIsNotNull() {
			addCriterion("PRODUCT_NO is not null");
			return this;
		}

		public Criteria andProductNoEqualTo(String value) {
			addCriterion("PRODUCT_NO =", value, "productNo");
			return this;
		}

		public Criteria andProductNoNotEqualTo(String value) {
			addCriterion("PRODUCT_NO <>", value, "productNo");
			return this;
		}

		public Criteria andProductNoGreaterThan(String value) {
			addCriterion("PRODUCT_NO >", value, "productNo");
			return this;
		}

		public Criteria andProductNoGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NO >=", value, "productNo");
			return this;
		}

		public Criteria andProductNoLessThan(String value) {
			addCriterion("PRODUCT_NO <", value, "productNo");
			return this;
		}

		public Criteria andProductNoLessThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NO <=", value, "productNo");
			return this;
		}

		public Criteria andProductNoLike(String value) {
			addCriterion("PRODUCT_NO like", value, "productNo");
			return this;
		}

		public Criteria andProductNoNotLike(String value) {
			addCriterion("PRODUCT_NO not like", value, "productNo");
			return this;
		}

		public Criteria andProductNoIn(List values) {
			addCriterion("PRODUCT_NO in", values, "productNo");
			return this;
		}

		public Criteria andProductNoNotIn(List values) {
			addCriterion("PRODUCT_NO not in", values, "productNo");
			return this;
		}

		public Criteria andProductNoBetween(String value1, String value2) {
			addCriterion("PRODUCT_NO between", value1, value2, "productNo");
			return this;
		}

		public Criteria andProductNoNotBetween(String value1, String value2) {
			addCriterion("PRODUCT_NO not between", value1, value2, "productNo");
			return this;
		}

		public Criteria andPackListingIsNull() {
			addCriterion("PACK_LISTING is null");
			return this;
		}

		public Criteria andPackListingIsNotNull() {
			addCriterion("PACK_LISTING is not null");
			return this;
		}

		public Criteria andPackListingEqualTo(String value) {
			addCriterion("PACK_LISTING =", value, "packListing");
			return this;
		}

		public Criteria andPackListingNotEqualTo(String value) {
			addCriterion("PACK_LISTING <>", value, "packListing");
			return this;
		}

		public Criteria andPackListingGreaterThan(String value) {
			addCriterion("PACK_LISTING >", value, "packListing");
			return this;
		}

		public Criteria andPackListingGreaterThanOrEqualTo(String value) {
			addCriterion("PACK_LISTING >=", value, "packListing");
			return this;
		}

		public Criteria andPackListingLessThan(String value) {
			addCriterion("PACK_LISTING <", value, "packListing");
			return this;
		}

		public Criteria andPackListingLessThanOrEqualTo(String value) {
			addCriterion("PACK_LISTING <=", value, "packListing");
			return this;
		}

		public Criteria andPackListingLike(String value) {
			addCriterion("PACK_LISTING like", value, "packListing");
			return this;
		}

		public Criteria andPackListingNotLike(String value) {
			addCriterion("PACK_LISTING not like", value, "packListing");
			return this;
		}

		public Criteria andPackListingIn(List values) {
			addCriterion("PACK_LISTING in", values, "packListing");
			return this;
		}

		public Criteria andPackListingNotIn(List values) {
			addCriterion("PACK_LISTING not in", values, "packListing");
			return this;
		}

		public Criteria andPackListingBetween(String value1, String value2) {
			addCriterion("PACK_LISTING between", value1, value2, "packListing");
			return this;
		}

		public Criteria andPackListingNotBetween(String value1, String value2) {
			addCriterion("PACK_LISTING not between", value1, value2,
					"packListing");
			return this;
		}

		public Criteria andProductTitleIsNull() {
			addCriterion("PRODUCT_TITLE is null");
			return this;
		}

		public Criteria andProductTitleIsNotNull() {
			addCriterion("PRODUCT_TITLE is not null");
			return this;
		}

		public Criteria andProductTitleEqualTo(String value) {
			addCriterion("PRODUCT_TITLE =", value, "productTitle");
			return this;
		}

		public Criteria andProductTitleNotEqualTo(String value) {
			addCriterion("PRODUCT_TITLE <>", value, "productTitle");
			return this;
		}

		public Criteria andProductTitleGreaterThan(String value) {
			addCriterion("PRODUCT_TITLE >", value, "productTitle");
			return this;
		}

		public Criteria andProductTitleGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCT_TITLE >=", value, "productTitle");
			return this;
		}

		public Criteria andProductTitleLessThan(String value) {
			addCriterion("PRODUCT_TITLE <", value, "productTitle");
			return this;
		}

		public Criteria andProductTitleLessThanOrEqualTo(String value) {
			addCriterion("PRODUCT_TITLE <=", value, "productTitle");
			return this;
		}

		public Criteria andProductTitleLike(String value) {
			addCriterion("PRODUCT_TITLE like", value, "productTitle");
			return this;
		}

		public Criteria andProductTitleNotLike(String value) {
			addCriterion("PRODUCT_TITLE not like", value, "productTitle");
			return this;
		}

		public Criteria andProductTitleIn(List values) {
			addCriterion("PRODUCT_TITLE in", values, "productTitle");
			return this;
		}

		public Criteria andProductTitleNotIn(List values) {
			addCriterion("PRODUCT_TITLE not in", values, "productTitle");
			return this;
		}

		public Criteria andProductTitleBetween(String value1, String value2) {
			addCriterion("PRODUCT_TITLE between", value1, value2,
					"productTitle");
			return this;
		}

		public Criteria andProductTitleNotBetween(String value1, String value2) {
			addCriterion("PRODUCT_TITLE not between", value1, value2,
					"productTitle");
			return this;
		}

		public Criteria andKeywordIsNull() {
			addCriterion("KEYWORD is null");
			return this;
		}

		public Criteria andKeywordIsNotNull() {
			addCriterion("KEYWORD is not null");
			return this;
		}

		public Criteria andKeywordEqualTo(String value) {
			addCriterion("KEYWORD =", value, "keyword");
			return this;
		}

		public Criteria andKeywordNotEqualTo(String value) {
			addCriterion("KEYWORD <>", value, "keyword");
			return this;
		}

		public Criteria andKeywordGreaterThan(String value) {
			addCriterion("KEYWORD >", value, "keyword");
			return this;
		}

		public Criteria andKeywordGreaterThanOrEqualTo(String value) {
			addCriterion("KEYWORD >=", value, "keyword");
			return this;
		}

		public Criteria andKeywordLessThan(String value) {
			addCriterion("KEYWORD <", value, "keyword");
			return this;
		}

		public Criteria andKeywordLessThanOrEqualTo(String value) {
			addCriterion("KEYWORD <=", value, "keyword");
			return this;
		}

		public Criteria andKeywordLike(String value) {
			addCriterion("KEYWORD like", value, "keyword");
			return this;
		}

		public Criteria andKeywordNotLike(String value) {
			addCriterion("KEYWORD not like", value, "keyword");
			return this;
		}

		public Criteria andKeywordIn(List values) {
			addCriterion("KEYWORD in", values, "keyword");
			return this;
		}

		public Criteria andKeywordNotIn(List values) {
			addCriterion("KEYWORD not in", values, "keyword");
			return this;
		}

		public Criteria andKeywordBetween(String value1, String value2) {
			addCriterion("KEYWORD between", value1, value2, "keyword");
			return this;
		}

		public Criteria andKeywordNotBetween(String value1, String value2) {
			addCriterion("KEYWORD not between", value1, value2, "keyword");
			return this;
		}

		public Criteria andBrandIdIsNull() {
			addCriterion("BRAND_ID is null");
			return this;
		}

		public Criteria andBrandIdIsNotNull() {
			addCriterion("BRAND_ID is not null");
			return this;
		}

		public Criteria andBrandIdEqualTo(Long value) {
			addCriterion("BRAND_ID =", value, "brandId");
			return this;
		}

		public Criteria andBrandIdNotEqualTo(Long value) {
			addCriterion("BRAND_ID <>", value, "brandId");
			return this;
		}

		public Criteria andBrandIdGreaterThan(Long value) {
			addCriterion("BRAND_ID >", value, "brandId");
			return this;
		}

		public Criteria andBrandIdGreaterThanOrEqualTo(Long value) {
			addCriterion("BRAND_ID >=", value, "brandId");
			return this;
		}

		public Criteria andBrandIdLessThan(Long value) {
			addCriterion("BRAND_ID <", value, "brandId");
			return this;
		}

		public Criteria andBrandIdLessThanOrEqualTo(Long value) {
			addCriterion("BRAND_ID <=", value, "brandId");
			return this;
		}

		public Criteria andBrandIdIn(List values) {
			addCriterion("BRAND_ID in", values, "brandId");
			return this;
		}

		public Criteria andBrandIdNotIn(List values) {
			addCriterion("BRAND_ID not in", values, "brandId");
			return this;
		}

		public Criteria andBrandIdBetween(Long value1, Long value2) {
			addCriterion("BRAND_ID between", value1, value2, "brandId");
			return this;
		}

		public Criteria andBrandIdNotBetween(Long value1,
				Long value2) {
			addCriterion("BRAND_ID not between", value1, value2, "brandId");
			return this;
		}

		public Criteria andBrandNameIsNull() {
			addCriterion("BRAND_NAME is null");
			return this;
		}

		public Criteria andBrandNameIsNotNull() {
			addCriterion("BRAND_NAME is not null");
			return this;
		}

		public Criteria andBrandNameEqualTo(String value) {
			addCriterion("BRAND_NAME =", value, "brandName");
			return this;
		}

		public Criteria andBrandNameNotEqualTo(String value) {
			addCriterion("BRAND_NAME <>", value, "brandName");
			return this;
		}

		public Criteria andBrandNameGreaterThan(String value) {
			addCriterion("BRAND_NAME >", value, "brandName");
			return this;
		}

		public Criteria andBrandNameGreaterThanOrEqualTo(String value) {
			addCriterion("BRAND_NAME >=", value, "brandName");
			return this;
		}

		public Criteria andBrandNameLessThan(String value) {
			addCriterion("BRAND_NAME <", value, "brandName");
			return this;
		}

		public Criteria andBrandNameLessThanOrEqualTo(String value) {
			addCriterion("BRAND_NAME <=", value, "brandName");
			return this;
		}

		public Criteria andBrandNameLike(String value) {
			addCriterion("BRAND_NAME like", value, "brandName");
			return this;
		}

		public Criteria andBrandNameNotLike(String value) {
			addCriterion("BRAND_NAME not like", value, "brandName");
			return this;
		}

		public Criteria andBrandNameIn(List values) {
			addCriterion("BRAND_NAME in", values, "brandName");
			return this;
		}

		public Criteria andBrandNameNotIn(List values) {
			addCriterion("BRAND_NAME not in", values, "brandName");
			return this;
		}

		public Criteria andBrandNameBetween(String value1, String value2) {
			addCriterion("BRAND_NAME between", value1, value2, "brandName");
			return this;
		}

		public Criteria andBrandNameNotBetween(String value1, String value2) {
			addCriterion("BRAND_NAME not between", value1, value2, "brandName");
			return this;
		}

		public Criteria andDrugCateIdIsNull() {
			addCriterion("DRUG_CATE_ID is null");
			return this;
		}

		public Criteria andDrugCateIdIsNotNull() {
			addCriterion("DRUG_CATE_ID is not null");
			return this;
		}

		public Criteria andDrugCateIdEqualTo(Long value) {
			addCriterion("DRUG_CATE_ID =", value, "drugCateId");
			return this;
		}

		public Criteria andDrugCateIdNotEqualTo(Long value) {
			addCriterion("DRUG_CATE_ID <>", value, "drugCateId");
			return this;
		}

		public Criteria andDrugCateIdGreaterThan(Long value) {
			addCriterion("DRUG_CATE_ID >", value, "drugCateId");
			return this;
		}

		public Criteria andDrugCateIdGreaterThanOrEqualTo(Long value) {
			addCriterion("DRUG_CATE_ID >=", value, "drugCateId");
			return this;
		}

		public Criteria andDrugCateIdLessThan(Long value) {
			addCriterion("DRUG_CATE_ID <", value, "drugCateId");
			return this;
		}

		public Criteria andDrugCateIdLessThanOrEqualTo(Long value) {
			addCriterion("DRUG_CATE_ID <=", value, "drugCateId");
			return this;
		}

		public Criteria andDrugCateIdIn(List values) {
			addCriterion("DRUG_CATE_ID in", values, "drugCateId");
			return this;
		}

		public Criteria andDrugCateIdNotIn(List values) {
			addCriterion("DRUG_CATE_ID not in", values, "drugCateId");
			return this;
		}

		public Criteria andDrugCateIdBetween(Long value1,
				Long value2) {
			addCriterion("DRUG_CATE_ID between", value1, value2, "drugCateId");
			return this;
		}

		public Criteria andDrugCateIdNotBetween(Long value1,
				Long value2) {
			addCriterion("DRUG_CATE_ID not between", value1, value2,
					"drugCateId");
			return this;
		}

		public Criteria andDrugCateCodeIsNull() {
			addCriterion("DRUG_CATE_CODE is null");
			return this;
		}

		public Criteria andDrugCateCodeIsNotNull() {
			addCriterion("DRUG_CATE_CODE is not null");
			return this;
		}

		public Criteria andDrugCateCodeEqualTo(String value) {
			addCriterion("DRUG_CATE_CODE =", value, "drugCateCode");
			return this;
		}

		public Criteria andDrugCateCodeNotEqualTo(String value) {
			addCriterion("DRUG_CATE_CODE <>", value, "drugCateCode");
			return this;
		}

		public Criteria andDrugCateCodeGreaterThan(String value) {
			addCriterion("DRUG_CATE_CODE >", value, "drugCateCode");
			return this;
		}

		public Criteria andDrugCateCodeGreaterThanOrEqualTo(String value) {
			addCriterion("DRUG_CATE_CODE >=", value, "drugCateCode");
			return this;
		}

		public Criteria andDrugCateCodeLessThan(String value) {
			addCriterion("DRUG_CATE_CODE <", value, "drugCateCode");
			return this;
		}

		public Criteria andDrugCateCodeLessThanOrEqualTo(String value) {
			addCriterion("DRUG_CATE_CODE <=", value, "drugCateCode");
			return this;
		}

		public Criteria andDrugCateCodeLike(String value) {
			addCriterion("DRUG_CATE_CODE like", value, "drugCateCode");
			return this;
		}

		public Criteria andDrugCateCodeNotLike(String value) {
			addCriterion("DRUG_CATE_CODE not like", value, "drugCateCode");
			return this;
		}

		public Criteria andDrugCateCodeIn(List values) {
			addCriterion("DRUG_CATE_CODE in", values, "drugCateCode");
			return this;
		}

		public Criteria andDrugCateCodeNotIn(List values) {
			addCriterion("DRUG_CATE_CODE not in", values, "drugCateCode");
			return this;
		}

		public Criteria andDrugCateCodeBetween(String value1, String value2) {
			addCriterion("DRUG_CATE_CODE between", value1, value2,
					"drugCateCode");
			return this;
		}

		public Criteria andDrugCateCodeNotBetween(String value1, String value2) {
			addCriterion("DRUG_CATE_CODE not between", value1, value2,
					"drugCateCode");
			return this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return this;
		}

		public Criteria andCreateUserEqualTo(Long value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return this;
		}

		public Criteria andCreateUserNotEqualTo(Long value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return this;
		}

		public Criteria andCreateUserGreaterThan(Long value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(Long value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return this;
		}

		public Criteria andCreateUserLessThan(Long value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(Long value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return this;
		}

		public Criteria andCreateUserIn(List values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return this;
		}

		public Criteria andCreateUserNotIn(List values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return this;
		}

		public Criteria andCreateUserBetween(Long value1,
				Long value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return this;
		}

		public Criteria andCreateUserNotBetween(Long value1,
				Long value2) {
			addCriterion("CREATE_USER not between", value1, value2,
					"createUser");
			return this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_TIME =", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_TIME <>", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("CREATE_TIME >", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_TIME >=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterionForJDBCDate("CREATE_TIME <", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_TIME <=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeIn(List values) {
			addCriterionForJDBCDate("CREATE_TIME in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotIn(List values) {
			addCriterionForJDBCDate("CREATE_TIME not in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_TIME between", value1, value2,
					"createTime");
			return this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_TIME not between", value1, value2,
					"createTime");
			return this;
		}

		public Criteria andCheckUserIsNull() {
			addCriterion("CHECK_USER is null");
			return this;
		}

		public Criteria andCheckUserIsNotNull() {
			addCriterion("CHECK_USER is not null");
			return this;
		}

		public Criteria andCheckUserEqualTo(Long value) {
			addCriterion("CHECK_USER =", value, "checkUser");
			return this;
		}

		public Criteria andCheckUserNotEqualTo(Long value) {
			addCriterion("CHECK_USER <>", value, "checkUser");
			return this;
		}

		public Criteria andCheckUserGreaterThan(Long value) {
			addCriterion("CHECK_USER >", value, "checkUser");
			return this;
		}

		public Criteria andCheckUserGreaterThanOrEqualTo(Long value) {
			addCriterion("CHECK_USER >=", value, "checkUser");
			return this;
		}

		public Criteria andCheckUserLessThan(Long value) {
			addCriterion("CHECK_USER <", value, "checkUser");
			return this;
		}

		public Criteria andCheckUserLessThanOrEqualTo(Long value) {
			addCriterion("CHECK_USER <=", value, "checkUser");
			return this;
		}

		public Criteria andCheckUserIn(List values) {
			addCriterion("CHECK_USER in", values, "checkUser");
			return this;
		}

		public Criteria andCheckUserNotIn(List values) {
			addCriterion("CHECK_USER not in", values, "checkUser");
			return this;
		}

		public Criteria andCheckUserBetween(Long value1, Long value2) {
			addCriterion("CHECK_USER between", value1, value2, "checkUser");
			return this;
		}

		public Criteria andCheckUserNotBetween(Long value1,
				Long value2) {
			addCriterion("CHECK_USER not between", value1, value2, "checkUser");
			return this;
		}

		public Criteria andCheckTimeIsNull() {
			addCriterion("CHECK_TIME is null");
			return this;
		}

		public Criteria andCheckTimeIsNotNull() {
			addCriterion("CHECK_TIME is not null");
			return this;
		}

		public Criteria andCheckTimeEqualTo(Date value) {
			addCriterionForJDBCDate("CHECK_TIME =", value, "checkTime");
			return this;
		}

		public Criteria andCheckTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("CHECK_TIME <>", value, "checkTime");
			return this;
		}

		public Criteria andCheckTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("CHECK_TIME >", value, "checkTime");
			return this;
		}

		public Criteria andCheckTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CHECK_TIME >=", value, "checkTime");
			return this;
		}

		public Criteria andCheckTimeLessThan(Date value) {
			addCriterionForJDBCDate("CHECK_TIME <", value, "checkTime");
			return this;
		}

		public Criteria andCheckTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CHECK_TIME <=", value, "checkTime");
			return this;
		}

		public Criteria andCheckTimeIn(List values) {
			addCriterionForJDBCDate("CHECK_TIME in", values, "checkTime");
			return this;
		}

		public Criteria andCheckTimeNotIn(List values) {
			addCriterionForJDBCDate("CHECK_TIME not in", values, "checkTime");
			return this;
		}

		public Criteria andCheckTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CHECK_TIME between", value1, value2,
					"checkTime");
			return this;
		}

		public Criteria andCheckTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CHECK_TIME not between", value1, value2,
					"checkTime");
			return this;
		}

		public Criteria andModifUserIsNull() {
			addCriterion("MODIF_USER is null");
			return this;
		}

		public Criteria andModifUserIsNotNull() {
			addCriterion("MODIF_USER is not null");
			return this;
		}

		public Criteria andModifUserEqualTo(Long value) {
			addCriterion("MODIF_USER =", value, "modifUser");
			return this;
		}

		public Criteria andModifUserNotEqualTo(Long value) {
			addCriterion("MODIF_USER <>", value, "modifUser");
			return this;
		}

		public Criteria andModifUserGreaterThan(Long value) {
			addCriterion("MODIF_USER >", value, "modifUser");
			return this;
		}

		public Criteria andModifUserGreaterThanOrEqualTo(Long value) {
			addCriterion("MODIF_USER >=", value, "modifUser");
			return this;
		}

		public Criteria andModifUserLessThan(Long value) {
			addCriterion("MODIF_USER <", value, "modifUser");
			return this;
		}

		public Criteria andModifUserLessThanOrEqualTo(Long value) {
			addCriterion("MODIF_USER <=", value, "modifUser");
			return this;
		}

		public Criteria andModifUserIn(List values) {
			addCriterion("MODIF_USER in", values, "modifUser");
			return this;
		}

		public Criteria andModifUserNotIn(List values) {
			addCriterion("MODIF_USER not in", values, "modifUser");
			return this;
		}

		public Criteria andModifUserBetween(Long value1, Long value2) {
			addCriterion("MODIF_USER between", value1, value2, "modifUser");
			return this;
		}

		public Criteria andModifUserNotBetween(Long value1,
				Long value2) {
			addCriterion("MODIF_USER not between", value1, value2, "modifUser");
			return this;
		}

		public Criteria andModifTimeIsNull() {
			addCriterion("MODIF_TIME is null");
			return this;
		}

		public Criteria andModifTimeIsNotNull() {
			addCriterion("MODIF_TIME is not null");
			return this;
		}

		public Criteria andModifTimeEqualTo(Date value) {
			addCriterionForJDBCDate("MODIF_TIME =", value, "modifTime");
			return this;
		}

		public Criteria andModifTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("MODIF_TIME <>", value, "modifTime");
			return this;
		}

		public Criteria andModifTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("MODIF_TIME >", value, "modifTime");
			return this;
		}

		public Criteria andModifTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("MODIF_TIME >=", value, "modifTime");
			return this;
		}

		public Criteria andModifTimeLessThan(Date value) {
			addCriterionForJDBCDate("MODIF_TIME <", value, "modifTime");
			return this;
		}

		public Criteria andModifTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("MODIF_TIME <=", value, "modifTime");
			return this;
		}

		public Criteria andModifTimeIn(List values) {
			addCriterionForJDBCDate("MODIF_TIME in", values, "modifTime");
			return this;
		}

		public Criteria andModifTimeNotIn(List values) {
			addCriterionForJDBCDate("MODIF_TIME not in", values, "modifTime");
			return this;
		}

		public Criteria andModifTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("MODIF_TIME between", value1, value2,
					"modifTime");
			return this;
		}

		public Criteria andModifTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("MODIF_TIME not between", value1, value2,
					"modifTime");
			return this;
		}

		public Criteria andShopCodeIsNull() {
			addCriterion("SHOP_CODE is null");
			return this;
		}

		public Criteria andShopCodeIsNotNull() {
			addCriterion("SHOP_CODE is not null");
			return this;
		}

		public Criteria andShopCodeEqualTo(String value) {
			addCriterion("SHOP_CODE =", value, "shopCode");
			return this;
		}

		public Criteria andShopCodeNotEqualTo(String value) {
			addCriterion("SHOP_CODE <>", value, "shopCode");
			return this;
		}

		public Criteria andShopCodeGreaterThan(String value) {
			addCriterion("SHOP_CODE >", value, "shopCode");
			return this;
		}

		public Criteria andShopCodeGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_CODE >=", value, "shopCode");
			return this;
		}

		public Criteria andShopCodeLessThan(String value) {
			addCriterion("SHOP_CODE <", value, "shopCode");
			return this;
		}

		public Criteria andShopCodeLessThanOrEqualTo(String value) {
			addCriterion("SHOP_CODE <=", value, "shopCode");
			return this;
		}

		public Criteria andShopCodeLike(String value) {
			addCriterion("SHOP_CODE like", value, "shopCode");
			return this;
		}

		public Criteria andShopCodeNotLike(String value) {
			addCriterion("SHOP_CODE not like", value, "shopCode");
			return this;
		}

		public Criteria andShopCodeIn(List values) {
			addCriterion("SHOP_CODE in", values, "shopCode");
			return this;
		}

		public Criteria andShopCodeNotIn(List values) {
			addCriterion("SHOP_CODE not in", values, "shopCode");
			return this;
		}

		public Criteria andShopCodeBetween(String value1, String value2) {
			addCriterion("SHOP_CODE between", value1, value2, "shopCode");
			return this;
		}

		public Criteria andShopCodeNotBetween(String value1, String value2) {
			addCriterion("SHOP_CODE not between", value1, value2, "shopCode");
			return this;
		}

		public Criteria andUpTimeIsNull() {
			addCriterion("UP_TIME is null");
			return this;
		}

		public Criteria andUpTimeIsNotNull() {
			addCriterion("UP_TIME is not null");
			return this;
		}

		public Criteria andUpTimeEqualTo(Date value) {
			addCriterionForJDBCDate("UP_TIME =", value, "upTime");
			return this;
		}

		public Criteria andUpTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("UP_TIME <>", value, "upTime");
			return this;
		}

		public Criteria andUpTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("UP_TIME >", value, "upTime");
			return this;
		}

		public Criteria andUpTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("UP_TIME >=", value, "upTime");
			return this;
		}

		public Criteria andUpTimeLessThan(Date value) {
			addCriterionForJDBCDate("UP_TIME <", value, "upTime");
			return this;
		}

		public Criteria andUpTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("UP_TIME <=", value, "upTime");
			return this;
		}

		public Criteria andUpTimeIn(List values) {
			addCriterionForJDBCDate("UP_TIME in", values, "upTime");
			return this;
		}

		public Criteria andUpTimeNotIn(List values) {
			addCriterionForJDBCDate("UP_TIME not in", values, "upTime");
			return this;
		}

		public Criteria andUpTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("UP_TIME between", value1, value2, "upTime");
			return this;
		}

		public Criteria andUpTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("UP_TIME not between", value1, value2,
					"upTime");
			return this;
		}

        public Criteria andToCheckTimeGreaterThan(Timestamp value) {
            addCriterion("TO_CHECK_TIME >", value, "toCheckTime");
            return this;
        }

        public Criteria andToCheckTimeLessThan(Timestamp value) {
            addCriterion("TO_CHECK_TIME <", value, "toCheckTime");
            return this;
        }

        public Criteria andSupplyType(int type) {
            if (type == 2) {
                addCriterion("exists (select 1 from suppliers_info si where si.supplier_id=product_draft.shop_code " +
                        "and si.SUPPLIER_TYPE=2)");
            } else if (type == 1) {
                addCriterion("exists (select 1 from suppliers_info si where si.supplier_id=product_draft.shop_code " +
                        "and si.SUPPLIER_TYPE in (1,3))");
            }
            return this;
        }

		public Criteria andArchiveTimeIsNull() {
			addCriterion("ARCHIVE_TIME is null");
			return this;
		}

		public Criteria andArchiveTimeIsNotNull() {
			addCriterion("ARCHIVE_TIME is not null");
			return this;
		}

		public Criteria andArchiveTimeEqualTo(Date value) {
			addCriterionForJDBCDate("ARCHIVE_TIME =", value, "archiveTime");
			return this;
		}

		public Criteria andArchiveTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("ARCHIVE_TIME <>", value, "archiveTime");
			return this;
		}

		public Criteria andArchiveTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("ARCHIVE_TIME >", value, "archiveTime");
			return this;
		}

		public Criteria andArchiveTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ARCHIVE_TIME >=", value, "archiveTime");
			return this;
		}

		public Criteria andArchiveTimeLessThan(Date value) {
			addCriterionForJDBCDate("ARCHIVE_TIME <", value, "archiveTime");
			return this;
		}

		public Criteria andArchiveTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ARCHIVE_TIME <=", value, "archiveTime");
			return this;
		}

		public Criteria andArchiveTimeIn(List values) {
			addCriterionForJDBCDate("ARCHIVE_TIME in", values, "archiveTime");
			return this;
		}

		public Criteria andArchiveTimeNotIn(List values) {
			addCriterionForJDBCDate("ARCHIVE_TIME not in", values,
					"archiveTime");
			return this;
		}

		public Criteria andArchiveTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ARCHIVE_TIME between", value1, value2,
					"archiveTime");
			return this;
		}

		public Criteria andArchiveTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ARCHIVE_TIME not between", value1, value2,
					"archiveTime");
			return this;
		}

		public Criteria andChannelIsNull() {
			addCriterion("CHANNEL is null");
			return this;
		}

		public Criteria andChannelIsNotNull() {
			addCriterion("CHANNEL is not null");
			return this;
		}

		public Criteria andChannelEqualTo(String value) {
			addCriterion("CHANNEL =", value, "channel");
			return this;
		}

		public Criteria andChannelNotEqualTo(String value) {
			addCriterion("CHANNEL <>", value, "channel");
			return this;
		}

		public Criteria andChannelGreaterThan(String value) {
			addCriterion("CHANNEL >", value, "channel");
			return this;
		}

		public Criteria andChannelGreaterThanOrEqualTo(String value) {
			addCriterion("CHANNEL >=", value, "channel");
			return this;
		}

		public Criteria andChannelLessThan(String value) {
			addCriterion("CHANNEL <", value, "channel");
			return this;
		}

		public Criteria andChannelLessThanOrEqualTo(String value) {
			addCriterion("CHANNEL <=", value, "channel");
			return this;
		}

		public Criteria andChannelLike(String value) {
			addCriterion("CHANNEL like", value, "channel");
			return this;
		}

		public Criteria andChannelNotLike(String value) {
			addCriterion("CHANNEL not like", value, "channel");
			return this;
		}

		public Criteria andChannelIn(List values) {
			addCriterion("CHANNEL in", values, "channel");
			return this;
		}

		public Criteria andChannelNotIn(List values) {
			addCriterion("CHANNEL not in", values, "channel");
			return this;
		}

		public Criteria andChannelBetween(String value1, String value2) {
			addCriterion("CHANNEL between", value1, value2, "channel");
			return this;
		}

		public Criteria andChannelNotBetween(String value1, String value2) {
			addCriterion("CHANNEL not between", value1, value2, "channel");
			return this;
		}

		public Criteria andApprovalTypeIsNull() {
			addCriterion("APPROVAL_TYPE is null");
			return this;
		}

		public Criteria andApprovalTypeIsNotNull() {
			addCriterion("APPROVAL_TYPE is not null");
			return this;
		}

		public Criteria andApprovalTypeEqualTo(Short value) {
			addCriterion("APPROVAL_TYPE =", value, "approvalType");
			return this;
		}

		public Criteria andApprovalTypeNotEqualTo(Short value) {
			addCriterion("APPROVAL_TYPE <>", value, "approvalType");
			return this;
		}

		public Criteria andApprovalTypeGreaterThan(Short value) {
			addCriterion("APPROVAL_TYPE >", value, "approvalType");
			return this;
		}

		public Criteria andApprovalTypeGreaterThanOrEqualTo(Short value) {
			addCriterion("APPROVAL_TYPE >=", value, "approvalType");
			return this;
		}

		public Criteria andApprovalTypeLessThan(Short value) {
			addCriterion("APPROVAL_TYPE <", value, "approvalType");
			return this;
		}

		public Criteria andApprovalTypeLessThanOrEqualTo(Short value) {
			addCriterion("APPROVAL_TYPE <=", value, "approvalType");
			return this;
		}

		public Criteria andApprovalTypeIn(List values) {
			addCriterion("APPROVAL_TYPE in", values, "approvalType");
			return this;
		}

		public Criteria andApprovalTypeNotIn(List values) {
			addCriterion("APPROVAL_TYPE not in", values, "approvalType");
			return this;
		}

		public Criteria andApprovalTypeBetween(Short value1, Short value2) {
			addCriterion("APPROVAL_TYPE between", value1, value2,
					"approvalType");
			return this;
		}

		public Criteria andApprovalTypeNotBetween(Short value1, Short value2) {
			addCriterion("APPROVAL_TYPE not between", value1, value2,
					"approvalType");
			return this;
		}

		public Criteria andApprovalNoIsNull() {
			addCriterion("APPROVAL_NO is null");
			return this;
		}

		public Criteria andApprovalNoIsNotNull() {
			addCriterion("APPROVAL_NO is not null");
			return this;
		}

		public Criteria andApprovalNoEqualTo(String value) {
			addCriterion("APPROVAL_NO =", value, "approvalNo");
			return this;
		}

		public Criteria andApprovalNoNotEqualTo(String value) {
			addCriterion("APPROVAL_NO <>", value, "approvalNo");
			return this;
		}

		public Criteria andApprovalNoGreaterThan(String value) {
			addCriterion("APPROVAL_NO >", value, "approvalNo");
			return this;
		}

		public Criteria andApprovalNoGreaterThanOrEqualTo(String value) {
			addCriterion("APPROVAL_NO >=", value, "approvalNo");
			return this;
		}

		public Criteria andApprovalNoLessThan(String value) {
			addCriterion("APPROVAL_NO <", value, "approvalNo");
			return this;
		}

		public Criteria andApprovalNoLessThanOrEqualTo(String value) {
			addCriterion("APPROVAL_NO <=", value, "approvalNo");
			return this;
		}

		public Criteria andApprovalNoLike(String value) {
			addCriterion("APPROVAL_NO like", value, "approvalNo");
			return this;
		}

		public Criteria andApprovalNoNotLike(String value) {
			addCriterion("APPROVAL_NO not like", value, "approvalNo");
			return this;
		}

		public Criteria andApprovalNoIn(List values) {
			addCriterion("APPROVAL_NO in", values, "approvalNo");
			return this;
		}

		public Criteria andApprovalNoNotIn(List values) {
			addCriterion("APPROVAL_NO not in", values, "approvalNo");
			return this;
		}

		public Criteria andApprovalNoBetween(String value1, String value2) {
			addCriterion("APPROVAL_NO between", value1, value2, "approvalNo");
			return this;
		}

		public Criteria andApprovalNoNotBetween(String value1, String value2) {
			addCriterion("APPROVAL_NO not between", value1, value2,
					"approvalNo");
			return this;
		}

		public Criteria andProducthotIsNull() {
			addCriterion("PRODUCTHOT is null");
			return this;
		}

		public Criteria andProducthotIsNotNull() {
			addCriterion("PRODUCTHOT is not null");
			return this;
		}

		public Criteria andProducthotEqualTo(Long value) {
			addCriterion("PRODUCTHOT =", value, "producthot");
			return this;
		}

		public Criteria andProducthotNotEqualTo(Long value) {
			addCriterion("PRODUCTHOT <>", value, "producthot");
			return this;
		}

		public Criteria andProducthotGreaterThan(Long value) {
			addCriterion("PRODUCTHOT >", value, "producthot");
			return this;
		}

		public Criteria andProducthotGreaterThanOrEqualTo(Long value) {
			addCriterion("PRODUCTHOT >=", value, "producthot");
			return this;
		}

		public Criteria andProducthotLessThan(Long value) {
			addCriterion("PRODUCTHOT <", value, "producthot");
			return this;
		}

		public Criteria andProducthotLessThanOrEqualTo(Long value) {
			addCriterion("PRODUCTHOT <=", value, "producthot");
			return this;
		}

		public Criteria andProducthotIn(List values) {
			addCriterion("PRODUCTHOT in", values, "producthot");
			return this;
		}

		public Criteria andProducthotNotIn(List values) {
			addCriterion("PRODUCTHOT not in", values, "producthot");
			return this;
		}

		public Criteria andProducthotBetween(Long value1,
				Long value2) {
			addCriterion("PRODUCTHOT between", value1, value2, "producthot");
			return this;
		}

		public Criteria andProducthotNotBetween(Long value1,
				Long value2) {
			addCriterion("PRODUCTHOT not between", value1, value2, "producthot");
			return this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return this;
		}

		public Criteria andStatusIn(List values) {
			addCriterion("STATUS in", values, "status");
			return this;
		}

		public Criteria andStatusNotIn(List values) {
			addCriterion("STATUS not in", values, "status");
			return this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return this;
		}

		public Criteria andOpTypeIsNull() {
			addCriterion("OP_TYPE is null");
			return this;
		}

		public Criteria andOpTypeIsNotNull() {
			addCriterion("OP_TYPE is not null");
			return this;
		}

		public Criteria andOpTypeEqualTo(Short value) {
			addCriterion("OP_TYPE =", value, "opType");
			return this;
		}

		public Criteria andOpTypeNotEqualTo(Short value) {
			addCriterion("OP_TYPE <>", value, "opType");
			return this;
		}

		public Criteria andOpTypeGreaterThan(Short value) {
			addCriterion("OP_TYPE >", value, "opType");
			return this;
		}

		public Criteria andOpTypeGreaterThanOrEqualTo(Short value) {
			addCriterion("OP_TYPE >=", value, "opType");
			return this;
		}

		public Criteria andOpTypeLessThan(Short value) {
			addCriterion("OP_TYPE <", value, "opType");
			return this;
		}

		public Criteria andOpTypeLessThanOrEqualTo(Short value) {
			addCriterion("OP_TYPE <=", value, "opType");
			return this;
		}

		public Criteria andOpTypeIn(List values) {
			addCriterion("OP_TYPE in", values, "opType");
			return this;
		}

		public Criteria andOpTypeNotIn(List values) {
			addCriterion("OP_TYPE not in", values, "opType");
			return this;
		}

		public Criteria andOpTypeBetween(Short value1, Short value2) {
			addCriterion("OP_TYPE between", value1, value2, "opType");
			return this;
		}

		public Criteria andOpTypeNotBetween(Short value1, Short value2) {
			addCriterion("OP_TYPE not between", value1, value2, "opType");
			return this;
		}

		public Criteria andReasonsIsNull() {
			addCriterion("REASONS is null");
			return this;
		}

		public Criteria andReasonsIsNotNull() {
			addCriterion("REASONS is not null");
			return this;
		}

		public Criteria andReasonsEqualTo(String value) {
			addCriterion("REASONS =", value, "reasons");
			return this;
		}

		public Criteria andReasonsNotEqualTo(String value) {
			addCriterion("REASONS <>", value, "reasons");
			return this;
		}

		public Criteria andReasonsGreaterThan(String value) {
			addCriterion("REASONS >", value, "reasons");
			return this;
		}

		public Criteria andReasonsGreaterThanOrEqualTo(String value) {
			addCriterion("REASONS >=", value, "reasons");
			return this;
		}

		public Criteria andReasonsLessThan(String value) {
			addCriterion("REASONS <", value, "reasons");
			return this;
		}

		public Criteria andReasonsLessThanOrEqualTo(String value) {
			addCriterion("REASONS <=", value, "reasons");
			return this;
		}

		public Criteria andReasonsLike(String value) {
			addCriterion("REASONS like", value, "reasons");
			return this;
		}

		public Criteria andReasonsNotLike(String value) {
			addCriterion("REASONS not like", value, "reasons");
			return this;
		}

		public Criteria andReasonsIn(List values) {
			addCriterion("REASONS in", values, "reasons");
			return this;
		}

		public Criteria andReasonsNotIn(List values) {
			addCriterion("REASONS not in", values, "reasons");
			return this;
		}

		public Criteria andReasonsBetween(String value1, String value2) {
			addCriterion("REASONS between", value1, value2, "reasons");
			return this;
		}

		public Criteria andReasonsNotBetween(String value1, String value2) {
			addCriterion("REASONS not between", value1, value2, "reasons");
			return this;
		}

		public Criteria andProductDescIsNull() {
			addCriterion("PRODUCT_DESC is null");
			return this;
		}

		public Criteria andProductDescIsNotNull() {
			addCriterion("PRODUCT_DESC is not null");
			return this;
		}

		public Criteria andProductDescEqualTo(String value) {
			addCriterion("PRODUCT_DESC =", value, "productDesc");
			return this;
		}

		public Criteria andProductDescNotEqualTo(String value) {
			addCriterion("PRODUCT_DESC <>", value, "productDesc");
			return this;
		}

		public Criteria andProductDescGreaterThan(String value) {
			addCriterion("PRODUCT_DESC >", value, "productDesc");
			return this;
		}

		public Criteria andProductDescGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCT_DESC >=", value, "productDesc");
			return this;
		}

		public Criteria andProductDescLessThan(String value) {
			addCriterion("PRODUCT_DESC <", value, "productDesc");
			return this;
		}

		public Criteria andProductDescLessThanOrEqualTo(String value) {
			addCriterion("PRODUCT_DESC <=", value, "productDesc");
			return this;
		}

		public Criteria andProductDescLike(String value) {
			addCriterion("PRODUCT_DESC like", value, "productDesc");
			return this;
		}

		public Criteria andProductDescNotLike(String value) {
			addCriterion("PRODUCT_DESC not like", value, "productDesc");
			return this;
		}

		public Criteria andProductDescIn(List values) {
			addCriterion("PRODUCT_DESC in", values, "productDesc");
			return this;
		}

		public Criteria andProductDescNotIn(List values) {
			addCriterion("PRODUCT_DESC not in", values, "productDesc");
			return this;
		}

		public Criteria andProductDescBetween(String value1, String value2) {
			addCriterion("PRODUCT_DESC between", value1, value2, "productDesc");
			return this;
		}

		public Criteria andProductDescNotBetween(String value1, String value2) {
			addCriterion("PRODUCT_DESC not between", value1, value2,
					"productDesc");
			return this;
		}

		public Criteria andErpProducrCodeIsNull() {
			addCriterion("ERP_PRODUCT_CODE is null");
			return this;
		}

		public Criteria andErpProducrCodeIsNotNull() {
			addCriterion("ERP_PRODUCT_CODE is not null");
			return this;
		}

		public Criteria andErpProducrCodeEqualTo(String value) {
			addCriterion("ERP_PRODUCT_CODE =", value, "erpProductCode");
			return this;
		}

		public Criteria andErpProducrCodeNotEqualTo(String value) {
			addCriterion("ERP_PRODUCT_CODE <>", value, "erpProductCode");
			return this;
		}

		public Criteria andErpProducrCodeGreaterThan(String value) {
			addCriterion("ERP_PRODUCT_CODE >", value, "erpProductCode");
			return this;
		}

		public Criteria andErpProducrCodeGreaterThanOrEqualTo(String value) {
			addCriterion("ERP_PRODUCT_CODE >=", value, "erpProductCode");
			return this;
		}

		public Criteria andErpProducrCodeLessThan(String value) {
			addCriterion("ERP_PRODUCT_CODE <", value, "erpProductCode");
			return this;
		}

		public Criteria andErpProducrCodeLessThanOrEqualTo(String value) {
			addCriterion("ERP_PRODUCT_CODE <=", value, "erpProductCode");
			return this;
		}

		public Criteria andErpProducrCodeLike(String value) {
			addCriterion("ERP_PRODUCT_CODE like", value, "erpProductCode");
			return this;
		}

		public Criteria andErpProducrCodeNotLike(String value) {
			addCriterion("ERP_PRODUCT_CODE not like", value, "erpProductCode");
			return this;
		}

		public Criteria andErpProducrCodeIn(List values) {
			addCriterion("ERP_PRODUCT_CODE in", values, "erpProductCode");
			return this;
		}

		public Criteria andErpProducrCodeNotIn(List values) {
			addCriterion("ERP_PRODUCT_CODE not in", values, "erpProductCode");
			return this;
		}

		public Criteria andErpProducrCodeBetween(String value1, String value2) {
			addCriterion("ERP_PRODUCT_CODE between", value1, value2, "erpProductCode");
			return this;
		}

		public Criteria andErpProducrCodeNotBetween(String value1, String value2) {
			addCriterion("ERP_PRODUCT_CODE not between", value1, value2, "erpProductCode");
			return this;
		}
		
		public Criteria andPriceStatusIsNull() {
            addCriterion("PRICE_STATUS is null");
            return this;
        }

        public Criteria andPriceStatusIsNotNull() {
            addCriterion("PRICE_STATUS is not null");
            return this;
        }

        public Criteria andPriceStatusEqualTo(String value) {
            addCriterion("PRICE_STATUS =", value, "priceStatus");
            return this;
        }
        
        public Criteria andPriceStatusNotEqualTo(String value) {
            addCriterion("PRICE_STATUS <>", value, "priceStatus");
            return this;
        }

        public Criteria andPriceStatusGreaterThan(String value) {
            addCriterion("PRICE_STATUS >", value, "priceStatus");
            return this;
        }

        public Criteria andPriceStatusGreaterThanOrEqualTo(String value) {
            addCriterion("PRICE_STATUS >=", value, "priceStatus");
            return this;
        }

        public Criteria andPriceStatusLessThan(String value) {
            addCriterion("PRICE_STATUS <", value, "priceStatus");
            return this;
        }

        public Criteria andPriceStatusLessThanOrEqualTo(String value) {
            addCriterion("PRICE_STATUS <=", value, "priceStatus");
            return this;
        }

        public Criteria andPriceStatusLike(String value) {
            addCriterion("PRICE_STATUS like", value, "priceStatus");
            return this;
        }

        public Criteria andPriceStatusNotLike(String value) {
            addCriterion("PRICE_STATUS not like", value, "priceStatus");
            return this;
        }

        public Criteria andPriceStatusIn(List values) {
            addCriterion("PRICE_STATUS in", values, "priceStatus");
            return this;
        }

        public Criteria andPriceStatusNotIn(List values) {
            addCriterion("PRICE_STATUS not in", values, "priceStatus");
            return this;
        }

        public Criteria andPriceStatusBetween(String value1, String value2) {
            addCriterion("PRICE_STATUS between", value1, value2, "priceStatus");
            return this;
        }

        public Criteria andPriceStatusNotBetween(String value1, String value2) {
            addCriterion("PRICE_STATUS not between", value1, value2, "priceStatus");
            return this;
        }

        public Criteria andPriceReasonsIsNull() {
            addCriterion("PRICE_REASONS is null");
            return this;
        }

        public Criteria andPriceReasonsIsNotNull() {
            addCriterion("PRICE_REASONS is not null");
            return this;
        }

        public Criteria andPriceReasonsEqualTo(String value) {
            addCriterion("PRICE_REASONS =", value, "priceReasons");
            return this;
        }

        public Criteria andPriceReasonsNotEqualTo(String value) {
            addCriterion("PRICE_REASONS <>", value, "priceReasons");
            return this;
        }

        public Criteria andPriceReasonsGreaterThan(String value) {
            addCriterion("PRICE_REASONS >", value, "priceReasons");
            return this;
        }

        public Criteria andPriceReasonsGreaterThanOrEqualTo(String value) {
            addCriterion("PRICE_REASONS >=", value, "priceReasons");
            return this;
        }

        public Criteria andPriceReasonsLessThan(String value) {
            addCriterion("PRICE_REASONS <", value, "priceReasons");
            return this;
        }

        public Criteria andPriceReasonsLessThanOrEqualTo(String value) {
            addCriterion("PRICE_REASONS <=", value, "priceReasons");
            return this;
        }

        public Criteria andPriceReasonsLike(String value) {
            addCriterion("PRICE_REASONS like", value, "priceReasons");
            return this;
        }

        public Criteria andPriceReasonsNotLike(String value) {
            addCriterion("PRICE_REASONS not like", value, "priceReasons");
            return this;
        }

        public Criteria andPriceReasonsIn(List values) {
            addCriterion("PRICE_REASONS in", values, "priceReasons");
            return this;
        }

        public Criteria andPriceReasonsNotIn(List values) {
            addCriterion("PRICE_REASONS not in", values, "priceReasons");
            return this;
        }

        public Criteria andPriceReasonsBetween(String value1, String value2) {
            addCriterion("PRICE_REASONS between", value1, value2, "priceReasons");
            return this;
        }

        public Criteria andPriceReasonsNotBetween(String value1, String value2) {
            addCriterion("PRICE_REASONS not between", value1, value2, "priceReasons");
            return this;
        }

        public Criteria andImageStatusIsNull() {
            addCriterion("IMAGE_STATUS is null");
            return this;
        }

        public Criteria andImageStatusIsNotNull() {
            addCriterion("IMAGE_STATUS is not null");
            return this;
        }

        public Criteria andImageStatusEqualTo(String value) {
            addCriterion("IMAGE_STATUS =", value, "imageStatus");
            return this;
        }

        public Criteria andImageStatusNotEqualTo(String value) {
            addCriterion("IMAGE_STATUS <>", value, "imageStatus");
            return this;
        }

        public Criteria andImageStatusGreaterThan(String value) {
            addCriterion("IMAGE_STATUS >", value, "imageStatus");
            return this;
        }

        public Criteria andImageStatusGreaterThanOrEqualTo(String value) {
            addCriterion("IMAGE_STATUS >=", value, "imageStatus");
            return this;
        }

        public Criteria andImageStatusLessThan(String value) {
            addCriterion("IMAGE_STATUS <", value, "imageStatus");
            return this;
        }

        public Criteria andImageStatusLessThanOrEqualTo(String value) {
            addCriterion("IMAGE_STATUS <=", value, "imageStatus");
            return this;
        }

        public Criteria andImageStatusLike(String value) {
            addCriterion("IMAGE_STATUS like", value, "imageStatus");
            return this;
        }

        public Criteria andImageStatusNotLike(String value) {
            addCriterion("IMAGE_STATUS not like", value, "imageStatus");
            return this;
        }

        public Criteria andImageStatusIn(List values) {
            addCriterion("IMAGE_STATUS in", values, "imageStatus");
            return this;
        }

        public Criteria andImageStatusNotIn(List values) {
            addCriterion("IMAGE_STATUS not in", values, "imageStatus");
            return this;
        }

        public Criteria andImageStatusBetween(String value1, String value2) {
            addCriterion("IMAGE_STATUS between", value1, value2, "imageStatus");
            return this;
        }

        public Criteria andImageStatusNotBetween(String value1, String value2) {
            addCriterion("IMAGE_STATUS not between", value1, value2, "imageStatus");
            return this;
        }

        public Criteria andImageReasonsIsNull() {
            addCriterion("IMAGE_REASONS is null");
            return this;
        }

        public Criteria andImageReasonsIsNotNull() {
            addCriterion("IMAGE_REASONS is not null");
            return this;
        }

        public Criteria andImageReasonsEqualTo(String value) {
            addCriterion("IMAGE_REASONS =", value, "imageReasons");
            return this;
        }

        public Criteria andImageReasonsNotEqualTo(String value) {
            addCriterion("IMAGE_REASONS <>", value, "imageReasons");
            return this;
        }

        public Criteria andImageReasonsGreaterThan(String value) {
            addCriterion("IMAGE_REASONS >", value, "imageReasons");
            return this;
        }

        public Criteria andImageReasonsGreaterThanOrEqualTo(String value) {
            addCriterion("IMAGE_REASONS >=", value, "imageReasons");
            return this;
        }

        public Criteria andImageReasonsLessThan(String value) {
            addCriterion("IMAGE_REASONS <", value, "imageReasons");
            return this;
        }

        public Criteria andImageReasonsLessThanOrEqualTo(String value) {
            addCriterion("IMAGE_REASONS <=", value, "imageReasons");
            return this;
        }

        public Criteria andImageReasonsLike(String value) {
            addCriterion("IMAGE_REASONS like", value, "imageReasons");
            return this;
        }

        public Criteria andImageReasonsNotLike(String value) {
            addCriterion("IMAGE_REASONS not like", value, "imageReasons");
            return this;
        }

        public Criteria andImageReasonsIn(List values) {
            addCriterion("IMAGE_REASONS in", values, "imageReasons");
            return this;
        }

        public Criteria andImageReasonsNotIn(List values) {
            addCriterion("IMAGE_REASONS not in", values, "imageReasons");
            return this;
        }

        public Criteria andImageReasonsBetween(String value1, String value2) {
            addCriterion("IMAGE_REASONS between", value1, value2, "imageReasons");
            return this;
        }

        public Criteria andImageReasonsNotBetween(String value1, String value2) {
            addCriterion("IMAGE_REASONS not between", value1, value2, "imageReasons");
            return this;
        }
        
        public Criteria andProductSubtitleIsNull() {
			addCriterion("PRODUCT_SUBTITLE is null");
			return this;
		}

		public Criteria andProductSubtitleIsNotNull() {
			addCriterion("PRODUCT_SUBTITLE is not null");
			return this;
		}

		public Criteria andProductSubtitleEqualTo(String value) {
			addCriterion("PRODUCT_SUBTITLE =", value, "productSubtitle");
			return this;
		}

		public Criteria andProductSubtitleNotEqualTo(String value) {
			addCriterion("PRODUCT_SUBTITLE <>", value, "productSubtitle");
			return this;
		}

		public Criteria andProductSubtitleGreaterThan(String value) {
			addCriterion("PRODUCT_SUBTITLE >", value, "productSubtitle");
			return this;
		}

		public Criteria andProductSubtitleGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCT_SUBTITLE >=", value, "productSubtitle");
			return this;
		}

		public Criteria andProductSubtitleLessThan(String value) {
			addCriterion("PRODUCT_SUBTITLE <", value, "productSubtitle");
			return this;
		}

		public Criteria andProductSubtitleLessThanOrEqualTo(String value) {
			addCriterion("PRODUCT_SUBTITLE <=", value, "productSubtitle");
			return this;
		}

		public Criteria andProductSubtitleLike(String value) {
			addCriterion("PRODUCT_SUBTITLE like", value, "productSubtitle");
			return this;
		}

		public Criteria andProductSubtitleNotLike(String value) {
			addCriterion("PRODUCT_SUBTITLE not like", value, "productSubtitle");
			return this;
		}

		public Criteria andProductSubtitleIn(List values) {
			addCriterion("PRODUCT_SUBTITLE in", values, "productSubtitle");
			return this;
		}

		public Criteria andProductSubtitleNotIn(List values) {
			addCriterion("PRODUCT_SUBTITLE not in", values, "productSubtitle");
			return this;
		}

		public Criteria andProductSubtitleBetween(String value1, String value2) {
			addCriterion("PRODUCT_SUBTITLE between", value1, value2, "productSubtitle");
			return this;
		}

		public Criteria andProductSubtitleNotBetween(String value1, String value2) {
			addCriterion("PRODUCT_SUBTITLE not between", value1, value2,
					"productSubtitle");
			return this;
		}
		
		
		public Criteria andProductTypeIsNull() {
            addCriterion("PRODUCT_TYPE is null");
            return this;
        }

        public Criteria andProductTypeIsNotNull() {
            addCriterion("PRODUCT_TYPE is not null");
            return this;
        }

        public Criteria andProductTypeEqualTo(Integer value) {
            addCriterion("PRODUCT_TYPE =", value, "productType");
            return this;
        }

        public Criteria andProductTypeNotEqualTo(Integer value) {
            addCriterion("PRODUCT_TYPE <>", value, "productType");
            return this;
        }

        public Criteria andProductTypeGreaterThan(Integer value) {
            addCriterion("PRODUCT_TYPE >", value, "productType");
            return this;
        }

        public Criteria andProductTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRODUCT_TYPE >=", value, "productType");
            return this;
        }

        public Criteria andProductTypeLessThan(Integer value) {
            addCriterion("PRODUCT_TYPE <", value, "productType");
            return this;
        }

        public Criteria andProductTypeLessThanOrEqualTo(Integer value) {
            addCriterion("PRODUCT_TYPE <=", value, "productType");
            return this;
        }

        public Criteria andProductTypeIn(List values) {
            addCriterion("PRODUCT_TYPE in", values, "productType");
            return this;
        }

        public Criteria andProductTypeNotIn(List values) {
            addCriterion("PRODUCT_TYPE not in", values, "productType");
            return this;
        }

        public Criteria andProductTypeBetween(Integer value1, Integer value2) {
            addCriterion("PRODUCT_TYPE between", value1, value2, "productType");
            return this;
        }

        public Criteria andProductTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("PRODUCT_TYPE not between", value1, value2, "productType");
            return this;
        }
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getSearchBrandName() {
		return searchBrandName;
	}

	public void setSearchBrandName(String searchBrandName) {
		this.searchBrandName = searchBrandName;
	}

	public Long getmCategoryId() {
		return mCategoryId;
	}

	public void setmCategoryId(Long mCategoryId) {
		this.mCategoryId = mCategoryId;
	}

	public Long getbCategoryId() {
		return bCategoryId;
	}

	public void setbCategoryId(Long bCategoryId) {
		this.bCategoryId = bCategoryId;
	}

	public String getSupplierNameForSearch() {
		return supplierNameForSearch;
	}

	public void setSupplierNameForSearch(String supplierNameForSearch) {
		this.supplierNameForSearch = supplierNameForSearch;
	}

    public String getCategoryAudit() {
        return categoryAudit;
    }

    public void setCategoryAudit(String categoryAudit) {
        this.categoryAudit = categoryAudit;
    }
	
	
}