package com.pltfm.app.vobject;

import java.io.Serializable;

public class SaleRank implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -8042095699119977309L;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SALE_RANK.SALE_RANK_ID
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    private Long saleRankId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SALE_RANK.PRODUCT_SKU_ID
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    private Long productSkuId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SALE_RANK.MONTH_QUANTITY
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    private Long monthQuantity;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SALE_RANK.WEEK_QUANTITY
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    private Long weekQuantity;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SALE_RANK.MONTH
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    private String month;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SALE_RANK.WEEK
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    private String week;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SALE_RANK.SALE_RANK_ID
     *
     * @return the value of SALE_RANK.SALE_RANK_ID
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    public Long getSaleRankId() {
        return saleRankId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SALE_RANK.SALE_RANK_ID
     *
     * @param saleRankId the value for SALE_RANK.SALE_RANK_ID
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    public void setSaleRankId(Long saleRankId) {
        this.saleRankId = saleRankId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SALE_RANK.PRODUCT_SKU_ID
     *
     * @return the value of SALE_RANK.PRODUCT_SKU_ID
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    public Long getProductSkuId() {
        return productSkuId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SALE_RANK.PRODUCT_SKU_ID
     *
     * @param productSkuId the value for SALE_RANK.PRODUCT_SKU_ID
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    public void setProductSkuId(Long productSkuId) {
        this.productSkuId = productSkuId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SALE_RANK.MONTH_QUANTITY
     *
     * @return the value of SALE_RANK.MONTH_QUANTITY
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    public Long getMonthQuantity() {
        return monthQuantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SALE_RANK.MONTH_QUANTITY
     *
     * @param monthQuantity the value for SALE_RANK.MONTH_QUANTITY
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    public void setMonthQuantity(Long monthQuantity) {
        this.monthQuantity = monthQuantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SALE_RANK.WEEK_QUANTITY
     *
     * @return the value of SALE_RANK.WEEK_QUANTITY
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    public Long getWeekQuantity() {
        return weekQuantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SALE_RANK.WEEK_QUANTITY
     *
     * @param weekQuantity the value for SALE_RANK.WEEK_QUANTITY
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    public void setWeekQuantity(Long weekQuantity) {
        this.weekQuantity = weekQuantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SALE_RANK.MONTH
     *
     * @return the value of SALE_RANK.MONTH
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SALE_RANK.MONTH
     *
     * @param month the value for SALE_RANK.MONTH
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    public void setMonth(String month) {
        this.month = month;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SALE_RANK.WEEK
     *
     * @return the value of SALE_RANK.WEEK
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    public String getWeek() {
        return week;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SALE_RANK.WEEK
     *
     * @param week the value for SALE_RANK.WEEK
     *
     * @ibatorgenerated Mon Sep 02 14:39:41 CST 2013
     */
    public void setWeek(String week) {
        this.week = week;
    }
}