package com.pltfm.app.vobject;

import java.io.Serializable;

import com.pltfm.app.vobject.Product;


public class ShopProductCategory implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -1682441506134050907L;

    private Long id;

    private Long shopCategoryId;

    private Long productId;
    
    /**
     * 未修改之前的店内分类ID
     */
    private long originalCategoryId;

    
    private Product product;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SHOP_PRODUCT_CATEGORY.ID
     *
     * @return the value of SHOP_PRODUCT_CATEGORY.ID
     *
     * @ibatorgenerated Thu Nov 27 10:13:18 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SHOP_PRODUCT_CATEGORY.ID
     *
     * @param id the value for SHOP_PRODUCT_CATEGORY.ID
     *
     * @ibatorgenerated Thu Nov 27 10:13:18 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SHOP_PRODUCT_CATEGORY.SHOP_CATEGORY_ID
     *
     * @return the value of SHOP_PRODUCT_CATEGORY.SHOP_CATEGORY_ID
     *
     * @ibatorgenerated Thu Nov 27 10:13:18 CST 2014
     */
    public Long getShopCategoryId() {
        return shopCategoryId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SHOP_PRODUCT_CATEGORY.SHOP_CATEGORY_ID
     *
     * @param shopCategoryId the value for SHOP_PRODUCT_CATEGORY.SHOP_CATEGORY_ID
     *
     * @ibatorgenerated Thu Nov 27 10:13:18 CST 2014
     */
    public void setShopCategoryId(Long shopCategoryId) {
        this.shopCategoryId = shopCategoryId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SHOP_PRODUCT_CATEGORY.PRODUCT_ID
     *
     * @return the value of SHOP_PRODUCT_CATEGORY.PRODUCT_ID
     *
     * @ibatorgenerated Thu Nov 27 10:13:18 CST 2014
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SHOP_PRODUCT_CATEGORY.PRODUCT_ID
     *
     * @param productId the value for SHOP_PRODUCT_CATEGORY.PRODUCT_ID
     *
     * @ibatorgenerated Thu Nov 27 10:13:18 CST 2014
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public long getOriginalCategoryId() {
		return originalCategoryId;
	}

	public void setOriginalCategoryId(long originalCategoryId) {
		this.originalCategoryId = originalCategoryId;
	}
}