package com.kmzyc.b2b.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class FareType implements Serializable {
  /**
	 * 
	 */
  private static final long serialVersionUID = 1305142131879935800L;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * KMORDER.FARE_TYPE.TYPE_ID
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  private long type_id;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * KMORDER.FARE_TYPE.NAME
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  private String name;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * KMORDER.FARE_TYPE.PROTECT
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  private Short protect;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * KMORDER.FARE_TYPE.PROTECT_RATE
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  private String protectRate;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * KMORDER.FARE_TYPE.HAS_COD
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  private String hasCod;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * KMORDER.FARE_TYPE.MIN_PRICE
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  private String minPrice;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * KMORDER.FARE_TYPE.CORP_ID
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  private Integer corpId;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * KMORDER.FARE_TYPE.ORDERNUM
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  private Long ordernum;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * KMORDER.FARE_TYPE.DISABLED
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  private Short disabled;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * KMORDER.FARE_TYPE.IS_SAME
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  private Short isSame;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * KMORDER.FARE_TYPE.FREE_PRICE
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  private BigDecimal freePrice;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * KMORDER.FARE_TYPE.FIRST_HEAVY_FREIGHT
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  private BigDecimal firstHeavyFreight;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * KMORDER.FARE_TYPE.CONTINUED_HEAVY_FREIGHT
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  private BigDecimal continuedHeavyFreight;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * KMORDER.FARE_TYPE.FIRST_HEAVY
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  private BigDecimal firstHeavy;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * KMORDER.FARE_TYPE.CONTINUED_HEAVY
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  private BigDecimal continuedHeavy;

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column KMORDER.FARE_TYPE.TYPE_ID
   * 
   * @return the value of KMORDER.FARE_TYPE.TYPE_ID
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public long getType_id() {
    return type_id;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column KMORDER.FARE_TYPE.TYPE_ID
   * 
   * @param type_id the value for KMORDER.FARE_TYPE.TYPE_ID
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public void setType_id(long type_id) {
    this.type_id = type_id;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column KMORDER.FARE_TYPE.NAME
   * 
   * @return the value of KMORDER.FARE_TYPE.NAME
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column KMORDER.FARE_TYPE.NAME
   * 
   * @param name the value for KMORDER.FARE_TYPE.NAME
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column KMORDER.FARE_TYPE.PROTECT
   * 
   * @return the value of KMORDER.FARE_TYPE.PROTECT
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public Short getProtect() {
    return protect;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column KMORDER.FARE_TYPE.PROTECT
   * 
   * @param protect the value for KMORDER.FARE_TYPE.PROTECT
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public void setProtect(Short protect) {
    this.protect = protect;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column KMORDER.FARE_TYPE.PROTECT_RATE
   * 
   * @return the value of KMORDER.FARE_TYPE.PROTECT_RATE
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public String getProtectRate() {
    return protectRate;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column KMORDER.FARE_TYPE.PROTECT_RATE
   * 
   * @param protectRate the value for KMORDER.FARE_TYPE.PROTECT_RATE
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public void setProtectRate(String protectRate) {
    this.protectRate = protectRate;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column KMORDER.FARE_TYPE.HAS_COD
   * 
   * @return the value of KMORDER.FARE_TYPE.HAS_COD
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public String getHasCod() {
    return hasCod;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column KMORDER.FARE_TYPE.HAS_COD
   * 
   * @param hasCod the value for KMORDER.FARE_TYPE.HAS_COD
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public void setHasCod(String hasCod) {
    this.hasCod = hasCod;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column KMORDER.FARE_TYPE.MIN_PRICE
   * 
   * @return the value of KMORDER.FARE_TYPE.MIN_PRICE
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public String getMinPrice() {
    return minPrice;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column KMORDER.FARE_TYPE.MIN_PRICE
   * 
   * @param minPrice the value for KMORDER.FARE_TYPE.MIN_PRICE
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public void setMinPrice(String minPrice) {
    this.minPrice = minPrice;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column KMORDER.FARE_TYPE.CORP_ID
   * 
   * @return the value of KMORDER.FARE_TYPE.CORP_ID
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public Integer getCorpId() {
    return corpId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column KMORDER.FARE_TYPE.CORP_ID
   * 
   * @param corpId the value for KMORDER.FARE_TYPE.CORP_ID
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public void setCorpId(Integer corpId) {
    this.corpId = corpId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column KMORDER.FARE_TYPE.ORDERNUM
   * 
   * @return the value of KMORDER.FARE_TYPE.ORDERNUM
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public Long getOrdernum() {
    return ordernum;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column KMORDER.FARE_TYPE.ORDERNUM
   * 
   * @param ordernum the value for KMORDER.FARE_TYPE.ORDERNUM
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public void setOrdernum(Long ordernum) {
    this.ordernum = ordernum;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column KMORDER.FARE_TYPE.DISABLED
   * 
   * @return the value of KMORDER.FARE_TYPE.DISABLED
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public Short getDisabled() {
    return disabled;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column KMORDER.FARE_TYPE.DISABLED
   * 
   * @param disabled the value for KMORDER.FARE_TYPE.DISABLED
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public void setDisabled(Short disabled) {
    this.disabled = disabled;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column KMORDER.FARE_TYPE.IS_SAME
   * 
   * @return the value of KMORDER.FARE_TYPE.IS_SAME
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public Short getIsSame() {
    return isSame;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column KMORDER.FARE_TYPE.IS_SAME
   * 
   * @param isSame the value for KMORDER.FARE_TYPE.IS_SAME
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public void setIsSame(Short isSame) {
    this.isSame = isSame;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column KMORDER.FARE_TYPE.FREE_PRICE
   * 
   * @return the value of KMORDER.FARE_TYPE.FREE_PRICE
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public BigDecimal getFreePrice() {
    return freePrice;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column KMORDER.FARE_TYPE.FREE_PRICE
   * 
   * @param freePrice the value for KMORDER.FARE_TYPE.FREE_PRICE
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public void setFreePrice(BigDecimal freePrice) {
    this.freePrice = freePrice;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column KMORDER.FARE_TYPE.FIRST_HEAVY_FREIGHT
   * 
   * @return the value of KMORDER.FARE_TYPE.FIRST_HEAVY_FREIGHT
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public BigDecimal getFirstHeavyFreight() {
    return firstHeavyFreight;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column KMORDER.FARE_TYPE.FIRST_HEAVY_FREIGHT
   * 
   * @param firstHeavyFreight the value for KMORDER.FARE_TYPE.FIRST_HEAVY_FREIGHT
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public void setFirstHeavyFreight(BigDecimal firstHeavyFreight) {
    this.firstHeavyFreight = firstHeavyFreight;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column KMORDER.FARE_TYPE.CONTINUED_HEAVY_FREIGHT
   * 
   * @return the value of KMORDER.FARE_TYPE.CONTINUED_HEAVY_FREIGHT
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public BigDecimal getContinuedHeavyFreight() {
    return continuedHeavyFreight;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column KMORDER.FARE_TYPE.CONTINUED_HEAVY_FREIGHT
   * 
   * @param continuedHeavyFreight the value for KMORDER.FARE_TYPE.CONTINUED_HEAVY_FREIGHT
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public void setContinuedHeavyFreight(BigDecimal continuedHeavyFreight) {
    this.continuedHeavyFreight = continuedHeavyFreight;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column KMORDER.FARE_TYPE.FIRST_HEAVY
   * 
   * @return the value of KMORDER.FARE_TYPE.FIRST_HEAVY
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public BigDecimal getFirstHeavy() {
    return firstHeavy;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column KMORDER.FARE_TYPE.FIRST_HEAVY
   * 
   * @param firstHeavy the value for KMORDER.FARE_TYPE.FIRST_HEAVY
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public void setFirstHeavy(BigDecimal firstHeavy) {
    this.firstHeavy = firstHeavy;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column KMORDER.FARE_TYPE.CONTINUED_HEAVY
   * 
   * @return the value of KMORDER.FARE_TYPE.CONTINUED_HEAVY
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public BigDecimal getContinuedHeavy() {
    return continuedHeavy;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column KMORDER.FARE_TYPE.CONTINUED_HEAVY
   * 
   * @param continuedHeavy the value for KMORDER.FARE_TYPE.CONTINUED_HEAVY
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  public void setContinuedHeavy(BigDecimal continuedHeavy) {
    this.continuedHeavy = continuedHeavy;
  }
}
