package com.kmzyc.b2b.model;

import java.math.BigDecimal;

public class ProductStock {
  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.STOCK_ID
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private BigDecimal stockId;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.WAREHOUSE_ID
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private BigDecimal warehouseId;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.PRODUCT_ID
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private BigDecimal productId;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.PRODUCT_NAME
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private String productName;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.PRODUCT_NO
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private String productNo;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.SKU_ATTRIBUTE_ID
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private BigDecimal skuAttributeId;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.SKU_ATT_VALUE
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private String skuAttValue;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.STOCK_QUALITY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private Integer stockQuality;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.ORDER_QUALITY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private Integer orderQuality;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.IN_TRANSIT_QUALITY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private Integer inTransitQuality;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.ALARM_QUALITY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private Integer alarmQuality;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.TOTAL_SALES
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private BigDecimal totalSales;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.PRICE
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private BigDecimal price;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.MIN_DAY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private BigDecimal minDay;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.MAX_DAY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private BigDecimal maxDay;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.ADJUST
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private BigDecimal adjust;

  /**
   * This field was generated by Abator for iBATIS. This field corresponds to the database column
   * KMPRODUCT.PRODUCT_STOCK.REMARK
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  private String remark;

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.STOCK_ID
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.STOCK_ID
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public BigDecimal getStockId() {
    return stockId;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.STOCK_ID
   * 
   * @param stockId the value for KMPRODUCT.PRODUCT_STOCK.STOCK_ID
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setStockId(BigDecimal stockId) {
    this.stockId = stockId;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.WAREHOUSE_ID
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.WAREHOUSE_ID
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public BigDecimal getWarehouseId() {
    return warehouseId;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.WAREHOUSE_ID
   * 
   * @param warehouseId the value for KMPRODUCT.PRODUCT_STOCK.WAREHOUSE_ID
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setWarehouseId(BigDecimal warehouseId) {
    this.warehouseId = warehouseId;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.PRODUCT_ID
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.PRODUCT_ID
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public BigDecimal getProductId() {
    return productId;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.PRODUCT_ID
   * 
   * @param productId the value for KMPRODUCT.PRODUCT_STOCK.PRODUCT_ID
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setProductId(BigDecimal productId) {
    this.productId = productId;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.PRODUCT_NAME
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.PRODUCT_NAME
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public String getProductName() {
    return productName;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.PRODUCT_NAME
   * 
   * @param productName the value for KMPRODUCT.PRODUCT_STOCK.PRODUCT_NAME
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setProductName(String productName) {
    this.productName = productName;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.PRODUCT_NO
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.PRODUCT_NO
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public String getProductNo() {
    return productNo;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.PRODUCT_NO
   * 
   * @param productNo the value for KMPRODUCT.PRODUCT_STOCK.PRODUCT_NO
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setProductNo(String productNo) {
    this.productNo = productNo;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.SKU_ATTRIBUTE_ID
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.SKU_ATTRIBUTE_ID
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public BigDecimal getSkuAttributeId() {
    return skuAttributeId;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.SKU_ATTRIBUTE_ID
   * 
   * @param skuAttributeId the value for KMPRODUCT.PRODUCT_STOCK.SKU_ATTRIBUTE_ID
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setSkuAttributeId(BigDecimal skuAttributeId) {
    this.skuAttributeId = skuAttributeId;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.SKU_ATT_VALUE
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.SKU_ATT_VALUE
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public String getSkuAttValue() {
    return skuAttValue;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.SKU_ATT_VALUE
   * 
   * @param skuAttValue the value for KMPRODUCT.PRODUCT_STOCK.SKU_ATT_VALUE
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setSkuAttValue(String skuAttValue) {
    this.skuAttValue = skuAttValue;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.STOCK_QUALITY
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.STOCK_QUALITY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public Integer getStockQuality() {
    return stockQuality;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.STOCK_QUALITY
   * 
   * @param stockQuality the value for KMPRODUCT.PRODUCT_STOCK.STOCK_QUALITY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setStockQuality(Integer stockQuality) {
    this.stockQuality = stockQuality;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.ORDER_QUALITY
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.ORDER_QUALITY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public Integer getOrderQuality() {
    return orderQuality;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.ORDER_QUALITY
   * 
   * @param orderQuality the value for KMPRODUCT.PRODUCT_STOCK.ORDER_QUALITY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setOrderQuality(Integer orderQuality) {
    this.orderQuality = orderQuality;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.IN_TRANSIT_QUALITY
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.IN_TRANSIT_QUALITY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public Integer getInTransitQuality() {
    return inTransitQuality;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.IN_TRANSIT_QUALITY
   * 
   * @param inTransitQuality the value for KMPRODUCT.PRODUCT_STOCK.IN_TRANSIT_QUALITY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setInTransitQuality(Integer inTransitQuality) {
    this.inTransitQuality = inTransitQuality;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.ALARM_QUALITY
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.ALARM_QUALITY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public Integer getAlarmQuality() {
    return alarmQuality;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.ALARM_QUALITY
   * 
   * @param alarmQuality the value for KMPRODUCT.PRODUCT_STOCK.ALARM_QUALITY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setAlarmQuality(Integer alarmQuality) {
    this.alarmQuality = alarmQuality;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.TOTAL_SALES
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.TOTAL_SALES
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public BigDecimal getTotalSales() {
    return totalSales;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.TOTAL_SALES
   * 
   * @param totalSales the value for KMPRODUCT.PRODUCT_STOCK.TOTAL_SALES
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setTotalSales(BigDecimal totalSales) {
    this.totalSales = totalSales;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.PRICE
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.PRICE
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public BigDecimal getPrice() {
    return price;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.PRICE
   * 
   * @param price the value for KMPRODUCT.PRODUCT_STOCK.PRICE
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.MIN_DAY
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.MIN_DAY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public BigDecimal getMinDay() {
    return minDay;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.MIN_DAY
   * 
   * @param minDay the value for KMPRODUCT.PRODUCT_STOCK.MIN_DAY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setMinDay(BigDecimal minDay) {
    this.minDay = minDay;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.MAX_DAY
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.MAX_DAY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public BigDecimal getMaxDay() {
    return maxDay;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.MAX_DAY
   * 
   * @param maxDay the value for KMPRODUCT.PRODUCT_STOCK.MAX_DAY
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setMaxDay(BigDecimal maxDay) {
    this.maxDay = maxDay;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.ADJUST
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.ADJUST
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public BigDecimal getAdjust() {
    return adjust;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.ADJUST
   * 
   * @param adjust the value for KMPRODUCT.PRODUCT_STOCK.ADJUST
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setAdjust(BigDecimal adjust) {
    this.adjust = adjust;
  }

  /**
   * This method was generated by Abator for iBATIS. This method returns the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.REMARK
   * 
   * @return the value of KMPRODUCT.PRODUCT_STOCK.REMARK
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public String getRemark() {
    return remark;
  }

  /**
   * This method was generated by Abator for iBATIS. This method sets the value of the database
   * column KMPRODUCT.PRODUCT_STOCK.REMARK
   * 
   * @param remark the value for KMPRODUCT.PRODUCT_STOCK.REMARK
   * 
   * @abatorgenerated Tue Oct 15 09:22:56 CST 2013
   */
  public void setRemark(String remark) {
    this.remark = remark;
  }
}
