package com.pltfm.app.vobject;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Category implements Serializable {
    private static final long serialVersionUID = -3391215868469980905L;

    private Integer categoryId;

    //子类
    private List<Category> subCategory;


    private Integer parentId;

    private Integer ll;


    private String categoryCode;


    private String categoryName;


    private Integer status;


    private Integer sortno;

    private String categoryDesc;


    private Date createTime;


    private Date modifTime;

    private Integer modifUser;


//    private String channel;


    private String execSql;

    


	private Integer isPhy;
    
    private String filePath;

    public String getFilePath() {
		return filePath;
	}


	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}
    public Integer getCategoryId() {
        return categoryId;
    }


    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CATEGORY.PARENT_ID
     *
     * @return the value of CATEGORY.PARENT_ID
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CATEGORY.PARENT_ID
     *
     * @param parentId the value for CATEGORY.PARENT_ID
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CATEGORY.CATEGORY_CODE
     *
     * @return the value of CATEGORY.CATEGORY_CODE
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CATEGORY.CATEGORY_CODE
     *
     * @param categoryCode the value for CATEGORY.CATEGORY_CODE
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CATEGORY.CATEGORY_NAME
     *
     * @return the value of CATEGORY.CATEGORY_NAME
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CATEGORY.CATEGORY_NAME
     *
     * @param categoryName the value for CATEGORY.CATEGORY_NAME
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CATEGORY.STATUS
     *
     * @return the value of CATEGORY.STATUS
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CATEGORY.STATUS
     *
     * @param status the value for CATEGORY.STATUS
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CATEGORY.SORTNO
     *
     * @return the value of CATEGORY.SORTNO
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public Integer getSortno() {
        return sortno;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CATEGORY.SORTNO
     *
     * @param sortno the value for CATEGORY.SORTNO
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public void setSortno(Integer sortno) {
        this.sortno = sortno;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CATEGORY.CATEGORY_DESC
     *
     * @return the value of CATEGORY.CATEGORY_DESC
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public String getCategoryDesc() {
        return categoryDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CATEGORY.CATEGORY_DESC
     *
     * @param categoryDesc the value for CATEGORY.CATEGORY_DESC
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public void setCategoryDesc(String categoryDesc) {
        this.categoryDesc = categoryDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CATEGORY.CREATE_TIME
     *
     * @return the value of CATEGORY.CREATE_TIME
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CATEGORY.CREATE_TIME
     *
     * @param createTime the value for CATEGORY.CREATE_TIME
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CATEGORY.MODIF_TIME
     *
     * @return the value of CATEGORY.MODIF_TIME
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public Date getModifTime() {
        return modifTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CATEGORY.MODIF_TIME
     *
     * @param modifTime the value for CATEGORY.MODIF_TIME
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public void setModifTime(Date modifTime) {
        this.modifTime = modifTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CATEGORY.MODIF_USER
     *
     * @return the value of CATEGORY.MODIF_USER
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public Integer getModifUser() {
        return modifUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CATEGORY.MODIF_USER
     *
     * @param modifUser the value for CATEGORY.MODIF_USER
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public void setModifUser(Integer modifUser) {
        this.modifUser = modifUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CATEGORY.CHANNEL
     *
     * @return the value of CATEGORY.CHANNEL
     *
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
//    public String getChannel() {
//        return channel;
//    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CATEGORY.CHANNEL
     *
     * @param channel the value for CATEGORY.CHANNEL
     *
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
//    public void setChannel(String channel) {
//        this.channel = channel;
//    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CATEGORY.EXEC_SQL
     *
     * @return the value of CATEGORY.EXEC_SQL
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public String getExecSql() {
        return execSql;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CATEGORY.EXEC_SQL
     *
     * @param execSql the value for CATEGORY.EXEC_SQL
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public void setExecSql(String execSql) {
        this.execSql = execSql;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CATEGORY.IS_PHY
     *
     * @return the value of CATEGORY.IS_PHY
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public Integer getIsPhy() {
        return isPhy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CATEGORY.IS_PHY
     *
     * @param isPhy the value for CATEGORY.IS_PHY
     * @abatorgenerated Fri Sep 06 16:24:19 CST 2013
     */
    public void setIsPhy(Integer isPhy) {
        this.isPhy = isPhy;
    }


    public List<Category> getSubCategory() {
        return subCategory;
    }


    public void setSubCategory(List<Category> subCategory) {
        this.subCategory = subCategory;
    }


    public Integer getLl() {
        return ll;
    }


    public void setLl(Integer ll) {
        this.ll = ll;
    }

}