package com.pltfm.app.vobject;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * 活动信息实体类
 *
 * @author cjm
 * @since 2013-9-3
 */
public class ViewPromotion implements Serializable {
    private static final long serialVersionUID = -8228448004858780065L;

    private List promotionIds; //活动ID集合
    private List promotionIdsSort;//活动ID集合排序
    /**
     * 结束时间页面显示
     */
    private String endTimePage;
    /**
     * 起始时间页面显示
     */
    private String startTimePage;
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_ID
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private Integer promotionId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_NAME
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private String promotionName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.SLOGAN
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private String slogan;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_DESCRIBE
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private String promotionDescribe;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.STATUS
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private Integer status;

    private Integer onlineStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.IS_USE_COUPON
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private Integer isUseCoupon;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.START_TIME
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private Date startTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.END_TIME
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private Date endTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.MUTEX_PROMOTION_ID
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private String mutexPromotionId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_PRIORITY
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private Integer promotionPriority;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_RULE_ID
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private Integer promotionRuleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PRODUCT_FILTER_TYPE
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private Integer productFilterType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PRODUCT_FILTER_SQL
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private String productFilterSql;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.CREATER_USER
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private Integer createrUser;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.CREATETIME
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private Date createtime;

    private String promotionTitle;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_RULE_RULE_NAME
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private String promotionRuleRuleName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_RULE_EXPRESSION
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private String promotionRuleExpression;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_TYPE_ID
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private Integer promotionTypeId;

    private List<Integer> promotionTypeIdList;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_TYPE_NAME
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private String promotionTypeName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_ATTR_ID
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private Integer promotionAttrId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_IMG_FIRST
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private String promotionImgFirst;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_IMG_SECOND
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private String promotionImgSecond;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_URL
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private String promotionUrl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_TINY_ICON
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private String promotionTinyIcon;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_BIG_ICON
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private String promotionBigIcon;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_TAG
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private String promotionTag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_REMARK1
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private String promotionRemark1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column VIEW_PROMOTION.PROMOTION_REMARK2
     *
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    private String promotionRemark2;

    /**
     * 开始索引值
     */
    private Integer startIndex;
    /**
     * 结束索引值
     */
    private Integer endIndex;

    /**
     * 标志
     */
    private Integer flag;

    /**
     * 活动类型
     */
    private String promotionType;

    private String path;
    /**
     * 过期标志
     */
    private Integer expiredFlag;

    /**
     * 当前系统时间
     */
    private Date nowTime;

    public Date getNowTime() {
        return nowTime;
    }

    public void setNowTime(Date nowTime) {
        this.nowTime = nowTime;
    }

    public Integer getExpiredFlag() {
        return expiredFlag;
    }

    public void setExpiredFlag(Integer expiredFlag) {
        this.expiredFlag = expiredFlag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_ID
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_ID
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public Integer getPromotionId() {
        return promotionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_ID
     *
     * @param promotionId the value for VIEW_PROMOTION.PROMOTION_ID
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionId(Integer promotionId) {
        this.promotionId = promotionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_NAME
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_NAME
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public String getPromotionName() {
        return promotionName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_NAME
     *
     * @param promotionName the value for VIEW_PROMOTION.PROMOTION_NAME
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionName(String promotionName) {
        this.promotionName = promotionName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.SLOGAN
     *
     * @return the value of VIEW_PROMOTION.SLOGAN
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public String getSlogan() {
        return slogan;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.SLOGAN
     *
     * @param slogan the value for VIEW_PROMOTION.SLOGAN
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setSlogan(String slogan) {
        this.slogan = slogan;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_DESCRIBE
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_DESCRIBE
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public String getPromotionDescribe() {
        return promotionDescribe;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_DESCRIBE
     *
     * @param promotionDescribe the value for VIEW_PROMOTION.PROMOTION_DESCRIBE
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionDescribe(String promotionDescribe) {
        this.promotionDescribe = promotionDescribe;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.STATUS
     *
     * @return the value of VIEW_PROMOTION.STATUS
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.STATUS
     *
     * @param status the value for VIEW_PROMOTION.STATUS
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.IS_USE_COUPON
     *
     * @return the value of VIEW_PROMOTION.IS_USE_COUPON
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public Integer getIsUseCoupon() {
        return isUseCoupon;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.IS_USE_COUPON
     *
     * @param isUseCoupon the value for VIEW_PROMOTION.IS_USE_COUPON
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setIsUseCoupon(Integer isUseCoupon) {
        this.isUseCoupon = isUseCoupon;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.START_TIME
     *
     * @return the value of VIEW_PROMOTION.START_TIME
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.START_TIME
     *
     * @param startTime the value for VIEW_PROMOTION.START_TIME
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.END_TIME
     *
     * @return the value of VIEW_PROMOTION.END_TIME
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.END_TIME
     *
     * @param endTime the value for VIEW_PROMOTION.END_TIME
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.MUTEX_PROMOTION_ID
     *
     * @return the value of VIEW_PROMOTION.MUTEX_PROMOTION_ID
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public String getMutexPromotionId() {
        return mutexPromotionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.MUTEX_PROMOTION_ID
     *
     * @param mutexPromotionId the value for VIEW_PROMOTION.MUTEX_PROMOTION_ID
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setMutexPromotionId(String mutexPromotionId) {
        this.mutexPromotionId = mutexPromotionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_PRIORITY
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_PRIORITY
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public Integer getPromotionPriority() {
        return promotionPriority;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_PRIORITY
     *
     * @param promotionPriority the value for VIEW_PROMOTION.PROMOTION_PRIORITY
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionPriority(Integer promotionPriority) {
        this.promotionPriority = promotionPriority;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_RULE_ID
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_RULE_ID
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public Integer getPromotionRuleId() {
        return promotionRuleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_RULE_ID
     *
     * @param promotionRuleId the value for VIEW_PROMOTION.PROMOTION_RULE_ID
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionRuleId(Integer promotionRuleId) {
        this.promotionRuleId = promotionRuleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PRODUCT_FILTER_TYPE
     *
     * @return the value of VIEW_PROMOTION.PRODUCT_FILTER_TYPE
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public Integer getProductFilterType() {
        return productFilterType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PRODUCT_FILTER_TYPE
     *
     * @param productFilterType the value for VIEW_PROMOTION.PRODUCT_FILTER_TYPE
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setProductFilterType(Integer productFilterType) {
        this.productFilterType = productFilterType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PRODUCT_FILTER_SQL
     *
     * @return the value of VIEW_PROMOTION.PRODUCT_FILTER_SQL
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public String getProductFilterSql() {
        return productFilterSql;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PRODUCT_FILTER_SQL
     *
     * @param productFilterSql the value for VIEW_PROMOTION.PRODUCT_FILTER_SQL
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setProductFilterSql(String productFilterSql) {
        this.productFilterSql = productFilterSql;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.CREATER_USER
     *
     * @return the value of VIEW_PROMOTION.CREATER_USER
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public Integer getCreaterUser() {
        return createrUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.CREATER_USER
     *
     * @param createrUser the value for VIEW_PROMOTION.CREATER_USER
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setCreaterUser(Integer createrUser) {
        this.createrUser = createrUser;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.CREATETIME
     *
     * @return the value of VIEW_PROMOTION.CREATETIME
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.CREATETIME
     *
     * @param createtime the value for VIEW_PROMOTION.CREATETIME
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public String getPromotionTitle() {
        return promotionTitle;
    }

    public void setPromotionTitle(String promotionTitle) {
        this.promotionTitle = promotionTitle;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_RULE_RULE_NAME
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_RULE_RULE_NAME
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public String getPromotionRuleRuleName() {
        return promotionRuleRuleName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_RULE_RULE_NAME
     *
     * @param promotionRuleRuleName the value for VIEW_PROMOTION.PROMOTION_RULE_RULE_NAME
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionRuleRuleName(String promotionRuleRuleName) {
        this.promotionRuleRuleName = promotionRuleRuleName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_RULE_EXPRESSION
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_RULE_EXPRESSION
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public String getPromotionRuleExpression() {
        return promotionRuleExpression;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_RULE_EXPRESSION
     *
     * @param promotionRuleExpression the value for VIEW_PROMOTION.PROMOTION_RULE_EXPRESSION
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionRuleExpression(String promotionRuleExpression) {
        this.promotionRuleExpression = promotionRuleExpression;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_TYPE_ID
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_TYPE_ID
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public Integer getPromotionTypeId() {
        return promotionTypeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_TYPE_ID
     *
     * @param promotionTypeId the value for VIEW_PROMOTION.PROMOTION_TYPE_ID
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionTypeId(Integer promotionTypeId) {
        this.promotionTypeId = promotionTypeId;
    }

    public List<Integer> getPromotionTypeIdList() {
        return promotionTypeIdList;
    }

    public void setPromotionTypeIdList(List<Integer> promotionTypeIdList) {
        this.promotionTypeIdList = promotionTypeIdList;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_TYPE_NAME
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_TYPE_NAME
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public String getPromotionTypeName() {
        return promotionTypeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_TYPE_NAME
     *
     * @param promotionTypeName the value for VIEW_PROMOTION.PROMOTION_TYPE_NAME
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionTypeName(String promotionTypeName) {
        this.promotionTypeName = promotionTypeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_ATTR_ID
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_ATTR_ID
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public Integer getPromotionAttrId() {
        return promotionAttrId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_ATTR_ID
     *
     * @param promotionAttrId the value for VIEW_PROMOTION.PROMOTION_ATTR_ID
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionAttrId(Integer promotionAttrId) {
        this.promotionAttrId = promotionAttrId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_IMG_FIRST
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_IMG_FIRST
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public String getPromotionImgFirst() {
        return promotionImgFirst;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_IMG_FIRST
     *
     * @param promotionImgFirst the value for VIEW_PROMOTION.PROMOTION_IMG_FIRST
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionImgFirst(String promotionImgFirst) {
        this.promotionImgFirst = promotionImgFirst;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_IMG_SECOND
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_IMG_SECOND
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public String getPromotionImgSecond() {
        return promotionImgSecond;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_IMG_SECOND
     *
     * @param promotionImgSecond the value for VIEW_PROMOTION.PROMOTION_IMG_SECOND
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionImgSecond(String promotionImgSecond) {
        this.promotionImgSecond = promotionImgSecond;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_URL
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_URL
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public String getPromotionUrl() {
        return promotionUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_URL
     *
     * @param promotionUrl the value for VIEW_PROMOTION.PROMOTION_URL
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionUrl(String promotionUrl) {
        this.promotionUrl = promotionUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_TINY_ICON
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_TINY_ICON
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public String getPromotionTinyIcon() {
        return promotionTinyIcon;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_TINY_ICON
     *
     * @param promotionTinyIcon the value for VIEW_PROMOTION.PROMOTION_TINY_ICON
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionTinyIcon(String promotionTinyIcon) {
        this.promotionTinyIcon = promotionTinyIcon;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_BIG_ICON
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_BIG_ICON
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public String getPromotionBigIcon() {
        return promotionBigIcon;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_BIG_ICON
     *
     * @param promotionBigIcon the value for VIEW_PROMOTION.PROMOTION_BIG_ICON
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionBigIcon(String promotionBigIcon) {
        this.promotionBigIcon = promotionBigIcon;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_TAG
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_TAG
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public String getPromotionTag() {
        return promotionTag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_TAG
     *
     * @param promotionTag the value for VIEW_PROMOTION.PROMOTION_TAG
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionTag(String promotionTag) {
        this.promotionTag = promotionTag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_REMARK1
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_REMARK1
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public String getPromotionRemark1() {
        return promotionRemark1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_REMARK1
     *
     * @param promotionRemark1 the value for VIEW_PROMOTION.PROMOTION_REMARK1
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionRemark1(String promotionRemark1) {
        this.promotionRemark1 = promotionRemark1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column VIEW_PROMOTION.PROMOTION_REMARK2
     *
     * @return the value of VIEW_PROMOTION.PROMOTION_REMARK2
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public String getPromotionRemark2() {
        return promotionRemark2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column VIEW_PROMOTION.PROMOTION_REMARK2
     *
     * @param promotionRemark2 the value for VIEW_PROMOTION.PROMOTION_REMARK2
     * @abatorgenerated Tue Sep 03 16:15:27 CST 2013
     */
    public void setPromotionRemark2(String promotionRemark2) {
        this.promotionRemark2 = promotionRemark2;
    }

    public Integer getStartIndex() {
        return startIndex;
    }

    public void setStartIndex(Integer startIndex) {
        this.startIndex = startIndex;
    }

    public Integer getEndIndex() {
        return endIndex;
    }

    public void setEndIndex(Integer endIndex) {
        this.endIndex = endIndex;
    }

    public String getEndTimePage() {
        return endTimePage;
    }

    public void setEndTimePage(String endTimePage) {
        this.endTimePage = endTimePage;
    }

    public String getStartTimePage() {
        return startTimePage;
    }

    public void setStartTimePage(String startTimePage) {
        this.startTimePage = startTimePage;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Integer getFlag() {
        return flag;
    }

    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    public String getPromotionType() {
        return promotionType;
    }

    public void setPromotionType(String promotionType) {
        this.promotionType = promotionType;
    }


    public Integer getOnlineStatus() {
        return onlineStatus;
    }

    public void setOnlineStatus(Integer onlineStatus) {
        this.onlineStatus = onlineStatus;
    }

    public List getPromotionIds() {
        return promotionIds;
    }

    public void setPromotionIds(List promotionIds) {
        this.promotionIds = promotionIds;
    }

    public List getPromotionIdsSort() {
        return promotionIdsSort;
    }

    public void setPromotionIdsSort(List promotionIdsSort) {
        this.promotionIdsSort = promotionIdsSort;
    }


}