package com.pltfm.app.vobject;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ViewProductInfoExample implements Serializable {
    private static final long serialVersionUID = 1614554739474882064L;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table VIEW_PRODUCT_INFO
     *
     * @abatorgenerated Wed Sep 18 15:15:58 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table VIEW_PRODUCT_INFO
     *
     * @abatorgenerated Wed Sep 18 15:15:58 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table VIEW_PRODUCT_INFO
     *
     * @abatorgenerated Wed Sep 18 15:15:58 CST 2013
     */
    public ViewProductInfoExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table VIEW_PRODUCT_INFO
     *
     * @abatorgenerated Wed Sep 18 15:15:58 CST 2013
     */
    protected ViewProductInfoExample(ViewProductInfoExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table VIEW_PRODUCT_INFO
     *
     * @abatorgenerated Wed Sep 18 15:15:58 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table VIEW_PRODUCT_INFO
     *
     * @abatorgenerated Wed Sep 18 15:15:58 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table VIEW_PRODUCT_INFO
     *
     * @abatorgenerated Wed Sep 18 15:15:58 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table VIEW_PRODUCT_INFO
     *
     * @abatorgenerated Wed Sep 18 15:15:58 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table VIEW_PRODUCT_INFO
     *
     * @abatorgenerated Wed Sep 18 15:15:58 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table VIEW_PRODUCT_INFO
     *
     * @abatorgenerated Wed Sep 18 15:15:58 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table VIEW_PRODUCT_INFO
     *
     * @abatorgenerated Wed Sep 18 15:15:58 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table VIEW_PRODUCT_INFO
     *
     * @abatorgenerated Wed Sep 18 15:15:58 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                    || criteriaWithSingleValue.size() > 0
                    || criteriaWithListValue.size() > 0
                    || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andProductIdIsNull() {
            addCriterion("PRODUCT_ID is null");
            return this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("PRODUCT_ID is not null");
            return this;
        }

        public Criteria andProductIdEqualTo(Integer value) {
            addCriterion("PRODUCT_ID =", value, "productId");
            return this;
        }

        public Criteria andProductIdNotEqualTo(Integer value) {
            addCriterion("PRODUCT_ID <>", value, "productId");
            return this;
        }

        public Criteria andProductIdGreaterThan(Integer value) {
            addCriterion("PRODUCT_ID >", value, "productId");
            return this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRODUCT_ID >=", value, "productId");
            return this;
        }

        public Criteria andProductIdLessThan(Integer value) {
            addCriterion("PRODUCT_ID <", value, "productId");
            return this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("PRODUCT_ID <=", value, "productId");
            return this;
        }

        public Criteria andProductIdIn(List values) {
            addCriterion("PRODUCT_ID in", values, "productId");
            return this;
        }

        public Criteria andProductIdNotIn(List values) {
            addCriterion("PRODUCT_ID not in", values, "productId");
            return this;
        }

        public Criteria andProductIdBetween(Integer value1, Integer value2) {
            addCriterion("PRODUCT_ID between", value1, value2, "productId");
            return this;
        }

        public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PRODUCT_ID not between", value1, value2, "productId");
            return this;
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("CATEGORY_ID is null");
            return this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("CATEGORY_ID is not null");
            return this;
        }

        public Criteria andCategoryIdEqualTo(Integer value) {
            addCriterion("CATEGORY_ID =", value, "categoryId");
            return this;
        }

        public Criteria andCategoryIdNotEqualTo(Integer value) {
            addCriterion("CATEGORY_ID <>", value, "categoryId");
            return this;
        }

        public Criteria andCategoryIdGreaterThan(Integer value) {
            addCriterion("CATEGORY_ID >", value, "categoryId");
            return this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CATEGORY_ID >=", value, "categoryId");
            return this;
        }

        public Criteria andCategoryIdLessThan(Integer value) {
            addCriterion("CATEGORY_ID <", value, "categoryId");
            return this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("CATEGORY_ID <=", value, "categoryId");
            return this;
        }

        public Criteria andCategoryIdIn(List values) {
            addCriterion("CATEGORY_ID in", values, "categoryId");
            return this;
        }

        public Criteria andCategoryIdNotIn(List values) {
            addCriterion("CATEGORY_ID not in", values, "categoryId");
            return this;
        }

        public Criteria andCategoryIdBetween(Integer value1, Integer value2) {
            addCriterion("CATEGORY_ID between", value1, value2, "categoryId");
            return this;
        }

        public Criteria andCategoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CATEGORY_ID not between", value1, value2, "categoryId");
            return this;
        }

        public Criteria andCategoryNameIsNull() {
            addCriterion("CATEGORY_NAME is null");
            return this;
        }

        public Criteria andCategoryNameIsNotNull() {
            addCriterion("CATEGORY_NAME is not null");
            return this;
        }

        public Criteria andCategoryNameEqualTo(String value) {
            addCriterion("CATEGORY_NAME =", value, "categoryName");
            return this;
        }

        public Criteria andCategoryNameNotEqualTo(String value) {
            addCriterion("CATEGORY_NAME <>", value, "categoryName");
            return this;
        }

        public Criteria andCategoryNameGreaterThan(String value) {
            addCriterion("CATEGORY_NAME >", value, "categoryName");
            return this;
        }

        public Criteria andCategoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("CATEGORY_NAME >=", value, "categoryName");
            return this;
        }

        public Criteria andCategoryNameLessThan(String value) {
            addCriterion("CATEGORY_NAME <", value, "categoryName");
            return this;
        }

        public Criteria andCategoryNameLessThanOrEqualTo(String value) {
            addCriterion("CATEGORY_NAME <=", value, "categoryName");
            return this;
        }

        public Criteria andCategoryNameLike(String value) {
            addCriterion("CATEGORY_NAME like", value, "categoryName");
            return this;
        }

        public Criteria andCategoryNameNotLike(String value) {
            addCriterion("CATEGORY_NAME not like", value, "categoryName");
            return this;
        }

        public Criteria andCategoryNameIn(List values) {
            addCriterion("CATEGORY_NAME in", values, "categoryName");
            return this;
        }

        public Criteria andCategoryNameNotIn(List values) {
            addCriterion("CATEGORY_NAME not in", values, "categoryName");
            return this;
        }

        public Criteria andCategoryNameBetween(String value1, String value2) {
            addCriterion("CATEGORY_NAME between", value1, value2, "categoryName");
            return this;
        }

        public Criteria andCategoryNameNotBetween(String value1, String value2) {
            addCriterion("CATEGORY_NAME not between", value1, value2, "categoryName");
            return this;
        }

        public Criteria andProcuctNameIsNull() {
            addCriterion("PROCUCT_NAME is null");
            return this;
        }

        public Criteria andProcuctNameIsNotNull() {
            addCriterion("PROCUCT_NAME is not null");
            return this;
        }

        public Criteria andProcuctNameEqualTo(String value) {
            addCriterion("PROCUCT_NAME =", value, "procuctName");
            return this;
        }

        public Criteria andProcuctNameNotEqualTo(String value) {
            addCriterion("PROCUCT_NAME <>", value, "procuctName");
            return this;
        }

        public Criteria andProcuctNameGreaterThan(String value) {
            addCriterion("PROCUCT_NAME >", value, "procuctName");
            return this;
        }

        public Criteria andProcuctNameGreaterThanOrEqualTo(String value) {
            addCriterion("PROCUCT_NAME >=", value, "procuctName");
            return this;
        }

        public Criteria andProcuctNameLessThan(String value) {
            addCriterion("PROCUCT_NAME <", value, "procuctName");
            return this;
        }

        public Criteria andProcuctNameLessThanOrEqualTo(String value) {
            addCriterion("PROCUCT_NAME <=", value, "procuctName");
            return this;
        }

        public Criteria andProcuctNameLike(String value) {
            addCriterion("PROCUCT_NAME like", value, "procuctName");
            return this;
        }

        public Criteria andProcuctNameNotLike(String value) {
            addCriterion("PROCUCT_NAME not like", value, "procuctName");
            return this;
        }

        public Criteria andProcuctNameIn(List values) {
            addCriterion("PROCUCT_NAME in", values, "procuctName");
            return this;
        }

        public Criteria andProcuctNameNotIn(List values) {
            addCriterion("PROCUCT_NAME not in", values, "procuctName");
            return this;
        }

        public Criteria andProcuctNameBetween(String value1, String value2) {
            addCriterion("PROCUCT_NAME between", value1, value2, "procuctName");
            return this;
        }

        public Criteria andProcuctNameNotBetween(String value1, String value2) {
            addCriterion("PROCUCT_NAME not between", value1, value2, "procuctName");
            return this;
        }

        public Criteria andProductTitleIsNull() {
            addCriterion("PRODUCT_TITLE is null");
            return this;
        }

        public Criteria andProductTitleIsNotNull() {
            addCriterion("PRODUCT_TITLE is not null");
            return this;
        }

        public Criteria andProductTitleEqualTo(String value) {
            addCriterion("PRODUCT_TITLE =", value, "productTitle");
            return this;
        }

        public Criteria andProductTitleNotEqualTo(String value) {
            addCriterion("PRODUCT_TITLE <>", value, "productTitle");
            return this;
        }

        public Criteria andProductTitleGreaterThan(String value) {
            addCriterion("PRODUCT_TITLE >", value, "productTitle");
            return this;
        }

        public Criteria andProductTitleGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_TITLE >=", value, "productTitle");
            return this;
        }

        public Criteria andProductTitleLessThan(String value) {
            addCriterion("PRODUCT_TITLE <", value, "productTitle");
            return this;
        }

        public Criteria andProductTitleLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_TITLE <=", value, "productTitle");
            return this;
        }

        public Criteria andProductTitleLike(String value) {
            addCriterion("PRODUCT_TITLE like", value, "productTitle");
            return this;
        }

        public Criteria andProductTitleNotLike(String value) {
            addCriterion("PRODUCT_TITLE not like", value, "productTitle");
            return this;
        }

        public Criteria andProductTitleIn(List values) {
            addCriterion("PRODUCT_TITLE in", values, "productTitle");
            return this;
        }

        public Criteria andProductTitleNotIn(List values) {
            addCriterion("PRODUCT_TITLE not in", values, "productTitle");
            return this;
        }

        public Criteria andProductTitleBetween(String value1, String value2) {
            addCriterion("PRODUCT_TITLE between", value1, value2, "productTitle");
            return this;
        }

        public Criteria andProductTitleNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_TITLE not between", value1, value2, "productTitle");
            return this;
        }

        public Criteria andKeywordIsNull() {
            addCriterion("KEYWORD is null");
            return this;
        }

        public Criteria andKeywordIsNotNull() {
            addCriterion("KEYWORD is not null");
            return this;
        }

        public Criteria andKeywordEqualTo(String value) {
            addCriterion("KEYWORD =", value, "keyword");
            return this;
        }

        public Criteria andKeywordNotEqualTo(String value) {
            addCriterion("KEYWORD <>", value, "keyword");
            return this;
        }

        public Criteria andKeywordGreaterThan(String value) {
            addCriterion("KEYWORD >", value, "keyword");
            return this;
        }

        public Criteria andKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("KEYWORD >=", value, "keyword");
            return this;
        }

        public Criteria andKeywordLessThan(String value) {
            addCriterion("KEYWORD <", value, "keyword");
            return this;
        }

        public Criteria andKeywordLessThanOrEqualTo(String value) {
            addCriterion("KEYWORD <=", value, "keyword");
            return this;
        }

        public Criteria andKeywordLike(String value) {
            addCriterion("KEYWORD like", value, "keyword");
            return this;
        }

        public Criteria andKeywordNotLike(String value) {
            addCriterion("KEYWORD not like", value, "keyword");
            return this;
        }

        public Criteria andKeywordIn(List values) {
            addCriterion("KEYWORD in", values, "keyword");
            return this;
        }

        public Criteria andKeywordNotIn(List values) {
            addCriterion("KEYWORD not in", values, "keyword");
            return this;
        }

        public Criteria andKeywordBetween(String value1, String value2) {
            addCriterion("KEYWORD between", value1, value2, "keyword");
            return this;
        }

        public Criteria andKeywordNotBetween(String value1, String value2) {
            addCriterion("KEYWORD not between", value1, value2, "keyword");
            return this;
        }

        public Criteria andProducthotIsNull() {
            addCriterion("PRODUCTHOT is null");
            return this;
        }

        public Criteria andProducthotIsNotNull() {
            addCriterion("PRODUCTHOT is not null");
            return this;
        }

        public Criteria andProducthotEqualTo(Integer value) {
            addCriterion("PRODUCTHOT =", value, "producthot");
            return this;
        }

        public Criteria andProducthotNotEqualTo(Integer value) {
            addCriterion("PRODUCTHOT <>", value, "producthot");
            return this;
        }

        public Criteria andProducthotGreaterThan(Integer value) {
            addCriterion("PRODUCTHOT >", value, "producthot");
            return this;
        }

        public Criteria andProducthotGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRODUCTHOT >=", value, "producthot");
            return this;
        }

        public Criteria andProducthotLessThan(Integer value) {
            addCriterion("PRODUCTHOT <", value, "producthot");
            return this;
        }

        public Criteria andProducthotLessThanOrEqualTo(Integer value) {
            addCriterion("PRODUCTHOT <=", value, "producthot");
            return this;
        }

        public Criteria andProducthotIn(List values) {
            addCriterion("PRODUCTHOT in", values, "producthot");
            return this;
        }

        public Criteria andProducthotNotIn(List values) {
            addCriterion("PRODUCTHOT not in", values, "producthot");
            return this;
        }

        public Criteria andProducthotBetween(Integer value1, Integer value2) {
            addCriterion("PRODUCTHOT between", value1, value2, "producthot");
            return this;
        }

        public Criteria andProducthotNotBetween(Integer value1, Integer value2) {
            addCriterion("PRODUCTHOT not between", value1, value2, "producthot");
            return this;
        }

        public Criteria andShopCodeIsNull() {
            addCriterion("SHOP_CODE is null");
            return this;
        }

        public Criteria andShopCodeIsNotNull() {
            addCriterion("SHOP_CODE is not null");
            return this;
        }

        public Criteria andShopCodeEqualTo(String value) {
            addCriterion("SHOP_CODE =", value, "shopCode");
            return this;
        }

        public Criteria andShopCodeNotEqualTo(String value) {
            addCriterion("SHOP_CODE <>", value, "shopCode");
            return this;
        }

        public Criteria andShopCodeGreaterThan(String value) {
            addCriterion("SHOP_CODE >", value, "shopCode");
            return this;
        }

        public Criteria andShopCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SHOP_CODE >=", value, "shopCode");
            return this;
        }

        public Criteria andShopCodeLessThan(String value) {
            addCriterion("SHOP_CODE <", value, "shopCode");
            return this;
        }

        public Criteria andShopCodeLessThanOrEqualTo(String value) {
            addCriterion("SHOP_CODE <=", value, "shopCode");
            return this;
        }

        public Criteria andShopCodeLike(String value) {
            addCriterion("SHOP_CODE like", value, "shopCode");
            return this;
        }

        public Criteria andShopCodeNotLike(String value) {
            addCriterion("SHOP_CODE not like", value, "shopCode");
            return this;
        }

        public Criteria andShopCodeIn(List values) {
            addCriterion("SHOP_CODE in", values, "shopCode");
            return this;
        }

        public Criteria andShopCodeNotIn(List values) {
            addCriterion("SHOP_CODE not in", values, "shopCode");
            return this;
        }

        public Criteria andShopCodeBetween(String value1, String value2) {
            addCriterion("SHOP_CODE between", value1, value2, "shopCode");
            return this;
        }

        public Criteria andShopCodeNotBetween(String value1, String value2) {
            addCriterion("SHOP_CODE not between", value1, value2, "shopCode");
            return this;
        }


        public Criteria andMarketPriceIsNull() {
            addCriterion("MARKET_PRICE is null");
            return this;
        }

        public Criteria andMarketPriceIsNotNull() {
            addCriterion("MARKET_PRICE is not null");
            return this;
        }

        public Criteria andMarketPriceEqualTo(Integer value) {
            addCriterion("MARKET_PRICE =", value, "marketPrice");
            return this;
        }

        public Criteria andMarketPriceNotEqualTo(Integer value) {
            addCriterion("MARKET_PRICE <>", value, "marketPrice");
            return this;
        }

        public Criteria andMarketPriceGreaterThan(Integer value) {
            addCriterion("MARKET_PRICE >", value, "marketPrice");
            return this;
        }

        public Criteria andMarketPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("MARKET_PRICE >=", value, "marketPrice");
            return this;
        }

        public Criteria andMarketPriceLessThan(Integer value) {
            addCriterion("MARKET_PRICE <", value, "marketPrice");
            return this;
        }

        public Criteria andMarketPriceLessThanOrEqualTo(Integer value) {
            addCriterion("MARKET_PRICE <=", value, "marketPrice");
            return this;
        }

        public Criteria andMarketPriceIn(List values) {
            addCriterion("MARKET_PRICE in", values, "marketPrice");
            return this;
        }

        public Criteria andMarketPriceNotIn(List values) {
            addCriterion("MARKET_PRICE not in", values, "marketPrice");
            return this;
        }

        public Criteria andMarketPriceBetween(Integer value1, Integer value2) {
            addCriterion("MARKET_PRICE between", value1, value2, "marketPrice");
            return this;
        }

        public Criteria andMarketPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("MARKET_PRICE not between", value1, value2, "marketPrice");
            return this;
        }

        public Criteria andProductNoIsNull() {
            addCriterion("PRODUCT_NO is null");
            return this;
        }

        public Criteria andProductNoIsNotNull() {
            addCriterion("PRODUCT_NO is not null");
            return this;
        }

        public Criteria andProductNoEqualTo(String value) {
            addCriterion("PRODUCT_NO =", value, "productNo");
            return this;
        }

        public Criteria andProductNoNotEqualTo(String value) {
            addCriterion("PRODUCT_NO <>", value, "productNo");
            return this;
        }

        public Criteria andProductNoGreaterThan(String value) {
            addCriterion("PRODUCT_NO >", value, "productNo");
            return this;
        }

        public Criteria andProductNoGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_NO >=", value, "productNo");
            return this;
        }

        public Criteria andProductNoLessThan(String value) {
            addCriterion("PRODUCT_NO <", value, "productNo");
            return this;
        }

        public Criteria andProductNoLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_NO <=", value, "productNo");
            return this;
        }

        public Criteria andProductNoLike(String value) {
            addCriterion("PRODUCT_NO like", value, "productNo");
            return this;
        }

        public Criteria andProductNoNotLike(String value) {
            addCriterion("PRODUCT_NO not like", value, "productNo");
            return this;
        }

        public Criteria andProductNoIn(List values) {
            addCriterion("PRODUCT_NO in", values, "productNo");
            return this;
        }

        public Criteria andProductNoNotIn(List values) {
            addCriterion("PRODUCT_NO not in", values, "productNo");
            return this;
        }

        public Criteria andProductNoBetween(String value1, String value2) {
            addCriterion("PRODUCT_NO between", value1, value2, "productNo");
            return this;
        }

        public Criteria andProductNoNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_NO not between", value1, value2, "productNo");
            return this;
        }

        public Criteria andBrandIdIsNull() {
            addCriterion("BRAND_ID is null");
            return this;
        }

        public Criteria andBrandIdIsNotNull() {
            addCriterion("BRAND_ID is not null");
            return this;
        }

        public Criteria andBrandIdEqualTo(Integer value) {
            addCriterion("BRAND_ID =", value, "brandId");
            return this;
        }

        public Criteria andBrandIdNotEqualTo(Integer value) {
            addCriterion("BRAND_ID <>", value, "brandId");
            return this;
        }

        public Criteria andBrandIdGreaterThan(Integer value) {
            addCriterion("BRAND_ID >", value, "brandId");
            return this;
        }

        public Criteria andBrandIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("BRAND_ID >=", value, "brandId");
            return this;
        }

        public Criteria andBrandIdLessThan(Integer value) {
            addCriterion("BRAND_ID <", value, "brandId");
            return this;
        }

        public Criteria andBrandIdLessThanOrEqualTo(Integer value) {
            addCriterion("BRAND_ID <=", value, "brandId");
            return this;
        }

        public Criteria andBrandIdIn(List values) {
            addCriterion("BRAND_ID in", values, "brandId");
            return this;
        }

        public Criteria andBrandIdNotIn(List values) {
            addCriterion("BRAND_ID not in", values, "brandId");
            return this;
        }

        public Criteria andBrandIdBetween(Integer value1, Integer value2) {
            addCriterion("BRAND_ID between", value1, value2, "brandId");
            return this;
        }

        public Criteria andBrandIdNotBetween(Integer value1, Integer value2) {
            addCriterion("BRAND_ID not between", value1, value2, "brandId");
            return this;
        }

        public Criteria andBrandNameIsNull() {
            addCriterion("BRAND_NAME is null");
            return this;
        }

        public Criteria andBrandNameIsNotNull() {
            addCriterion("BRAND_NAME is not null");
            return this;
        }

        public Criteria andBrandNameEqualTo(String value) {
            addCriterion("BRAND_NAME =", value, "brandName");
            return this;
        }

        public Criteria andBrandNameNotEqualTo(String value) {
            addCriterion("BRAND_NAME <>", value, "brandName");
            return this;
        }

        public Criteria andBrandNameGreaterThan(String value) {
            addCriterion("BRAND_NAME >", value, "brandName");
            return this;
        }

        public Criteria andBrandNameGreaterThanOrEqualTo(String value) {
            addCriterion("BRAND_NAME >=", value, "brandName");
            return this;
        }

        public Criteria andBrandNameLessThan(String value) {
            addCriterion("BRAND_NAME <", value, "brandName");
            return this;
        }

        public Criteria andBrandNameLessThanOrEqualTo(String value) {
            addCriterion("BRAND_NAME <=", value, "brandName");
            return this;
        }

        public Criteria andBrandNameLike(String value) {
            addCriterion("BRAND_NAME like", value, "brandName");
            return this;
        }

        public Criteria andBrandNameNotLike(String value) {
            addCriterion("BRAND_NAME not like", value, "brandName");
            return this;
        }

        public Criteria andBrandNameIn(List values) {
            addCriterion("BRAND_NAME in", values, "brandName");
            return this;
        }

        public Criteria andBrandNameNotIn(List values) {
            addCriterion("BRAND_NAME not in", values, "brandName");
            return this;
        }

        public Criteria andBrandNameBetween(String value1, String value2) {
            addCriterion("BRAND_NAME between", value1, value2, "brandName");
            return this;
        }

        public Criteria andBrandNameNotBetween(String value1, String value2) {
            addCriterion("BRAND_NAME not between", value1, value2, "brandName");
            return this;
        }

        public Criteria andApprovalTypeIsNull() {
            addCriterion("APPROVAL_TYPE is null");
            return this;
        }

        public Criteria andApprovalTypeIsNotNull() {
            addCriterion("APPROVAL_TYPE is not null");
            return this;
        }

        public Criteria andApprovalTypeEqualTo(Integer value) {
            addCriterion("APPROVAL_TYPE =", value, "approvalType");
            return this;
        }

        public Criteria andApprovalTypeNotEqualTo(Integer value) {
            addCriterion("APPROVAL_TYPE <>", value, "approvalType");
            return this;
        }

        public Criteria andApprovalTypeGreaterThan(Integer value) {
            addCriterion("APPROVAL_TYPE >", value, "approvalType");
            return this;
        }

        public Criteria andApprovalTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("APPROVAL_TYPE >=", value, "approvalType");
            return this;
        }

        public Criteria andApprovalTypeLessThan(Integer value) {
            addCriterion("APPROVAL_TYPE <", value, "approvalType");
            return this;
        }

        public Criteria andApprovalTypeLessThanOrEqualTo(Integer value) {
            addCriterion("APPROVAL_TYPE <=", value, "approvalType");
            return this;
        }

        public Criteria andApprovalTypeIn(List values) {
            addCriterion("APPROVAL_TYPE in", values, "approvalType");
            return this;
        }

        public Criteria andApprovalTypeNotIn(List values) {
            addCriterion("APPROVAL_TYPE not in", values, "approvalType");
            return this;
        }

        public Criteria andApprovalTypeBetween(Integer value1, Integer value2) {
            addCriterion("APPROVAL_TYPE between", value1, value2, "approvalType");
            return this;
        }

        public Criteria andApprovalTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("APPROVAL_TYPE not between", value1, value2, "approvalType");
            return this;
        }

        public Criteria andApprovalNoIsNull() {
            addCriterion("APPROVAL_NO is null");
            return this;
        }

        public Criteria andApprovalNoIsNotNull() {
            addCriterion("APPROVAL_NO is not null");
            return this;
        }

        public Criteria andApprovalNoEqualTo(String value) {
            addCriterion("APPROVAL_NO =", value, "approvalNo");
            return this;
        }

        public Criteria andApprovalNoNotEqualTo(String value) {
            addCriterion("APPROVAL_NO <>", value, "approvalNo");
            return this;
        }

        public Criteria andApprovalNoGreaterThan(String value) {
            addCriterion("APPROVAL_NO >", value, "approvalNo");
            return this;
        }

        public Criteria andApprovalNoGreaterThanOrEqualTo(String value) {
            addCriterion("APPROVAL_NO >=", value, "approvalNo");
            return this;
        }

        public Criteria andApprovalNoLessThan(String value) {
            addCriterion("APPROVAL_NO <", value, "approvalNo");
            return this;
        }

        public Criteria andApprovalNoLessThanOrEqualTo(String value) {
            addCriterion("APPROVAL_NO <=", value, "approvalNo");
            return this;
        }

        public Criteria andApprovalNoLike(String value) {
            addCriterion("APPROVAL_NO like", value, "approvalNo");
            return this;
        }

        public Criteria andApprovalNoNotLike(String value) {
            addCriterion("APPROVAL_NO not like", value, "approvalNo");
            return this;
        }

        public Criteria andApprovalNoIn(List values) {
            addCriterion("APPROVAL_NO in", values, "approvalNo");
            return this;
        }

        public Criteria andApprovalNoNotIn(List values) {
            addCriterion("APPROVAL_NO not in", values, "approvalNo");
            return this;
        }

        public Criteria andApprovalNoBetween(String value1, String value2) {
            addCriterion("APPROVAL_NO between", value1, value2, "approvalNo");
            return this;
        }

        public Criteria andApprovalNoNotBetween(String value1, String value2) {
            addCriterion("APPROVAL_NO not between", value1, value2, "approvalNo");
            return this;
        }

        public Criteria andDrugCateIdIsNull() {
            addCriterion("DRUG_CATE_ID is null");
            return this;
        }

        public Criteria andDrugCateIdIsNotNull() {
            addCriterion("DRUG_CATE_ID is not null");
            return this;
        }

        public Criteria andDrugCateIdEqualTo(Integer value) {
            addCriterion("DRUG_CATE_ID =", value, "drugCateId");
            return this;
        }

        public Criteria andDrugCateIdNotEqualTo(Integer value) {
            addCriterion("DRUG_CATE_ID <>", value, "drugCateId");
            return this;
        }

        public Criteria andDrugCateIdGreaterThan(Integer value) {
            addCriterion("DRUG_CATE_ID >", value, "drugCateId");
            return this;
        }

        public Criteria andDrugCateIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("DRUG_CATE_ID >=", value, "drugCateId");
            return this;
        }

        public Criteria andDrugCateIdLessThan(Integer value) {
            addCriterion("DRUG_CATE_ID <", value, "drugCateId");
            return this;
        }

        public Criteria andDrugCateIdLessThanOrEqualTo(Integer value) {
            addCriterion("DRUG_CATE_ID <=", value, "drugCateId");
            return this;
        }

        public Criteria andDrugCateIdIn(List values) {
            addCriterion("DRUG_CATE_ID in", values, "drugCateId");
            return this;
        }

        public Criteria andDrugCateIdNotIn(List values) {
            addCriterion("DRUG_CATE_ID not in", values, "drugCateId");
            return this;
        }

        public Criteria andDrugCateIdBetween(Integer value1, Integer value2) {
            addCriterion("DRUG_CATE_ID between", value1, value2, "drugCateId");
            return this;
        }

        public Criteria andDrugCateIdNotBetween(Integer value1, Integer value2) {
            addCriterion("DRUG_CATE_ID not between", value1, value2, "drugCateId");
            return this;
        }

        public Criteria andDrugCategoryNameIsNull() {
            addCriterion("DRUG_CATEGORY_NAME is null");
            return this;
        }

        public Criteria andDrugCategoryNameIsNotNull() {
            addCriterion("DRUG_CATEGORY_NAME is not null");
            return this;
        }

        public Criteria andDrugCategoryNameEqualTo(String value) {
            addCriterion("DRUG_CATEGORY_NAME =", value, "drugCategoryName");
            return this;
        }

        public Criteria andDrugCategoryNameNotEqualTo(String value) {
            addCriterion("DRUG_CATEGORY_NAME <>", value, "drugCategoryName");
            return this;
        }

        public Criteria andDrugCategoryNameGreaterThan(String value) {
            addCriterion("DRUG_CATEGORY_NAME >", value, "drugCategoryName");
            return this;
        }

        public Criteria andDrugCategoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("DRUG_CATEGORY_NAME >=", value, "drugCategoryName");
            return this;
        }

        public Criteria andDrugCategoryNameLessThan(String value) {
            addCriterion("DRUG_CATEGORY_NAME <", value, "drugCategoryName");
            return this;
        }

        public Criteria andDrugCategoryNameLessThanOrEqualTo(String value) {
            addCriterion("DRUG_CATEGORY_NAME <=", value, "drugCategoryName");
            return this;
        }

        public Criteria andDrugCategoryNameLike(String value) {
            addCriterion("DRUG_CATEGORY_NAME like", value, "drugCategoryName");
            return this;
        }

        public Criteria andDrugCategoryNameNotLike(String value) {
            addCriterion("DRUG_CATEGORY_NAME not like", value, "drugCategoryName");
            return this;
        }

        public Criteria andDrugCategoryNameIn(List values) {
            addCriterion("DRUG_CATEGORY_NAME in", values, "drugCategoryName");
            return this;
        }

        public Criteria andDrugCategoryNameNotIn(List values) {
            addCriterion("DRUG_CATEGORY_NAME not in", values, "drugCategoryName");
            return this;
        }

        public Criteria andDrugCategoryNameBetween(String value1, String value2) {
            addCriterion("DRUG_CATEGORY_NAME between", value1, value2, "drugCategoryName");
            return this;
        }

        public Criteria andDrugCategoryNameNotBetween(String value1, String value2) {
            addCriterion("DRUG_CATEGORY_NAME not between", value1, value2, "drugCategoryName");
            return this;
        }

        public Criteria andProductSkuIdIsNull() {
            addCriterion("PRODUCT_SKU_ID is null");
            return this;
        }

        public Criteria andProductSkuIdIsNotNull() {
            addCriterion("PRODUCT_SKU_ID is not null");
            return this;
        }

        public Criteria andProductSkuIdEqualTo(Integer value) {
            addCriterion("PRODUCT_SKU_ID =", value, "productSkuId");
            return this;
        }

        public Criteria andProductSkuIdNotEqualTo(Integer value) {
            addCriterion("PRODUCT_SKU_ID <>", value, "productSkuId");
            return this;
        }

        public Criteria andProductSkuIdGreaterThan(Integer value) {
            addCriterion("PRODUCT_SKU_ID >", value, "productSkuId");
            return this;
        }

        public Criteria andProductSkuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRODUCT_SKU_ID >=", value, "productSkuId");
            return this;
        }

        public Criteria andProductSkuIdLessThan(Integer value) {
            addCriterion("PRODUCT_SKU_ID <", value, "productSkuId");
            return this;
        }

        public Criteria andProductSkuIdLessThanOrEqualTo(Integer value) {
            addCriterion("PRODUCT_SKU_ID <=", value, "productSkuId");
            return this;
        }

        public Criteria andProductSkuIdIn(List values) {
            addCriterion("PRODUCT_SKU_ID in", values, "productSkuId");
            return this;
        }

        public Criteria andProductSkuIdNotIn(List values) {
            addCriterion("PRODUCT_SKU_ID not in", values, "productSkuId");
            return this;
        }

        public Criteria andProductSkuIdBetween(Integer value1, Integer value2) {
            addCriterion("PRODUCT_SKU_ID between", value1, value2, "productSkuId");
            return this;
        }

        public Criteria andProductSkuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PRODUCT_SKU_ID not between", value1, value2, "productSkuId");
            return this;
        }

        public Criteria andProductSkuCodeIsNull() {
            addCriterion("PRODUCT_SKU_CODE is null");
            return this;
        }

        public Criteria andProductSkuCodeIsNotNull() {
            addCriterion("PRODUCT_SKU_CODE is not null");
            return this;
        }

        public Criteria andProductSkuCodeEqualTo(String value) {
            addCriterion("PRODUCT_SKU_CODE =", value, "productSkuCode");
            return this;
        }

        public Criteria andProductSkuCodeNotEqualTo(String value) {
            addCriterion("PRODUCT_SKU_CODE <>", value, "productSkuCode");
            return this;
        }

        public Criteria andProductSkuCodeGreaterThan(String value) {
            addCriterion("PRODUCT_SKU_CODE >", value, "productSkuCode");
            return this;
        }

        public Criteria andProductSkuCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_SKU_CODE >=", value, "productSkuCode");
            return this;
        }

        public Criteria andProductSkuCodeLessThan(String value) {
            addCriterion("PRODUCT_SKU_CODE <", value, "productSkuCode");
            return this;
        }

        public Criteria andProductSkuCodeLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_SKU_CODE <=", value, "productSkuCode");
            return this;
        }

        public Criteria andProductSkuCodeLike(String value) {
            addCriterion("PRODUCT_SKU_CODE like", value, "productSkuCode");
            return this;
        }

        public Criteria andProductSkuCodeNotLike(String value) {
            addCriterion("PRODUCT_SKU_CODE not like", value, "productSkuCode");
            return this;
        }

        public Criteria andProductSkuCodeIn(List values) {
            addCriterion("PRODUCT_SKU_CODE in", values, "productSkuCode");
            return this;
        }

        public Criteria andProductSkuCodeNotIn(List values) {
            addCriterion("PRODUCT_SKU_CODE not in", values, "productSkuCode");
            return this;
        }

        public Criteria andProductSkuCodeBetween(String value1, String value2) {
            addCriterion("PRODUCT_SKU_CODE between", value1, value2, "productSkuCode");
            return this;
        }

        public Criteria andProductSkuCodeNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_SKU_CODE not between", value1, value2, "productSkuCode");
            return this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("PRICE is null");
            return this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("PRICE is not null");
            return this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("PRICE =", value, "price");
            return this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("PRICE <>", value, "price");
            return this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("PRICE >", value, "price");
            return this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRICE >=", value, "price");
            return this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("PRICE <", value, "price");
            return this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("PRICE <=", value, "price");
            return this;
        }

        public Criteria andPriceIn(List values) {
            addCriterion("PRICE in", values, "price");
            return this;
        }

        public Criteria andPriceNotIn(List values) {
            addCriterion("PRICE not in", values, "price");
            return this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("PRICE between", value1, value2, "price");
            return this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("PRICE not between", value1, value2, "price");
            return this;
        }
    }
}