package com.pltfm.app.dao;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import com.pltfm.app.entities.DiffAdj;
import com.pltfm.app.entities.DiffAdjCriteria;
import com.pltfm.app.entities.DiffAdjExample;

@SuppressWarnings("unchecked")
public interface DiffAdjDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table DIFF_ADJ
     * 
     * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
     */
    int countByExample(DiffAdjExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table DIFF_ADJ
     * 
     * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
     */
    int deleteByExample(DiffAdjExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table DIFF_ADJ
     * 
     * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
     */
    int deleteByPrimaryKey(Long diffAdjId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table DIFF_ADJ
     * 
     * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
     */
    Long insert(DiffAdj record) throws SQLException;

    /**
     * 插入差异调整，预售超时未发付赔付
     * 
     * @param record
     * @return
     * @throws SQLException
     */
    Long insertForPresell(Map map) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table DIFF_ADJ
     * 
     * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
     */
    Long insertSelective(DiffAdj record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table DIFF_ADJ
     * 
     * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
     */
    List selectByExample(DiffAdjExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table DIFF_ADJ
     * 
     * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
     */
    DiffAdj selectByPrimaryKey(Long diffAdjId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table DIFF_ADJ
     * 
     * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
     */
    int updateByExampleSelective(DiffAdj record, DiffAdjExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table DIFF_ADJ
     * 
     * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
     */
    int updateByExample(DiffAdj record, DiffAdjExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table DIFF_ADJ
     * 
     * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
     */
    int updateByPrimaryKeySelective(DiffAdj record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table DIFF_ADJ
     * 
     * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
     */
    int updateByPrimaryKey(DiffAdj record) throws SQLException;

    String getUserName(DiffAdj record) throws SQLException;

    /**
     * 查询列表
     * 
     * @param criteria
     * @return
     * @throws SQLException
     */
    public List<DiffAdj> selectDiffAdjList(DiffAdjCriteria criteria) throws SQLException;

    /**
     * 统计数量
     * 
     * @param criteria
     * @return
     * @throws SQLException
     */
    public int selectDiffAdjSize(DiffAdjCriteria criteria) throws SQLException;

    /**
     * 结算差异调整金额到商家账户
     * 
     * @param record
     * @return
     * @throws SQLException
     */
    public int updateDiffAccountAmount(DiffAdj record) throws SQLException;

    /**
     * 差异调整金额汇总
     * 
     * @param diffAdjCriteria
     * @return
     * @throws SQLException
     */
    public Map selectSumDiff(DiffAdjCriteria diffAdjCriteria) throws SQLException;

    /**
     * 差异调整明细导出数据查询
     * 
     * @param map
     * @return
     * @throws SQLException
     */
    public List<Map<String, Object>> queryExportDiffAdjInfo(Map<String, String> map)
            throws SQLException;

    /**
     * 查询差异调整记录，用于商家结算
     * 
     * @param map
     * @return
     * @throws SQLException
     */
    public List<DiffAdj> queryDiffAdjForSellerSettlement(Map<String, Object> map)
            throws SQLException;

}
