package com.pltfm.app.dao;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import com.pltfm.app.entities.HurlFare;
import com.pltfm.app.entities.HurlFareCriteria;
import com.pltfm.app.entities.HurlFareExample;

@SuppressWarnings("unchecked")
public interface HurlFareDAO {

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table HURL_FARE
   * 
   * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
   */
  int countByExample(HurlFareExample example) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table HURL_FARE
   * 
   * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
   */
  int deleteByExample(HurlFareExample example) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table HURL_FARE
   * 
   * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
   */
  int deleteByPrimaryKey(Long settlementFareId) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table HURL_FARE
   * 
   * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
   */
  Long insert(HurlFare record) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table HURL_FARE
   * 
   * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
   */
  Long insertSelective(HurlFare record) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table HURL_FARE
   * 
   * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
   */
  List selectByExample(HurlFareExample example) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table HURL_FARE
   * 
   * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
   */
  HurlFare selectByPrimaryKey(Long settlementFareId) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table HURL_FARE
   * 
   * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
   */
  int updateByExampleSelective(HurlFare record, HurlFareExample example) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table HURL_FARE
   * 
   * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
   */
  int updateByExample(HurlFare record, HurlFareExample example) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table HURL_FARE
   * 
   * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
   */
  int updateByPrimaryKeySelective(HurlFare record) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table HURL_FARE
   * 
   * @ibatorgenerated Wed Apr 15 10:27:20 CST 2015
   */
  int updateByPrimaryKey(HurlFare record) throws SQLException;

  /**
   * 获取运费总金额数
   * 
   * @param hurlFareCriteria
   * @return
   * @throws SQLException
   */
  Map hurlFareSumResult(HurlFareCriteria hurlFareCriteria) throws SQLException;

  /**
   * 运费明细导出信息查询
   * 
   * @param map
   * @return
   * @throws SQLException
   */
  List<Map<String, Object>> queryExportHurlFare(Map<String, String> map) throws SQLException;
}
