package com.pltfm.app.dao;

import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.Map;

import com.pltfm.app.entities.OrderCarry;
import com.pltfm.app.entities.OrderCarryExample;

@SuppressWarnings("unchecked")
public interface OrderCarryDAO {
  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_CARRY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  int countByExample(OrderCarryExample example) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_CARRY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  int deleteByExample(OrderCarryExample example) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_CARRY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  int deleteByPrimaryKey(Long handleId) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_CARRY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  Long insert(OrderCarry record) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_CARRY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  Long insertSelective(OrderCarry record) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_CARRY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  List selectByExample(OrderCarryExample example) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_CARRY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  OrderCarry selectByPrimaryKey(Long handleId) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_CARRY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  int updateByExampleSelective(OrderCarry record, OrderCarryExample example) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_CARRY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  int updateByExample(OrderCarry record, OrderCarryExample example) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_CARRY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  int updateByPrimaryKeySelective(OrderCarry record) throws SQLException;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_CARRY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  int updateByPrimaryKey(OrderCarry record) throws SQLException;

  /**
   * 查询处最近的一次结转单
   * 
   * @return
   * @throws SQLException
   */
  public List selectAllByrownum() throws SQLException;

  /**
   * 查询结转列表计数
   * 
   * @param map
   * @return
   * @throws SQLException
   */
  public Integer countByMap(Map<String, String> map) throws SQLException;

  /**
   * 查询出结转列表
   * 
   * @param map
   * @return
   * @throws SQLException
   */
  public List<OrderCarry> selectByMap(Map<String, String> map) throws SQLException;

  /**
   * 查询结转最近的时间
   * 
   * @param operator
   * @return
   * @throws SQLException
   */
  public Date queryMaxCreateDate(String operator) throws SQLException;
}
