package com.pltfm.sys.model;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

public class SysMenu implements Serializable, Cloneable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_MENU.MENU_ID
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    private Integer menuId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_MENU.MENU_UPID
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    private Integer menuUpid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_MENU.MENU_NAME
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    private String menuName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_MENU.MENU_LINK
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    private String menuLink;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_MENU.MENU_LV
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    private String menuLv;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_MENU.MENU_ST
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    private String menuSt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_MENU.MENU_IMG
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    private String menuImg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_MENU.MENU_REMARK
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    private String menuRemark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_MENU.SORTNO
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    private String sortno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_MENU.IS_ENABLE
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    private String isEnable;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_MENU.CREATE_DATE
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    private Date createDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_MENU.CREATE_USER
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    private Integer createUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_MENU.UPDATE_DATE
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    private Date updateDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_MENU.UPDATE_USER
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    private Integer updateUser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table SYS_MENU
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_MENU.MENU_ID
     *
     * @return the value of SYS_MENU.MENU_ID
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_MENU.MENU_ID
     *
     * @param menuId the value for SYS_MENU.MENU_ID
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_MENU.MENU_UPID
     *
     * @return the value of SYS_MENU.MENU_UPID
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public Integer getMenuUpid() {
        return menuUpid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_MENU.MENU_UPID
     *
     * @param menuUpid the value for SYS_MENU.MENU_UPID
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public void setMenuUpid(Integer menuUpid) {
        this.menuUpid = menuUpid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_MENU.MENU_NAME
     *
     * @return the value of SYS_MENU.MENU_NAME
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_MENU.MENU_NAME
     *
     * @param menuName the value for SYS_MENU.MENU_NAME
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_MENU.MENU_LINK
     *
     * @return the value of SYS_MENU.MENU_LINK
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public String getMenuLink() {
        return menuLink;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_MENU.MENU_LINK
     *
     * @param menuLink the value for SYS_MENU.MENU_LINK
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public void setMenuLink(String menuLink) {
        this.menuLink = menuLink == null ? null : menuLink.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_MENU.MENU_LV
     *
     * @return the value of SYS_MENU.MENU_LV
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public String getMenuLv() {
        return menuLv;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_MENU.MENU_LV
     *
     * @param menuLv the value for SYS_MENU.MENU_LV
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public void setMenuLv(String menuLv) {
        this.menuLv = menuLv == null ? null : menuLv.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_MENU.MENU_ST
     *
     * @return the value of SYS_MENU.MENU_ST
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public String getMenuSt() {
        return menuSt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_MENU.MENU_ST
     *
     * @param menuSt the value for SYS_MENU.MENU_ST
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public void setMenuSt(String menuSt) {
        this.menuSt = menuSt == null ? null : menuSt.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_MENU.MENU_IMG
     *
     * @return the value of SYS_MENU.MENU_IMG
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public String getMenuImg() {
        return menuImg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_MENU.MENU_IMG
     *
     * @param menuImg the value for SYS_MENU.MENU_IMG
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public void setMenuImg(String menuImg) {
        this.menuImg = menuImg == null ? null : menuImg.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_MENU.MENU_REMARK
     *
     * @return the value of SYS_MENU.MENU_REMARK
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public String getMenuRemark() {
        return menuRemark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_MENU.MENU_REMARK
     *
     * @param menuRemark the value for SYS_MENU.MENU_REMARK
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public void setMenuRemark(String menuRemark) {
        this.menuRemark = menuRemark == null ? null : menuRemark.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_MENU.SORTNO
     *
     * @return the value of SYS_MENU.SORTNO
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public String getSortno() {
        return sortno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_MENU.SORTNO
     *
     * @param sortno the value for SYS_MENU.SORTNO
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public void setSortno(String sortno) {
        this.sortno = sortno == null ? null : sortno.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_MENU.IS_ENABLE
     *
     * @return the value of SYS_MENU.IS_ENABLE
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_MENU.IS_ENABLE
     *
     * @param isEnable the value for SYS_MENU.IS_ENABLE
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable == null ? null : isEnable.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_MENU.CREATE_DATE
     *
     * @return the value of SYS_MENU.CREATE_DATE
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_MENU.CREATE_DATE
     *
     * @param createDate the value for SYS_MENU.CREATE_DATE
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_MENU.CREATE_USER
     *
     * @return the value of SYS_MENU.CREATE_USER
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_MENU.CREATE_USER
     *
     * @param createUser the value for SYS_MENU.CREATE_USER
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_MENU.UPDATE_DATE
     *
     * @return the value of SYS_MENU.UPDATE_DATE
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_MENU.UPDATE_DATE
     *
     * @param updateDate the value for SYS_MENU.UPDATE_DATE
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_MENU.UPDATE_USER
     *
     * @return the value of SYS_MENU.UPDATE_USER
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_MENU.UPDATE_USER
     *
     * @param updateUser the value for SYS_MENU.UPDATE_USER
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_MENU
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SysMenu sysMenu = (SysMenu) o;
        return Objects.equals(menuId, sysMenu.menuId) &&
                Objects.equals(menuUpid, sysMenu.menuUpid) &&
                Objects.equals(menuName, sysMenu.menuName) &&
                Objects.equals(menuLink, sysMenu.menuLink) &&
                Objects.equals(menuLv, sysMenu.menuLv) &&
                Objects.equals(menuSt, sysMenu.menuSt) &&
                Objects.equals(menuImg, sysMenu.menuImg) &&
                Objects.equals(menuRemark, sysMenu.menuRemark) &&
                Objects.equals(sortno, sysMenu.sortno) &&
                Objects.equals(isEnable, sysMenu.isEnable) &&
                Objects.equals(createDate, sysMenu.createDate) &&
                Objects.equals(createUser, sysMenu.createUser) &&
                Objects.equals(updateDate, sysMenu.updateDate) &&
                Objects.equals(updateUser, sysMenu.updateUser);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_MENU
     *
     * @ibatorgenerated Fri Nov 25 22:18:12 CST 2011
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getMenuId() != null) {
            hash *= getMenuId().hashCode();
        }
        if (getMenuUpid() != null) {
            hash *= getMenuUpid().hashCode();
        }
        if (getMenuName() != null) {
            hash *= getMenuName().hashCode();
        }
        if (getMenuLink() != null) {
            hash *= getMenuLink().hashCode();
        }
        if (getMenuLv() != null) {
            hash *= getMenuLv().hashCode();
        }
        if (getMenuSt() != null) {
            hash *= getMenuSt().hashCode();
        }
        if (getMenuImg() != null) {
            hash *= getMenuImg().hashCode();
        }
        if (getMenuRemark() != null) {
            hash *= getMenuRemark().hashCode();
        }
        if (getSortno() != null) {
            hash *= getSortno().hashCode();
        }
        if (getIsEnable() != null) {
            hash *= getIsEnable().hashCode();
        }
        if (getCreateDate() != null) {
            hash *= getCreateDate().hashCode();
        }
        if (getCreateUser() != null) {
            hash *= getCreateUser().hashCode();
        }
        if (getUpdateDate() != null) {
            hash *= getUpdateDate().hashCode();
        }
        if (getUpdateUser() != null) {
            hash *= getUpdateUser().hashCode();
        }
        return hash;
    }


    @Override
    public Object clone() {
        Object o = null;
        try {
            o = super.clone();//Object 中的clone()识别出你要复制的是哪一个对象。
        } catch (CloneNotSupportedException e) {
            System.out.println(e.toString());
        }
        return o;
    }


}