package com.kmzyc.promotion.app.vobject;

import java.util.Date;

public class Category implements java.io.Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = -2543050148585195716L;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * CATEGORY.CATEGORY_ID
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  private Long categoryId;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * CATEGORY.PARENT_ID
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  private Long parentId;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * CATEGORY.CATEGORY_CODE
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  private String categoryCode;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * CATEGORY.CATEGORY_NAME
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  private String categoryName;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * CATEGORY.STATUS
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  private Integer status;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * CATEGORY.SORTNO
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  private Integer sortno;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * CATEGORY.CATEGORY_DESC
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  private String categoryDesc;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * CATEGORY.CREATE_TIME
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  private Date createTime;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * CATEGORY.MODIF_TIME
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  private Date modifTime;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * CATEGORY.MODIF_USER
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  private Integer modifUser;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * CATEGORY.EXEC_SQL
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  private String execSql;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * CATEGORY.IS_PHY
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  private Integer isPhy;

  /**
   * sql关系文字描述
   */
  private String sqlString;

  /**
   * 父类名称
   */
  private String parentName;

  /**
   * 父类是否物理类目标识
   */
  private Integer parentIsPhy;

  /**
   * 类目ID字符串
   */
  private String categoryIds;

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column CATEGORY.PARENT_ID
   * 
   * @return the value of CATEGORY.PARENT_ID
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public Long getParentId() {
    return parentId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column CATEGORY.PARENT_ID
   * 
   * @param parentId the value for CATEGORY.PARENT_ID
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public void setParentId(Long parentId) {
    this.parentId = parentId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column CATEGORY.CATEGORY_CODE
   * 
   * @return the value of CATEGORY.CATEGORY_CODE
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public String getCategoryCode() {
    return categoryCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column CATEGORY.CATEGORY_CODE
   * 
   * @param categoryCode the value for CATEGORY.CATEGORY_CODE
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public void setCategoryCode(String categoryCode) {
    this.categoryCode = categoryCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column CATEGORY.CATEGORY_NAME
   * 
   * @return the value of CATEGORY.CATEGORY_NAME
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public String getCategoryName() {
    return categoryName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column CATEGORY.CATEGORY_NAME
   * 
   * @param categoryName the value for CATEGORY.CATEGORY_NAME
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName.trim();
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column CATEGORY.STATUS
   * 
   * @return the value of CATEGORY.STATUS
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public Integer getStatus() {
    return status;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column CATEGORY.STATUS
   * 
   * @param status the value for CATEGORY.STATUS
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column CATEGORY.SORTNO
   * 
   * @return the value of CATEGORY.SORTNO
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public Integer getSortno() {
    return sortno;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column CATEGORY.SORTNO
   * 
   * @param sortno the value for CATEGORY.SORTNO
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public void setSortno(Integer sortno) {
    this.sortno = sortno;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column CATEGORY.CATEGORY_DESC
   * 
   * @return the value of CATEGORY.CATEGORY_DESC
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public String getCategoryDesc() {
    return categoryDesc;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column CATEGORY.CATEGORY_DESC
   * 
   * @param categoryDesc the value for CATEGORY.CATEGORY_DESC
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public void setCategoryDesc(String categoryDesc) {
    this.categoryDesc = categoryDesc;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column CATEGORY.CREATE_TIME
   * 
   * @return the value of CATEGORY.CREATE_TIME
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column CATEGORY.CREATE_TIME
   * 
   * @param createTime the value for CATEGORY.CREATE_TIME
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column CATEGORY.MODIF_TIME
   * 
   * @return the value of CATEGORY.MODIF_TIME
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public Date getModifTime() {
    return modifTime;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column CATEGORY.MODIF_TIME
   * 
   * @param modifTime the value for CATEGORY.MODIF_TIME
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public void setModifTime(Date modifTime) {
    this.modifTime = modifTime;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column CATEGORY.MODIF_USER
   * 
   * @return the value of CATEGORY.MODIF_USER
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public Integer getModifUser() {
    return modifUser;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column CATEGORY.MODIF_USER
   * 
   * @param modifUser the value for CATEGORY.MODIF_USER
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public void setModifUser(Integer modifUser) {
    this.modifUser = modifUser;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column CATEGORY.EXEC_SQL
   * 
   * @return the value of CATEGORY.EXEC_SQL
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public String getExecSql() {
    return execSql;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column CATEGORY.EXEC_SQL
   * 
   * @param execSql the value for CATEGORY.EXEC_SQL
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public void setExecSql(String execSql) {
    this.execSql = execSql;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column CATEGORY.IS_PHY
   * 
   * @return the value of CATEGORY.IS_PHY
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public Integer getIsPhy() {
    return isPhy;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column CATEGORY.IS_PHY
   * 
   * @param isPhy the value for CATEGORY.IS_PHY
   * 
   * @ibatorgenerated Tue Aug 13 10:02:57 CST 2013
   */
  public void setIsPhy(Integer isPhy) {
    this.isPhy = isPhy;
  }

  public String getParentName() {
    return parentName;
  }

  public void setParentName(String parentName) {
    this.parentName = parentName;
  }

  public String getCategoryIds() {
    return categoryIds;
  }

  public void setCategoryIds(String categoryIds) {
    this.categoryIds = categoryIds;
  }

  public Integer getParentIsPhy() {
    return parentIsPhy;
  }

  public void setParentIsPhy(Integer parentIsPhy) {
    this.parentIsPhy = parentIsPhy;
  }

  public Long getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(Long categoryId) {
    this.categoryId = categoryId;
  }

  public String getSqlString() {
    return sqlString;
  }

  public void setSqlString(String sqlString) {
    this.sqlString = sqlString;
  }
}
