package com.kmzyc.promotion.app.vobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

@SuppressWarnings("unchecked")
public class DirectionalReleasePriceExample {
	/**
	 * 
	 */
	private String userId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database table DIRECTIONAL_RELEASE_PRICE
	 * 
	 * @ibatorgenerated Tue Jul 30 16:27:38 CST 2013
	 */
	protected String orderByClause;

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database table DIRECTIONAL_RELEASE_PRICE
	 * 
	 * @ibatorgenerated Tue Jul 30 16:27:38 CST 2013
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table DIRECTIONAL_RELEASE_PRICE
	 * 
	 * @ibatorgenerated Tue Jul 30 16:27:38 CST 2013
	 */
	public DirectionalReleasePriceExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table DIRECTIONAL_RELEASE_PRICE
	 * 
	 * @ibatorgenerated Tue Jul 30 16:27:38 CST 2013
	 */
	protected DirectionalReleasePriceExample(DirectionalReleasePriceExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table DIRECTIONAL_RELEASE_PRICE
	 * 
	 * @ibatorgenerated Tue Jul 30 16:27:38 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table DIRECTIONAL_RELEASE_PRICE
	 * 
	 * @ibatorgenerated Tue Jul 30 16:27:38 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table DIRECTIONAL_RELEASE_PRICE
	 * 
	 * @ibatorgenerated Tue Jul 30 16:27:38 CST 2013
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table DIRECTIONAL_RELEASE_PRICE
	 * 
	 * @ibatorgenerated Tue Jul 30 16:27:38 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table DIRECTIONAL_RELEASE_PRICE
	 * 
	 * @ibatorgenerated Tue Jul 30 16:27:38 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table DIRECTIONAL_RELEASE_PRICE
	 * 
	 * @ibatorgenerated Tue Jul 30 16:27:38 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table DIRECTIONAL_RELEASE_PRICE
	 * 
	 * @ibatorgenerated Tue Jul 30 16:27:38 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds
	 * to the database table DIRECTIONAL_RELEASE_PRICE
	 * 
	 * @ibatorgenerated Tue Jul 30 16:27:38 CST 2013
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;

		protected List criteriaWithSingleValue;

		protected List criteriaWithListValue;

		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List dateList = new ArrayList();
			Iterator iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(((Date) iter.next()).getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andPriceIdIsNull() {
			addCriterion("PRICE_ID is null");
			return this;
		}

		public Criteria andPriceIdIsNotNull() {
			addCriterion("PRICE_ID is not null");
			return this;
		}

		public Criteria andPriceIdEqualTo(Integer value) {
			addCriterion("PRICE_ID =", value, "priceId");
			return this;
		}

		public Criteria andPriceIdNotEqualTo(Integer value) {
			addCriterion("PRICE_ID <>", value, "priceId");
			return this;
		}

		public Criteria andPriceIdGreaterThan(Integer value) {
			addCriterion("PRICE_ID >", value, "priceId");
			return this;
		}

		public Criteria andPriceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("PRICE_ID >=", value, "priceId");
			return this;
		}

		public Criteria andPriceIdLessThan(Integer value) {
			addCriterion("PRICE_ID <", value, "priceId");
			return this;
		}

		public Criteria andPriceIdLessThanOrEqualTo(Integer value) {
			addCriterion("PRICE_ID <=", value, "priceId");
			return this;
		}

		public Criteria andPriceIdIn(List values) {
			addCriterion("PRICE_ID in", values, "priceId");
			return this;
		}

		public Criteria andPriceIdNotIn(List values) {
			addCriterion("PRICE_ID not in", values, "priceId");
			return this;
		}

		public Criteria andPriceIdBetween(Integer value1, Integer value2) {
			addCriterion("PRICE_ID between", value1, value2, "priceId");
			return this;
		}

		public Criteria andPriceIdNotBetween(Integer value1, Integer value2) {
			addCriterion("PRICE_ID not between", value1, value2, "priceId");
			return this;
		}

		public Criteria andProductIdIsNull() {
			addCriterion("PRODUCT_ID is null");
			return this;
		}

		public Criteria andProductIdIsNotNull() {
			addCriterion("PRODUCT_ID is not null");
			return this;
		}

		public Criteria andProductIdEqualTo(Long value) {
			addCriterion("PRODUCT_ID =", value, "productId");
			return this;
		}

		public Criteria andProductIdNotEqualTo(Integer value) {
			addCriterion("PRODUCT_ID <>", value, "productId");
			return this;
		}

		public Criteria andProductIdGreaterThan(Integer value) {
			addCriterion("PRODUCT_ID >", value, "productId");
			return this;
		}

		public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("PRODUCT_ID >=", value, "productId");
			return this;
		}

		public Criteria andProductIdLessThan(Integer value) {
			addCriterion("PRODUCT_ID <", value, "productId");
			return this;
		}

		public Criteria andProductIdLessThanOrEqualTo(Integer value) {
			addCriterion("PRODUCT_ID <=", value, "productId");
			return this;
		}

		public Criteria andProductIdIn(List values) {
			addCriterion("PRODUCT_ID in", values, "productId");
			return this;
		}

		public Criteria andProductIdNotIn(List values) {
			addCriterion("PRODUCT_ID not in", values, "productId");
			return this;
		}

		public Criteria andProductIdBetween(Integer value1, Integer value2) {
			addCriterion("PRODUCT_ID between", value1, value2, "productId");
			return this;
		}

		public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
			addCriterion("PRODUCT_ID not between", value1, value2, "productId");
			return this;
		}

		public Criteria andProductNameIsNull() {
			addCriterion("PRODUCT_NAME is null");
			return this;
		}

		public Criteria andProductNameIsNotNull() {
			addCriterion("PRODUCT_NAME is not null");
			return this;
		}

		public Criteria andProductNameEqualTo(String value) {
			addCriterion("PRODUCT_NAME =", value, "productName");
			return this;
		}

		public Criteria andProductNameNotEqualTo(String value) {
			addCriterion("PRODUCT_NAME <>", value, "productName");
			return this;
		}

		public Criteria andProductNameGreaterThan(String value) {
			addCriterion("PRODUCT_NAME >", value, "productName");
			return this;
		}

		public Criteria andProductNameGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NAME >=", value, "productName");
			return this;
		}

		public Criteria andProductNameLessThan(String value) {
			addCriterion("PRODUCT_NAME <", value, "productName");
			return this;
		}

		public Criteria andProductNameLessThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NAME <=", value, "productName");
			return this;
		}

		public Criteria andProductNameLike(String value) {
			addCriterion("PRODUCT_NAME like", value, "productName");
			return this;
		}

		public Criteria andProductNameNotLike(String value) {
			addCriterion("PRODUCT_NAME not like", value, "productName");
			return this;
		}

		public Criteria andProductNameIn(List values) {
			addCriterion("PRODUCT_NAME in", values, "productName");
			return this;
		}

		public Criteria andProductNameNotIn(List values) {
			addCriterion("PRODUCT_NAME not in", values, "productName");
			return this;
		}

		public Criteria andProductNameBetween(String value1, String value2) {
			addCriterion("PRODUCT_NAME between", value1, value2, "productName");
			return this;
		}

		public Criteria andProductNameNotBetween(String value1, String value2) {
			addCriterion("PRODUCT_NAME not between", value1, value2, "productName");
			return this;
		}

		public Criteria andProductNoIsNull() {
			addCriterion("PRODUCT_NO is null");
			return this;
		}

		public Criteria andProductNoIsNotNull() {
			addCriterion("PRODUCT_NO is not null");
			return this;
		}

		public Criteria andProductNoEqualTo(String value) {
			addCriterion("PRODUCT_NO =", value, "productNo");
			return this;
		}

		public Criteria andProductNoNotEqualTo(String value) {
			addCriterion("PRODUCT_NO <>", value, "productNo");
			return this;
		}

		public Criteria andProductNoGreaterThan(String value) {
			addCriterion("PRODUCT_NO >", value, "productNo");
			return this;
		}

		public Criteria andProductNoGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NO >=", value, "productNo");
			return this;
		}

		public Criteria andProductNoLessThan(String value) {
			addCriterion("PRODUCT_NO <", value, "productNo");
			return this;
		}

		public Criteria andProductNoLessThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NO <=", value, "productNo");
			return this;
		}

		public Criteria andProductNoLike(String value) {
			addCriterion("PRODUCT_NO like", value, "productNo");
			return this;
		}

		public Criteria andProductNoNotLike(String value) {
			addCriterion("PRODUCT_NO not like", value, "productNo");
			return this;
		}

		public Criteria andProductNoIn(List values) {
			addCriterion("PRODUCT_NO in", values, "productNo");
			return this;
		}

		public Criteria andProductNoNotIn(List values) {
			addCriterion("PRODUCT_NO not in", values, "productNo");
			return this;
		}

		public Criteria andProductNoBetween(String value1, String value2) {
			addCriterion("PRODUCT_NO between", value1, value2, "productNo");
			return this;
		}

		public Criteria andProductNoNotBetween(String value1, String value2) {
			addCriterion("PRODUCT_NO not between", value1, value2, "productNo");
			return this;
		}

		public Criteria andSkuIdIsNull() {
			addCriterion("SKU_ID is null");
			return this;
		}

		public Criteria andSkuIdIsNotNull() {
			addCriterion("SKU_ID is not null");
			return this;
		}

		public Criteria andSkuIdEqualTo(Long value) {
			addCriterion("SKU_ID =", value, "skuId");
			return this;
		}

		public Criteria andSkuIdNotEqualTo(Integer value) {
			addCriterion("SKU_ID <>", value, "skuId");
			return this;
		}

		public Criteria andSkuIdGreaterThan(Integer value) {
			addCriterion("SKU_ID >", value, "skuId");
			return this;
		}

		public Criteria andSkuIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("SKU_ID >=", value, "skuId");
			return this;
		}

		public Criteria andSkuIdLessThan(Integer value) {
			addCriterion("SKU_ID <", value, "skuId");
			return this;
		}

		public Criteria andSkuIdLessThanOrEqualTo(Integer value) {
			addCriterion("SKU_ID <=", value, "skuId");
			return this;
		}

		public Criteria andSkuIdIn(List values) {
			addCriterion("SKU_ID in", values, "skuId");
			return this;
		}

		public Criteria andSkuIdNotIn(List values) {
			addCriterion("SKU_ID not in", values, "skuId");
			return this;
		}

		public Criteria andSkuIdBetween(Integer value1, Integer value2) {
			addCriterion("SKU_ID between", value1, value2, "skuId");
			return this;
		}

		public Criteria andSkuIdNotBetween(Integer value1, Integer value2) {
			addCriterion("SKU_ID not between", value1, value2, "skuId");
			return this;
		}

		public Criteria andAreaPriceIsNull() {
			addCriterion("AREA_PRICE is null");
			return this;
		}

		public Criteria andAreaPriceIsNotNull() {
			addCriterion("AREA_PRICE is not null");
			return this;
		}

		public Criteria andAreaPriceEqualTo(Double value) {
			addCriterion("AREA_PRICE =", value, "areaPrice");
			return this;
		}

		public Criteria andAreaPriceNotEqualTo(Double value) {
			addCriterion("AREA_PRICE <>", value, "areaPrice");
			return this;
		}

		public Criteria andAreaPriceGreaterThan(Double value) {
			addCriterion("AREA_PRICE >", value, "areaPrice");
			return this;
		}

		public Criteria andAreaPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("AREA_PRICE >=", value, "areaPrice");
			return this;
		}

		public Criteria andAreaPriceLessThan(Double value) {
			addCriterion("AREA_PRICE <", value, "areaPrice");
			return this;
		}

		public Criteria andAreaPriceLessThanOrEqualTo(Double value) {
			addCriterion("AREA_PRICE <=", value, "areaPrice");
			return this;
		}

		public Criteria andAreaPriceIn(List values) {
			addCriterion("AREA_PRICE in", values, "areaPrice");
			return this;
		}

		public Criteria andAreaPriceNotIn(List values) {
			addCriterion("AREA_PRICE not in", values, "areaPrice");
			return this;
		}

		public Criteria andAreaPriceBetween(Double value1, Double value2) {
			addCriterion("AREA_PRICE between", value1, value2, "areaPrice");
			return this;
		}

		public Criteria andAreaPriceNotBetween(Double value1, Double value2) {
			addCriterion("AREA_PRICE not between", value1, value2, "areaPrice");
			return this;
		}

		public Criteria andAreaIdIsNull() {
			addCriterion("AREA_ID is null");
			return this;
		}

		public Criteria andAreaIdIsNotNull() {
			addCriterion("AREA_ID is not null");
			return this;
		}

		public Criteria andAreaIdEqualTo(Integer value) {
			addCriterion("AREA_ID =", value, "areaId");
			return this;
		}

		public Criteria andAreaIdNotEqualTo(Integer value) {
			addCriterion("AREA_ID <>", value, "areaId");
			return this;
		}

		public Criteria andAreaIdGreaterThan(Integer value) {
			addCriterion("AREA_ID >", value, "areaId");
			return this;
		}

		public Criteria andAreaIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("AREA_ID >=", value, "areaId");
			return this;
		}

		public Criteria andAreaIdLessThan(Integer value) {
			addCriterion("AREA_ID <", value, "areaId");
			return this;
		}

		public Criteria andAreaIdLessThanOrEqualTo(Integer value) {
			addCriterion("AREA_ID <=", value, "areaId");
			return this;
		}

		public Criteria andAreaIdIn(List values) {
			addCriterion("AREA_ID in", values, "areaId");
			return this;
		}

		public Criteria andAreaIdNotIn(List values) {
			addCriterion("AREA_ID not in", values, "areaId");
			return this;
		}

		public Criteria andAreaIdBetween(Integer value1, Integer value2) {
			addCriterion("AREA_ID between", value1, value2, "areaId");
			return this;
		}

		public Criteria andAreaIdNotBetween(Integer value1, Integer value2) {
			addCriterion("AREA_ID not between", value1, value2, "areaId");
			return this;
		}

		public Criteria andUserLevelIsNull() {
			addCriterion("USER_LEVEL is null");
			return this;
		}

		public Criteria andUserLevelIsNotNull() {
			addCriterion("USER_LEVEL is not null");
			return this;
		}

		public Criteria andUserLevelEqualTo(Integer value) {
			addCriterion("USER_LEVEL =", value, "userLevel");
			return this;
		}

		public Criteria andUserLevelNotEqualTo(Integer value) {
			addCriterion("USER_LEVEL <>", value, "userLevel");
			return this;
		}

		public Criteria andUserLevelGreaterThan(Integer value) {
			addCriterion("USER_LEVEL >", value, "userLevel");
			return this;
		}

		public Criteria andUserLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("USER_LEVEL >=", value, "userLevel");
			return this;
		}

		public Criteria andUserLevelLessThan(Integer value) {
			addCriterion("USER_LEVEL <", value, "userLevel");
			return this;
		}

		public Criteria andUserLevelLessThanOrEqualTo(Integer value) {
			addCriterion("USER_LEVEL <=", value, "userLevel");
			return this;
		}

		public Criteria andUserLevelIn(List values) {
			addCriterion("USER_LEVEL in", values, "userLevel");
			return this;
		}

		public Criteria andUserLevelNotIn(List values) {
			addCriterion("USER_LEVEL not in", values, "userLevel");
			return this;
		}

		public Criteria andUserLevelBetween(Integer value1, Integer value2) {
			addCriterion("USER_LEVEL between", value1, value2, "userLevel");
			return this;
		}

		public Criteria andUserLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("USER_LEVEL not between", value1, value2, "userLevel");
			return this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return this;
		}

		public Criteria andCreateUserEqualTo(Integer value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return this;
		}

		public Criteria andCreateUserNotEqualTo(Integer value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return this;
		}

		public Criteria andCreateUserGreaterThan(Integer value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(Integer value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return this;
		}

		public Criteria andCreateUserLessThan(Integer value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(Integer value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return this;
		}

		public Criteria andCreateUserIn(List values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return this;
		}

		public Criteria andCreateUserNotIn(List values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return this;
		}

		public Criteria andCreateUserBetween(Integer value1, Integer value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return this;
		}

		public Criteria andCreateUserNotBetween(Integer value1, Integer value2) {
			addCriterion("CREATE_USER not between", value1, value2, "createUser");
			return this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("CREATE_DATE is null");
			return this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("CREATE_DATE is not null");
			return this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE =", value, "createDate");
			return this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <>", value, "createDate");
			return this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterionForJDBCDate("CREATE_DATE >", value, "createDate");
			return this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE >=", value, "createDate");
			return this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <", value, "createDate");
			return this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_DATE <=", value, "createDate");
			return this;
		}

		public Criteria andCreateDateIn(List values) {
			addCriterionForJDBCDate("CREATE_DATE in", values, "createDate");
			return this;
		}

		public Criteria andCreateDateNotIn(List values) {
			addCriterionForJDBCDate("CREATE_DATE not in", values, "createDate");
			return this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_DATE between", value1, value2, "createDate");
			return this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_DATE not between", value1, value2, "createDate");
			return this;
		}

		public Criteria andAuditUserIsNull() {
			addCriterion("AUDIT_USER is null");
			return this;
		}

		public Criteria andAuditUserIsNotNull() {
			addCriterion("AUDIT_USER is not null");
			return this;
		}

		public Criteria andAuditUserEqualTo(Integer value) {
			addCriterion("AUDIT_USER =", value, "auditUser");
			return this;
		}

		public Criteria andAuditUserNotEqualTo(Integer value) {
			addCriterion("AUDIT_USER <>", value, "auditUser");
			return this;
		}

		public Criteria andAuditUserGreaterThan(Integer value) {
			addCriterion("AUDIT_USER >", value, "auditUser");
			return this;
		}

		public Criteria andAuditUserGreaterThanOrEqualTo(Integer value) {
			addCriterion("AUDIT_USER >=", value, "auditUser");
			return this;
		}

		public Criteria andAuditUserLessThan(Integer value) {
			addCriterion("AUDIT_USER <", value, "auditUser");
			return this;
		}

		public Criteria andAuditUserLessThanOrEqualTo(Integer value) {
			addCriterion("AUDIT_USER <=", value, "auditUser");
			return this;
		}

		public Criteria andAuditUserIn(List values) {
			addCriterion("AUDIT_USER in", values, "auditUser");
			return this;
		}

		public Criteria andAuditUserNotIn(List values) {
			addCriterion("AUDIT_USER not in", values, "auditUser");
			return this;
		}

		public Criteria andAuditUserBetween(Integer value1, Integer value2) {
			addCriterion("AUDIT_USER between", value1, value2, "auditUser");
			return this;
		}

		public Criteria andAuditUserNotBetween(Integer value1, Integer value2) {
			addCriterion("AUDIT_USER not between", value1, value2, "auditUser");
			return this;
		}

		public Criteria andAuditDateIsNull() {
			addCriterion("AUDIT_DATE is null");
			return this;
		}

		public Criteria andAuditDateIsNotNull() {
			addCriterion("AUDIT_DATE is not null");
			return this;
		}

		public Criteria andAuditDateEqualTo(Date value) {
			addCriterionForJDBCDate("AUDIT_DATE =", value, "auditDate");
			return this;
		}

		public Criteria andAuditDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("AUDIT_DATE <>", value, "auditDate");
			return this;
		}

		public Criteria andAuditDateGreaterThan(Date value) {
			addCriterionForJDBCDate("AUDIT_DATE >", value, "auditDate");
			return this;
		}

		public Criteria andAuditDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("AUDIT_DATE >=", value, "auditDate");
			return this;
		}

		public Criteria andAuditDateLessThan(Date value) {
			addCriterionForJDBCDate("AUDIT_DATE <", value, "auditDate");
			return this;
		}

		public Criteria andAuditDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("AUDIT_DATE <=", value, "auditDate");
			return this;
		}

		public Criteria andAuditDateIn(List values) {
			addCriterionForJDBCDate("AUDIT_DATE in", values, "auditDate");
			return this;
		}

		public Criteria andAuditDateNotIn(List values) {
			addCriterionForJDBCDate("AUDIT_DATE not in", values, "auditDate");
			return this;
		}

		public Criteria andAuditDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("AUDIT_DATE between", value1, value2, "auditDate");
			return this;
		}

		public Criteria andAuditDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("AUDIT_DATE not between", value1, value2, "auditDate");
			return this;
		}

		public Criteria andAuditStatusIsNull() {
			addCriterion("AUDIT_STATUS is null");
			return this;
		}

		public Criteria andAuditStatusIsNotNull() {
			addCriterion("AUDIT_STATUS is not null");
			return this;
		}

		public Criteria andAuditStatusEqualTo(String value) {
			addCriterion("AUDIT_STATUS =", value, "auditStatus");
			return this;
		}

		public Criteria andAuditStatusNotEqualTo(String value) {
			addCriterion("AUDIT_STATUS <>", value, "auditStatus");
			return this;
		}

		public Criteria andAuditStatusGreaterThan(String value) {
			addCriterion("AUDIT_STATUS >", value, "auditStatus");
			return this;
		}

		public Criteria andAuditStatusGreaterThanOrEqualTo(String value) {
			addCriterion("AUDIT_STATUS >=", value, "auditStatus");
			return this;
		}

		public Criteria andAuditStatusLessThan(String value) {
			addCriterion("AUDIT_STATUS <", value, "auditStatus");
			return this;
		}

		public Criteria andAuditStatusLessThanOrEqualTo(String value) {
			addCriterion("AUDIT_STATUS <=", value, "auditStatus");
			return this;
		}

		public Criteria andAuditStatusLike(String value) {
			addCriterion("AUDIT_STATUS like", value, "auditStatus");
			return this;
		}

		public Criteria andAuditStatusNotLike(String value) {
			addCriterion("AUDIT_STATUS not like", value, "auditStatus");
			return this;
		}

		public Criteria andAuditStatusIn(List values) {
			addCriterion("AUDIT_STATUS in", values, "auditStatus");
			return this;
		}

		public Criteria andAuditStatusNotIn(List values) {
			addCriterion("AUDIT_STATUS not in", values, "auditStatus");
			return this;
		}

		public Criteria andAuditStatusBetween(String value1, String value2) {
			addCriterion("AUDIT_STATUS between", value1, value2, "auditStatus");
			return this;
		}

		public Criteria andAuditStatusNotBetween(String value1, String value2) {
			addCriterion("AUDIT_STATUS not between", value1, value2, "auditStatus");
			return this;
		}

		public Criteria andIsValidIsNull() {
			addCriterion("IS_VALID is null");
			return this;
		}

		public Criteria andIsValidIsNotNull() {
			addCriterion("IS_VALID is not null");
			return this;
		}

		public Criteria andIsValidEqualTo(String value) {
			addCriterion("IS_VALID =", value, "isValid");
			return this;
		}

		public Criteria andIsValidNotEqualTo(String value) {
			addCriterion("IS_VALID <>", value, "isValid");
			return this;
		}

		public Criteria andIsValidGreaterThan(String value) {
			addCriterion("IS_VALID >", value, "isValid");
			return this;
		}

		public Criteria andIsValidGreaterThanOrEqualTo(String value) {
			addCriterion("IS_VALID >=", value, "isValid");
			return this;
		}

		public Criteria andIsValidLessThan(String value) {
			addCriterion("IS_VALID <", value, "isValid");
			return this;
		}

		public Criteria andIsValidLessThanOrEqualTo(String value) {
			addCriterion("IS_VALID <=", value, "isValid");
			return this;
		}

		public Criteria andIsValidLike(String value) {
			addCriterion("IS_VALID like", value, "isValid");
			return this;
		}

		public Criteria andIsValidNotLike(String value) {
			addCriterion("IS_VALID not like", value, "isValid");
			return this;
		}

		public Criteria andIsValidIn(List values) {
			addCriterion("IS_VALID in", values, "isValid");
			return this;
		}

		public Criteria andIsValidNotIn(List values) {
			addCriterion("IS_VALID not in", values, "isValid");
			return this;
		}

		public Criteria andIsValidBetween(String value1, String value2) {
			addCriterion("IS_VALID between", value1, value2, "isValid");
			return this;
		}

		public Criteria andIsValidNotBetween(String value1, String value2) {
			addCriterion("IS_VALID not between", value1, value2, "isValid");
			return this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("REMARK is null");
			return this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("REMARK is not null");
			return this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("REMARK =", value, "remark");
			return this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("REMARK <>", value, "remark");
			return this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("REMARK >", value, "remark");
			return this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("REMARK >=", value, "remark");
			return this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("REMARK <", value, "remark");
			return this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("REMARK <=", value, "remark");
			return this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("REMARK like", value, "remark");
			return this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("REMARK not like", value, "remark");
			return this;
		}

		public Criteria andRemarkIn(List values) {
			addCriterion("REMARK in", values, "remark");
			return this;
		}

		public Criteria andRemarkNotIn(List values) {
			addCriterion("REMARK not in", values, "remark");
			return this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("REMARK between", value1, value2, "remark");
			return this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("REMARK not between", value1, value2, "remark");
			return this;
		}

		public Criteria andAreaNameIsNull() {
			addCriterion("AREA_NAME is null");
			return this;
		}

		public Criteria andAreaNameIsNotNull() {
			addCriterion("AREA_NAME is not null");
			return this;
		}

		public Criteria andAreaNameEqualTo(String value) {
			addCriterion("AREA_NAME =", value, "areaName");
			return this;
		}

		public Criteria andAreaNameNotEqualTo(String value) {
			addCriterion("AREA_NAME <>", value, "areaName");
			return this;
		}

		public Criteria andAreaNameGreaterThan(String value) {
			addCriterion("AREA_NAME >", value, "areaName");
			return this;
		}

		public Criteria andAreaNameGreaterThanOrEqualTo(String value) {
			addCriterion("AREA_NAME >=", value, "areaName");
			return this;
		}

		public Criteria andAreaNameLessThan(String value) {
			addCriterion("AREA_NAME <", value, "areaName");
			return this;
		}

		public Criteria andAreaNameLessThanOrEqualTo(String value) {
			addCriterion("AREA_NAME <=", value, "areaName");
			return this;
		}

		public Criteria andAreaNameLike(String value) {
			addCriterion("AREA_NAME like", value, "areaName");
			return this;
		}

		public Criteria andAreaNameNotLike(String value) {
			addCriterion("AREA_NAME not like", value, "areaName");
			return this;
		}

		public Criteria andAreaNameIn(List values) {
			addCriterion("AREA_NAME in", values, "areaName");
			return this;
		}

		public Criteria andAreaNameNotIn(List values) {
			addCriterion("AREA_NAME not in", values, "areaName");
			return this;
		}

		public Criteria andAreaNameBetween(String value1, String value2) {
			addCriterion("AREA_NAME between", value1, value2, "areaName");
			return this;
		}

		public Criteria andAreaNameNotBetween(String value1, String value2) {
			addCriterion("AREA_NAME not between", value1, value2, "areaName");
			return this;
		}

		public Criteria andCreateUserNameIsNull() {
			addCriterion("CREATE_USER_NAME is null");
			return this;
		}

		public Criteria andCreateUserNameIsNotNull() {
			addCriterion("CREATE_USER_NAME is not null");
			return this;
		}

		public Criteria andCreateUserNameEqualTo(String value) {
			addCriterion("CREATE_USER_NAME =", value, "createUserName");
			return this;
		}

		public Criteria andCreateUserNameNotEqualTo(String value) {
			addCriterion("CREATE_USER_NAME <>", value, "createUserName");
			return this;
		}

		public Criteria andCreateUserNameGreaterThan(String value) {
			addCriterion("CREATE_USER_NAME >", value, "createUserName");
			return this;
		}

		public Criteria andCreateUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER_NAME >=", value, "createUserName");
			return this;
		}

		public Criteria andCreateUserNameLessThan(String value) {
			addCriterion("CREATE_USER_NAME <", value, "createUserName");
			return this;
		}

		public Criteria andCreateUserNameLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER_NAME <=", value, "createUserName");
			return this;
		}

		public Criteria andCreateUserNameLike(String value) {
			addCriterion("CREATE_USER_NAME like", value, "createUserName");
			return this;
		}

		public Criteria andCreateUserNameNotLike(String value) {
			addCriterion("CREATE_USER_NAME not like", value, "createUserName");
			return this;
		}

		public Criteria andCreateUserNameIn(List values) {
			addCriterion("CREATE_USER_NAME in", values, "createUserName");
			return this;
		}

		public Criteria andCreateUserNameNotIn(List values) {
			addCriterion("CREATE_USER_NAME not in", values, "createUserName");
			return this;
		}

		public Criteria andCreateUserNameBetween(String value1, String value2) {
			addCriterion("CREATE_USER_NAME between", value1, value2, "createUserName");
			return this;
		}

		public Criteria andCreateUserNameNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER_NAME not between", value1, value2, "createUserName");
			return this;
		}

		public Criteria andAuditUserNameIsNull() {
			addCriterion("AUDIT_USER_NAME is null");
			return this;
		}

		public Criteria andAuditUserNameIsNotNull() {
			addCriterion("AUDIT_USER_NAME is not null");
			return this;
		}

		public Criteria andAuditUserNameEqualTo(String value) {
			addCriterion("AUDIT_USER_NAME =", value, "auditUserName");
			return this;
		}

		public Criteria andAuditUserNameNotEqualTo(String value) {
			addCriterion("AUDIT_USER_NAME <>", value, "auditUserName");
			return this;
		}

		public Criteria andAuditUserNameGreaterThan(String value) {
			addCriterion("AUDIT_USER_NAME >", value, "auditUserName");
			return this;
		}

		public Criteria andAuditUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("AUDIT_USER_NAME >=", value, "auditUserName");
			return this;
		}

		public Criteria andAuditUserNameLessThan(String value) {
			addCriterion("AUDIT_USER_NAME <", value, "auditUserName");
			return this;
		}

		public Criteria andAuditUserNameLessThanOrEqualTo(String value) {
			addCriterion("AUDIT_USER_NAME <=", value, "auditUserName");
			return this;
		}

		public Criteria andAuditUserNameLike(String value) {
			addCriterion("AUDIT_USER_NAME like", value, "auditUserName");
			return this;
		}

		public Criteria andAuditUserNameNotLike(String value) {
			addCriterion("AUDIT_USER_NAME not like", value, "auditUserName");
			return this;
		}

		public Criteria andAuditUserNameIn(List values) {
			addCriterion("AUDIT_USER_NAME in", values, "auditUserName");
			return this;
		}

		public Criteria andAuditUserNameNotIn(List values) {
			addCriterion("AUDIT_USER_NAME not in", values, "auditUserName");
			return this;
		}

		public Criteria andAuditUserNameBetween(String value1, String value2) {
			addCriterion("AUDIT_USER_NAME between", value1, value2, "auditUserName");
			return this;
		}

		public Criteria andAuditUserNameNotBetween(String value1, String value2) {
			addCriterion("AUDIT_USER_NAME not between", value1, value2, "auditUserName");
			return this;
		}

		public Criteria andSkuCodeIsNull() {
			addCriterion("SKU_CODE is null");
			return this;
		}

		public Criteria andSkuCodeIsNotNull() {
			addCriterion("SKU_CODE is not null");
			return this;
		}

		public Criteria andSkuCodeEqualTo(String value) {
			addCriterion("SKU_CODE =", value, "skuCode");
			return this;
		}

		public Criteria andSkuCodeNotEqualTo(String value) {
			addCriterion("SKU_CODE <>", value, "skuCode");
			return this;
		}

		public Criteria andSkuCodeGreaterThan(String value) {
			addCriterion("SKU_CODE >", value, "skuCode");
			return this;
		}

		public Criteria andSkuCodeGreaterThanOrEqualTo(String value) {
			addCriterion("SKU_CODE >=", value, "skuCode");
			return this;
		}

		public Criteria andSkuCodeLessThan(String value) {
			addCriterion("SKU_CODE <", value, "skuCode");
			return this;
		}

		public Criteria andSkuCodeLessThanOrEqualTo(String value) {
			addCriterion("SKU_CODE <=", value, "skuCode");
			return this;
		}

		public Criteria andSkuCodeLike(String value) {
			addCriterion("SKU_CODE like", value, "skuCode");
			return this;
		}

		public Criteria andSkuCodeNotLike(String value) {
			addCriterion("SKU_CODE not like", value, "skuCode");
			return this;
		}

		public Criteria andSkuCodeIn(List values) {
			addCriterion("SKU_CODE in", values, "skuCode");
			return this;
		}

		public Criteria andSkuCodeNotIn(List values) {
			addCriterion("SKU_CODE not in", values, "skuCode");
			return this;
		}

		public Criteria andSkuCodeBetween(String value1, String value2) {
			addCriterion("SKU_CODE between", value1, value2, "skuCode");
			return this;
		}

		public Criteria andSkuCodeNotBetween(String value1, String value2) {
			addCriterion("SKU_CODE not between", value1, value2, "skuCode");
			return this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return this;
		}

		public Criteria andStatusIn(List values) {
			addCriterion("STATUS in", values, "status");
			return this;
		}

		public Criteria andStatusNotIn(List values) {
			addCriterion("STATUS not in", values, "status");
			return this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return this;
		}
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}