package com.kmzyc.promotion.app.vobject;

import java.util.List;

/**
 * 
 * @author Administrator sections_detail�?
 */
public class SectionsDetail implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 3042545583627121560L;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column SECTIONS_DETAIL.SECTIONS_DETAIL_ID
	 * 
	 * @ibatorgenerated Tue Jul 30 10:57:37 CST 2013
	 */
	private Long sectionsDetailId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column SECTIONS_DETAIL.SECTIONS_ID
	 * 
	 * @ibatorgenerated Tue Jul 30 10:57:37 CST 2013
	 */
	private Long sectionsId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column SECTIONS_DETAIL.PRODUCT_ID
	 * 
	 * @ibatorgenerated Tue Jul 30 10:57:37 CST 2013
	 */
	private Long productId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column SECTIONS_DETAIL.TITLE
	 * 
	 * @ibatorgenerated Tue Jul 30 10:57:37 CST 2013
	 */
	private String title;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column SECTIONS_DETAIL.URL_LINK
	 * 
	 * @ibatorgenerated Tue Jul 30 10:57:37 CST 2013
	 */
	private String urlLink;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column SECTIONS_DETAIL.REFERENCE_PRICE
	 * 
	 * @ibatorgenerated Tue Jul 30 10:57:37 CST 2013
	 */
	private Integer referencePrice;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column SECTIONS_DETAIL.PRICE
	 * 
	 * @ibatorgenerated Tue Jul 30 10:57:37 CST 2013
	 */
	private Integer price;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column SECTIONS_DETAIL.IMAGE
	 * 
	 * @ibatorgenerated Tue Jul 30 10:57:37 CST 2013
	 */
	private String image;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column SECTIONS_DETAIL.SORTNO
	 * 
	 * @ibatorgenerated Tue Jul 30 10:57:37 CST 2013
	 */
	private Short sortno;

	private Long skuId;

	/**
	 * 每条栏目明细关联的产品
	 */
	private List<Product> product;

	private List<ProductSku> productSku;

	//	
	// private Sections sections;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column SECTIONS_DETAIL.SECTIONS_DETAIL_ID
	 * 
	 * @return the value of SECTIONS_DETAIL.SECTIONS_DETAIL_ID
	 * @ibatorgenerated Tue Jul 30 10:57:37 CST 2013
	 */
	public Long getSectionsDetailId() {
		return sectionsDetailId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column SECTIONS_DETAIL.SECTIONS_DETAIL_ID
	 * 
	 * @param sectionsDetailId
	 *            the value for SECTIONS_DETAIL.SECTIONS_DETAIL_ID
	 * @ibatorgenerated Tue Jul 30 10:57:37 CST 2013
	 */
	public void setSectionsDetailId(Long sectionsDetailId) {
		this.sectionsDetailId = sectionsDetailId;
	}

	// ====page
	// ------------ for page
	int skip;
	int max;

	public int getSkip() {
		return skip;
	}

	public void setSkip(int skip) {
		this.skip = skip;
	}

	public int getMax() {
		return max;
	}

	public void setMax(int max) {
		this.max = max;
	}

	public Long getSectionsId() {
		return sectionsId;
	}

	public void setSectionsId(Long sectionsId) {
		this.sectionsId = sectionsId;
	}

	public Long getProductId() {
		return productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getUrlLink() {
		return urlLink;
	}

	public void setUrlLink(String urlLink) {
		this.urlLink = urlLink;
	}

	public Integer getReferencePrice() {
		return referencePrice;
	}

	public void setReferencePrice(Integer referencePrice) {
		this.referencePrice = referencePrice;
	}

	public Integer getPrice() {
		return price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Short getSortno() {
		return sortno;
	}

	public void setSortno(Short sortno) {
		this.sortno = sortno;
	}

	public List<Product> getProduct() {
		return product;
	}

	public void setProduct(List<Product> product) {
		this.product = product;
	}

	public Long getSkuId() {
		return skuId;
	}

	public void setSkuId(Long skuId) {
		this.skuId = skuId;
	}

	public List<ProductSku> getProductSku() {
		return productSku;
	}

	public void setProductSku(List<ProductSku> productSku) {
		this.productSku = productSku;
	}

}