package com.pltfm.cms.vobject;

import java.util.Date;

public class CmsPromotionTask {

    private Integer id;

    private Integer flag;

    private Integer image;

    private Integer status;

    private String output;

    private String ruleName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column CMS_PROMOTION_TASK.BEGIN_TIME
     *
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    private Date beginTime;
    private String beginTimeStr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column CMS_PROMOTION_TASK.END_TIME
     *
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    private Date endTime;
    private String endTimeStr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column CMS_PROMOTION_TASK.NAME
     *
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column CMS_PROMOTION_TASK.MODIFY_DATE
     *
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    private Date modifyDate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column CMS_PROMOTION_TASK.MODIFIED
     *
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    private Integer modified;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column CMS_PROMOTION_TASK.P2
     *
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    private String p2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column CMS_PROMOTION_TASK.P3
     *
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    private String p3;


    /**
     * 开始索引值
     */
    private Integer startIndex;
    /**
     * 结束索引值
     */
    private Integer endIndex;

    /**
     * 内容
     */
    private String content;
    /**
     * 活动类型
     */
    private Integer productFilterType;
    /**
     * 活动规则
     */
    private Integer promotionTypeId;
    /**
     * 广告语
     */
    private String slogan;
    /**
     * 模板路径
     */
    private String tempaltePath;
    /**
     * 发布类型
     */
    private Integer publicType;
    //站点
    private Integer siteId;
    /**
     * id集合
     */
    private String ids;
    /**
     * 运营端类型
     */
    private Integer operateType;

    private String imagesFile;
    private String imagesFile2;
    private String imagesFile3;
    private String imagesFile4;

    public String getOutput() {
        return output;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CMS_PROMOTION_TASK.OUTPUT
     *
     * @param output the value for CMS_PROMOTION_TASK.OUTPUT
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    public void setOutput(String output) {
        this.output = output;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CMS_PROMOTION_TASK.BEGIN_TIME
     *
     * @return the value of CMS_PROMOTION_TASK.BEGIN_TIME
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CMS_PROMOTION_TASK.BEGIN_TIME
     *
     * @param beginTime the value for CMS_PROMOTION_TASK.BEGIN_TIME
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CMS_PROMOTION_TASK.END_TIME
     *
     * @return the value of CMS_PROMOTION_TASK.END_TIME
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CMS_PROMOTION_TASK.END_TIME
     *
     * @param endTime the value for CMS_PROMOTION_TASK.END_TIME
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CMS_PROMOTION_TASK.NAME
     *
     * @return the value of CMS_PROMOTION_TASK.NAME
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CMS_PROMOTION_TASK.NAME
     *
     * @param name the value for CMS_PROMOTION_TASK.NAME
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CMS_PROMOTION_TASK.MODIFY_DATE
     *
     * @return the value of CMS_PROMOTION_TASK.MODIFY_DATE
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CMS_PROMOTION_TASK.MODIFY_DATE
     *
     * @param modifyDate the value for CMS_PROMOTION_TASK.MODIFY_DATE
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    public String getP2() {
        return p2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CMS_PROMOTION_TASK.P2
     *
     * @param p2 the value for CMS_PROMOTION_TASK.P2
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    public void setP2(String p2) {
        this.p2 = p2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column CMS_PROMOTION_TASK.P3
     *
     * @return the value of CMS_PROMOTION_TASK.P3
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    public String getP3() {
        return p3;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column CMS_PROMOTION_TASK.P3
     *
     * @param p3 the value for CMS_PROMOTION_TASK.P3
     * @abatorgenerated Sat Oct 12 16:04:02 CST 2013
     */
    public void setP3(String p3) {
        this.p3 = p3;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getImage() {
        return image;
    }

    public void setImage(Integer image) {
        this.image = image;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getModified() {
        return modified;
    }

    public void setModified(Integer modified) {
        this.modified = modified;
    }

    public Integer getStartIndex() {
        return startIndex;
    }

    public void setStartIndex(Integer startIndex) {
        this.startIndex = startIndex;
    }

    public Integer getEndIndex() {
        return endIndex;
    }

    public void setEndIndex(Integer endIndex) {
        this.endIndex = endIndex;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getImagesFile() {
        return imagesFile;
    }

    public void setImagesFile(String imagesFile) {
        this.imagesFile = imagesFile;
    }

    public String getImagesFile2() {
        return imagesFile2;
    }

    public void setImagesFile2(String imagesFile2) {
        this.imagesFile2 = imagesFile2;
    }

    public String getImagesFile3() {
        return imagesFile3;
    }

    public void setImagesFile3(String imagesFile3) {
        this.imagesFile3 = imagesFile3;
    }

    public String getImagesFile4() {
        return imagesFile4;
    }

    public void setImagesFile4(String imagesFile4) {
        this.imagesFile4 = imagesFile4;
    }

    public Integer getProductFilterType() {
        return productFilterType;
    }

    public void setProductFilterType(Integer productFilterType) {
        this.productFilterType = productFilterType;
    }

    public String getTempaltePath() {
        return tempaltePath;
    }

    public void setTempaltePath(String tempaltePath) {
        this.tempaltePath = tempaltePath;
    }

    public Integer getPromotionTypeId() {
        return promotionTypeId;
    }

    public void setPromotionTypeId(Integer promotionTypeId) {
        this.promotionTypeId = promotionTypeId;
    }

    public String getSlogan() {
        return slogan;
    }

    public void setSlogan(String slogan) {
        this.slogan = slogan;
    }

    public Integer getPublicType() {
        return publicType;
    }

    public void setPublicType(Integer publicType) {
        this.publicType = publicType;
    }

    public Integer getSiteId() {
        return siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    public String getIds() {
        return ids;
    }

    public void setIds(String ids) {
        this.ids = ids;
    }

    public Integer getOperateType() {
        return operateType;
    }

    public void setOperateType(Integer operateType) {
        this.operateType = operateType;
    }

    public Integer getFlag() {
        return flag;
    }

    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    public String getRuleName() {
        return ruleName;
    }

    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }

    public String getBeginTimeStr() {
        return beginTimeStr;
    }

    public void setBeginTimeStr(String beginTimeStr) {
        this.beginTimeStr = beginTimeStr;
    }

    public String getEndTimeStr() {
        return endTimeStr;
    }

    public void setEndTimeStr(String endTimeStr) {
        this.endTimeStr = endTimeStr;
    }

}