package com.pltfm.cms.vobject;

import com.pltfm.sys.model.SysUser;

import java.io.Serializable;
import java.util.Date;

/**
 * 用户与站点
 */
public class CmsUserSite implements Serializable {
    /**
     * 用户站点主键
     */
    private Integer userSiteId;

    /**
     * 用户主键
     */
    private Integer userId;

    /**
     * 用户实体
     */
    private SysUser sysUser;

    /**
     * 站点实体
     */
    private CmsSite cmsSite;

    /**
     * 用户姓名
     */
    private String userName;
    /**
     * 站点主键
     */
    private Integer siteId;

    /**
     * 备注
     */
    private String remark;
    /**
     * 状态:0.有效1.无效
     */
    private Integer status;
    /**
     * 查询条件如 1,2,3
     **/
    private String userIds;
    /**
     * 创建日期
     */
    private Date createDate;

    /**
     * 创建人
     */
    private Integer created;

    /**
     * 修改日期
     */
    private Date modifyDate;

    /**
     * 修改人
     */
    private Integer modified;
    /**
     * 开始索引值
     */
    private Integer startIndex;
    /**
     * 结束索引值
     */

    private Integer endIndex;
    /**
     * 站点名
     */
    private String siteName;


    /**
     * 站点域名
     */
    private String url;

    /**
     * 页面模板路径
     */
    private String templatePath;

    /**
     * 页面输出路径
     */
    private String pageOutputPath;

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getTemplatePath() {
        return templatePath;
    }

    public void setTemplatePath(String templatePath) {
        this.templatePath = templatePath;
    }

    public String getPageOutputPath() {
        return pageOutputPath;
    }

    public void setPageOutputPath(String pageOutputPath) {
        this.pageOutputPath = pageOutputPath;
    }

//		public String getChannel() {
//			return channel;
//		}
//
//		public void setChannel(String channel) {
//			this.channel = channel;
//		}

    /**
     * 对应渠道信息
     */
//	    private String channel;
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Integer getStartIndex() {
        return startIndex;
    }

    public void setStartIndex(Integer startIndex) {
        this.startIndex = startIndex;
    }

    public Integer getEndIndex() {
        return endIndex;
    }

    public void setEndIndex(Integer endIndex) {
        this.endIndex = endIndex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CMS_USER_SITE.USER_SITE_ID
     *
     * @return the value of CMS_USER_SITE.USER_SITE_ID
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public Integer getUserSiteId() {
        return userSiteId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CMS_USER_SITE.USER_SITE_ID
     *
     * @param userSiteId the value for CMS_USER_SITE.USER_SITE_ID
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public void setUserSiteId(Integer userSiteId) {
        this.userSiteId = userSiteId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CMS_USER_SITE.USER_ID
     *
     * @return the value of CMS_USER_SITE.USER_ID
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CMS_USER_SITE.USER_ID
     *
     * @param userId the value for CMS_USER_SITE.USER_ID
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CMS_USER_SITE.SITE_ID
     *
     * @return the value of CMS_USER_SITE.SITE_ID
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CMS_USER_SITE.SITE_ID
     *
     * @param siteId the value for CMS_USER_SITE.SITE_ID
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CMS_USER_SITE.REMARK
     *
     * @return the value of CMS_USER_SITE.REMARK
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CMS_USER_SITE.REMARK
     *
     * @param remark the value for CMS_USER_SITE.REMARK
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CMS_USER_SITE.STATUS
     *
     * @return the value of CMS_USER_SITE.STATUS
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CMS_USER_SITE.STATUS
     *
     * @param status the value for CMS_USER_SITE.STATUS
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CMS_USER_SITE.CREATE_DATE
     *
     * @return the value of CMS_USER_SITE.CREATE_DATE
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CMS_USER_SITE.CREATE_DATE
     *
     * @param createDate the value for CMS_USER_SITE.CREATE_DATE
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CMS_USER_SITE.CREATED
     *
     * @return the value of CMS_USER_SITE.CREATED
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CMS_USER_SITE.CREATED
     *
     * @param created the value for CMS_USER_SITE.CREATED
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CMS_USER_SITE.MODIFY_DATE
     *
     * @return the value of CMS_USER_SITE.MODIFY_DATE
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CMS_USER_SITE.MODIFY_DATE
     *
     * @param modifyDate the value for CMS_USER_SITE.MODIFY_DATE
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column CMS_USER_SITE.MODIFIED
     *
     * @return the value of CMS_USER_SITE.MODIFIED
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public Integer getModified() {
        return modified;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column CMS_USER_SITE.MODIFIED
     *
     * @param modified the value for CMS_USER_SITE.MODIFIED
     * @ibatorgenerated Fri Nov 15 13:56:27 CST 2013
     */
    public void setModified(Integer modified) {
        this.modified = modified;
    }

    public SysUser getSysUser() {
        return sysUser;
    }

    public void setSysUser(SysUser sysUser) {
        this.sysUser = sysUser;
    }

    public CmsSite getCmsSite() {
        return cmsSite;
    }

    public void setCmsSite(CmsSite cmsSite) {
        this.cmsSite = cmsSite;
    }

    public String getSiteName() {
        return siteName;
    }

    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }

    public String getUserIds() {
        return userIds;
    }

    public void setUserIds(String userIds) {
        this.userIds = userIds;
    }


}