package com.kmzyc.promotion.app.dao.impl;

import java.sql.SQLException;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Repository;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.kmzyc.commons.page.Page;
import com.kmzyc.promotion.app.dao.CouponGrantFlowDAO;
import com.kmzyc.promotion.app.vobject.CouponGrantFlow;

@SuppressWarnings("unchecked")
@Repository("couponGrantFlowDao")
public class CouponGrantFlowDAOImpl implements CouponGrantFlowDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table
     * KMPRODUCT.COUPON_GRANT_FLOW
     * 
     * @abatorgenerated Mon Jun 09 04:40:49 CST 2014
     */
    public CouponGrantFlowDAOImpl() {

    }

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * table COUPON_GRANT
     * 
     * @ibatorgenerated Thu Aug 22 09:45:29 CST 2013
     */
    @Resource
    private SqlMapClient sqlMapClient;

    public CouponGrantFlowDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    @Override
    public void insert(CouponGrantFlow record) throws SQLException {
        sqlMapClient.insert("COUPON_GRANT_FLOW.abatorgenerated_insert", record);

    }

    @Override
    public int countItem(CouponGrantFlow couponGrantFlow) throws SQLException {
        // 此SQL不存在
        int i = (Integer) sqlMapClient.queryForObject("COUPON_GRANT_FLOW.countItem",
                couponGrantFlow);

        return i;
    }

    @Override
    public List<CouponGrantFlow> selectList(CouponGrantFlow couponGrantFlow, Page page)
            throws SQLException {
        List<CouponGrantFlow> list = sqlMapClient.queryForList(
                "COUPON_GRANT_FLOW.abatorgenerated_selectByExample", couponGrantFlow,
                (page.getPageNo() - 1) * page.getPageSize(), page.getPageSize());

        return list;
    }

    @Override
    public Page selectPageByVo(Page page, CouponGrantFlow couponGrantFlow) throws SQLException {
        if (couponGrantFlow == null) {
            couponGrantFlow = new CouponGrantFlow();
        }

        int pageIndex = page.getPageNo();
        if (pageIndex == 0)
            pageIndex = 1;
        int pageSize = page.getPageSize();
        int skip = (pageIndex - 1) * pageSize + 1;
        int max = pageSize * pageIndex;
        couponGrantFlow.setSkip(skip);
        couponGrantFlow.setMax(max);

        int count = (Integer) sqlMapClient.queryForObject("COUPON_GRANT_FLOW.getCount",
                couponGrantFlow, "the_count");
        List<CouponGrantFlow> list =
                sqlMapClient.queryForList("COUPON_GRANT_FLOW.selectlist", couponGrantFlow);
        page.setRecordCount(count);
        page.setDataList(list);
        return page;
    }

}
