package com.kmzyc.promotion.app.dao.impl;

import java.sql.SQLException;
import java.util.List;

import org.springframework.stereotype.Repository;

import com.kmzyc.promotion.app.dao.BaseDao;
import com.kmzyc.promotion.app.dao.ViewSkuAttrDAO;
import com.kmzyc.promotion.app.vobject.ViewSkuAttr;
import com.kmzyc.promotion.app.vobject.ViewSkuAttrExample;

/**
 * SKU关联属性视图
 * 
 * @author tanyunxing
 * 
 */
@Repository("viewSkuAttrDao")
@SuppressWarnings({"unchecked", "unused"})
public class ViewSkuAttrDAOImpl extends BaseDao implements ViewSkuAttrDAO {

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table VIEW_SKU_ATTR
   * 
   * @ibatorgenerated Thu Aug 01 17:46:25 CST 2013
   */
  public ViewSkuAttrDAOImpl() {
    super();
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table VIEW_SKU_ATTR
   * 
   * @ibatorgenerated Thu Aug 01 17:46:25 CST 2013
   */
  @Override
  public int countByExample(ViewSkuAttrExample example) throws SQLException {
    // mkw 20150819 add

    // end
    Integer count =
        (Integer) sqlMapClient.queryForObject("VIEW_SKU_ATTR.ibatorgenerated_countByExample",
            example);
    return count.intValue();
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table VIEW_SKU_ATTR
   * 
   * @ibatorgenerated Thu Aug 01 17:46:25 CST 2013
   */
  @Override
  public int deleteByExample(ViewSkuAttrExample example) throws SQLException {
    // mkw 20150819 add

    // end
    int rows = sqlMapClient.delete("VIEW_SKU_ATTR.ibatorgenerated_deleteByExample", example);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table VIEW_SKU_ATTR
   * 
   * @ibatorgenerated Thu Aug 01 17:46:25 CST 2013
   */
  @Override
  public void insert(ViewSkuAttr record) throws SQLException {
    // mkw 20150819 add

    // end
    sqlMapClient.insert("VIEW_SKU_ATTR.ibatorgenerated_insert", record);
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table VIEW_SKU_ATTR
   * 
   * @ibatorgenerated Thu Aug 01 17:46:25 CST 2013
   */
  @Override
  public void insertSelective(ViewSkuAttr record) throws SQLException {
    // mkw 20150819 add

    // end
    sqlMapClient.insert("VIEW_SKU_ATTR.ibatorgenerated_insertSelective", record);
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table VIEW_SKU_ATTR
   * 
   * @ibatorgenerated Thu Aug 01 17:46:25 CST 2013
   */
  @Override
  public List selectByExample(ViewSkuAttrExample example) throws SQLException {
    // mkw 20150819 add

    // end
    List list = sqlMapClient.queryForList("VIEW_SKU_ATTR.ibatorgenerated_selectByExample", example);
    return list;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table VIEW_SKU_ATTR
   * 
   * @ibatorgenerated Thu Aug 01 17:46:25 CST 2013
   */
  @Override
  public int updateByExampleSelective(ViewSkuAttr record, ViewSkuAttrExample example)
      throws SQLException {
    // mkw 20150819 add

    // end
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows = sqlMapClient.update("VIEW_SKU_ATTR.ibatorgenerated_updateByExampleSelective", parms);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table VIEW_SKU_ATTR
   * 
   * @ibatorgenerated Thu Aug 01 17:46:25 CST 2013
   */
  @Override
  public int updateByExample(ViewSkuAttr record, ViewSkuAttrExample example) throws SQLException {
    // mkw 20150819 add

    // end
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows = sqlMapClient.update("VIEW_SKU_ATTR.ibatorgenerated_updateByExample", parms);
    return rows;
  }

  /**
   * This class was generated by Apache iBATIS ibator. This class corresponds to the database table
   * VIEW_SKU_ATTR
   * 
   * @ibatorgenerated Thu Aug 01 17:46:25 CST 2013
   */
  private static class UpdateByExampleParms extends ViewSkuAttrExample {
    private final Object record;

    public UpdateByExampleParms(Object record, ViewSkuAttrExample example) {
      super(example);
      this.record = record;
    }

    public Object getRecord() {
      return record;
    }
  }

  @Override
  public Long selectByAttrIdAndValueId(ViewSkuAttrExample example) throws SQLException {
    // mkw 20150819 add

    // end
    Object obj = sqlMapClient.queryForObject("VIEW_SKU_ATTR.findSkuIdByAttrAndValue", example);
    return (Long) obj;
  }

  @Override
  public List<ViewSkuAttr> findProductAttrAndValueByProductId(Long productId) throws SQLException {
    // mkw 20150819 add

    // end
    return sqlMapClient.queryForList("VIEW_SKU_ATTR.queryProductAttrAndValue", productId);
  }
}
