package com.pltfm.cms.dao;

import com.pltfm.cms.vobject.CmsAdcolumn;
import com.pltfm.cms.vobject.CmsAdv;
import com.pltfm.cms.vobject.CmsAdvExample;

import java.sql.SQLException;
import java.util.List;

public interface CmsAdvDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table CMS_ADV
     *
     * @abatorgenerated Tue Sep 03 08:55:19 CST 2013
     */
    Integer insert(CmsAdv record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table CMS_ADV
     *
     * @abatorgenerated Tue Sep 03 08:55:19 CST 2013
     */
    int updateByPrimaryKeyWithoutBLOBs(CmsAdv record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table CMS_ADV
     *
     * @abatorgenerated Tue Sep 03 08:55:19 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(CmsAdv record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table CMS_ADV
     *
     * @abatorgenerated Tue Sep 03 08:55:19 CST 2013
     */
    int updateByPrimaryKeySelective(CmsAdv record) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table CMS_ADV
     *
     * @abatorgenerated Tue Sep 03 08:55:19 CST 2013
     */
    List selectByExampleWithoutBLOBs(CmsAdvExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table CMS_ADV
     *
     * @abatorgenerated Tue Sep 03 08:55:19 CST 2013
     */
    List selectByExampleWithBLOBs(CmsAdvExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table CMS_ADV
     *
     * @abatorgenerated Tue Sep 03 08:55:19 CST 2013
     */
    CmsAdv selectByPrimaryKey(Integer advId) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table CMS_ADV
     *
     * @abatorgenerated Tue Sep 03 08:55:19 CST 2013
     */
    int deleteByExample(CmsAdvExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table CMS_ADV
     *
     * @abatorgenerated Tue Sep 03 08:55:19 CST 2013
     */
    int deleteByPrimaryKey(Integer advId) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table CMS_ADV
     *
     * @abatorgenerated Tue Sep 03 08:55:19 CST 2013
     */
    int countByExample(CmsAdv example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table CMS_ADV
     *
     * @abatorgenerated Tue Sep 03 08:55:19 CST 2013
     */
    int updateByExampleSelective(CmsAdv record, CmsAdvExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table CMS_ADV
     *
     * @abatorgenerated Tue Sep 03 08:55:19 CST 2013
     */
    int updateByExampleWithBLOBs(CmsAdv record, CmsAdvExample example) throws SQLException;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table CMS_ADV
     *
     * @abatorgenerated Tue Sep 03 08:55:19 CST 2013
     */
    int updateByExampleWithoutBLOBs(CmsAdv record, CmsAdvExample example) throws SQLException;

    public List queryForPage(CmsAdv record) throws SQLException;

    public List adcolumnList(int i) throws SQLException;

    public CmsAdv byid(Integer Advid) throws SQLException;

    //返回广告列表
    public List queryAdvList(CmsAdv cmsAdv) throws SQLException;

    //自动检查广告是否过期
    public List checkAllAdv() throws SQLException;

    public Integer countByAdvname(CmsAdv cmsAdv) throws SQLException;

    /**
     * 根据广告查询条件获取记录数
     *
     * @param cmsAdv 广告
     * @return 记录数
     */
    public Integer countByAdv(CmsAdv cmsAdv) throws SQLException;

    //查询需要更新的广告数据


    public List queryUpdateAdvTempList(CmsAdcolumn cmsAdcolumn) throws SQLException;
}