package com.pltfm.cms.dao;

import com.pltfm.cms.vobject.CmsAppManage;
import com.pltfm.cms.vobject.CmsAppManageExample;

import java.sql.SQLException;
import java.util.List;

/**
 * 手机端应用管理DAO接口
 *
 * @author cjm
 * @since 2014-4-18
 */
public interface CmsAppManageDAO {


    /**
     * 手机端应用信息总数量
     *
     * @param cmsAppManage 手机端应用信息实体
     * @throws SQLException 异常
     * @return 返回值
     */
    public Integer countByCmsAppManage(CmsAppManage cmsAppManage) throws SQLException;

    /**
     * 查询同一应用名称、版本名、版本号 记录数
     */
    public Integer countByNameAndVer(CmsAppManage cmsAppManage) throws SQLException;

    /**
     * 分页查询手机端应用信息
     *
     * @param cmsAppManage 手机端应用信息实体
     * @throws SQLException 异常
     * @return 返回值
     */
    public List queryForPage(CmsAppManage cmsAppManage) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    int countByExample(CmsAppManageExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    int deleteByExample(CmsAppManageExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    int deleteByPrimaryKey(Integer appmanageId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    void insert(CmsAppManage record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    void insertSelective(CmsAppManage record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    List selectByExample(CmsAppManageExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    CmsAppManage selectByPrimaryKey(Integer appmanageId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    int updateByExampleSelective(CmsAppManage record, CmsAppManageExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    int updateByExample(CmsAppManage record, CmsAppManageExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    int updateByPrimaryKeySelective(CmsAppManage record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table CMS_APP_MANAGE
     *
     * @ibatorgenerated Fri Apr 18 14:10:48 CST 2014
     */
    int updateByPrimaryKey(CmsAppManage record) throws SQLException;
}