package com.pltfm.sys.dao;

import com.pltfm.sys.model.ReportParam;
import com.pltfm.sys.model.ReportParamExample;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;

public class ReportParamDAOImpl implements ReportParamDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table report_param
	 * @ibatorgenerated  Thu Jan 28 16:04:43 CST 2010
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table report_param
	 * @ibatorgenerated  Thu Jan 28 16:04:43 CST 2010
	 */
	public ReportParamDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table report_param
	 * @ibatorgenerated  Thu Jan 28 16:04:43 CST 2010
	 */
	public int countByExample(ReportParamExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject(
				"report_param.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table report_param
	 * @ibatorgenerated  Thu Jan 28 16:04:43 CST 2010
	 */
	public int deleteByExample(ReportParamExample example) throws SQLException {
		int rows = sqlMapClient.delete(
				"report_param.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table report_param
	 * @ibatorgenerated  Thu Jan 28 16:04:43 CST 2010
	 */
	public int deleteByPrimaryKey(Integer paramId) throws SQLException {
		ReportParam key = new ReportParam();
		key.setParamId(paramId);
		int rows = sqlMapClient.delete(
				"report_param.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table report_param
	 * @ibatorgenerated  Thu Jan 28 16:04:43 CST 2010
	 */
	public Integer insert(ReportParam record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"report_param.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table report_param
	 * @ibatorgenerated  Thu Jan 28 16:04:43 CST 2010
	 */
	public Integer insertSelective(ReportParam record) throws SQLException {
		Object newKey = sqlMapClient.insert(
				"report_param.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table report_param
	 * @ibatorgenerated  Thu Jan 28 16:04:43 CST 2010
	 */
	public List selectByExample(ReportParamExample example) throws SQLException {
		List list = sqlMapClient.queryForList(
				"report_param.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table report_param
	 * @ibatorgenerated  Thu Jan 28 16:04:43 CST 2010
	 */
	public ReportParam selectByPrimaryKey(Integer paramId) throws SQLException {
		ReportParam key = new ReportParam();
		key.setParamId(paramId);
		ReportParam record = (ReportParam) sqlMapClient.queryForObject(
				"report_param.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table report_param
	 * @ibatorgenerated  Thu Jan 28 16:04:43 CST 2010
	 */
	public int updateByExampleSelective(ReportParam record,
			ReportParamExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"report_param.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table report_param
	 * @ibatorgenerated  Thu Jan 28 16:04:43 CST 2010
	 */
	public int updateByExample(ReportParam record, ReportParamExample example)
			throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update(
				"report_param.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table report_param
	 * @ibatorgenerated  Thu Jan 28 16:04:43 CST 2010
	 */
	public int updateByPrimaryKeySelective(ReportParam record)
			throws SQLException {
		int rows = sqlMapClient.update(
				"report_param.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table report_param
	 * @ibatorgenerated  Thu Jan 28 16:04:43 CST 2010
	 */
	public int updateByPrimaryKey(ReportParam record) throws SQLException {
		int rows = sqlMapClient.update(
				"report_param.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table report_param
	 * @ibatorgenerated  Thu Jan 28 16:04:43 CST 2010
	 */
	private static class UpdateByExampleParms extends ReportParamExample {
		private Object record;

		public UpdateByExampleParms(Object record, ReportParamExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}