package com.pltfm.app.vobject;

import java.io.Serializable;
import java.util.Date;

/**
 * 用药史信息.
 * 
 *
 *
 */
public class DrugHistoryInfo implements Serializable {
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * DRUG_HISTORY_INFO.N_DRUG_HISTORY_ID
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  private Integer nDrugHistoryId;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * DRUG_HISTORY_INFO.N_HEALTH_YGENERIC_ID
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  private Integer nHealthYgenericId;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * DRUG_HISTORY_INFO.DRUG_NAME
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  private String drugName;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * DRUG_HISTORY_INFO.N_DOSE
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  private Integer nDose;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * DRUG_HISTORY_INFO.PRESCRIBE_NAME
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  private String prescribeName;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * DRUG_HISTORY_INFO.D_PRESCRIBE_TIME
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  private Date dPrescribeTime;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * DRUG_HISTORY_INFO.DOCTOR
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  private String doctor;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * DRUG_HISTORY_INFO.D_CREATE_DATE
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  private Date dCreateDate;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * DRUG_HISTORY_INFO.N_CREATED
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  private Integer nCreated;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * DRUG_HISTORY_INFO.D_MODIFY_DATE
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  private Date dModifyDate;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database column
   * DRUG_HISTORY_INFO.N_MODIFIED
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  private Integer nModified;

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column DRUG_HISTORY_INFO.N_DRUG_HISTORY_ID
   *
   * @return the value of DRUG_HISTORY_INFO.N_DRUG_HISTORY_ID
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public Integer getnDrugHistoryId() {
    return nDrugHistoryId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column DRUG_HISTORY_INFO.N_DRUG_HISTORY_ID
   *
   * @param nDrugHistoryId the value for DRUG_HISTORY_INFO.N_DRUG_HISTORY_ID
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public void setnDrugHistoryId(Integer nDrugHistoryId) {
    this.nDrugHistoryId = nDrugHistoryId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column DRUG_HISTORY_INFO.N_HEALTH_YGENERIC_ID
   *
   * @return the value of DRUG_HISTORY_INFO.N_HEALTH_YGENERIC_ID
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public Integer getnHealthYgenericId() {
    return nHealthYgenericId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column DRUG_HISTORY_INFO.N_HEALTH_YGENERIC_ID
   *
   * @param nHealthYgenericId the value for DRUG_HISTORY_INFO.N_HEALTH_YGENERIC_ID
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public void setnHealthYgenericId(Integer nHealthYgenericId) {
    this.nHealthYgenericId = nHealthYgenericId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column DRUG_HISTORY_INFO.DRUG_NAME
   *
   * @return the value of DRUG_HISTORY_INFO.DRUG_NAME
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public String getDrugName() {
    return drugName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column DRUG_HISTORY_INFO.DRUG_NAME
   *
   * @param drugName the value for DRUG_HISTORY_INFO.DRUG_NAME
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public void setDrugName(String drugName) {
    this.drugName = drugName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column DRUG_HISTORY_INFO.N_DOSE
   *
   * @return the value of DRUG_HISTORY_INFO.N_DOSE
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public Integer getnDose() {
    return nDose;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column DRUG_HISTORY_INFO.N_DOSE
   *
   * @param nDose the value for DRUG_HISTORY_INFO.N_DOSE
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public void setnDose(Integer nDose) {
    this.nDose = nDose;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column DRUG_HISTORY_INFO.PRESCRIBE_NAME
   *
   * @return the value of DRUG_HISTORY_INFO.PRESCRIBE_NAME
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public String getPrescribeName() {
    return prescribeName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column DRUG_HISTORY_INFO.PRESCRIBE_NAME
   *
   * @param prescribeName the value for DRUG_HISTORY_INFO.PRESCRIBE_NAME
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public void setPrescribeName(String prescribeName) {
    this.prescribeName = prescribeName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column DRUG_HISTORY_INFO.D_PRESCRIBE_TIME
   *
   * @return the value of DRUG_HISTORY_INFO.D_PRESCRIBE_TIME
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public Date getdPrescribeTime() {
    return dPrescribeTime;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column DRUG_HISTORY_INFO.D_PRESCRIBE_TIME
   *
   * @param dPrescribeTime the value for DRUG_HISTORY_INFO.D_PRESCRIBE_TIME
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public void setdPrescribeTime(Date dPrescribeTime) {
    this.dPrescribeTime = dPrescribeTime;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column DRUG_HISTORY_INFO.DOCTOR
   *
   * @return the value of DRUG_HISTORY_INFO.DOCTOR
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public String getDoctor() {
    return doctor;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column DRUG_HISTORY_INFO.DOCTOR
   *
   * @param doctor the value for DRUG_HISTORY_INFO.DOCTOR
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public void setDoctor(String doctor) {
    this.doctor = doctor;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column DRUG_HISTORY_INFO.D_CREATE_DATE
   *
   * @return the value of DRUG_HISTORY_INFO.D_CREATE_DATE
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public Date getdCreateDate() {
    return dCreateDate;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column DRUG_HISTORY_INFO.D_CREATE_DATE
   *
   * @param dCreateDate the value for DRUG_HISTORY_INFO.D_CREATE_DATE
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public void setdCreateDate(Date dCreateDate) {
    this.dCreateDate = dCreateDate;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column DRUG_HISTORY_INFO.N_CREATED
   *
   * @return the value of DRUG_HISTORY_INFO.N_CREATED
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public Integer getnCreated() {
    return nCreated;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column DRUG_HISTORY_INFO.N_CREATED
   *
   * @param nCreated the value for DRUG_HISTORY_INFO.N_CREATED
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public void setnCreated(Integer nCreated) {
    this.nCreated = nCreated;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column DRUG_HISTORY_INFO.D_MODIFY_DATE
   *
   * @return the value of DRUG_HISTORY_INFO.D_MODIFY_DATE
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public Date getdModifyDate() {
    return dModifyDate;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column DRUG_HISTORY_INFO.D_MODIFY_DATE
   *
   * @param dModifyDate the value for DRUG_HISTORY_INFO.D_MODIFY_DATE
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public void setdModifyDate(Date dModifyDate) {
    this.dModifyDate = dModifyDate;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column DRUG_HISTORY_INFO.N_MODIFIED
   *
   * @return the value of DRUG_HISTORY_INFO.N_MODIFIED
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public Integer getnModified() {
    return nModified;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column DRUG_HISTORY_INFO.N_MODIFIED
   *
   * @param nModified the value for DRUG_HISTORY_INFO.N_MODIFIED
   *
   * @ibatorgenerated Fri Jul 12 09:37:37 CST 2013
   */
  public void setnModified(Integer nModified) {
    this.nModified = nModified;
  }
}
