package com.pltfm.app.dao.impl;

import java.sql.SQLException;
import java.util.List;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Repository;

import com.pltfm.app.dao.BaseDAO;
import com.pltfm.app.dao.CouponStatementDAO;
import com.pltfm.app.entities.CouponStatement;
import com.pltfm.app.entities.CouponStatementExample;

@SuppressWarnings("unchecked")
@Repository("couponStatementDAO")
@Scope("singleton")
public class CouponStatementDAOImpl extends BaseDAO implements CouponStatementDAO {
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database table
   * KMORDER.FARE_TYPE
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  // private SqlMapClient sqlMapClient;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.FARE_TYPE
   * 
   * @ibatorgenerated Wed Aug 07 14:18:22 CST 2013
   */
  // public FareTypeDAOImpl(SqlMapClient sqlMapClient) {
  // super();
  // this.sqlMapClient = sqlMapClient;
  // }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.COUPON_STATEMENT
   * 
   * @ibatorgenerated Wed Jan 08 15:27:02 CST 2014
   */
  public int countByExample(CouponStatementExample example) throws SQLException {
    Integer count =
        (Integer) sqlMapClient.queryForObject(
            "KMORDER_COUPON_STATEMENT.ibatorgenerated_countByExample", example);
    return count.intValue();
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.COUPON_STATEMENT
   * 
   * @ibatorgenerated Wed Jan 08 15:27:02 CST 2014
   */
  public int deleteByExample(CouponStatementExample example) throws SQLException {
    int rows =
        sqlMapClient.delete("KMORDER_COUPON_STATEMENT.ibatorgenerated_deleteByExample", example);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.COUPON_STATEMENT
   * 
   * @ibatorgenerated Wed Jan 08 15:27:02 CST 2014
   */
  public int deleteByPrimaryKey(Long statementNo) throws SQLException {
    CouponStatement key = new CouponStatement();
    key.setStatementNo(statementNo);
    int rows =
        sqlMapClient.delete("KMORDER_COUPON_STATEMENT.ibatorgenerated_deleteByPrimaryKey", key);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.COUPON_STATEMENT
   * 
   * @ibatorgenerated Wed Jan 08 15:27:02 CST 2014
   */
  public Long insert(CouponStatement record) throws SQLException {
    Object newKey = sqlMapClient.insert("KMORDER_COUPON_STATEMENT.ibatorgenerated_insert", record);
    return (Long) newKey;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.COUPON_STATEMENT
   * 
   * @ibatorgenerated Wed Jan 08 15:27:02 CST 2014
   */
  public Long insertSelective(CouponStatement record) throws SQLException {
    Object newKey =
        sqlMapClient.insert("KMORDER_COUPON_STATEMENT.ibatorgenerated_insertSelective", record);
    return (Long) newKey;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.COUPON_STATEMENT
   * 
   * @ibatorgenerated Wed Jan 08 15:27:02 CST 2014
   */
  public List selectByExample(CouponStatementExample example) throws SQLException {
    List list =
        sqlMapClient.queryForList("KMORDER_COUPON_STATEMENT.ibatorgenerated_selectByExample",
            example);
    return list;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.COUPON_STATEMENT
   * 
   * @ibatorgenerated Wed Jan 08 15:27:02 CST 2014
   */
  public CouponStatement selectByPrimaryKey(Long statementNo) throws SQLException {
    CouponStatement key = new CouponStatement();
    key.setStatementNo(statementNo);
    CouponStatement record =
        (CouponStatement) sqlMapClient.queryForObject(
            "KMORDER_COUPON_STATEMENT.ibatorgenerated_selectByPrimaryKey", key);
    return record;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.COUPON_STATEMENT
   * 
   * @ibatorgenerated Wed Jan 08 15:27:02 CST 2014
   */
  public int updateByExampleSelective(CouponStatement record, CouponStatementExample example)
      throws SQLException {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows =
        sqlMapClient.update("KMORDER_COUPON_STATEMENT.ibatorgenerated_updateByExampleSelective",
            parms);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.COUPON_STATEMENT
   * 
   * @ibatorgenerated Wed Jan 08 15:27:02 CST 2014
   */
  public int updateByExample(CouponStatement record, CouponStatementExample example)
      throws SQLException {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows =
        sqlMapClient.update("KMORDER_COUPON_STATEMENT.ibatorgenerated_updateByExample", parms);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.COUPON_STATEMENT
   * 
   * @ibatorgenerated Wed Jan 08 15:27:02 CST 2014
   */
  public int updateByPrimaryKeySelective(CouponStatement record) throws SQLException {
    int rows =
        sqlMapClient.update("KMORDER_COUPON_STATEMENT.ibatorgenerated_updateByPrimaryKeySelective",
            record);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.COUPON_STATEMENT
   * 
   * @ibatorgenerated Wed Jan 08 15:27:02 CST 2014
   */
  public int updateByPrimaryKey(CouponStatement record) throws SQLException {
    int rows =
        sqlMapClient.update("KMORDER_COUPON_STATEMENT.ibatorgenerated_updateByPrimaryKey", record);
    return rows;
  }

  /**
   * This class was generated by Apache iBATIS ibator. This class corresponds to the database table
   * KMORDER.COUPON_STATEMENT
   * 
   * @ibatorgenerated Wed Jan 08 15:27:02 CST 2014
   */
  private static class UpdateByExampleParms extends CouponStatementExample {
    private static final long serialVersionUID = 1L;
    private Object record;

    public UpdateByExampleParms(Object record, CouponStatementExample example) {
      super(example);
      this.record = record;
    }

    @SuppressWarnings("unused")
    public Object getRecord() {
      return record;
    }
  }

  @Override
  public int batchUpdateByPrimaryKey(List<CouponStatement> records) throws SQLException {
    sqlMapClient.startBatch();
    int result = 0;
    for (CouponStatement cs : records) {
      try {
        result =
            sqlMapClient.update("KMORDER_COUPON_STATEMENT.ibatorgenerated_updateByPrimaryKey", cs);
      } catch (Exception e) {
        result = 0;
        logger.error("更改出现错误", e);
      }
    }
    sqlMapClient.executeBatch();
    return result;
  }
}
