package com.pltfm.app.dao.impl;

import java.sql.SQLException;
import java.util.List;

import org.springframework.stereotype.Repository;

import com.pltfm.app.dao.BaseDAO;
import com.pltfm.app.dao.InvoiceDictionaryDAO;
import com.pltfm.app.entities.InvoiceDictionary;
import com.pltfm.app.entities.InvoiceDictionaryExample;

@SuppressWarnings("unchecked")
@Repository("invoiceDictionaryDAO")
public class InvoiceDictionaryDAOImpl extends BaseDAO implements InvoiceDictionaryDAO {
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database table
   * KMORDER.INVOICE_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  // private SqlMapClient sqlMapClient;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  // public InvoiceDictionaryDAOImpl(SqlMapClient sqlMapClient) {
  // super();
  // this.sqlMapClient = sqlMapClient;
  // }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int countByExample(InvoiceDictionaryExample example) throws SQLException {
    Integer count =
        (Integer) sqlMapClient.queryForObject(
            "KMORDER_INVOICE_DICTIONARY.ibatorgenerated_countByExample", example);
    return count.intValue();
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int deleteByExample(InvoiceDictionaryExample example) throws SQLException {
    int rows =
        sqlMapClient.delete("KMORDER_INVOICE_DICTIONARY.ibatorgenerated_deleteByExample", example);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int deleteByPrimaryKey(long invoice_dictionary_id) throws SQLException {
    InvoiceDictionary key = new InvoiceDictionary();
    key.setInvoice_dictionary_id(invoice_dictionary_id);
    int rows =
        sqlMapClient.delete("KMORDER_INVOICE_DICTIONARY.ibatorgenerated_deleteByPrimaryKey", key);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public void insert(InvoiceDictionary record) throws SQLException {
    sqlMapClient.insert("KMORDER_INVOICE_DICTIONARY.ibatorgenerated_insert", record);
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public void insertSelective(InvoiceDictionary record) throws SQLException {
    sqlMapClient.insert("KMORDER_INVOICE_DICTIONARY.ibatorgenerated_insertSelective", record);
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public List selectByExample(InvoiceDictionaryExample example) throws SQLException {
    List list =
        sqlMapClient.queryForList("KMORDER_INVOICE_DICTIONARY.ibatorgenerated_selectByExample",
            example);
    return list;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public InvoiceDictionary selectByPrimaryKey(long invoice_dictionary_id) throws SQLException {
    InvoiceDictionary key = new InvoiceDictionary();
    key.setInvoice_dictionary_id(invoice_dictionary_id);
    InvoiceDictionary record =
        (InvoiceDictionary) sqlMapClient.queryForObject(
            "KMORDER_INVOICE_DICTIONARY.ibatorgenerated_selectByPrimaryKey", key);
    return record;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int updateByExampleSelective(InvoiceDictionary record, InvoiceDictionaryExample example)
      throws SQLException {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows =
        sqlMapClient.update("KMORDER_INVOICE_DICTIONARY.ibatorgenerated_updateByExampleSelective",
            parms);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int updateByExample(InvoiceDictionary record, InvoiceDictionaryExample example)
      throws SQLException {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows =
        sqlMapClient.update("KMORDER_INVOICE_DICTIONARY.ibatorgenerated_updateByExample", parms);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int updateByPrimaryKeySelective(InvoiceDictionary record) throws SQLException {
    int rows =
        sqlMapClient.update(
            "KMORDER_INVOICE_DICTIONARY.ibatorgenerated_updateByPrimaryKeySelective", record);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int updateByPrimaryKey(InvoiceDictionary record) throws SQLException {
    int rows =
        sqlMapClient
            .update("KMORDER_INVOICE_DICTIONARY.ibatorgenerated_updateByPrimaryKey", record);
    return rows;
  }

  /**
   * This class was generated by Apache iBATIS ibator. This class corresponds to the database table
   * KMORDER.INVOICE_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  private static class UpdateByExampleParms extends InvoiceDictionaryExample {
    private static final long serialVersionUID = 1L;
    private Object record;

    public UpdateByExampleParms(Object record, InvoiceDictionaryExample example) {
      super(example);
      this.record = record;
    }

    @SuppressWarnings("unused")
    public Object getRecord() {
      return record;
    }
  }
}
