package com.pltfm.app.dao.impl;

import java.sql.SQLException;
import java.util.List;

import org.springframework.stereotype.Repository;

import com.pltfm.app.dao.BaseDAO;
import com.pltfm.app.dao.InvoiceDAO;
import com.pltfm.app.entities.Invoice;
import com.pltfm.app.entities.InvoiceExample;

@SuppressWarnings("unchecked")
@Repository("invoiceDAO")
public class InvoiceDAOImpl extends BaseDAO implements InvoiceDAO {
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database table
   * KMORDER.INVOICE
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  // private SqlMapClient sqlMapClient;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  // public InvoiceDAOImpl(SqlMapClient sqlMapClient) {
  // super();
  // this.sqlMapClient = sqlMapClient;
  // }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int countByExample(InvoiceExample example) throws SQLException {
    Integer count =
        (Integer) sqlMapClient.queryForObject("KMORDER_INVOICE.ibatorgenerated_countByExample",
            example);
    return count.intValue();
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int deleteByExample(InvoiceExample example) throws SQLException {
    int rows = sqlMapClient.delete("KMORDER_INVOICE.ibatorgenerated_deleteByExample", example);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public Long insert(Invoice record) throws SQLException {
    Object newKey = sqlMapClient.insert("KMORDER_INVOICE.ibatorgenerated_insert", record);
    return (Long) newKey;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public Long insertSelective(Invoice record) throws SQLException {
    Object newKey = sqlMapClient.insert("KMORDER_INVOICE.ibatorgenerated_insertSelective", record);
    return (Long) newKey;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public List selectByExample(InvoiceExample example) throws SQLException {
    List list =
        sqlMapClient.queryForList("KMORDER_INVOICE.ibatorgenerated_selectByExample", example);
    return list;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int updateByExampleSelective(Invoice record, InvoiceExample example) throws SQLException {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows =
        sqlMapClient.update("KMORDER_INVOICE.ibatorgenerated_updateByExampleSelective", parms);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.INVOICE
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int updateByExample(Invoice record, InvoiceExample example) throws SQLException {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows = sqlMapClient.update("KMORDER_INVOICE.ibatorgenerated_updateByExample", parms);
    return rows;
  }

  /**
   * This class was generated by Apache iBATIS ibator. This class corresponds to the database table
   * KMORDER.INVOICE
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  private static class UpdateByExampleParms extends InvoiceExample {
    private static final long serialVersionUID = 1L;
    private Object record;

    public UpdateByExampleParms(Object record, InvoiceExample example) {
      super(example);
      this.record = record;
    }

    @SuppressWarnings("unused")
    public Object getRecord() {
      return record;
    }
  }

  @Override
  public Invoice selectByPrimaryKey(Long invoiceId) throws SQLException {
    Invoice key = new Invoice();
    key.setInvoiceId(invoiceId);
    Invoice record =
        (Invoice) sqlMapClient.queryForObject("KMORDER_INVOICE.ibatorgenerated_selectByPrimaryKey",
            key);

    return record;
  }

}
