package com.pltfm.app.dao.impl;

import java.sql.SQLException;
import java.util.List;

import org.springframework.stereotype.Repository;

import com.pltfm.app.dao.BaseDAO;
import com.pltfm.app.dao.OrderDictionaryDAO;
import com.pltfm.app.entities.OrderDictionary;
import com.pltfm.app.entities.OrderDictionaryExample;

@SuppressWarnings("unchecked")
@Repository("orderDictionaryDAO")
public class OrderDictionaryDAOImpl extends BaseDAO implements OrderDictionaryDAO {
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database table
   * KMORDER.ORDER_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  // private SqlMapClient sqlMapClient;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  // public OrderDictionaryDAOImpl(SqlMapClient sqlMapClient) {
  // super();
  // this.sqlMapClient = sqlMapClient;
  // }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int countByExample(OrderDictionaryExample example) throws SQLException {
    Integer count =
        (Integer) sqlMapClient.queryForObject(
            "KMORDER_ORDER_DICTIONARY.ibatorgenerated_countByExample", example);
    return count.intValue();
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int deleteByExample(OrderDictionaryExample example) throws SQLException {
    int rows =
        sqlMapClient.delete("KMORDER_ORDER_DICTIONARY.ibatorgenerated_deleteByExample", example);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int deleteByPrimaryKey(long order_dictionary_id) throws SQLException {
    OrderDictionary key = new OrderDictionary();
    key.setOrder_dictionary_id(order_dictionary_id);
    int rows =
        sqlMapClient.delete("KMORDER_ORDER_DICTIONARY.ibatorgenerated_deleteByPrimaryKey", key);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public void insert(OrderDictionary record) throws SQLException {
    sqlMapClient.insert("KMORDER_ORDER_DICTIONARY.ibatorgenerated_insert", record);
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public void insertSelective(OrderDictionary record) throws SQLException {
    sqlMapClient.insert("KMORDER_ORDER_DICTIONARY.ibatorgenerated_insertSelective", record);
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public List selectByExample(OrderDictionaryExample example) throws SQLException {
    List list =
        sqlMapClient.queryForList("KMORDER_ORDER_DICTIONARY.ibatorgenerated_selectByExample",
            example);
    return list;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public OrderDictionary selectByPrimaryKey(long order_dictionary_id) throws SQLException {
    OrderDictionary key = new OrderDictionary();
    key.setOrder_dictionary_id(order_dictionary_id);
    OrderDictionary record =
        (OrderDictionary) sqlMapClient.queryForObject(
            "KMORDER_ORDER_DICTIONARY.ibatorgenerated_selectByPrimaryKey", key);
    return record;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int updateByExampleSelective(OrderDictionary record, OrderDictionaryExample example)
      throws SQLException {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows =
        sqlMapClient.update("KMORDER_ORDER_DICTIONARY.ibatorgenerated_updateByExampleSelective",
            parms);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int updateByExample(OrderDictionary record, OrderDictionaryExample example)
      throws SQLException {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows =
        sqlMapClient.update("KMORDER_ORDER_DICTIONARY.ibatorgenerated_updateByExample", parms);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int updateByPrimaryKeySelective(OrderDictionary record) throws SQLException {
    int rows =
        sqlMapClient.update("KMORDER_ORDER_DICTIONARY.ibatorgenerated_updateByPrimaryKeySelective",
            record);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public int updateByPrimaryKey(OrderDictionary record) throws SQLException {
    int rows =
        sqlMapClient.update("KMORDER_ORDER_DICTIONARY.ibatorgenerated_updateByPrimaryKey", record);
    return rows;
  }

  /**
   * This class was generated by Apache iBATIS ibator. This class corresponds to the database table
   * KMORDER.ORDER_DICTIONARY
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  private static class UpdateByExampleParms extends OrderDictionaryExample {
    private static final long serialVersionUID = 1L;
    private Object record;

    public UpdateByExampleParms(Object record, OrderDictionaryExample example) {
      super(example);
      this.record = record;
    }

    @SuppressWarnings("unused")
    public Object getRecord() {
      return record;
    }
  }

  public void updateList(List<OrderDictionary> records) throws SQLException {
    super.batchUpdateData("KMORDER_ORDER_DICTIONARY.ibatorgenerated_updateByPrimaryKeySelective",
        records);
  }

  public void deleteList(List<OrderDictionary> records) throws SQLException {
    super.batchUpdateData("KMORDER_ORDER_DICTIONARY.ibatorgenerated_deleteByPrimaryKey", records);
  }

  public void insertList(List<OrderDictionary> records) throws SQLException {
    super.batchUpdateData("KMORDER_ORDER_DICTIONARY.ibatorgenerated_insert", records);
  }

  public List<OrderDictionary> queryDictionaryByType(String type) throws SQLException {
    List<OrderDictionary> dictList =
        (List<OrderDictionary>) super.queryForList(
            "KMORDER_ORDER_DICTIONARY.queryDictionaryByType", type);
    return dictList;
  }
}
