package com.pltfm.app.fobject;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * 店内分类类目实体
 * 
 * @author Administrator
 * 
 */
public class ShopCategorys implements Serializable {
  /**
	 * 
	 */
  private static final long serialVersionUID = 1023198528082384325L;

  /**
   * 店内分类类目ID
   */
  private Long shopCategoryId;

  /**
   * 店铺ID
   */
  private Long shopId;

  /**
   * 父类编码ID
   */
  private Long parentCategoryId;

  /**
   * 类目编码规则
   */
  private String categoryCode;

  /**
   * 类目名称
   */
  private String categoryName;

  /**
   * 类目级别
   */
  private Integer categoryLevel;

  /**
   * 启用状态
   */
  private Integer status;

  /**
   * 排列序号
   */
  private Integer sortno;

  /**
   * 创建时间
   */
  private Date createTime;

  /**
   * 最后修改时间
   */
  private Date modifTime;

  /**
   * 最后修改人
   */
  private Long modifUser;

  /**
     * 
     */
  private String execSql;

  /**
   * 是否为重点推荐类目 0:不推荐 1:推荐
   */
  private Integer isSuggest;


  /**
   * 类目备注
   */
  private String remark;

  /**
   * 该店内类目所在店所属的供应商ID
   */
  private String supplierId;

  /**
   * 一级类目是否默认展开
   */
  private String isExpandAll;

  /**
   * 是否为店铺的默认分类字段,为0则说明是店铺的默认分类
   */
  private String isDefault;

  /**
   * 二级类目集合
   */
  private List<ShopCategorys> shopCategoryChildrenList = new ArrayList<ShopCategorys>();

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column SHOP_CATEGORYS.SHOP_CATEGORY_ID
   * 
   * @return the value of SHOP_CATEGORYS.SHOP_CATEGORY_ID
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public Long getShopCategoryId() {
    return shopCategoryId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column SHOP_CATEGORYS.SHOP_CATEGORY_ID
   * 
   * @param shopCategoryId the value for SHOP_CATEGORYS.SHOP_CATEGORY_ID
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public void setShopCategoryId(Long shopCategoryId) {
    this.shopCategoryId = shopCategoryId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column SHOP_CATEGORYS.SHOP_ID
   * 
   * @return the value of SHOP_CATEGORYS.SHOP_ID
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public Long getShopId() {
    return shopId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column SHOP_CATEGORYS.SHOP_ID
   * 
   * @param shopId the value for SHOP_CATEGORYS.SHOP_ID
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public void setShopId(Long shopId) {
    this.shopId = shopId;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column SHOP_CATEGORYS.CATEGORY_CODE
   * 
   * @return the value of SHOP_CATEGORYS.CATEGORY_CODE
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public String getCategoryCode() {
    return categoryCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column SHOP_CATEGORYS.CATEGORY_CODE
   * 
   * @param categoryCode the value for SHOP_CATEGORYS.CATEGORY_CODE
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public void setCategoryCode(String categoryCode) {
    this.categoryCode = categoryCode;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column SHOP_CATEGORYS.CATEGORY_NAME
   * 
   * @return the value of SHOP_CATEGORYS.CATEGORY_NAME
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public String getCategoryName() {
    return categoryName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column SHOP_CATEGORYS.CATEGORY_NAME
   * 
   * @param categoryName the value for SHOP_CATEGORYS.CATEGORY_NAME
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column SHOP_CATEGORYS.CATEGORY_LEVEL
   * 
   * @return the value of SHOP_CATEGORYS.CATEGORY_LEVEL
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public Integer getCategoryLevel() {
    return categoryLevel;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column SHOP_CATEGORYS.CATEGORY_LEVEL
   * 
   * @param categoryLevel the value for SHOP_CATEGORYS.CATEGORY_LEVEL
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public void setCategoryLevel(Integer categoryLevel) {
    this.categoryLevel = categoryLevel;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column SHOP_CATEGORYS.STATUS
   * 
   * @return the value of SHOP_CATEGORYS.STATUS
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public Integer getStatus() {
    return status;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column SHOP_CATEGORYS.STATUS
   * 
   * @param status the value for SHOP_CATEGORYS.STATUS
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column SHOP_CATEGORYS.SORTNO
   * 
   * @return the value of SHOP_CATEGORYS.SORTNO
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public Integer getSortno() {
    return sortno;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column SHOP_CATEGORYS.SORTNO
   * 
   * @param sortno the value for SHOP_CATEGORYS.SORTNO
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public void setSortno(Integer sortno) {
    this.sortno = sortno;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column SHOP_CATEGORYS.CREATE_TIME
   * 
   * @return the value of SHOP_CATEGORYS.CREATE_TIME
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column SHOP_CATEGORYS.CREATE_TIME
   * 
   * @param createTime the value for SHOP_CATEGORYS.CREATE_TIME
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column SHOP_CATEGORYS.MODIF_TIME
   * 
   * @return the value of SHOP_CATEGORYS.MODIF_TIME
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public Date getModifTime() {
    return modifTime;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column SHOP_CATEGORYS.MODIF_TIME
   * 
   * @param modifTime the value for SHOP_CATEGORYS.MODIF_TIME
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public void setModifTime(Date modifTime) {
    this.modifTime = modifTime;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column SHOP_CATEGORYS.MODIF_USER
   * 
   * @return the value of SHOP_CATEGORYS.MODIF_USER
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public Long getModifUser() {
    return modifUser;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column SHOP_CATEGORYS.MODIF_USER
   * 
   * @param modifUser the value for SHOP_CATEGORYS.MODIF_USER
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public void setModifUser(Long modifUser) {
    this.modifUser = modifUser;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method returns the value of the
   * database column SHOP_CATEGORYS.EXEC_SQL
   * 
   * @return the value of SHOP_CATEGORYS.EXEC_SQL
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public String getExecSql() {
    return execSql;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method sets the value of the database
   * column SHOP_CATEGORYS.EXEC_SQL
   * 
   * @param execSql the value for SHOP_CATEGORYS.EXEC_SQL
   * 
   * @ibatorgenerated Thu Nov 27 09:57:58 CST 2014
   */
  public void setExecSql(String execSql) {
    this.execSql = execSql;
  }

  public String getRemark() {
    return remark;
  }

  public void setRemark(String remark) {
    this.remark = remark;
  }

  public Long getParentCategoryId() {
    return parentCategoryId;
  }

  public void setParentCategoryId(Long parentCategoryId) {
    this.parentCategoryId = parentCategoryId;
  }

  public String getSupplierId() {
    return supplierId;
  }

  public void setSupplierId(String supplierId) {
    this.supplierId = supplierId;
  }

  public List<ShopCategorys> getShopCategoryChildrenList() {
    return shopCategoryChildrenList;
  }

  public void setShopCategoryChildrenList(List<ShopCategorys> shopCategoryChildrenList) {
    this.shopCategoryChildrenList = shopCategoryChildrenList;
  }

  public Integer getIsSuggest() {
    return isSuggest;
  }

  public void setIsSuggest(Integer isSuggest) {
    this.isSuggest = isSuggest;
  }

  public String getIsExpandAll() {
    return isExpandAll;
  }

  public void setIsExpandAll(String isExpandAll) {
    this.isExpandAll = isExpandAll;
  }

  public String getIsDefault() {
    return isDefault;
  }

  public void setIsDefault(String isDefault) {
    this.isDefault = isDefault;
  }
}
