package com.pltfm.app.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

@SuppressWarnings("unchecked")
public class OrderOperateStatementExample implements Serializable {
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database table
   * KMORDER.ORDER_OPERATE_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  protected String orderByClause;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database table
   * KMORDER.ORDER_OPERATE_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  protected List oredCriteria;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OPERATE_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public OrderOperateStatementExample() {
    oredCriteria = new ArrayList();
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OPERATE_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  protected OrderOperateStatementExample(OrderOperateStatementExample example) {
    this.orderByClause = example.orderByClause;
    this.oredCriteria = example.oredCriteria;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OPERATE_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OPERATE_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OPERATE_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public List getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OPERATE_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OPERATE_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OPERATE_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OPERATE_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public void clear() {
    oredCriteria.clear();
  }

  /**
   * This class was generated by Apache iBATIS ibator. This class corresponds to the database table
   * KMORDER.ORDER_OPERATE_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public static class Criteria {
    protected List criteriaWithoutValue;

    protected List criteriaWithSingleValue;

    protected List criteriaWithListValue;

    protected List criteriaWithBetweenValue;

    protected Criteria() {
      super();
      criteriaWithoutValue = new ArrayList();
      criteriaWithSingleValue = new ArrayList();
      criteriaWithListValue = new ArrayList();
      criteriaWithBetweenValue = new ArrayList();
    }

    public boolean isValid() {
      return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
          || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
    }

    public List getCriteriaWithoutValue() {
      return criteriaWithoutValue;
    }

    public List getCriteriaWithSingleValue() {
      return criteriaWithSingleValue;
    }

    public List getCriteriaWithListValue() {
      return criteriaWithListValue;
    }

    public List getCriteriaWithBetweenValue() {
      return criteriaWithBetweenValue;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteriaWithoutValue.add(condition);
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("value", value);
      criteriaWithSingleValue.add(map);
    }

    protected void addCriterion(String condition, List values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", values);
      criteriaWithListValue.add(map);
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      List list = new ArrayList();
      list.add(value1);
      list.add(value2);
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", list);
      criteriaWithBetweenValue.add(map);
    }

    protected void addCriterionForJDBCDate(String condition, Date value, String property) {
      addCriterion(condition, new java.sql.Date(value.getTime()), property);
    }

    protected void addCriterionForJDBCDate(String condition, List values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      List dateList = new ArrayList();
      Iterator iter = values.iterator();
      while (iter.hasNext()) {
        dateList.add(new java.sql.Date(((Date) iter.next()).getTime()));
      }
      addCriterion(condition, dateList, property);
    }

    protected void addCriterionForJDBCDate(String condition, Date value1, Date value2,
        String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2
          .getTime()), property);
    }

    public Criteria andStatementIdIsNull() {
      addCriterion("STATEMENT_ID is null");
      return this;
    }

    public Criteria andStatementIdIsNotNull() {
      addCriterion("STATEMENT_ID is not null");
      return this;
    }

    public Criteria andStatementIdEqualTo(Long value) {
      addCriterion("STATEMENT_ID =", value, "statementId");
      return this;
    }

    public Criteria andStatementIdNotEqualTo(Long value) {
      addCriterion("STATEMENT_ID <>", value, "statementId");
      return this;
    }

    public Criteria andStatementIdGreaterThan(Long value) {
      addCriterion("STATEMENT_ID >", value, "statementId");
      return this;
    }

    public Criteria andStatementIdGreaterThanOrEqualTo(Long value) {
      addCriterion("STATEMENT_ID >=", value, "statementId");
      return this;
    }

    public Criteria andStatementIdLessThan(Long value) {
      addCriterion("STATEMENT_ID <", value, "statementId");
      return this;
    }

    public Criteria andStatementIdLessThanOrEqualTo(Long value) {
      addCriterion("STATEMENT_ID <=", value, "statementId");
      return this;
    }

    public Criteria andStatementIdIn(List values) {
      addCriterion("STATEMENT_ID in", values, "statementId");
      return this;
    }

    public Criteria andStatementIdNotIn(List values) {
      addCriterion("STATEMENT_ID not in", values, "statementId");
      return this;
    }

    public Criteria andStatementIdBetween(Long value1, Long value2) {
      addCriterion("STATEMENT_ID between", value1, value2, "statementId");
      return this;
    }

    public Criteria andStatementIdNotBetween(Long value1, Long value2) {
      addCriterion("STATEMENT_ID not between", value1, value2, "statementId");
      return this;
    }

    public Criteria andOrderCodeIsNull() {
      addCriterion("ORDER_CODE is null");
      return this;
    }

    public Criteria andOrderCodeIsNotNull() {
      addCriterion("ORDER_CODE is not null");
      return this;
    }

    public Criteria andOrderCodeEqualTo(String value) {
      addCriterion("ORDER_CODE =", value, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeNotEqualTo(String value) {
      addCriterion("ORDER_CODE <>", value, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeGreaterThan(String value) {
      addCriterion("ORDER_CODE >", value, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeGreaterThanOrEqualTo(String value) {
      addCriterion("ORDER_CODE >=", value, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeLessThan(String value) {
      addCriterion("ORDER_CODE <", value, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeLessThanOrEqualTo(String value) {
      addCriterion("ORDER_CODE <=", value, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeIn(List values) {
      addCriterion("ORDER_CODE in", values, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeNotIn(List values) {
      addCriterion("ORDER_CODE not in", values, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeBetween(String value1, String value2) {
      addCriterion("ORDER_CODE between", value1, value2, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeNotBetween(String value1, String value2) {
      addCriterion("ORDER_CODE not between", value1, value2, "OrderCode");
      return this;
    }

    public Criteria andOrderItemIdIsNull() {
      addCriterion("ORDER_ITEM_ID is null");
      return this;
    }

    public Criteria andOrderItemIdIsNotNull() {
      addCriterion("ORDER_ITEM_ID is not null");
      return this;
    }

    public Criteria andOrderItemIdEqualTo(Long value) {
      addCriterion("ORDER_ITEM_ID =", value, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdNotEqualTo(Long value) {
      addCriterion("ORDER_ITEM_ID <>", value, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdGreaterThan(Long value) {
      addCriterion("ORDER_ITEM_ID >", value, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdGreaterThanOrEqualTo(Long value) {
      addCriterion("ORDER_ITEM_ID >=", value, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdLessThan(Long value) {
      addCriterion("ORDER_ITEM_ID <", value, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdLessThanOrEqualTo(Long value) {
      addCriterion("ORDER_ITEM_ID <=", value, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdIn(List values) {
      addCriterion("ORDER_ITEM_ID in", values, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdNotIn(List values) {
      addCriterion("ORDER_ITEM_ID not in", values, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdBetween(Long value1, Long value2) {
      addCriterion("ORDER_ITEM_ID between", value1, value2, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdNotBetween(Long value1, Long value2) {
      addCriterion("ORDER_ITEM_ID not between", value1, value2, "orderItemId");
      return this;
    }

    public Criteria andPreviousOrderStatusIsNull() {
      addCriterion("PREVIOUS_ORDER_STATUS is null");
      return this;
    }

    public Criteria andPreviousOrderStatusIsNotNull() {
      addCriterion("PREVIOUS_ORDER_STATUS is not null");
      return this;
    }

    public Criteria andPreviousOrderStatusEqualTo(Long value) {
      addCriterion("PREVIOUS_ORDER_STATUS =", value, "previousOrderStatus");
      return this;
    }

    public Criteria andPreviousOrderStatusNotEqualTo(Long value) {
      addCriterion("PREVIOUS_ORDER_STATUS <>", value, "previousOrderStatus");
      return this;
    }

    public Criteria andPreviousOrderStatusGreaterThan(Long value) {
      addCriterion("PREVIOUS_ORDER_STATUS >", value, "previousOrderStatus");
      return this;
    }

    public Criteria andPreviousOrderStatusGreaterThanOrEqualTo(Long value) {
      addCriterion("PREVIOUS_ORDER_STATUS >=", value, "previousOrderStatus");
      return this;
    }

    public Criteria andPreviousOrderStatusLessThan(Long value) {
      addCriterion("PREVIOUS_ORDER_STATUS <", value, "previousOrderStatus");
      return this;
    }

    public Criteria andPreviousOrderStatusLessThanOrEqualTo(Long value) {
      addCriterion("PREVIOUS_ORDER_STATUS <=", value, "previousOrderStatus");
      return this;
    }

    public Criteria andPreviousOrderStatusIn(List values) {
      addCriterion("PREVIOUS_ORDER_STATUS in", values, "previousOrderStatus");
      return this;
    }

    public Criteria andPreviousOrderStatusNotIn(List values) {
      addCriterion("PREVIOUS_ORDER_STATUS not in", values, "previousOrderStatus");
      return this;
    }

    public Criteria andPreviousOrderStatusBetween(Long value1, Long value2) {
      addCriterion("PREVIOUS_ORDER_STATUS between", value1, value2, "previousOrderStatus");
      return this;
    }

    public Criteria andPreviousOrderStatusNotBetween(Long value1, Long value2) {
      addCriterion("PREVIOUS_ORDER_STATUS not between", value1, value2, "previousOrderStatus");
      return this;
    }

    public Criteria andNowOrderStatusIsNull() {
      addCriterion("NOW_ORDER_STATUS is null");
      return this;
    }

    public Criteria andNowOrderStatusIsNotNull() {
      addCriterion("NOW_ORDER_STATUS is not null");
      return this;
    }

    public Criteria andNowOrderStatusEqualTo(Long value) {
      addCriterion("NOW_ORDER_STATUS =", value, "nowOrderStatus");
      return this;
    }

    public Criteria andNowOrderStatusNotEqualTo(Long value) {
      addCriterion("NOW_ORDER_STATUS <>", value, "nowOrderStatus");
      return this;
    }

    public Criteria andNowOrderStatusGreaterThan(Long value) {
      addCriterion("NOW_ORDER_STATUS >", value, "nowOrderStatus");
      return this;
    }

    public Criteria andNowOrderStatusGreaterThanOrEqualTo(Long value) {
      addCriterion("NOW_ORDER_STATUS >=", value, "nowOrderStatus");
      return this;
    }

    public Criteria andNowOrderStatusLessThan(Long value) {
      addCriterion("NOW_ORDER_STATUS <", value, "nowOrderStatus");
      return this;
    }

    public Criteria andNowOrderStatusLessThanOrEqualTo(Long value) {
      addCriterion("NOW_ORDER_STATUS <=", value, "nowOrderStatus");
      return this;
    }

    public Criteria andNowOrderStatusIn(List values) {
      addCriterion("NOW_ORDER_STATUS in", values, "nowOrderStatus");
      return this;
    }

    public Criteria andNowOrderStatusNotIn(List values) {
      addCriterion("NOW_ORDER_STATUS not in", values, "nowOrderStatus");
      return this;
    }

    public Criteria andNowOrderStatusBetween(Long value1, Long value2) {
      addCriterion("NOW_ORDER_STATUS between", value1, value2, "nowOrderStatus");
      return this;
    }

    public Criteria andNowOrderStatusNotBetween(Long value1, Long value2) {
      addCriterion("NOW_ORDER_STATUS not between", value1, value2, "nowOrderStatus");
      return this;
    }

    public Criteria andPreviousOperatorIsNull() {
      addCriterion("PREVIOUS_OPERATOR is null");
      return this;
    }

    public Criteria andPreviousOperatorIsNotNull() {
      addCriterion("PREVIOUS_OPERATOR is not null");
      return this;
    }

    public Criteria andPreviousOperatorEqualTo(String value) {
      addCriterion("PREVIOUS_OPERATOR =", value, "previousOperator");
      return this;
    }

    public Criteria andPreviousOperatorNotEqualTo(String value) {
      addCriterion("PREVIOUS_OPERATOR <>", value, "previousOperator");
      return this;
    }

    public Criteria andPreviousOperatorGreaterThan(String value) {
      addCriterion("PREVIOUS_OPERATOR >", value, "previousOperator");
      return this;
    }

    public Criteria andPreviousOperatorGreaterThanOrEqualTo(String value) {
      addCriterion("PREVIOUS_OPERATOR >=", value, "previousOperator");
      return this;
    }

    public Criteria andPreviousOperatorLessThan(String value) {
      addCriterion("PREVIOUS_OPERATOR <", value, "previousOperator");
      return this;
    }

    public Criteria andPreviousOperatorLessThanOrEqualTo(String value) {
      addCriterion("PREVIOUS_OPERATOR <=", value, "previousOperator");
      return this;
    }

    public Criteria andPreviousOperatorLike(String value) {
      addCriterion("PREVIOUS_OPERATOR like", value, "previousOperator");
      return this;
    }

    public Criteria andPreviousOperatorNotLike(String value) {
      addCriterion("PREVIOUS_OPERATOR not like", value, "previousOperator");
      return this;
    }

    public Criteria andPreviousOperatorIn(List values) {
      addCriterion("PREVIOUS_OPERATOR in", values, "previousOperator");
      return this;
    }

    public Criteria andPreviousOperatorNotIn(List values) {
      addCriterion("PREVIOUS_OPERATOR not in", values, "previousOperator");
      return this;
    }

    public Criteria andPreviousOperatorBetween(String value1, String value2) {
      addCriterion("PREVIOUS_OPERATOR between", value1, value2, "previousOperator");
      return this;
    }

    public Criteria andPreviousOperatorNotBetween(String value1, String value2) {
      addCriterion("PREVIOUS_OPERATOR not between", value1, value2, "previousOperator");
      return this;
    }

    public Criteria andNowOperatorIsNull() {
      addCriterion("NOW_OPERATOR is null");
      return this;
    }

    public Criteria andNowOperatorIsNotNull() {
      addCriterion("NOW_OPERATOR is not null");
      return this;
    }

    public Criteria andNowOperatorEqualTo(String value) {
      addCriterion("NOW_OPERATOR =", value, "nowOperator");
      return this;
    }

    public Criteria andNowOperatorNotEqualTo(String value) {
      addCriterion("NOW_OPERATOR <>", value, "nowOperator");
      return this;
    }

    public Criteria andNowOperatorGreaterThan(String value) {
      addCriterion("NOW_OPERATOR >", value, "nowOperator");
      return this;
    }

    public Criteria andNowOperatorGreaterThanOrEqualTo(String value) {
      addCriterion("NOW_OPERATOR >=", value, "nowOperator");
      return this;
    }

    public Criteria andNowOperatorLessThan(String value) {
      addCriterion("NOW_OPERATOR <", value, "nowOperator");
      return this;
    }

    public Criteria andNowOperatorLessThanOrEqualTo(String value) {
      addCriterion("NOW_OPERATOR <=", value, "nowOperator");
      return this;
    }

    public Criteria andNowOperatorLike(String value) {
      addCriterion("NOW_OPERATOR like", value, "nowOperator");
      return this;
    }

    public Criteria andNowOperatorNotLike(String value) {
      addCriterion("NOW_OPERATOR not like", value, "nowOperator");
      return this;
    }

    public Criteria andNowOperatorIn(List values) {
      addCriterion("NOW_OPERATOR in", values, "nowOperator");
      return this;
    }

    public Criteria andNowOperatorNotIn(List values) {
      addCriterion("NOW_OPERATOR not in", values, "nowOperator");
      return this;
    }

    public Criteria andNowOperatorBetween(String value1, String value2) {
      addCriterion("NOW_OPERATOR between", value1, value2, "nowOperator");
      return this;
    }

    public Criteria andNowOperatorNotBetween(String value1, String value2) {
      addCriterion("NOW_OPERATOR not between", value1, value2, "nowOperator");
      return this;
    }

    public Criteria andPreviousOperateDateIsNull() {
      addCriterion("PREVIOUS_OPERATE_DATE is null");
      return this;
    }

    public Criteria andPreviousOperateDateIsNotNull() {
      addCriterion("PREVIOUS_OPERATE_DATE is not null");
      return this;
    }

    public Criteria andPreviousOperateDateEqualTo(Date value) {
      addCriterionForJDBCDate("PREVIOUS_OPERATE_DATE =", value, "previousOperateDate");
      return this;
    }

    public Criteria andPreviousOperateDateNotEqualTo(Date value) {
      addCriterionForJDBCDate("PREVIOUS_OPERATE_DATE <>", value, "previousOperateDate");
      return this;
    }

    public Criteria andPreviousOperateDateGreaterThan(Date value) {
      addCriterionForJDBCDate("PREVIOUS_OPERATE_DATE >", value, "previousOperateDate");
      return this;
    }

    public Criteria andPreviousOperateDateGreaterThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("PREVIOUS_OPERATE_DATE >=", value, "previousOperateDate");
      return this;
    }

    public Criteria andPreviousOperateDateLessThan(Date value) {
      addCriterionForJDBCDate("PREVIOUS_OPERATE_DATE <", value, "previousOperateDate");
      return this;
    }

    public Criteria andPreviousOperateDateLessThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("PREVIOUS_OPERATE_DATE <=", value, "previousOperateDate");
      return this;
    }

    public Criteria andPreviousOperateDateIn(List values) {
      addCriterionForJDBCDate("PREVIOUS_OPERATE_DATE in", values, "previousOperateDate");
      return this;
    }

    public Criteria andPreviousOperateDateNotIn(List values) {
      addCriterionForJDBCDate("PREVIOUS_OPERATE_DATE not in", values, "previousOperateDate");
      return this;
    }

    public Criteria andPreviousOperateDateBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("PREVIOUS_OPERATE_DATE between", value1, value2,
          "previousOperateDate");
      return this;
    }

    public Criteria andPreviousOperateDateNotBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("PREVIOUS_OPERATE_DATE not between", value1, value2,
          "previousOperateDate");
      return this;
    }

    public Criteria andNowOperateDateIsNull() {
      addCriterion("NOW_OPERATE_DATE is null");
      return this;
    }

    public Criteria andNowOperateDateIsNotNull() {
      addCriterion("NOW_OPERATE_DATE is not null");
      return this;
    }

    public Criteria andNowOperateDateEqualTo(Date value) {
      addCriterionForJDBCDate("NOW_OPERATE_DATE =", value, "nowOperateDate");
      return this;
    }

    public Criteria andNowOperateDateNotEqualTo(Date value) {
      addCriterionForJDBCDate("NOW_OPERATE_DATE <>", value, "nowOperateDate");
      return this;
    }

    public Criteria andNowOperateDateGreaterThan(Date value) {
      addCriterionForJDBCDate("NOW_OPERATE_DATE >", value, "nowOperateDate");
      return this;
    }

    public Criteria andNowOperateDateGreaterThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("NOW_OPERATE_DATE >=", value, "nowOperateDate");
      return this;
    }

    public Criteria andNowOperateDateLessThan(Date value) {
      addCriterionForJDBCDate("NOW_OPERATE_DATE <", value, "nowOperateDate");
      return this;
    }

    public Criteria andNowOperateDateLessThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("NOW_OPERATE_DATE <=", value, "nowOperateDate");
      return this;
    }

    public Criteria andNowOperateDateIn(List values) {
      addCriterionForJDBCDate("NOW_OPERATE_DATE in", values, "nowOperateDate");
      return this;
    }

    public Criteria andNowOperateDateNotIn(List values) {
      addCriterionForJDBCDate("NOW_OPERATE_DATE not in", values, "nowOperateDate");
      return this;
    }

    public Criteria andNowOperateDateBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("NOW_OPERATE_DATE between", value1, value2, "nowOperateDate");
      return this;
    }

    public Criteria andNowOperateDateNotBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("NOW_OPERATE_DATE not between", value1, value2, "nowOperateDate");
      return this;
    }

    public Criteria andPreviousOperateTypeIsNull() {
      addCriterion("PREVIOUS_OPERATE_TYPE is null");
      return this;
    }

    public Criteria andPreviousOperateTypeIsNotNull() {
      addCriterion("PREVIOUS_OPERATE_TYPE is not null");
      return this;
    }

    public Criteria andPreviousOperateTypeEqualTo(Long value) {
      addCriterion("PREVIOUS_OPERATE_TYPE =", value, "previousOperateType");
      return this;
    }

    public Criteria andPreviousOperateTypeNotEqualTo(Long value) {
      addCriterion("PREVIOUS_OPERATE_TYPE <>", value, "previousOperateType");
      return this;
    }

    public Criteria andPreviousOperateTypeGreaterThan(Long value) {
      addCriterion("PREVIOUS_OPERATE_TYPE >", value, "previousOperateType");
      return this;
    }

    public Criteria andPreviousOperateTypeGreaterThanOrEqualTo(Long value) {
      addCriterion("PREVIOUS_OPERATE_TYPE >=", value, "previousOperateType");
      return this;
    }

    public Criteria andPreviousOperateTypeLessThan(Long value) {
      addCriterion("PREVIOUS_OPERATE_TYPE <", value, "previousOperateType");
      return this;
    }

    public Criteria andPreviousOperateTypeLessThanOrEqualTo(Long value) {
      addCriterion("PREVIOUS_OPERATE_TYPE <=", value, "previousOperateType");
      return this;
    }

    public Criteria andPreviousOperateTypeIn(List values) {
      addCriterion("PREVIOUS_OPERATE_TYPE in", values, "previousOperateType");
      return this;
    }

    public Criteria andPreviousOperateTypeNotIn(List values) {
      addCriterion("PREVIOUS_OPERATE_TYPE not in", values, "previousOperateType");
      return this;
    }

    public Criteria andPreviousOperateTypeBetween(Long value1, Long value2) {
      addCriterion("PREVIOUS_OPERATE_TYPE between", value1, value2, "previousOperateType");
      return this;
    }

    public Criteria andPreviousOperateTypeNotBetween(Long value1, Long value2) {
      addCriterion("PREVIOUS_OPERATE_TYPE not between", value1, value2, "previousOperateType");
      return this;
    }

    public Criteria andNowOperateTypeIsNull() {
      addCriterion("NOW_OPERATE_TYPE is null");
      return this;
    }

    public Criteria andNowOperateTypeIsNotNull() {
      addCriterion("NOW_OPERATE_TYPE is not null");
      return this;
    }

    public Criteria andNowOperateTypeEqualTo(Long value) {
      addCriterion("NOW_OPERATE_TYPE =", value, "nowOperateType");
      return this;
    }

    public Criteria andNowOperateTypeNotEqualTo(Long value) {
      addCriterion("NOW_OPERATE_TYPE <>", value, "nowOperateType");
      return this;
    }

    public Criteria andNowOperateTypeGreaterThan(Long value) {
      addCriterion("NOW_OPERATE_TYPE >", value, "nowOperateType");
      return this;
    }

    public Criteria andNowOperateTypeGreaterThanOrEqualTo(Long value) {
      addCriterion("NOW_OPERATE_TYPE >=", value, "nowOperateType");
      return this;
    }

    public Criteria andNowOperateTypeLessThan(Long value) {
      addCriterion("NOW_OPERATE_TYPE <", value, "nowOperateType");
      return this;
    }

    public Criteria andNowOperateTypeLessThanOrEqualTo(Long value) {
      addCriterion("NOW_OPERATE_TYPE <=", value, "nowOperateType");
      return this;
    }

    public Criteria andNowOperateTypeIn(List values) {
      addCriterion("NOW_OPERATE_TYPE in", values, "nowOperateType");
      return this;
    }

    public Criteria andNowOperateTypeNotIn(List values) {
      addCriterion("NOW_OPERATE_TYPE not in", values, "nowOperateType");
      return this;
    }

    public Criteria andNowOperateTypeBetween(Long value1, Long value2) {
      addCriterion("NOW_OPERATE_TYPE between", value1, value2, "nowOperateType");
      return this;
    }

    public Criteria andNowOperateTypeNotBetween(Long value1, Long value2) {
      addCriterion("NOW_OPERATE_TYPE not between", value1, value2, "nowOperateType");
      return this;
    }

    public Criteria andPreviousOrderSumIsNull() {
      addCriterion("PREVIOUS_ORDER_SUM is null");
      return this;
    }

    public Criteria andPreviousOrderSumIsNotNull() {
      addCriterion("PREVIOUS_ORDER_SUM is not null");
      return this;
    }

    public Criteria andPreviousOrderSumEqualTo(BigDecimal value) {
      addCriterion("PREVIOUS_ORDER_SUM =", value, "previousOrderSum");
      return this;
    }

    public Criteria andPreviousOrderSumNotEqualTo(BigDecimal value) {
      addCriterion("PREVIOUS_ORDER_SUM <>", value, "previousOrderSum");
      return this;
    }

    public Criteria andPreviousOrderSumGreaterThan(BigDecimal value) {
      addCriterion("PREVIOUS_ORDER_SUM >", value, "previousOrderSum");
      return this;
    }

    public Criteria andPreviousOrderSumGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("PREVIOUS_ORDER_SUM >=", value, "previousOrderSum");
      return this;
    }

    public Criteria andPreviousOrderSumLessThan(BigDecimal value) {
      addCriterion("PREVIOUS_ORDER_SUM <", value, "previousOrderSum");
      return this;
    }

    public Criteria andPreviousOrderSumLessThanOrEqualTo(BigDecimal value) {
      addCriterion("PREVIOUS_ORDER_SUM <=", value, "previousOrderSum");
      return this;
    }

    public Criteria andPreviousOrderSumIn(List values) {
      addCriterion("PREVIOUS_ORDER_SUM in", values, "previousOrderSum");
      return this;
    }

    public Criteria andPreviousOrderSumNotIn(List values) {
      addCriterion("PREVIOUS_ORDER_SUM not in", values, "previousOrderSum");
      return this;
    }

    public Criteria andPreviousOrderSumBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PREVIOUS_ORDER_SUM between", value1, value2, "previousOrderSum");
      return this;
    }

    public Criteria andPreviousOrderSumNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PREVIOUS_ORDER_SUM not between", value1, value2, "previousOrderSum");
      return this;
    }

    public Criteria andNowOrderSumIsNull() {
      addCriterion("NOW_ORDER_SUM is null");
      return this;
    }

    public Criteria andNowOrderSumIsNotNull() {
      addCriterion("NOW_ORDER_SUM is not null");
      return this;
    }

    public Criteria andNowOrderSumEqualTo(BigDecimal value) {
      addCriterion("NOW_ORDER_SUM =", value, "nowOrderSum");
      return this;
    }

    public Criteria andNowOrderSumNotEqualTo(BigDecimal value) {
      addCriterion("NOW_ORDER_SUM <>", value, "nowOrderSum");
      return this;
    }

    public Criteria andNowOrderSumGreaterThan(BigDecimal value) {
      addCriterion("NOW_ORDER_SUM >", value, "nowOrderSum");
      return this;
    }

    public Criteria andNowOrderSumGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("NOW_ORDER_SUM >=", value, "nowOrderSum");
      return this;
    }

    public Criteria andNowOrderSumLessThan(BigDecimal value) {
      addCriterion("NOW_ORDER_SUM <", value, "nowOrderSum");
      return this;
    }

    public Criteria andNowOrderSumLessThanOrEqualTo(BigDecimal value) {
      addCriterion("NOW_ORDER_SUM <=", value, "nowOrderSum");
      return this;
    }

    public Criteria andNowOrderSumIn(List values) {
      addCriterion("NOW_ORDER_SUM in", values, "nowOrderSum");
      return this;
    }

    public Criteria andNowOrderSumNotIn(List values) {
      addCriterion("NOW_ORDER_SUM not in", values, "nowOrderSum");
      return this;
    }

    public Criteria andNowOrderSumBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("NOW_ORDER_SUM between", value1, value2, "nowOrderSum");
      return this;
    }

    public Criteria andNowOrderSumNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("NOW_ORDER_SUM not between", value1, value2, "nowOrderSum");
      return this;
    }

    public Criteria andOperateInfoIsNull() {
      addCriterion("OPERATE_INFO is null");
      return this;
    }

    public Criteria andOperateInfoIsNotNull() {
      addCriterion("OPERATE_INFO is not null");
      return this;
    }

    public Criteria andOperateInfoEqualTo(String value) {
      addCriterion("OPERATE_INFO =", value, "operateInfo");
      return this;
    }

    public Criteria andOperateInfoNotEqualTo(String value) {
      addCriterion("OPERATE_INFO <>", value, "operateInfo");
      return this;
    }

    public Criteria andOperateInfoGreaterThan(String value) {
      addCriterion("OPERATE_INFO >", value, "operateInfo");
      return this;
    }

    public Criteria andOperateInfoGreaterThanOrEqualTo(String value) {
      addCriterion("OPERATE_INFO >=", value, "operateInfo");
      return this;
    }

    public Criteria andOperateInfoLessThan(String value) {
      addCriterion("OPERATE_INFO <", value, "operateInfo");
      return this;
    }

    public Criteria andOperateInfoLessThanOrEqualTo(String value) {
      addCriterion("OPERATE_INFO <=", value, "operateInfo");
      return this;
    }

    public Criteria andOperateInfoLike(String value) {
      addCriterion("OPERATE_INFO like", value, "operateInfo");
      return this;
    }

    public Criteria andOperateInfoNotLike(String value) {
      addCriterion("OPERATE_INFO not like", value, "operateInfo");
      return this;
    }

    public Criteria andOperateInfoIn(List values) {
      addCriterion("OPERATE_INFO in", values, "operateInfo");
      return this;
    }

    public Criteria andOperateInfoNotIn(List values) {
      addCriterion("OPERATE_INFO not in", values, "operateInfo");
      return this;
    }

    public Criteria andOperateInfoBetween(String value1, String value2) {
      addCriterion("OPERATE_INFO between", value1, value2, "operateInfo");
      return this;
    }

    public Criteria andOperateInfoNotBetween(String value1, String value2) {
      addCriterion("OPERATE_INFO not between", value1, value2, "operateInfo");
      return this;
    }
  }
}
