package com.pltfm.app.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

@SuppressWarnings("unchecked")
public class OrderPayStatementExample implements Serializable {
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database table
   * KMORDER.ORDER_PAY_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  protected String orderByClause;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database table
   * KMORDER.ORDER_PAY_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  protected List oredCriteria;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_PAY_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public OrderPayStatementExample() {
    oredCriteria = new ArrayList();
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_PAY_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  protected OrderPayStatementExample(OrderPayStatementExample example) {
    this.orderByClause = example.orderByClause;
    this.oredCriteria = example.oredCriteria;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_PAY_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_PAY_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_PAY_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public List getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_PAY_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_PAY_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_PAY_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_PAY_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public void clear() {
    oredCriteria.clear();
  }

  /**
   * This class was generated by Apache iBATIS ibator. This class corresponds to the database table
   * KMORDER.ORDER_PAY_STATEMENT
   * 
   * @ibatorgenerated Mon Jul 29 11:23:58 CST 2013
   */
  public static class Criteria {
    protected List criteriaWithoutValue;

    protected List criteriaWithSingleValue;

    protected List criteriaWithListValue;

    protected List criteriaWithBetweenValue;

    protected Criteria() {
      super();
      criteriaWithoutValue = new ArrayList();
      criteriaWithSingleValue = new ArrayList();
      criteriaWithListValue = new ArrayList();
      criteriaWithBetweenValue = new ArrayList();
    }

    public boolean isValid() {
      return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
          || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
    }

    public List getCriteriaWithoutValue() {
      return criteriaWithoutValue;
    }

    public List getCriteriaWithSingleValue() {
      return criteriaWithSingleValue;
    }

    public List getCriteriaWithListValue() {
      return criteriaWithListValue;
    }

    public List getCriteriaWithBetweenValue() {
      return criteriaWithBetweenValue;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteriaWithoutValue.add(condition);
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("value", value);
      criteriaWithSingleValue.add(map);
    }

    protected void addCriterion(String condition, List values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", values);
      criteriaWithListValue.add(map);
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      List list = new ArrayList();
      list.add(value1);
      list.add(value2);
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", list);
      criteriaWithBetweenValue.add(map);
    }

    protected void addCriterionForJDBCDate(String condition, Date value, String property) {
      addCriterion(condition, new java.sql.Date(value.getTime()), property);
    }

    protected void addCriterionForJDBCDate(String condition, List values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      List dateList = new ArrayList();
      Iterator iter = values.iterator();
      while (iter.hasNext()) {
        dateList.add(new java.sql.Date(((Date) iter.next()).getTime()));
      }
      addCriterion(condition, dateList, property);
    }

    protected void addCriterionForJDBCDate(String condition, Date value1, Date value2,
        String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2
          .getTime()), property);
    }

    public Criteria andPayStatementNoIsNull() {
      addCriterion("PAY_STATEMENT_NO is null");
      return this;
    }

    public Criteria andPayStatementNoIsNotNull() {
      addCriterion("PAY_STATEMENT_NO is not null");
      return this;
    }

    public Criteria andPayStatementNoEqualTo(Long value) {
      addCriterion("PAY_STATEMENT_NO =", value, "payStatementNo");
      return this;
    }

    public Criteria andPayStatementNoNotEqualTo(Long value) {
      addCriterion("PAY_STATEMENT_NO <>", value, "payStatementNo");
      return this;
    }

    public Criteria andPayStatementNoGreaterThan(Long value) {
      addCriterion("PAY_STATEMENT_NO >", value, "payStatementNo");
      return this;
    }

    public Criteria andPayStatementNoGreaterThanOrEqualTo(Long value) {
      addCriterion("PAY_STATEMENT_NO >=", value, "payStatementNo");
      return this;
    }

    public Criteria andPayStatementNoLessThan(Long value) {
      addCriterion("PAY_STATEMENT_NO <", value, "payStatementNo");
      return this;
    }

    public Criteria andPayStatementNoLessThanOrEqualTo(Long value) {
      addCriterion("PAY_STATEMENT_NO <=", value, "payStatementNo");
      return this;
    }

    public Criteria andPayStatementNoIn(List values) {
      addCriterion("PAY_STATEMENT_NO in", values, "payStatementNo");
      return this;
    }

    public Criteria andPayStatementNoNotIn(List values) {
      addCriterion("PAY_STATEMENT_NO not in", values, "payStatementNo");
      return this;
    }

    public Criteria andPayStatementNoBetween(Long value1, Long value2) {
      addCriterion("PAY_STATEMENT_NO between", value1, value2, "payStatementNo");
      return this;
    }

    public Criteria andPayStatementNoNotBetween(Long value1, Long value2) {
      addCriterion("PAY_STATEMENT_NO not between", value1, value2, "payStatementNo");
      return this;
    }

    public Criteria andPaymentWayIsNull() {
      addCriterion("PAYMENT_WAY is null");
      return this;
    }

    public Criteria andPaymentWayIsNotNull() {
      addCriterion("PAYMENT_WAY is not null");
      return this;
    }

    public Criteria andPaymentWayEqualTo(Long value) {
      addCriterion("PAYMENT_WAY =", value, "paymentWay");
      return this;
    }

    public Criteria andPaymentWayNotEqualTo(Long value) {
      addCriterion("PAYMENT_WAY <>", value, "paymentWay");
      return this;
    }

    public Criteria andPaymentWayGreaterThan(Long value) {
      addCriterion("PAYMENT_WAY >", value, "paymentWay");
      return this;
    }

    public Criteria andPaymentWayGreaterThanOrEqualTo(Long value) {
      addCriterion("PAYMENT_WAY >=", value, "paymentWay");
      return this;
    }

    public Criteria andPaymentWayLessThan(Long value) {
      addCriterion("PAYMENT_WAY <", value, "paymentWay");
      return this;
    }

    public Criteria andPaymentWayLessThanOrEqualTo(Long value) {
      addCriterion("PAYMENT_WAY <=", value, "paymentWay");
      return this;
    }

    public Criteria andPaymentWayIn(List values) {
      addCriterion("PAYMENT_WAY in", values, "paymentWay");
      return this;
    }

    public Criteria andPaymentWayNotIn(List values) {
      addCriterion("PAYMENT_WAY not in", values, "paymentWay");
      return this;
    }

    public Criteria andPaymentWayBetween(Long value1, Long value2) {
      addCriterion("PAYMENT_WAY between", value1, value2, "paymentWay");
      return this;
    }

    public Criteria andPaymentWayNotBetween(Long value1, Long value2) {
      addCriterion("PAYMENT_WAY not between", value1, value2, "paymentWay");
      return this;
    }

    public Criteria andStateIsNull() {
      addCriterion("STATE is null");
      return this;
    }

    public Criteria andStateIsNotNull() {
      addCriterion("STATE is not null");
      return this;
    }

    public Criteria andStateEqualTo(Long value) {
      addCriterion("STATE =", value, "state");
      return this;
    }
    
    public Criteria addYsFlageEqualTo(String value) {
      addCriterion("YSFLAGE =", value, "ysflage");
      return this;
    }

    public Criteria andStateNotEqualTo(Long value) {
      addCriterion("STATE <>", value, "state");
      return this;
    }

    public Criteria andStateGreaterThan(Long value) {
      addCriterion("STATE >", value, "state");
      return this;
    }

    public Criteria andStateGreaterThanOrEqualTo(Long value) {
      addCriterion("STATE >=", value, "state");
      return this;
    }

    public Criteria andStateLessThan(Long value) {
      addCriterion("STATE <", value, "state");
      return this;
    }

    public Criteria andStateLessThanOrEqualTo(Long value) {
      addCriterion("STATE <=", value, "state");
      return this;
    }

    public Criteria andStateIn(List values) {
      addCriterion("STATE in", values, "state");
      return this;
    }

    public Criteria andStateNotIn(List values) {
      addCriterion("STATE not in", values, "state");
      return this;
    }

    public Criteria andStateBetween(Long value1, Long value2) {
      addCriterion("STATE between", value1, value2, "state");
      return this;
    }

    public Criteria andStateNotBetween(Long value1, Long value2) {
      addCriterion("STATE not between", value1, value2, "state");
      return this;
    }

    public Criteria andAccountIsNull() {
      addCriterion("ACCOUNT is null");
      return this;
    }

    public Criteria andAccountIsNotNull() {
      addCriterion("ACCOUNT is not null");
      return this;
    }

    public Criteria andAccountEqualTo(String value) {
      addCriterion("ACCOUNT =", value, "account");
      return this;
    }

    public Criteria andAccountNotEqualTo(String value) {
      addCriterion("ACCOUNT <>", value, "account");
      return this;
    }

    public Criteria andAccountGreaterThan(String value) {
      addCriterion("ACCOUNT >", value, "account");
      return this;
    }

    public Criteria andAccountGreaterThanOrEqualTo(String value) {
      addCriterion("ACCOUNT >=", value, "account");
      return this;
    }

    public Criteria andAccountLessThan(String value) {
      addCriterion("ACCOUNT <", value, "account");
      return this;
    }

    public Criteria andAccountLessThanOrEqualTo(String value) {
      addCriterion("ACCOUNT <=", value, "account");
      return this;
    }

    public Criteria andAccountLike(String value) {
      addCriterion("ACCOUNT like", value, "account");
      return this;
    }

    public Criteria andAccountNotLike(String value) {
      addCriterion("ACCOUNT not like", value, "account");
      return this;
    }

    public Criteria andAccountIn(List values) {
      addCriterion("ACCOUNT in", values, "account");
      return this;
    }

    public Criteria andAccountNotIn(List values) {
      addCriterion("ACCOUNT not in", values, "account");
      return this;
    }

    public Criteria andAccountBetween(String value1, String value2) {
      addCriterion("ACCOUNT between", value1, value2, "account");
      return this;
    }

    public Criteria andAccountNotBetween(String value1, String value2) {
      addCriterion("ACCOUNT not between", value1, value2, "account");
      return this;
    }

    public Criteria andOrderIdIsNull() {
      addCriterion("ORDER_ID is null");
      return this;
    }

    public Criteria andOrderIdIsNotNull() {
      addCriterion("ORDER_ID is not null");
      return this;
    }

    public Criteria andOrderIdEqualTo(String value) {
      addCriterion("ORDER_ID =", value, "orderId");
      return this;
    }

    public Criteria andOrderIdNotEqualTo(String value) {
      addCriterion("ORDER_ID <>", value, "orderId");
      return this;
    }

    public Criteria andOrderIdGreaterThan(String value) {
      addCriterion("ORDER_ID >", value, "orderId");
      return this;
    }

    public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
      addCriterion("ORDER_ID >=", value, "orderId");
      return this;
    }

    public Criteria andOrderIdLessThan(String value) {
      addCriterion("ORDER_ID <", value, "orderId");
      return this;
    }

    public Criteria andOrderIdLessThanOrEqualTo(String value) {
      addCriterion("ORDER_ID <=", value, "orderId");
      return this;
    }

    public Criteria andOrderIdLike(String value) {
      addCriterion("ORDER_ID like", value, "orderId");
      return this;
    }

    public Criteria andOrderIdNotLike(String value) {
      addCriterion("ORDER_ID not like", value, "orderId");
      return this;
    }

    public Criteria andOrderIdIn(List values) {
      addCriterion("ORDER_ID in", values, "orderId");
      return this;
    }

    public Criteria andOrderIdNotIn(List values) {
      addCriterion("ORDER_ID not in", values, "orderId");
      return this;
    }

    public Criteria andOrderIdBetween(String value1, String value2) {
      addCriterion("ORDER_ID between", value1, value2, "orderId");
      return this;
    }

    public Criteria andOrderIdNotBetween(String value1, String value2) {
      addCriterion("ORDER_ID not between", value1, value2, "orderId");
      return this;
    }

    public Criteria andOrderMoneyIsNull() {
      addCriterion("ORDER_MONEY is null");
      return this;
    }

    public Criteria andOrderMoneyIsNotNull() {
      addCriterion("ORDER_MONEY is not null");
      return this;
    }

    public Criteria andOrderMoneyEqualTo(BigDecimal value) {
      addCriterion("ORDER_MONEY =", value, "orderMoney");
      return this;
    }

    public Criteria andOrderMoneyNotEqualTo(BigDecimal value) {
      addCriterion("ORDER_MONEY <>", value, "orderMoney");
      return this;
    }

    public Criteria andOrderMoneyGreaterThan(BigDecimal value) {
      addCriterion("ORDER_MONEY >", value, "orderMoney");
      return this;
    }

    public Criteria andOrderMoneyGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("ORDER_MONEY >=", value, "orderMoney");
      return this;
    }

    public Criteria andOrderMoneyLessThan(BigDecimal value) {
      addCriterion("ORDER_MONEY <", value, "orderMoney");
      return this;
    }

    public Criteria andOrderMoneyLessThanOrEqualTo(BigDecimal value) {
      addCriterion("ORDER_MONEY <=", value, "orderMoney");
      return this;
    }

    public Criteria andOrderMoneyIn(List values) {
      addCriterion("ORDER_MONEY in", values, "orderMoney");
      return this;
    }

    public Criteria andOrderMoneyNotIn(List values) {
      addCriterion("ORDER_MONEY not in", values, "orderMoney");
      return this;
    }

    public Criteria andOrderMoneyBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("ORDER_MONEY between", value1, value2, "orderMoney");
      return this;
    }

    public Criteria andOrderMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("ORDER_MONEY not between", value1, value2, "orderMoney");
      return this;
    }

    public Criteria andCreateDateIsNull() {
      addCriterion("CREATE_DATE is null");
      return this;
    }

    public Criteria andCreateDateIsNotNull() {
      addCriterion("CREATE_DATE is not null");
      return this;
    }

    public Criteria andCreateDateEqualTo(Date value) {
      addCriterionForJDBCDate("CREATE_DATE =", value, "createDate");
      return this;
    }

    public Criteria andCreateDateNotEqualTo(Date value) {
      addCriterionForJDBCDate("CREATE_DATE <>", value, "createDate");
      return this;
    }

    public Criteria andCreateDateGreaterThan(Date value) {
      addCriterionForJDBCDate("CREATE_DATE >", value, "createDate");
      return this;
    }

    public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("CREATE_DATE >=", value, "createDate");
      return this;
    }

    public Criteria andCreateDateLessThan(Date value) {
      addCriterionForJDBCDate("CREATE_DATE <", value, "createDate");
      return this;
    }

    public Criteria andCreateDateLessThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("CREATE_DATE <=", value, "createDate");
      return this;
    }

    public Criteria andCreateDateIn(List values) {
      addCriterionForJDBCDate("CREATE_DATE in", values, "createDate");
      return this;
    }

    public Criteria andCreateDateNotIn(List values) {
      addCriterionForJDBCDate("CREATE_DATE not in", values, "createDate");
      return this;
    }

    public Criteria andCreateDateBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("CREATE_DATE between", value1, value2, "createDate");
      return this;
    }

    public Criteria andCreateDateNotBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("CREATE_DATE not between", value1, value2, "createDate");
      return this;
    }

    public Criteria andEndDateIsNull() {
      addCriterion("END_DATE is null");
      return this;
    }

    public Criteria andEndDateIsNotNull() {
      addCriterion("END_DATE is not null");
      return this;
    }

    public Criteria andEndDateEqualTo(Date value) {
      addCriterionForJDBCDate("END_DATE =", value, "endDate");
      return this;
    }

    public Criteria andEndDateNotEqualTo(Date value) {
      addCriterionForJDBCDate("END_DATE <>", value, "endDate");
      return this;
    }

    public Criteria andEndDateGreaterThan(Date value) {
      addCriterionForJDBCDate("END_DATE >", value, "endDate");
      return this;
    }

    public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("END_DATE >=", value, "endDate");
      return this;
    }

    public Criteria andEndDateLessThan(Date value) {
      addCriterionForJDBCDate("END_DATE <", value, "endDate");
      return this;
    }

    public Criteria andEndDateLessThanOrEqualTo(Date value) {
      addCriterionForJDBCDate("END_DATE <=", value, "endDate");
      return this;
    }

    public Criteria andEndDateIn(List values) {
      addCriterionForJDBCDate("END_DATE in", values, "endDate");
      return this;
    }

    public Criteria andEndDateNotIn(List values) {
      addCriterionForJDBCDate("END_DATE not in", values, "endDate");
      return this;
    }

    public Criteria andEndDateBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("END_DATE between", value1, value2, "endDate");
      return this;
    }

    public Criteria andEndDateNotBetween(Date value1, Date value2) {
      addCriterionForJDBCDate("END_DATE not between", value1, value2, "endDate");
      return this;
    }

    public Criteria andOutsidePayStatementNoIsNull() {
      addCriterion("OUTSIDE_PAY_STATEMENT_NO is null");
      return this;
    }

    public Criteria andOutsidePayStatementNoIsNotNull() {
      addCriterion("OUTSIDE_PAY_STATEMENT_NO is not null");
      return this;
    }

    public Criteria andOutsidePayStatementNoEqualTo(Long value) {
      addCriterion("OUTSIDE_PAY_STATEMENT_NO =", value, "outsidePayStatementNo");
      return this;
    }

    public Criteria andOutsidePayStatementNoNotEqualTo(Long value) {
      addCriterion("OUTSIDE_PAY_STATEMENT_NO <>", value, "outsidePayStatementNo");
      return this;
    }

    public Criteria andOutsidePayStatementNoGreaterThan(Long value) {
      addCriterion("OUTSIDE_PAY_STATEMENT_NO >", value, "outsidePayStatementNo");
      return this;
    }

    public Criteria andOutsidePayStatementNoGreaterThanOrEqualTo(Long value) {
      addCriterion("OUTSIDE_PAY_STATEMENT_NO >=", value, "outsidePayStatementNo");
      return this;
    }

    public Criteria andOutsidePayStatementNoLessThan(Long value) {
      addCriterion("OUTSIDE_PAY_STATEMENT_NO <", value, "outsidePayStatementNo");
      return this;
    }

    public Criteria andOutsidePayStatementNoLessThanOrEqualTo(Long value) {
      addCriterion("OUTSIDE_PAY_STATEMENT_NO <=", value, "outsidePayStatementNo");
      return this;
    }

    public Criteria andOutsidePayStatementNoIn(List values) {
      addCriterion("OUTSIDE_PAY_STATEMENT_NO in", values, "outsidePayStatementNo");
      return this;
    }

    public Criteria andOutsidePayStatementNoNotIn(List values) {
      addCriterion("OUTSIDE_PAY_STATEMENT_NO not in", values, "outsidePayStatementNo");
      return this;
    }

    public Criteria andOutsidePayStatementNoBetween(Long value1, Long value2) {
      addCriterion("OUTSIDE_PAY_STATEMENT_NO between", value1, value2, "outsidePayStatementNo");
      return this;
    }

    public Criteria andOutsidePayStatementNoNotBetween(Long value1, Long value2) {
      addCriterion("OUTSIDE_PAY_STATEMENT_NO not between", value1, value2, "outsidePayStatementNo");
      return this;
    }

    public Criteria andFlagIsNull() {
      addCriterion("FLAG is null");
      return this;
    }

    public Criteria andFlagIsNotNull() {
      addCriterion("FLAG is not null");
      return this;
    }

    public Criteria andFlagEqualTo(Long value) {
      addCriterion("FLAG =", value, "flag");
      return this;
    }

    public Criteria andFlagNotEqualTo(Long value) {
      addCriterion("FLAG <>", value, "flag");
      return this;
    }

    public Criteria andFlagGreaterThan(Long value) {
      addCriterion("FLAG >", value, "flag");
      return this;
    }

    public Criteria andFlagGreaterThanOrEqualTo(Long value) {
      addCriterion("FLAG >=", value, "flag");
      return this;
    }

    public Criteria andFlagLessThan(Long value) {
      addCriterion("FLAG <", value, "flag");
      return this;
    }

    public Criteria andFlagLessThanOrEqualTo(Long value) {
      addCriterion("FLAG <=", value, "flag");
      return this;
    }

    public Criteria andFlagIn(List values) {
      addCriterion("FLAG in", values, "flag");
      return this;
    }

    public Criteria andFlagNotIn(List values) {
      addCriterion("FLAG not in", values, "flag");
      return this;
    }

    public Criteria andFlagBetween(Long value1, Long value2) {
      addCriterion("FLAG between", value1, value2, "flag");
      return this;
    }

    public Criteria andFlagNotBetween(Long value1, Long value2) {
      addCriterion("FLAG not between", value1, value2, "flag");
      return this;
    }

    public Criteria andPreferentialNoIsNull() {
      addCriterion("PREFERENTIAL_NO is null");
      return this;
    }

    public Criteria andPreferentialNoIsNotNull() {
      addCriterion("PREFERENTIAL_NO is not null");
      return this;
    }

    public Criteria andPreferentialNoEqualTo(BigDecimal value) {
      addCriterion("PREFERENTIAL_NO =", value, "preferentialNo");
      return this;
    }

    public Criteria andPreferentialNoNotEqualTo(BigDecimal value) {
      addCriterion("PREFERENTIAL_NO <>", value, "preferentialNo");
      return this;
    }

    public Criteria andPreferentialNoGreaterThan(BigDecimal value) {
      addCriterion("PREFERENTIAL_NO >", value, "preferentialNo");
      return this;
    }

    public Criteria andPreferentialNoGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("PREFERENTIAL_NO >=", value, "preferentialNo");
      return this;
    }

    public Criteria andPreferentialNoLessThan(BigDecimal value) {
      addCriterion("PREFERENTIAL_NO <", value, "preferentialNo");
      return this;
    }

    public Criteria andPreferentialNoLessThanOrEqualTo(BigDecimal value) {
      addCriterion("PREFERENTIAL_NO <=", value, "preferentialNo");
      return this;
    }

    public Criteria andPreferentialNoIn(List values) {
      addCriterion("PREFERENTIAL_NO in", values, "preferentialNo");
      return this;
    }

    public Criteria andPreferentialNoNotIn(List values) {
      addCriterion("PREFERENTIAL_NO not in", values, "preferentialNo");
      return this;
    }

    public Criteria andPreferentialNoBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PREFERENTIAL_NO between", value1, value2, "preferentialNo");
      return this;
    }

    public Criteria andPreferentialNoNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PREFERENTIAL_NO not between", value1, value2, "preferentialNo");
      return this;
    }

    public Criteria andPreferentialNameIsNull() {
      addCriterion("PREFERENTIAL_NAME is null");
      return this;
    }

    public Criteria andPreferentialNameIsNotNull() {
      addCriterion("PREFERENTIAL_NAME is not null");
      return this;
    }

    public Criteria andPreferentialNameEqualTo(String value) {
      addCriterion("PREFERENTIAL_NAME =", value, "preferentialName");
      return this;
    }

    public Criteria andPreferentialNameNotEqualTo(String value) {
      addCriterion("PREFERENTIAL_NAME <>", value, "preferentialName");
      return this;
    }

    public Criteria andPreferentialNameGreaterThan(String value) {
      addCriterion("PREFERENTIAL_NAME >", value, "preferentialName");
      return this;
    }

    public Criteria andPreferentialNameGreaterThanOrEqualTo(String value) {
      addCriterion("PREFERENTIAL_NAME >=", value, "preferentialName");
      return this;
    }

    public Criteria andPreferentialNameLessThan(String value) {
      addCriterion("PREFERENTIAL_NAME <", value, "preferentialName");
      return this;
    }

    public Criteria andPreferentialNameLessThanOrEqualTo(String value) {
      addCriterion("PREFERENTIAL_NAME <=", value, "preferentialName");
      return this;
    }

    public Criteria andPreferentialNameLike(String value) {
      addCriterion("PREFERENTIAL_NAME like", value, "preferentialName");
      return this;
    }

    public Criteria andPreferentialNameNotLike(String value) {
      addCriterion("PREFERENTIAL_NAME not like", value, "preferentialName");
      return this;
    }

    public Criteria andPreferentialNameIn(List values) {
      addCriterion("PREFERENTIAL_NAME in", values, "preferentialName");
      return this;
    }

    public Criteria andPreferentialNameNottIn(List values) {
      addCriterion("PREFERENTIAL_NAME not in", values, "preferentialName");
      return this;
    }

    public Criteria andPreferentialNameBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PREFERENTIAL_NAME between", value1, value2, "preferentialName");
      return this;
    }

    public Criteria andPreferentialNameNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PREFERENTIAL_NAME not between", value1, value2, "preferentialName");
      return this;
    }

    public Criteria andOrderCodeIsNull() {
      addCriterion("ORDER_CODE is null");
      return this;
    }

    public Criteria andOrderCodeIsNotNull() {
      addCriterion("ORDER_CODE is not null");
      return this;
    }

    public Criteria andOrderCodeEqualTo(String value) {
      addCriterion("ORDER_CODE =", value, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeNotEqualTo(String value) {
      addCriterion("ORDER_CODE <>", value, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeGreaterThan(String value) {
      addCriterion("ORDER_CODE >", value, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeGreaterThanOrEqualTo(String value) {
      addCriterion("ORDER_CODE >=", value, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeLessThan(String value) {
      addCriterion("ORDER_CODE <", value, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeLessThanOrEqualTo(String value) {
      addCriterion("ORDER_CODE <=", value, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeIn(List values) {
      addCriterion("ORDER_CODE in", values, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeNotIn(List values) {
      addCriterion("ORDER_CODE not in", values, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeBetween(String value1, String value2) {
      addCriterion("ORDER_CODE between", value1, value2, "OrderCode");
      return this;
    }

    public Criteria andOrderCodeNotBetween(String value1, String value2) {
      addCriterion("ORDER_CODE not between", value1, value2, "OrderCode");
      return this;
    }

    public Criteria andBankNameIsNull() {
      addCriterion("BANK_NAME is null");
      return this;
    }

    public Criteria andBankNameIsNotNull() {
      addCriterion("BANK_NAME is not null");
      return this;
    }

    public Criteria andBankNameEqualTo(String value) {
      addCriterion("BANK_NAME =", value, "bankName");
      return this;
    }

    public Criteria andBankNameNotEqualTo(String value) {
      addCriterion("BANK_NAME <>", value, "bankName");
      return this;
    }

    public Criteria andBankNameGreaterThan(String value) {
      addCriterion("BANK_NAME >", value, "bankName");
      return this;
    }

    public Criteria andBankNameGreaterThanOrEqualTo(String value) {
      addCriterion("BANK_NAME >=", value, "bankName");
      return this;
    }

    public Criteria andBankNameLessThan(String value) {
      addCriterion("BANK_NAME <", value, "bankName");
      return this;
    }

    public Criteria andBankNameLessThanOrEqualTo(String value) {
      addCriterion("BANK_NAME <=", value, "bankName");
      return this;
    }

    public Criteria andBankNameLike(String value) {
      addCriterion("BANK_NAME like", value, "bankName");
      return this;
    }

    public Criteria andBankNameNotLike(String value) {
      addCriterion("BANK_NAME not like", value, "bankName");
      return this;
    }

    public Criteria andBankNameIn(List values) {
      addCriterion("BANK_NAME in", values, "bankName");
      return this;
    }

    public Criteria andBankNametIn(List values) {
      addCriterion("BANK_NAME not in", values, "bankName");
      return this;
    }

    public Criteria andBankNameBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("BANK_NAME between", value1, value2, "bankName");
      return this;
    }

    public Criteria andBankNameNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("BANK_NAME not between", value1, value2, "bankName");
      return this;
    }

    public Criteria andBankCodeIsNull() {
      addCriterion("BANK_CODE is null");
      return this;
    }

    public Criteria andBankCodeIsNotNull() {
      addCriterion("BANK_CODE is not null");
      return this;
    }

    public Criteria andBankCodeEqualTo(String value) {
      addCriterion("BANK_CODE =", value, "bankCode");
      return this;
    }

    public Criteria andBankCodeNotEqualTo(String value) {
      addCriterion("BANK_CODE <>", value, "bankCode");
      return this;
    }

    public Criteria andBankCodeGreaterThan(String value) {
      addCriterion("BANK_CODE >", value, "bankCode");
      return this;
    }

    public Criteria andBankCodeGreaterThanOrEqualTo(String value) {
      addCriterion("BANK_CODE >=", value, "bankCode");
      return this;
    }

    public Criteria andBankCodeLessThan(String value) {
      addCriterion("BANK_CODE <", value, "bankCode");
      return this;
    }

    public Criteria andBankCodeLessThanOrEqualTo(String value) {
      addCriterion("BANK_CODE <=", value, "bankCode");
      return this;
    }

    public Criteria andBankCodeLike(String value) {
      addCriterion("BANK_CODE like", value, "bankCode");
      return this;
    }

    public Criteria andBankCodeNotLike(String value) {
      addCriterion("BANK_CODE not like", value, "bankCode");
      return this;
    }

    public Criteria andBankCodeIn(List values) {
      addCriterion("BANK_CODE in", values, "bankCode");
      return this;
    }

    public Criteria andBankCodetIn(List values) {
      addCriterion("BANK_CODE not in", values, "bankCode");
      return this;
    }

    public Criteria andBankCodeBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("BANK_CODE between", value1, value2, "bankCode");
      return this;
    }

    public Criteria andBankCodeNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("BANK_CODE not between", value1, value2, "bankCode");
      return this;
    }

    public Criteria andPlatFormNameIsNull() {
      addCriterion("PLATFORM_NAME is null");
      return this;
    }

    public Criteria andPlatFormNameIsNotNull() {
      addCriterion("PLATFORM_NAME is not null");
      return this;
    }

    public Criteria andPlatFormNameEqualTo(String value) {
      addCriterion("PLATFORM_NAME =", value, "platFormName");
      return this;
    }

    public Criteria andPlatFormNameNotEqualTo(String value) {
      addCriterion("PLATFORM_NAME <>", value, "platFormName");
      return this;
    }

    public Criteria andPlatFormNameGreaterThan(String value) {
      addCriterion("PLATFORM_NAME >", value, "platFormName");
      return this;
    }

    public Criteria andPlatFormNameGreaterThanOrEqualTo(String value) {
      addCriterion("PLATFORM_NAME >=", value, "platFormName");
      return this;
    }

    public Criteria andPlatFormNameLessThan(String value) {
      addCriterion("PLATFORM_NAME <", value, "platFormName");
      return this;
    }

    public Criteria andPlatFormNameLessThanOrEqualTo(String value) {
      addCriterion("PLATFORM_NAME <=", value, "platFormName");
      return this;
    }

    public Criteria andPlatFormNameLike(String value) {
      addCriterion("PLATFORM_NAME like", value, "platFormName");
      return this;
    }

    public Criteria andPlatFormNameNotLike(String value) {
      addCriterion("PLATFORM_NAME not like", value, "platFormName");
      return this;
    }

    public Criteria andPlatFormNameIn(List values) {
      addCriterion("PLATFORM_NAME in", values, "platFormName");
      return this;
    }

    public Criteria andPlatFormNametIn(List values) {
      addCriterion("PLATFORM_NAME not in", values, "platFormName");
      return this;
    }

    public Criteria andPlatFormNameBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PLATFORM_NAME between", value1, value2, "platFormName");
      return this;
    }

    public Criteria andPlatFormNameNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PLATFORM_NAME not between", value1, value2, "platFormName");
      return this;
    }

    public Criteria andPlatFormCodeIsNull() {
      addCriterion("PLATFORM_CODE is null");
      return this;
    }

    public Criteria andPlatFormCodeIsNotNull() {
      addCriterion("PLATFORM_CODE is not null");
      return this;
    }

    public Criteria andPlatFormCodeEqualTo(String value) {
      addCriterion("PLATFORM_CODE =", value, "platFormCode");
      return this;
    }

    public Criteria andPlatFormCodeNotEqualTo(String value) {
      addCriterion("PLATFORM_CODE <>", value, "platFormCode");
      return this;
    }

    public Criteria andPlatFormCodeGreaterThan(String value) {
      addCriterion("PLATFORM_CODE >", value, "platFormCode");
      return this;
    }

    public Criteria andPlatFormCodeGreaterThanOrEqualTo(String value) {
      addCriterion("PLATFORM_CODE >=", value, "platFormCode");
      return this;
    }

    public Criteria andPlatFormCodeLessThan(String value) {
      addCriterion("PLATFORM_CODE <", value, "platFormCode");
      return this;
    }

    public Criteria andPlatFormCodeLessThanOrEqualTo(String value) {
      addCriterion("PLATFORM_CODE <=", value, "platFormCode");
      return this;
    }

    public Criteria andPlatFormCodeLike(String value) {
      addCriterion("PLATFORM_CODE like", value, "platFormCode");
      return this;
    }

    public Criteria andPlatFormCodeNotLike(String value) {
      addCriterion("PLATFORM_CODE not like", value, "platFormCode");
      return this;
    }

    public Criteria andPlatFormCodeIn(List values) {
      addCriterion("PLATFORM_CODE in", values, "platFormCode");
      return this;
    }

    public Criteria andPlatFormCodetIn(List values) {
      addCriterion("PLATFORM_CODE not in", values, "platFormCode");
      return this;
    }

    public Criteria andPlatFormCodeBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PLATFORM_CODE between", value1, value2, "platFormCode");
      return this;
    }

    public Criteria andPlatFormCodeNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PLATFORM_CODE not between", value1, value2, "platFormCode");
      return this;
    }

    public Criteria andPreferentialGrantIdIsNull() {
      addCriterion("PREFERENTIAL_GRANT_ID is null");
      return this;
    }

    public Criteria andPreferentialGrantIdIsNotNull() {
      addCriterion("PREFERENTIAL_GRANT_ID is not null");
      return this;
    }

    public Criteria andPreferentialGrantIdEqualTo(BigDecimal value) {
      addCriterion("PREFERENTIAL_GRANT_ID =", value, "preferentialGrantId");
      return this;
    }

    public Criteria andPreferentialGrantIdNotEqualTo(BigDecimal value) {
      addCriterion("PREFERENTIAL_GRANT_ID <>", value, "preferentialGrantId");
      return this;
    }

    public Criteria andPreferentialGrantIdGreaterThan(BigDecimal value) {
      addCriterion("PREFERENTIAL_GRANT_ID >", value, "preferentialGrantId");
      return this;
    }

    public Criteria andPreferentialGrantIdGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("PREFERENTIAL_GRANT_ID >=", value, "preferentialGrantId");
      return this;
    }

    public Criteria andPreferentialGrantIdLessThan(BigDecimal value) {
      addCriterion("PREFERENTIAL_GRANT_ID <", value, "preferentialGrantId");
      return this;
    }

    public Criteria andPreferentialGrantIdLessThanOrEqualTo(BigDecimal value) {
      addCriterion("PREFERENTIAL_GRANT_ID <=", value, "preferentialGrantId");
      return this;
    }

    public Criteria andPreferentialGrantIdIn(List values) {
      addCriterion("PREFERENTIAL_GRANT_ID in", values, "preferentialGrantId");
      return this;
    }

    public Criteria andPreferentialGrantIdNotIn(List values) {
      addCriterion("PREFERENTIAL_GRANT_ID not in", values, "preferentialGrantId");
      return this;
    }

    public Criteria andPreferentialGrantIdBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PREFERENTIAL_GRANT_ID between", value1, value2, "preferentialGrantId");
      return this;
    }

    public Criteria andPreferentialGrantIdNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PREFERENTIAL_GRANT_ID not between", value1, value2, "preferentialGrantId");
      return this;
    }
  }
}
