package com.pltfm.app.vobject;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

public class ActivitySku extends OrderItemVo implements Serializable {
    // 公司名称（commercial_tenant_basic.CORPORATE_NAME）
    private String corporateName;
    // 店铺名称（SHOP_MAIN.SHOP_NAME）
    private String shopName;
    // 登录帐号
    private String loginAccount;
    // 联系电话
    private String mobile;
    // 商品标题（PRODUCTMAIN.PRODUCT_TITLE）
    private String productTitle;
    // sku编号(PRODUCT_SKU.PRODUCT_SKU_CODE)
    // sku价格(PRODUCT_SKU.PRICE)
    private BigDecimal price;
    // 品牌id（prod_brand.brand_id）
    private Long brandId;
    // 品牌名称（prod_brand.brand_name）
    private String brandName;
    // 最大库存（maxStock）
    private Long maxStock;
    // 商品名称
    private String productName;
    // 追加数量
    private Integer appendPreSaleQuantity;
    // 商品剩余活动总费用
    private BigDecimal residualSkuPrice;
    
    private static final long serialVersionUID = 1303061045065218893L;

    public BigDecimal getResidualSkuPrice() {
        return residualSkuPrice;
    }

    public void setResidualSkuPrice(BigDecimal residualSkuPrice) {
        this.residualSkuPrice = residualSkuPrice;
    }

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.ACTIVITY_SKU_ID
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private Long activitySkuId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.ACTIVITY_ID
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private Long activityId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.SUPPLIER_ENTRY_ID
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private Long supplierEntryId;
    private Long orderItemId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.PRODUCT_SKU_ID
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private Long productSkuId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.AUDIT_STATUS
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private Integer auditStatus;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.PRE_SALE_QUANTITY
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private Integer preSaleQuantity;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.SALE_QUANTITY
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private Integer saleQuantity;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.SKU_TOTAL_PRICE
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private BigDecimal skuTotalPrice;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.ACTIVITY_SKU_IMAGE
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private String activitySkuImage;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.PROMOTION_ID
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private Long promotionId;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.ACTIVITY_PRICE
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private BigDecimal activityPrice;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.COMMISSION_RATE
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private BigDecimal commissionRate;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.ACTIVITY_SKU_TYPE
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private Integer activitySkuType;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.CREATE_TIME
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private Timestamp createTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.MODIFY_TIME
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private Timestamp modifyTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.AUDIT_TIME
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private Timestamp auditTime;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.CREATE_USER
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private Long createUser;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.MODIF_USER
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private Long modifUser;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.AUDIT_USER
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private Long auditUser;

    /**
     * This field was generated by Apache iBATIS ibator. This field corresponds to the database
     * column ACTIVITY_SKU.REMARK
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    private String remark;

    public String getCorporateName() {
        return corporateName;
    }

    public void setCorporateName(String corporateName) {
        this.corporateName = corporateName;
    }

    public String getShopName() {
        return shopName;
    }

    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    public String getLoginAccount() {
        return loginAccount;
    }

    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getProductTitle() {
        return productTitle;
    }

    public void setProductTitle(String productTitle) {
        this.productTitle = productTitle;
    }



    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Long getBrandId() {
        return brandId;
    }

    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    public String getBrandName() {
        return brandName;
    }

    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    public Long getMaxStock() {
        return maxStock;
    }

    public void setMaxStock(Long maxStock) {
        this.maxStock = maxStock;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.ACTIVITY_SKU_ID
     *
     * @return the value of ACTIVITY_SKU.ACTIVITY_SKU_ID
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public Long getActivitySkuId() {
        return activitySkuId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.ACTIVITY_SKU_ID
     *
     * @param activitySkuId the value for ACTIVITY_SKU.ACTIVITY_SKU_ID
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setActivitySkuId(Long activitySkuId) {
        this.activitySkuId = activitySkuId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.ACTIVITY_ID
     *
     * @return the value of ACTIVITY_SKU.ACTIVITY_ID
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.ACTIVITY_ID
     *
     * @param activityId the value for ACTIVITY_SKU.ACTIVITY_ID
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.SUPPLIER_ENTRY_ID
     *
     * @return the value of ACTIVITY_SKU.SUPPLIER_ENTRY_ID
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public Long getSupplierEntryId() {
        return supplierEntryId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.SUPPLIER_ENTRY_ID
     *
     * @param supplierEntryId the value for ACTIVITY_SKU.SUPPLIER_ENTRY_ID
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setSupplierEntryId(Long supplierEntryId) {
        this.supplierEntryId = supplierEntryId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.PRODUCT_SKU_ID
     *
     * @return the value of ACTIVITY_SKU.PRODUCT_SKU_ID
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public Long getProductSkuId() {
        return productSkuId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.PRODUCT_SKU_ID
     *
     * @param productSkuId the value for ACTIVITY_SKU.PRODUCT_SKU_ID
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setProductSkuId(Long productSkuId) {
        this.productSkuId = productSkuId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.AUDIT_STATUS
     *
     * @return the value of ACTIVITY_SKU.AUDIT_STATUS
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.AUDIT_STATUS
     *
     * @param auditStatus the value for ACTIVITY_SKU.AUDIT_STATUS
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.PRE_SALE_QUANTITY
     *
     * @return the value of ACTIVITY_SKU.PRE_SALE_QUANTITY
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public Integer getPreSaleQuantity() {
        return preSaleQuantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.PRE_SALE_QUANTITY
     *
     * @param preSaleQuantity the value for ACTIVITY_SKU.PRE_SALE_QUANTITY
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setPreSaleQuantity(Integer preSaleQuantity) {
        this.preSaleQuantity = preSaleQuantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.SALE_QUANTITY
     *
     * @return the value of ACTIVITY_SKU.SALE_QUANTITY
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public Integer getSaleQuantity() {
        return saleQuantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.SALE_QUANTITY
     *
     * @param saleQuantity the value for ACTIVITY_SKU.SALE_QUANTITY
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setSaleQuantity(Integer saleQuantity) {
        this.saleQuantity = saleQuantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.SKU_TOTAL_PRICE
     *
     * @return the value of ACTIVITY_SKU.SKU_TOTAL_PRICE
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public BigDecimal getSkuTotalPrice() {
        return skuTotalPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.SKU_TOTAL_PRICE
     *
     * @param skuTotalPrice the value for ACTIVITY_SKU.SKU_TOTAL_PRICE
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setSkuTotalPrice(BigDecimal skuTotalPrice) {
        this.skuTotalPrice = skuTotalPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.ACTIVITY_SKU_IMAGE
     *
     * @return the value of ACTIVITY_SKU.ACTIVITY_SKU_IMAGE
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public String getActivitySkuImage() {
        return activitySkuImage;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.ACTIVITY_SKU_IMAGE
     *
     * @param activitySkuImage the value for ACTIVITY_SKU.ACTIVITY_SKU_IMAGE
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setActivitySkuImage(String activitySkuImage) {
        this.activitySkuImage = activitySkuImage;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.PROMOTION_ID
     *
     * @return the value of ACTIVITY_SKU.PROMOTION_ID
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public Long getPromotionId() {
        return promotionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.PROMOTION_ID
     *
     * @param promotionId the value for ACTIVITY_SKU.PROMOTION_ID
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setPromotionId(Long promotionId) {
        this.promotionId = promotionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.ACTIVITY_PRICE
     *
     * @return the value of ACTIVITY_SKU.ACTIVITY_PRICE
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public BigDecimal getActivityPrice() {
        return activityPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.ACTIVITY_PRICE
     *
     * @param activityPrice the value for ACTIVITY_SKU.ACTIVITY_PRICE
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setActivityPrice(BigDecimal activityPrice) {
        this.activityPrice = activityPrice;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.COMMISSION_RATE
     *
     * @return the value of ACTIVITY_SKU.COMMISSION_RATE
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public BigDecimal getCommissionRate() {
        return commissionRate;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.COMMISSION_RATE
     *
     * @param commissionRate the value for ACTIVITY_SKU.COMMISSION_RATE
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setCommissionRate(BigDecimal commissionRate) {
        this.commissionRate = commissionRate;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.ACTIVITY_SKU_TYPE
     *
     * @return the value of ACTIVITY_SKU.ACTIVITY_SKU_TYPE
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public Integer getActivitySkuType() {
        return activitySkuType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.ACTIVITY_SKU_TYPE
     *
     * @param activitySkuType the value for ACTIVITY_SKU.ACTIVITY_SKU_TYPE
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setActivitySkuType(Integer activitySkuType) {
        this.activitySkuType = activitySkuType;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.CREATE_TIME
     *
     * @return the value of ACTIVITY_SKU.CREATE_TIME
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.CREATE_TIME
     *
     * @param createTime the value for ACTIVITY_SKU.CREATE_TIME
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.MODIFY_TIME
     *
     * @return the value of ACTIVITY_SKU.MODIFY_TIME
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public Timestamp getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.MODIFY_TIME
     *
     * @param modifyTime the value for ACTIVITY_SKU.MODIFY_TIME
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setModifyTime(Timestamp modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.AUDIT_TIME
     *
     * @return the value of ACTIVITY_SKU.AUDIT_TIME
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public Timestamp getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.AUDIT_TIME
     *
     * @param auditTime the value for ACTIVITY_SKU.AUDIT_TIME
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setAuditTime(Timestamp auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.CREATE_USER
     *
     * @return the value of ACTIVITY_SKU.CREATE_USER
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.CREATE_USER
     *
     * @param createUser the value for ACTIVITY_SKU.CREATE_USER
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.MODIF_USER
     *
     * @return the value of ACTIVITY_SKU.MODIF_USER
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public Long getModifUser() {
        return modifUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.MODIF_USER
     *
     * @param modifUser the value for ACTIVITY_SKU.MODIF_USER
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setModifUser(Long modifUser) {
        this.modifUser = modifUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.AUDIT_USER
     *
     * @return the value of ACTIVITY_SKU.AUDIT_USER
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public Long getAuditUser() {
        return auditUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.AUDIT_USER
     *
     * @param auditUser the value for ACTIVITY_SKU.AUDIT_USER
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setAuditUser(Long auditUser) {
        this.auditUser = auditUser;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method returns the value of the
     * database column ACTIVITY_SKU.REMARK
     *
     * @return the value of ACTIVITY_SKU.REMARK
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS ibator. This method sets the value of the database
     * column ACTIVITY_SKU.REMARK
     *
     * @param remark the value for ACTIVITY_SKU.REMARK
     *
     * @ibatorgenerated Thu Mar 17 15:36:08 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Integer getAppendPreSaleQuantity() {
        return appendPreSaleQuantity;
    }

    public void setAppendPreSaleQuantity(Integer appendPreSaleQuantity) {
        this.appendPreSaleQuantity = appendPreSaleQuantity;
    }

    public Long getOrderItemId() {
        return orderItemId;
    }

    public void setOrderItemId(Long orderItemId) {
        this.orderItemId = orderItemId;
    }
}
