package com.pltfm.app.vobject;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.sql.Timestamp;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.pltfm.app.vobject.ActivityInfoExample.Criteria;

public class ActivitySupplierEntryExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ACTIVITY_SUPPLIER_ENTRY
     *
     * @ibatorgenerated Thu Mar 17 15:35:56 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ACTIVITY_SUPPLIER_ENTRY
     *
     * @ibatorgenerated Thu Mar 17 15:35:56 CST 2016
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ACTIVITY_SUPPLIER_ENTRY
     *
     * @ibatorgenerated Thu Mar 17 15:35:56 CST 2016
     */
    public ActivitySupplierEntryExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ACTIVITY_SUPPLIER_ENTRY
     *
     * @ibatorgenerated Thu Mar 17 15:35:56 CST 2016
     */
    protected ActivitySupplierEntryExample(ActivitySupplierEntryExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ACTIVITY_SUPPLIER_ENTRY
     *
     * @ibatorgenerated Thu Mar 17 15:35:56 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ACTIVITY_SUPPLIER_ENTRY
     *
     * @ibatorgenerated Thu Mar 17 15:35:56 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ACTIVITY_SUPPLIER_ENTRY
     *
     * @ibatorgenerated Thu Mar 17 15:35:56 CST 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ACTIVITY_SUPPLIER_ENTRY
     *
     * @ibatorgenerated Thu Mar 17 15:35:56 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ACTIVITY_SUPPLIER_ENTRY
     *
     * @ibatorgenerated Thu Mar 17 15:35:56 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ACTIVITY_SUPPLIER_ENTRY
     *
     * @ibatorgenerated Thu Mar 17 15:35:56 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ACTIVITY_SUPPLIER_ENTRY
     *
     * @ibatorgenerated Thu Mar 17 15:35:56 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ACTIVITY_SUPPLIER_ENTRY
     *
     * @ibatorgenerated Thu Mar 17 15:35:56 CST 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSupplierEntryIdIsNull() {
            addCriterion("SUPPLIER_ENTRY_ID is null");
            return this;
        }

        public Criteria andSupplierEntryIdIsNotNull() {
            addCriterion("SUPPLIER_ENTRY_ID is not null");
            return this;
        }

        public Criteria andSupplierEntryIdEqualTo(Long value) {
            addCriterion("SUPPLIER_ENTRY_ID =", value, "supplierEntryId");
            return this;
        }

        public Criteria andSupplierEntryIdNotEqualTo(Long value) {
            addCriterion("SUPPLIER_ENTRY_ID <>", value, "supplierEntryId");
            return this;
        }

        public Criteria andSupplierEntryIdGreaterThan(Long value) {
            addCriterion("SUPPLIER_ENTRY_ID >", value, "supplierEntryId");
            return this;
        }

        public Criteria andSupplierEntryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SUPPLIER_ENTRY_ID >=", value, "supplierEntryId");
            return this;
        }

        public Criteria andSupplierEntryIdLessThan(Long value) {
            addCriterion("SUPPLIER_ENTRY_ID <", value, "supplierEntryId");
            return this;
        }

        public Criteria andSupplierEntryIdLessThanOrEqualTo(Long value) {
            addCriterion("SUPPLIER_ENTRY_ID <=", value, "supplierEntryId");
            return this;
        }

        public Criteria andSupplierEntryIdIn(List values) {
            addCriterion("SUPPLIER_ENTRY_ID in", values, "supplierEntryId");
            return this;
        }

        public Criteria andSupplierEntryIdNotIn(List values) {
            addCriterion("SUPPLIER_ENTRY_ID not in", values, "supplierEntryId");
            return this;
        }

        public Criteria andSupplierEntryIdBetween(Long value1, Long value2) {
            addCriterion("SUPPLIER_ENTRY_ID between", value1, value2, "supplierEntryId");
            return this;
        }

        public Criteria andSupplierEntryIdNotBetween(Long value1, Long value2) {
            addCriterion("SUPPLIER_ENTRY_ID not between", value1, value2, "supplierEntryId");
            return this;
        }

        public Criteria andActivityIdIsNull() {
            addCriterion("ACTIVITY_ID is null");
            return this;
        }

        public Criteria andActivityIdIsNotNull() {
            addCriterion("ACTIVITY_ID is not null");
            return this;
        }

        public Criteria andActivityIdEqualTo(Long value) {
            addCriterion("ACTIVITY_ID =", value, "activityId");
            return this;
        }

        public Criteria andActivityIdNotEqualTo(Long value) {
            addCriterion("ACTIVITY_ID <>", value, "activityId");
            return this;
        }

        public Criteria andActivityIdGreaterThan(Long value) {
            addCriterion("ACTIVITY_ID >", value, "activityId");
            return this;
        }

        public Criteria andActivityIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ACTIVITY_ID >=", value, "activityId");
            return this;
        }

        public Criteria andActivityIdLessThan(Long value) {
            addCriterion("ACTIVITY_ID <", value, "activityId");
            return this;
        }

        public Criteria andActivityIdLessThanOrEqualTo(Long value) {
            addCriterion("ACTIVITY_ID <=", value, "activityId");
            return this;
        }

        public Criteria andActivityIdIn(List values) {
            addCriterion("ACTIVITY_ID in", values, "activityId");
            return this;
        }

        public Criteria andActivityIdNotIn(List values) {
            addCriterion("ACTIVITY_ID not in", values, "activityId");
            return this;
        }

        public Criteria andActivityIdBetween(Long value1, Long value2) {
            addCriterion("ACTIVITY_ID between", value1, value2, "activityId");
            return this;
        }

        public Criteria andActivityIdNotBetween(Long value1, Long value2) {
            addCriterion("ACTIVITY_ID not between", value1, value2, "activityId");
            return this;
        }

        public Criteria andSupplierIdIsNull() {
            addCriterion("SUPPLIER_ID is null");
            return this;
        }

        public Criteria andSupplierIdIsNotNull() {
            addCriterion("SUPPLIER_ID is not null");
            return this;
        }

        public Criteria andSupplierIdEqualTo(Long value) {
            addCriterion("SUPPLIER_ID =", value, "supplierId");
            return this;
        }

        public Criteria andSupplierIdNotEqualTo(Long value) {
            addCriterion("SUPPLIER_ID <>", value, "supplierId");
            return this;
        }

        public Criteria andSupplierIdGreaterThan(Long value) {
            addCriterion("SUPPLIER_ID >", value, "supplierId");
            return this;
        }

        public Criteria andSupplierIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SUPPLIER_ID >=", value, "supplierId");
            return this;
        }

        public Criteria andSupplierIdLessThan(Long value) {
            addCriterion("SUPPLIER_ID <", value, "supplierId");
            return this;
        }

        public Criteria andSupplierIdLessThanOrEqualTo(Long value) {
            addCriterion("SUPPLIER_ID <=", value, "supplierId");
            return this;
        }

        public Criteria andSupplierIdIn(List values) {
            addCriterion("SUPPLIER_ID in", values, "supplierId");
            return this;
        }

        public Criteria andSupplierIdNotIn(List values) {
            addCriterion("SUPPLIER_ID not in", values, "supplierId");
            return this;
        }

        public Criteria andSupplierIdBetween(Long value1, Long value2) {
            addCriterion("SUPPLIER_ID between", value1, value2, "supplierId");
            return this;
        }

        public Criteria andSupplierIdNotBetween(Long value1, Long value2) {
            addCriterion("SUPPLIER_ID not between", value1, value2, "supplierId");
            return this;
        }

        public Criteria andEntryStatusIsNull() {
            addCriterion("ENTRY_STATUS is null");
            return this;
        }

        public Criteria andEntryStatusIsNotNull() {
            addCriterion("ENTRY_STATUS is not null");
            return this;
        }

        public Criteria andEntryStatusEqualTo(Integer value) {
            addCriterion("ENTRY_STATUS =", value, "entryStatus");
            return this;
        }

        public Criteria andEntryStatusNotEqualTo(Integer value) {
            addCriterion("ENTRY_STATUS <>", value, "entryStatus");
            return this;
        }

        public Criteria andEntryStatusGreaterThan(Integer value) {
            addCriterion("ENTRY_STATUS >", value, "entryStatus");
            return this;
        }

        public Criteria andEntryStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("ENTRY_STATUS >=", value, "entryStatus");
            return this;
        }

        public Criteria andEntryStatusLessThan(Integer value) {
            addCriterion("ENTRY_STATUS <", value, "entryStatus");
            return this;
        }

        public Criteria andEntryStatusLessThanOrEqualTo(Integer value) {
            addCriterion("ENTRY_STATUS <=", value, "entryStatus");
            return this;
        }

        public Criteria andEntryStatusIn(List values) {
            addCriterion("ENTRY_STATUS in", values, "entryStatus");
            return this;
        }

        public Criteria andEntryStatusNotIn(List values) {
            addCriterion("ENTRY_STATUS not in", values, "entryStatus");
            return this;
        }

        public Criteria andEntryStatusBetween(Integer value1, Integer value2) {
            addCriterion("ENTRY_STATUS between", value1, value2, "entryStatus");
            return this;
        }

        public Criteria andEntryStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("ENTRY_STATUS not between", value1, value2, "entryStatus");
            return this;
        }

        public Criteria andActivitySupplierTypeIsNull() {
            addCriterion("ACTIVITY_SUPPLIER_TYPE is null");
            return this;
        }

        public Criteria andActivitySupplierTypeIsNotNull() {
            addCriterion("ACTIVITY_SUPPLIER_TYPE is not null");
            return this;
        }

        public Criteria andActivitySupplierTypeEqualTo(Integer value) {
            addCriterion("ACTIVITY_SUPPLIER_TYPE =", value, "activitySupplierType");
            return this;
        }

        public Criteria andActivitySupplierTypeNotEqualTo(Integer value) {
            addCriterion("ACTIVITY_SUPPLIER_TYPE <>", value, "activitySupplierType");
            return this;
        }

        public Criteria andActivitySupplierTypeGreaterThan(Integer value) {
            addCriterion("ACTIVITY_SUPPLIER_TYPE >", value, "activitySupplierType");
            return this;
        }

        public Criteria andActivitySupplierTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ACTIVITY_SUPPLIER_TYPE >=", value, "activitySupplierType");
            return this;
        }

        public Criteria andActivitySupplierTypeLessThan(Integer value) {
            addCriterion("ACTIVITY_SUPPLIER_TYPE <", value, "activitySupplierType");
            return this;
        }

        public Criteria andActivitySupplierTypeLessThanOrEqualTo(Integer value) {
            addCriterion("ACTIVITY_SUPPLIER_TYPE <=", value, "activitySupplierType");
            return this;
        }

        public Criteria andActivitySupplierTypeIn(List values) {
            addCriterion("ACTIVITY_SUPPLIER_TYPE in", values, "activitySupplierType");
            return this;
        }

        public Criteria andActivitySupplierTypeNotIn(List values) {
            addCriterion("ACTIVITY_SUPPLIER_TYPE not in", values, "activitySupplierType");
            return this;
        }

        public Criteria andActivitySupplierTypeBetween(Integer value1, Integer value2) {
            addCriterion("ACTIVITY_SUPPLIER_TYPE between", value1, value2, "activitySupplierType");
            return this;
        }

        public Criteria andActivitySupplierTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("ACTIVITY_SUPPLIER_TYPE not between", value1, value2, "activitySupplierType");
            return this;
        }

        public Criteria andAuditStatusIsNull() {
            addCriterion("AUDIT_STATUS is null");
            return this;
        }

        public Criteria andAuditStatusIsNotNull() {
            addCriterion("AUDIT_STATUS is not null");
            return this;
        }

        public Criteria andAuditStatusEqualTo(Integer value) {
            addCriterion("AUDIT_STATUS =", value, "auditStatus");
            return this;
        }

        public Criteria andAuditStatusNotEqualTo(Integer value) {
            addCriterion("AUDIT_STATUS <>", value, "auditStatus");
            return this;
        }

        public Criteria andAuditStatusGreaterThan(Integer value) {
            addCriterion("AUDIT_STATUS >", value, "auditStatus");
            return this;
        }

        public Criteria andAuditStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("AUDIT_STATUS >=", value, "auditStatus");
            return this;
        }

        public Criteria andAuditStatusLessThan(Integer value) {
            addCriterion("AUDIT_STATUS <", value, "auditStatus");
            return this;
        }

        public Criteria andAuditStatusLessThanOrEqualTo(Integer value) {
            addCriterion("AUDIT_STATUS <=", value, "auditStatus");
            return this;
        }

        public Criteria andAuditStatusIn(List values) {
            addCriterion("AUDIT_STATUS in", values, "auditStatus");
            return this;
        }

        public Criteria andAuditStatusNotIn(List values) {
            addCriterion("AUDIT_STATUS not in", values, "auditStatus");
            return this;
        }

        public Criteria andAuditStatusBetween(Integer value1, Integer value2) {
            addCriterion("AUDIT_STATUS between", value1, value2, "auditStatus");
            return this;
        }

        public Criteria andAuditStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("AUDIT_STATUS not between", value1, value2, "auditStatus");
            return this;
        }

        public Criteria andActivityTotalPriceIsNull() {
            addCriterion("ACTIVITY_TOTAL_PRICE is null");
            return this;
        }

        public Criteria andActivityTotalPriceIsNotNull() {
            addCriterion("ACTIVITY_TOTAL_PRICE is not null");
            return this;
        }

        public Criteria andActivityTotalPriceEqualTo(BigDecimal value) {
            addCriterion("ACTIVITY_TOTAL_PRICE =", value, "activityTotalPrice");
            return this;
        }

        public Criteria andActivityTotalPriceNotEqualTo(BigDecimal value) {
            addCriterion("ACTIVITY_TOTAL_PRICE <>", value, "activityTotalPrice");
            return this;
        }

        public Criteria andActivityTotalPriceGreaterThan(BigDecimal value) {
            addCriterion("ACTIVITY_TOTAL_PRICE >", value, "activityTotalPrice");
            return this;
        }

        public Criteria andActivityTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTIVITY_TOTAL_PRICE >=", value, "activityTotalPrice");
            return this;
        }

        public Criteria andActivityTotalPriceLessThan(BigDecimal value) {
            addCriterion("ACTIVITY_TOTAL_PRICE <", value, "activityTotalPrice");
            return this;
        }

        public Criteria andActivityTotalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTIVITY_TOTAL_PRICE <=", value, "activityTotalPrice");
            return this;
        }

        public Criteria andActivityTotalPriceIn(List values) {
            addCriterion("ACTIVITY_TOTAL_PRICE in", values, "activityTotalPrice");
            return this;
        }

        public Criteria andActivityTotalPriceNotIn(List values) {
            addCriterion("ACTIVITY_TOTAL_PRICE not in", values, "activityTotalPrice");
            return this;
        }

        public Criteria andActivityTotalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTIVITY_TOTAL_PRICE between", value1, value2, "activityTotalPrice");
            return this;
        }

        public Criteria andActivityTotalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTIVITY_TOTAL_PRICE not between", value1, value2, "activityTotalPrice");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(Timestamp value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(Timestamp value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return this;
        }

        public Criteria andModifyTimeEqualTo(Timestamp value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotEqualTo(Timestamp value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeGreaterThan(Timestamp value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeLessThan(Timestamp value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeIn(List values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotIn(List values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return this;
        }

        public Criteria andAuditTimeIsNull() {
            addCriterion("AUDIT_TIME is null");
            return this;
        }

        public Criteria andAuditTimeIsNotNull() {
            addCriterion("AUDIT_TIME is not null");
            return this;
        }

        public Criteria andAuditTimeEqualTo(Timestamp value) {
            addCriterion("AUDIT_TIME =", value, "auditTime");
            return this;
        }

        public Criteria andAuditTimeNotEqualTo(Timestamp value) {
            addCriterion("AUDIT_TIME <>", value, "auditTime");
            return this;
        }

        public Criteria andAuditTimeGreaterThan(Timestamp value) {
            addCriterion("AUDIT_TIME >", value, "auditTime");
            return this;
        }

        public Criteria andAuditTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("AUDIT_TIME >=", value, "auditTime");
            return this;
        }

        public Criteria andAuditTimeLessThan(Timestamp value) {
            addCriterion("AUDIT_TIME <", value, "auditTime");
            return this;
        }

        public Criteria andAuditTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("AUDIT_TIME <=", value, "auditTime");
            return this;
        }

        public Criteria andAuditTimeIn(List values) {
            addCriterion("AUDIT_TIME in", values, "auditTime");
            return this;
        }

        public Criteria andAuditTimeNotIn(List values) {
            addCriterion("AUDIT_TIME not in", values, "auditTime");
            return this;
        }

        public Criteria andAuditTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("AUDIT_TIME between", value1, value2, "auditTime");
            return this;
        }

        public Criteria andAuditTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("AUDIT_TIME not between", value1, value2, "auditTime");
            return this;
        }

        public Criteria andEntryTimeIsNull() {
            addCriterion("ENTRY_TIME is null");
            return this;
        }

        public Criteria andEntryTimeIsNotNull() {
            addCriterion("ENTRY_TIME is not null");
            return this;
        }

        public Criteria andEntryTimeEqualTo(Timestamp value) {
            addCriterion("ENTRY_TIME =", value, "entryTime");
            return this;
        }

        public Criteria andEntryTimeNotEqualTo(Timestamp value) {
            addCriterion("ENTRY_TIME <>", value, "entryTime");
            return this;
        }

        public Criteria andEntryTimeGreaterThan(Timestamp value) {
            addCriterion("ENTRY_TIME >", value, "entryTime");
            return this;
        }

        public Criteria andEntryTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("ENTRY_TIME >=", value, "entryTime");
            return this;
        }

        public Criteria andEntryTimeLessThan(Timestamp value) {
            addCriterion("ENTRY_TIME <", value, "entryTime");
            return this;
        }

        public Criteria andEntryTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("ENTRY_TIME <=", value, "entryTime");
            return this;
        }

        public Criteria andEntryTimeIn(List values) {
            addCriterion("ENTRY_TIME in", values, "entryTime");
            return this;
        }

        public Criteria andEntryTimeNotIn(List values) {
            addCriterion("ENTRY_TIME not in", values, "entryTime");
            return this;
        }

        public Criteria andEntryTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("ENTRY_TIME between", value1, value2, "entryTime");
            return this;
        }

        public Criteria andEntryTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("ENTRY_TIME not between", value1, value2, "entryTime");
            return this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return this;
        }

        public Criteria andCreateUserEqualTo(Long value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return this;
        }

        public Criteria andCreateUserNotEqualTo(Long value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return this;
        }

        public Criteria andCreateUserGreaterThan(Long value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Long value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return this;
        }

        public Criteria andCreateUserLessThan(Long value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Long value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return this;
        }

        public Criteria andCreateUserIn(List values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return this;
        }

        public Criteria andCreateUserNotIn(List values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return this;
        }

        public Criteria andCreateUserBetween(Long value1, Long value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return this;
        }

        public Criteria andCreateUserNotBetween(Long value1, Long value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return this;
        }

        public Criteria andModifUserIsNull() {
            addCriterion("MODIF_USER is null");
            return this;
        }

        public Criteria andModifUserIsNotNull() {
            addCriterion("MODIF_USER is not null");
            return this;
        }

        public Criteria andModifUserEqualTo(Long value) {
            addCriterion("MODIF_USER =", value, "modifUser");
            return this;
        }

        public Criteria andModifUserNotEqualTo(Long value) {
            addCriterion("MODIF_USER <>", value, "modifUser");
            return this;
        }

        public Criteria andModifUserGreaterThan(Long value) {
            addCriterion("MODIF_USER >", value, "modifUser");
            return this;
        }

        public Criteria andModifUserGreaterThanOrEqualTo(Long value) {
            addCriterion("MODIF_USER >=", value, "modifUser");
            return this;
        }

        public Criteria andModifUserLessThan(Long value) {
            addCriterion("MODIF_USER <", value, "modifUser");
            return this;
        }

        public Criteria andModifUserLessThanOrEqualTo(Long value) {
            addCriterion("MODIF_USER <=", value, "modifUser");
            return this;
        }

        public Criteria andModifUserIn(List values) {
            addCriterion("MODIF_USER in", values, "modifUser");
            return this;
        }

        public Criteria andModifUserNotIn(List values) {
            addCriterion("MODIF_USER not in", values, "modifUser");
            return this;
        }

        public Criteria andModifUserBetween(Long value1, Long value2) {
            addCriterion("MODIF_USER between", value1, value2, "modifUser");
            return this;
        }

        public Criteria andModifUserNotBetween(Long value1, Long value2) {
            addCriterion("MODIF_USER not between", value1, value2, "modifUser");
            return this;
        }

        public Criteria andEntryUserIsNull() {
            addCriterion("ENTRY_USER is null");
            return this;
        }

        public Criteria andEntryUserIsNotNull() {
            addCriterion("ENTRY_USER is not null");
            return this;
        }

        public Criteria andEntryUserEqualTo(Long value) {
            addCriterion("ENTRY_USER =", value, "entryUser");
            return this;
        }

        public Criteria andEntryUserNotEqualTo(Long value) {
            addCriterion("ENTRY_USER <>", value, "entryUser");
            return this;
        }

        public Criteria andEntryUserGreaterThan(Long value) {
            addCriterion("ENTRY_USER >", value, "entryUser");
            return this;
        }

        public Criteria andEntryUserGreaterThanOrEqualTo(Long value) {
            addCriterion("ENTRY_USER >=", value, "entryUser");
            return this;
        }

        public Criteria andEntryUserLessThan(Long value) {
            addCriterion("ENTRY_USER <", value, "entryUser");
            return this;
        }

        public Criteria andEntryUserLessThanOrEqualTo(Long value) {
            addCriterion("ENTRY_USER <=", value, "entryUser");
            return this;
        }

        public Criteria andEntryUserIn(List values) {
            addCriterion("ENTRY_USER in", values, "entryUser");
            return this;
        }

        public Criteria andEntryUserNotIn(List values) {
            addCriterion("ENTRY_USER not in", values, "entryUser");
            return this;
        }

        public Criteria andEntryUserBetween(Long value1, Long value2) {
            addCriterion("ENTRY_USER between", value1, value2, "entryUser");
            return this;
        }

        public Criteria andEntryUserNotBetween(Long value1, Long value2) {
            addCriterion("ENTRY_USER not between", value1, value2, "entryUser");
            return this;
        }

        public Criteria andAuditUserIsNull() {
            addCriterion("AUDIT_USER is null");
            return this;
        }

        public Criteria andAuditUserIsNotNull() {
            addCriterion("AUDIT_USER is not null");
            return this;
        }

        public Criteria andAuditUserEqualTo(Long value) {
            addCriterion("AUDIT_USER =", value, "auditUser");
            return this;
        }

        public Criteria andAuditUserNotEqualTo(Long value) {
            addCriterion("AUDIT_USER <>", value, "auditUser");
            return this;
        }

        public Criteria andAuditUserGreaterThan(Long value) {
            addCriterion("AUDIT_USER >", value, "auditUser");
            return this;
        }

        public Criteria andAuditUserGreaterThanOrEqualTo(Long value) {
            addCriterion("AUDIT_USER >=", value, "auditUser");
            return this;
        }

        public Criteria andAuditUserLessThan(Long value) {
            addCriterion("AUDIT_USER <", value, "auditUser");
            return this;
        }

        public Criteria andAuditUserLessThanOrEqualTo(Long value) {
            addCriterion("AUDIT_USER <=", value, "auditUser");
            return this;
        }

        public Criteria andAuditUserIn(List values) {
            addCriterion("AUDIT_USER in", values, "auditUser");
            return this;
        }

        public Criteria andAuditUserNotIn(List values) {
            addCriterion("AUDIT_USER not in", values, "auditUser");
            return this;
        }

        public Criteria andAuditUserBetween(Long value1, Long value2) {
            addCriterion("AUDIT_USER between", value1, value2, "auditUser");
            return this;
        }

        public Criteria andAuditUserNotBetween(Long value1, Long value2) {
            addCriterion("AUDIT_USER not between", value1, value2, "auditUser");
            return this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return this;
        }

        public Criteria andRemarkIn(List values) {
            addCriterion("REMARK in", values, "remark");
            return this;
        }

        public Criteria andRemarkNotIn(List values) {
            addCriterion("REMARK not in", values, "remark");
            return this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return this;
        }
    }
}