package com.pltfm.app.vobject;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class AftersaleReturnOrderExample  implements Serializable{

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table AFTERSALE_RETURN_ORDER
	 * @ibatorgenerated  Thu Aug 29 15:21:48 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table AFTERSALE_RETURN_ORDER
	 * @ibatorgenerated  Thu Aug 29 15:21:48 CST 2013
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table AFTERSALE_RETURN_ORDER
	 * @ibatorgenerated  Thu Aug 29 15:21:48 CST 2013
	 */
	public AftersaleReturnOrderExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table AFTERSALE_RETURN_ORDER
	 * @ibatorgenerated  Thu Aug 29 15:21:48 CST 2013
	 */
	protected AftersaleReturnOrderExample(AftersaleReturnOrderExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table AFTERSALE_RETURN_ORDER
	 * @ibatorgenerated  Thu Aug 29 15:21:48 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table AFTERSALE_RETURN_ORDER
	 * @ibatorgenerated  Thu Aug 29 15:21:48 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table AFTERSALE_RETURN_ORDER
	 * @ibatorgenerated  Thu Aug 29 15:21:48 CST 2013
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table AFTERSALE_RETURN_ORDER
	 * @ibatorgenerated  Thu Aug 29 15:21:48 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table AFTERSALE_RETURN_ORDER
	 * @ibatorgenerated  Thu Aug 29 15:21:48 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table AFTERSALE_RETURN_ORDER
	 * @ibatorgenerated  Thu Aug 29 15:21:48 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table AFTERSALE_RETURN_ORDER
	 * @ibatorgenerated  Thu Aug 29 15:21:48 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table AFTERSALE_RETURN_ORDER
	 * @ibatorgenerated  Thu Aug 29 15:21:48 CST 2013
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List dateList = new ArrayList();
			Iterator iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(((Date) iter.next()).getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andReturnIdIsNull() {
			addCriterion("RETURN_ID is null");
			return this;
		}

		public Criteria andReturnIdIsNotNull() {
			addCriterion("RETURN_ID is not null");
			return this;
		}

		public Criteria andReturnIdEqualTo(BigDecimal value) {
			addCriterion("RETURN_ID =", value, "returnId");
			return this;
		}

		public Criteria andReturnIdNotEqualTo(BigDecimal value) {
			addCriterion("RETURN_ID <>", value, "returnId");
			return this;
		}

		public Criteria andReturnIdGreaterThan(BigDecimal value) {
			addCriterion("RETURN_ID >", value, "returnId");
			return this;
		}

		public Criteria andReturnIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("RETURN_ID >=", value, "returnId");
			return this;
		}

		public Criteria andReturnIdLessThan(BigDecimal value) {
			addCriterion("RETURN_ID <", value, "returnId");
			return this;
		}

		public Criteria andReturnIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("RETURN_ID <=", value, "returnId");
			return this;
		}

		public Criteria andReturnIdIn(List values) {
			addCriterion("RETURN_ID in", values, "returnId");
			return this;
		}

		public Criteria andReturnIdNotIn(List values) {
			addCriterion("RETURN_ID not in", values, "returnId");
			return this;
		}

		public Criteria andReturnIdBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("RETURN_ID between", value1, value2, "returnId");
			return this;
		}

		public Criteria andReturnIdNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("RETURN_ID not between", value1, value2, "returnId");
			return this;
		}

		public Criteria andReturnNoIsNull() {
			addCriterion("RETURN_NO is null");
			return this;
		}

		public Criteria andReturnNoIsNotNull() {
			addCriterion("RETURN_NO is not null");
			return this;
		}

		public Criteria andReturnNoEqualTo(String value) {
			addCriterion("RETURN_NO =", value, "returnNo");
			return this;
		}

		public Criteria andReturnNoNotEqualTo(String value) {
			addCriterion("RETURN_NO <>", value, "returnNo");
			return this;
		}

		public Criteria andReturnNoGreaterThan(String value) {
			addCriterion("RETURN_NO >", value, "returnNo");
			return this;
		}

		public Criteria andReturnNoGreaterThanOrEqualTo(String value) {
			addCriterion("RETURN_NO >=", value, "returnNo");
			return this;
		}

		public Criteria andReturnNoLessThan(String value) {
			addCriterion("RETURN_NO <", value, "returnNo");
			return this;
		}

		public Criteria andReturnNoLessThanOrEqualTo(String value) {
			addCriterion("RETURN_NO <=", value, "returnNo");
			return this;
		}

		public Criteria andReturnNoLike(String value) {
			addCriterion("RETURN_NO like", value, "returnNo");
			return this;
		}

		public Criteria andReturnNoNotLike(String value) {
			addCriterion("RETURN_NO not like", value, "returnNo");
			return this;
		}

		public Criteria andReturnNoIn(List values) {
			addCriterion("RETURN_NO in", values, "returnNo");
			return this;
		}

		public Criteria andReturnNoNotIn(List values) {
			addCriterion("RETURN_NO not in", values, "returnNo");
			return this;
		}

		public Criteria andReturnNoBetween(String value1, String value2) {
			addCriterion("RETURN_NO between", value1, value2, "returnNo");
			return this;
		}

		public Criteria andReturnNoNotBetween(String value1, String value2) {
			addCriterion("RETURN_NO not between", value1, value2, "returnNo");
			return this;
		}

		public Criteria andCustIdIsNull() {
			addCriterion("CUST_ID is null");
			return this;
		}

		public Criteria andCustIdIsNotNull() {
			addCriterion("CUST_ID is not null");
			return this;
		}

		public Criteria andCustIdEqualTo(BigDecimal value) {
			addCriterion("CUST_ID =", value, "custId");
			return this;
		}

		public Criteria andCustIdNotEqualTo(BigDecimal value) {
			addCriterion("CUST_ID <>", value, "custId");
			return this;
		}

		public Criteria andCustIdGreaterThan(BigDecimal value) {
			addCriterion("CUST_ID >", value, "custId");
			return this;
		}

		public Criteria andCustIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("CUST_ID >=", value, "custId");
			return this;
		}

		public Criteria andCustIdLessThan(BigDecimal value) {
			addCriterion("CUST_ID <", value, "custId");
			return this;
		}

		public Criteria andCustIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("CUST_ID <=", value, "custId");
			return this;
		}

		public Criteria andCustIdIn(List values) {
			addCriterion("CUST_ID in", values, "custId");
			return this;
		}

		public Criteria andCustIdNotIn(List values) {
			addCriterion("CUST_ID not in", values, "custId");
			return this;
		}

		public Criteria andCustIdBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("CUST_ID between", value1, value2, "custId");
			return this;
		}

		public Criteria andCustIdNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("CUST_ID not between", value1, value2, "custId");
			return this;
		}

		public Criteria andCustNameIsNull() {
			addCriterion("CUST_NAME is null");
			return this;
		}

		public Criteria andCustNameIsNotNull() {
			addCriterion("CUST_NAME is not null");
			return this;
		}

		public Criteria andCustNameEqualTo(String value) {
			addCriterion("CUST_NAME =", value, "custName");
			return this;
		}

		public Criteria andCustNameNotEqualTo(String value) {
			addCriterion("CUST_NAME <>", value, "custName");
			return this;
		}

		public Criteria andCustNameGreaterThan(String value) {
			addCriterion("CUST_NAME >", value, "custName");
			return this;
		}

		public Criteria andCustNameGreaterThanOrEqualTo(String value) {
			addCriterion("CUST_NAME >=", value, "custName");
			return this;
		}

		public Criteria andCustNameLessThan(String value) {
			addCriterion("CUST_NAME <", value, "custName");
			return this;
		}

		public Criteria andCustNameLessThanOrEqualTo(String value) {
			addCriterion("CUST_NAME <=", value, "custName");
			return this;
		}

		public Criteria andCustNameLike(String value) {
			addCriterion("CUST_NAME like", value, "custName");
			return this;
		}

		public Criteria andCustNameNotLike(String value) {
			addCriterion("CUST_NAME not like", value, "custName");
			return this;
		}

		public Criteria andCustNameIn(List values) {
			addCriterion("CUST_NAME in", values, "custName");
			return this;
		}

		public Criteria andCustNameNotIn(List values) {
			addCriterion("CUST_NAME not in", values, "custName");
			return this;
		}

		public Criteria andCustNameBetween(String value1, String value2) {
			addCriterion("CUST_NAME between", value1, value2, "custName");
			return this;
		}

		public Criteria andCustNameNotBetween(String value1, String value2) {
			addCriterion("CUST_NAME not between", value1, value2, "custName");
			return this;
		}

		public Criteria andOrderCodeIsNull() {
			addCriterion("ORDER_CODE is null");
			return this;
		}

		public Criteria andOrderCodeIsNotNull() {
			addCriterion("ORDER_CODE is not null");
			return this;
		}

		public Criteria andOrderCodeEqualTo(String value) {
			addCriterion("ORDER_CODE =", value, "orderId");
			return this;
		}

		public Criteria andOrderCodeNotEqualTo(String value) {
			addCriterion("ORDER_CODE <>", value, "orderId");
			return this;
		}

		public Criteria andOrderCodeGreaterThan(String value) {
			addCriterion("ORDER_CODE >", value, "orderId");
			return this;
		}

		public Criteria andOrderCodeGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_CODE >=", value, "orderId");
			return this;
		}

		public Criteria andOrderCodeLessThan(String value) {
			addCriterion("ORDER_CODE <", value, "orderId");
			return this;
		}

		public Criteria andOrderCodeLessThanOrEqualTo(String value) {
			addCriterion("ORDER_CODE <=", value, "orderId");
			return this;
		}

		public Criteria andOrderCodeIn(List values) {
			addCriterion("ORDER_CODE in", values, "orderId");
			return this;
		}

		public Criteria andOrderCodeNotIn(List values) {
			addCriterion("ORDER_CODE not in", values, "orderId");
			return this;
		}

		public Criteria andOrderCodeBetween(String value1, String value2) {
			addCriterion("ORDER_CODE between", value1, value2, "orderId");
			return this;
		}

		public Criteria andOrderCodeNotBetween(String value1,
				String value2) {
			addCriterion("ORDER_CODE not between", value1, value2, "orderId");
			return this;
		}

		public Criteria andOrderdetailIdIsNull() {
			addCriterion("ORDERDETAIL_ID is null");
			return this;
		}

		public Criteria andOrderdetailIdIsNotNull() {
			addCriterion("ORDERDETAIL_ID is not null");
			return this;
		}

		public Criteria andOrderdetailIdEqualTo(BigDecimal value) {
			addCriterion("ORDERDETAIL_ID =", value, "orderdetailId");
			return this;
		}

		public Criteria andOrderdetailIdNotEqualTo(BigDecimal value) {
			addCriterion("ORDERDETAIL_ID <>", value, "orderdetailId");
			return this;
		}

		public Criteria andOrderdetailIdGreaterThan(BigDecimal value) {
			addCriterion("ORDERDETAIL_ID >", value, "orderdetailId");
			return this;
		}

		public Criteria andOrderdetailIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ORDERDETAIL_ID >=", value, "orderdetailId");
			return this;
		}

		public Criteria andOrderdetailIdLessThan(BigDecimal value) {
			addCriterion("ORDERDETAIL_ID <", value, "orderdetailId");
			return this;
		}

		public Criteria andOrderdetailIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("ORDERDETAIL_ID <=", value, "orderdetailId");
			return this;
		}

		public Criteria andOrderdetailIdIn(List values) {
			addCriterion("ORDERDETAIL_ID in", values, "orderdetailId");
			return this;
		}

		public Criteria andOrderdetailIdNotIn(List values) {
			addCriterion("ORDERDETAIL_ID not in", values, "orderdetailId");
			return this;
		}

		public Criteria andOrderdetailIdBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("ORDERDETAIL_ID between", value1, value2,
					"orderdetailId");
			return this;
		}

		public Criteria andOrderdetailIdNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("ORDERDETAIL_ID not between", value1, value2,
					"orderdetailId");
			return this;
		}

		public Criteria andOrderTypeIsNull() {
			addCriterion("ORDER_TYPE is null");
			return this;
		}

		public Criteria andOrderTypeIsNotNull() {
			addCriterion("ORDER_TYPE is not null");
			return this;
		}

		public Criteria andOrderTypeEqualTo(Short value) {
			addCriterion("ORDER_TYPE =", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeNotEqualTo(Short value) {
			addCriterion("ORDER_TYPE <>", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeGreaterThan(Short value) {
			addCriterion("ORDER_TYPE >", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeGreaterThanOrEqualTo(Short value) {
			addCriterion("ORDER_TYPE >=", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeLessThan(Short value) {
			addCriterion("ORDER_TYPE <", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeLessThanOrEqualTo(Short value) {
			addCriterion("ORDER_TYPE <=", value, "orderType");
			return this;
		}

		public Criteria andOrderTypeIn(List values) {
			addCriterion("ORDER_TYPE in", values, "orderType");
			return this;
		}

		public Criteria andOrderTypeNotIn(List values) {
			addCriterion("ORDER_TYPE not in", values, "orderType");
			return this;
		}

		public Criteria andOrderTypeBetween(Short value1, Short value2) {
			addCriterion("ORDER_TYPE between", value1, value2, "orderType");
			return this;
		}

		public Criteria andOrderTypeNotBetween(Short value1, Short value2) {
			addCriterion("ORDER_TYPE not between", value1, value2, "orderType");
			return this;
		}

		public Criteria andProductIdIsNull() {
			addCriterion("PRODUCT_ID is null");
			return this;
		}

		public Criteria andProductIdIsNotNull() {
			addCriterion("PRODUCT_ID is not null");
			return this;
		}

		public Criteria andProductIdEqualTo(BigDecimal value) {
			addCriterion("PRODUCT_ID =", value, "productId");
			return this;
		}

		public Criteria andProductIdNotEqualTo(BigDecimal value) {
			addCriterion("PRODUCT_ID <>", value, "productId");
			return this;
		}

		public Criteria andProductIdGreaterThan(BigDecimal value) {
			addCriterion("PRODUCT_ID >", value, "productId");
			return this;
		}

		public Criteria andProductIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("PRODUCT_ID >=", value, "productId");
			return this;
		}

		public Criteria andProductIdLessThan(BigDecimal value) {
			addCriterion("PRODUCT_ID <", value, "productId");
			return this;
		}

		public Criteria andProductIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("PRODUCT_ID <=", value, "productId");
			return this;
		}

		public Criteria andProductIdIn(List values) {
			addCriterion("PRODUCT_ID in", values, "productId");
			return this;
		}

		public Criteria andProductIdNotIn(List values) {
			addCriterion("PRODUCT_ID not in", values, "productId");
			return this;
		}

		public Criteria andProductIdBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PRODUCT_ID between", value1, value2, "productId");
			return this;
		}

		public Criteria andProductIdNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("PRODUCT_ID not between", value1, value2, "productId");
			return this;
		}

		public Criteria andProductNameIsNull() {
			addCriterion("PRODUCT_NAME is null");
			return this;
		}

		public Criteria andProductNameIsNotNull() {
			addCriterion("PRODUCT_NAME is not null");
			return this;
		}

		public Criteria andProductNameEqualTo(String value) {
			addCriterion("PRODUCT_NAME =", value, "productName");
			return this;
		}

		public Criteria andProductNameNotEqualTo(String value) {
			addCriterion("PRODUCT_NAME <>", value, "productName");
			return this;
		}

		public Criteria andProductNameGreaterThan(String value) {
			addCriterion("PRODUCT_NAME >", value, "productName");
			return this;
		}

		public Criteria andProductNameGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NAME >=", value, "productName");
			return this;
		}

		public Criteria andProductNameLessThan(String value) {
			addCriterion("PRODUCT_NAME <", value, "productName");
			return this;
		}

		public Criteria andProductNameLessThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NAME <=", value, "productName");
			return this;
		}

		public Criteria andProductNameLike(String value) {
			addCriterion("PRODUCT_NAME like", value, "productName");
			return this;
		}

		public Criteria andProductNameNotLike(String value) {
			addCriterion("PRODUCT_NAME not like", value, "productName");
			return this;
		}

		public Criteria andProductNameIn(List values) {
			addCriterion("PRODUCT_NAME in", values, "productName");
			return this;
		}

		public Criteria andProductNameNotIn(List values) {
			addCriterion("PRODUCT_NAME not in", values, "productName");
			return this;
		}

		public Criteria andProductNameBetween(String value1, String value2) {
			addCriterion("PRODUCT_NAME between", value1, value2, "productName");
			return this;
		}

		public Criteria andProductNameNotBetween(String value1, String value2) {
			addCriterion("PRODUCT_NAME not between", value1, value2,
					"productName");
			return this;
		}

		public Criteria andProductNoIsNull() {
			addCriterion("PRODUCT_NO is null");
			return this;
		}

		public Criteria andProductNoIsNotNull() {
			addCriterion("PRODUCT_NO is not null");
			return this;
		}

		public Criteria andProductNoEqualTo(String value) {
			addCriterion("PRODUCT_NO =", value, "productNo");
			return this;
		}

		public Criteria andProductNoNotEqualTo(String value) {
			addCriterion("PRODUCT_NO <>", value, "productNo");
			return this;
		}

		public Criteria andProductNoGreaterThan(String value) {
			addCriterion("PRODUCT_NO >", value, "productNo");
			return this;
		}

		public Criteria andProductNoGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NO >=", value, "productNo");
			return this;
		}

		public Criteria andProductNoLessThan(String value) {
			addCriterion("PRODUCT_NO <", value, "productNo");
			return this;
		}

		public Criteria andProductNoLessThanOrEqualTo(String value) {
			addCriterion("PRODUCT_NO <=", value, "productNo");
			return this;
		}

		public Criteria andProductNoLike(String value) {
			addCriterion("PRODUCT_NO like", value, "productNo");
			return this;
		}

		public Criteria andProductNoNotLike(String value) {
			addCriterion("PRODUCT_NO not like", value, "productNo");
			return this;
		}

		public Criteria andProductNoIn(List values) {
			addCriterion("PRODUCT_NO in", values, "productNo");
			return this;
		}

		public Criteria andProductNoNotIn(List values) {
			addCriterion("PRODUCT_NO not in", values, "productNo");
			return this;
		}

		public Criteria andProductNoBetween(String value1, String value2) {
			addCriterion("PRODUCT_NO between", value1, value2, "productNo");
			return this;
		}

		public Criteria andProductNoNotBetween(String value1, String value2) {
			addCriterion("PRODUCT_NO not between", value1, value2, "productNo");
			return this;
		}

		public Criteria andProductSkuIdIsNull() {
			addCriterion("PRODUCT_SKU_ID is null");
			return this;
		}

		public Criteria andProductSkuIdIsNotNull() {
			addCriterion("PRODUCT_SKU_ID is not null");
			return this;
		}

		public Criteria andProductSkuIdEqualTo(BigDecimal value) {
			addCriterion("PRODUCT_SKU_ID =", value, "productSkuId");
			return this;
		}

		public Criteria andProductSkuIdNotEqualTo(BigDecimal value) {
			addCriterion("PRODUCT_SKU_ID <>", value, "productSkuId");
			return this;
		}

		public Criteria andProductSkuIdGreaterThan(BigDecimal value) {
			addCriterion("PRODUCT_SKU_ID >", value, "productSkuId");
			return this;
		}

		public Criteria andProductSkuIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("PRODUCT_SKU_ID >=", value, "productSkuId");
			return this;
		}

		public Criteria andProductSkuIdLessThan(BigDecimal value) {
			addCriterion("PRODUCT_SKU_ID <", value, "productSkuId");
			return this;
		}

		public Criteria andProductSkuIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("PRODUCT_SKU_ID <=", value, "productSkuId");
			return this;
		}

		public Criteria andProductSkuIdIn(List values) {
			addCriterion("PRODUCT_SKU_ID in", values, "productSkuId");
			return this;
		}

		public Criteria andProductSkuIdNotIn(List values) {
			addCriterion("PRODUCT_SKU_ID not in", values, "productSkuId");
			return this;
		}

		public Criteria andProductSkuIdBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("PRODUCT_SKU_ID between", value1, value2,
					"productSkuId");
			return this;
		}

		public Criteria andProductSkuIdNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("PRODUCT_SKU_ID not between", value1, value2,
					"productSkuId");
			return this;
		}

		public Criteria andProductSkuIsNull() {
			addCriterion("PRODUCT_SKU is null");
			return this;
		}

		public Criteria andProductSkuIsNotNull() {
			addCriterion("PRODUCT_SKU is not null");
			return this;
		}

		public Criteria andProductSkuEqualTo(String value) {
			addCriterion("PRODUCT_SKU =", value, "productSku");
			return this;
		}

		public Criteria andProductSkuNotEqualTo(String value) {
			addCriterion("PRODUCT_SKU <>", value, "productSku");
			return this;
		}

		public Criteria andProductSkuGreaterThan(String value) {
			addCriterion("PRODUCT_SKU >", value, "productSku");
			return this;
		}

		public Criteria andProductSkuGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCT_SKU >=", value, "productSku");
			return this;
		}

		public Criteria andProductSkuLessThan(String value) {
			addCriterion("PRODUCT_SKU <", value, "productSku");
			return this;
		}

		public Criteria andProductSkuLessThanOrEqualTo(String value) {
			addCriterion("PRODUCT_SKU <=", value, "productSku");
			return this;
		}

		public Criteria andProductSkuLike(String value) {
			addCriterion("PRODUCT_SKU like", value, "productSku");
			return this;
		}

		public Criteria andProductSkuNotLike(String value) {
			addCriterion("PRODUCT_SKU not like", value, "productSku");
			return this;
		}

		public Criteria andProductSkuIn(List values) {
			addCriterion("PRODUCT_SKU in", values, "productSku");
			return this;
		}

		public Criteria andProductSkuNotIn(List values) {
			addCriterion("PRODUCT_SKU not in", values, "productSku");
			return this;
		}

		public Criteria andProductSkuBetween(String value1, String value2) {
			addCriterion("PRODUCT_SKU between", value1, value2, "productSku");
			return this;
		}

		public Criteria andProductSkuNotBetween(String value1, String value2) {
			addCriterion("PRODUCT_SKU not between", value1, value2,
					"productSku");
			return this;
		}

		public Criteria andBarCodeIsNull() {
			addCriterion("BAR_CODE is null");
			return this;
		}

		public Criteria andBarCodeIsNotNull() {
			addCriterion("BAR_CODE is not null");
			return this;
		}

		public Criteria andBarCodeEqualTo(String value) {
			addCriterion("BAR_CODE =", value, "barCode");
			return this;
		}

		public Criteria andBarCodeNotEqualTo(String value) {
			addCriterion("BAR_CODE <>", value, "barCode");
			return this;
		}

		public Criteria andBarCodeGreaterThan(String value) {
			addCriterion("BAR_CODE >", value, "barCode");
			return this;
		}

		public Criteria andBarCodeGreaterThanOrEqualTo(String value) {
			addCriterion("BAR_CODE >=", value, "barCode");
			return this;
		}

		public Criteria andBarCodeLessThan(String value) {
			addCriterion("BAR_CODE <", value, "barCode");
			return this;
		}

		public Criteria andBarCodeLessThanOrEqualTo(String value) {
			addCriterion("BAR_CODE <=", value, "barCode");
			return this;
		}

		public Criteria andBarCodeLike(String value) {
			addCriterion("BAR_CODE like", value, "barCode");
			return this;
		}

		public Criteria andBarCodeNotLike(String value) {
			addCriterion("BAR_CODE not like", value, "barCode");
			return this;
		}

		public Criteria andBarCodeIn(List values) {
			addCriterion("BAR_CODE in", values, "barCode");
			return this;
		}

		public Criteria andBarCodeNotIn(List values) {
			addCriterion("BAR_CODE not in", values, "barCode");
			return this;
		}

		public Criteria andBarCodeBetween(String value1, String value2) {
			addCriterion("BAR_CODE between", value1, value2, "barCode");
			return this;
		}

		public Criteria andBarCodeNotBetween(String value1, String value2) {
			addCriterion("BAR_CODE not between", value1, value2, "barCode");
			return this;
		}

		public Criteria andProductCountsIsNull() {
			addCriterion("PRODUCT_COUNTS is null");
			return this;
		}

		public Criteria andProductCountsIsNotNull() {
			addCriterion("PRODUCT_COUNTS is not null");
			return this;
		}

		public Criteria andProductCountsEqualTo(Long value) {
			addCriterion("PRODUCT_COUNTS =", value, "productCounts");
			return this;
		}

		public Criteria andProductCountsNotEqualTo(Long value) {
			addCriterion("PRODUCT_COUNTS <>", value, "productCounts");
			return this;
		}

		public Criteria andProductCountsGreaterThan(Long value) {
			addCriterion("PRODUCT_COUNTS >", value, "productCounts");
			return this;
		}

		public Criteria andProductCountsGreaterThanOrEqualTo(Long value) {
			addCriterion("PRODUCT_COUNTS >=", value, "productCounts");
			return this;
		}

		public Criteria andProductCountsLessThan(Long value) {
			addCriterion("PRODUCT_COUNTS <", value, "productCounts");
			return this;
		}

		public Criteria andProductCountsLessThanOrEqualTo(Long value) {
			addCriterion("PRODUCT_COUNTS <=", value, "productCounts");
			return this;
		}

		public Criteria andProductCountsIn(List values) {
			addCriterion("PRODUCT_COUNTS in", values, "productCounts");
			return this;
		}

		public Criteria andProductCountsNotIn(List values) {
			addCriterion("PRODUCT_COUNTS not in", values, "productCounts");
			return this;
		}

		public Criteria andProductCountsBetween(Long value1, Long value2) {
			addCriterion("PRODUCT_COUNTS between", value1, value2,
					"productCounts");
			return this;
		}

		public Criteria andProductCountsNotBetween(Long value1, Long value2) {
			addCriterion("PRODUCT_COUNTS not between", value1, value2,
					"productCounts");
			return this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("END_TIME is null");
			return this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("END_TIME is not null");
			return this;
		}

		public Criteria andEndTimeEqualTo(Date value) {
			addCriterionForJDBCDate("END_TIME =", value, "endTime");
			return this;
		}

		public Criteria andEndTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("END_TIME <>", value, "endTime");
			return this;
		}

		public Criteria andEndTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("END_TIME >", value, "endTime");
			return this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("END_TIME >=", value, "endTime");
			return this;
		}

		public Criteria andEndTimeLessThan(Date value) {
			addCriterionForJDBCDate("END_TIME <", value, "endTime");
			return this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("END_TIME <=", value, "endTime");
			return this;
		}

		public Criteria andEndTimeIn(List values) {
			addCriterionForJDBCDate("END_TIME in", values, "endTime");
			return this;
		}

		public Criteria andEndTimeNotIn(List values) {
			addCriterionForJDBCDate("END_TIME not in", values, "endTime");
			return this;
		}

		public Criteria andEndTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("END_TIME between", value1, value2,
					"endTime");
			return this;
		}

		public Criteria andEndTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("END_TIME not between", value1, value2,
					"endTime");
			return this;
		}

		public Criteria andProductDescIsNull() {
			addCriterion("PRODUCT_DESC is null");
			return this;
		}

		public Criteria andProductDescIsNotNull() {
			addCriterion("PRODUCT_DESC is not null");
			return this;
		}

		public Criteria andProductDescEqualTo(String value) {
			addCriterion("PRODUCT_DESC =", value, "productDesc");
			return this;
		}

		public Criteria andProductDescNotEqualTo(String value) {
			addCriterion("PRODUCT_DESC <>", value, "productDesc");
			return this;
		}

		public Criteria andProductDescGreaterThan(String value) {
			addCriterion("PRODUCT_DESC >", value, "productDesc");
			return this;
		}

		public Criteria andProductDescGreaterThanOrEqualTo(String value) {
			addCriterion("PRODUCT_DESC >=", value, "productDesc");
			return this;
		}

		public Criteria andProductDescLessThan(String value) {
			addCriterion("PRODUCT_DESC <", value, "productDesc");
			return this;
		}

		public Criteria andProductDescLessThanOrEqualTo(String value) {
			addCriterion("PRODUCT_DESC <=", value, "productDesc");
			return this;
		}

		public Criteria andProductDescLike(String value) {
			addCriterion("PRODUCT_DESC like", value, "productDesc");
			return this;
		}

		public Criteria andProductDescNotLike(String value) {
			addCriterion("PRODUCT_DESC not like", value, "productDesc");
			return this;
		}

		public Criteria andProductDescIn(List values) {
			addCriterion("PRODUCT_DESC in", values, "productDesc");
			return this;
		}

		public Criteria andProductDescNotIn(List values) {
			addCriterion("PRODUCT_DESC not in", values, "productDesc");
			return this;
		}

		public Criteria andProductDescBetween(String value1, String value2) {
			addCriterion("PRODUCT_DESC between", value1, value2, "productDesc");
			return this;
		}

		public Criteria andProductDescNotBetween(String value1, String value2) {
			addCriterion("PRODUCT_DESC not between", value1, value2,
					"productDesc");
			return this;
		}

		public Criteria andExteriorStateIsNull() {
			addCriterion("EXTERIOR_STATE is null");
			return this;
		}

		public Criteria andExteriorStateIsNotNull() {
			addCriterion("EXTERIOR_STATE is not null");
			return this;
		}

		public Criteria andExteriorStateEqualTo(String value) {
			addCriterion("EXTERIOR_STATE =", value, "exteriorState");
			return this;
		}

		public Criteria andExteriorStateNotEqualTo(String value) {
			addCriterion("EXTERIOR_STATE <>", value, "exteriorState");
			return this;
		}

		public Criteria andExteriorStateGreaterThan(String value) {
			addCriterion("EXTERIOR_STATE >", value, "exteriorState");
			return this;
		}

		public Criteria andExteriorStateGreaterThanOrEqualTo(String value) {
			addCriterion("EXTERIOR_STATE >=", value, "exteriorState");
			return this;
		}

		public Criteria andExteriorStateLessThan(String value) {
			addCriterion("EXTERIOR_STATE <", value, "exteriorState");
			return this;
		}

		public Criteria andExteriorStateLessThanOrEqualTo(String value) {
			addCriterion("EXTERIOR_STATE <=", value, "exteriorState");
			return this;
		}

		public Criteria andExteriorStateLike(String value) {
			addCriterion("EXTERIOR_STATE like", value, "exteriorState");
			return this;
		}

		public Criteria andExteriorStateNotLike(String value) {
			addCriterion("EXTERIOR_STATE not like", value, "exteriorState");
			return this;
		}

		public Criteria andExteriorStateIn(List values) {
			addCriterion("EXTERIOR_STATE in", values, "exteriorState");
			return this;
		}

		public Criteria andExteriorStateNotIn(List values) {
			addCriterion("EXTERIOR_STATE not in", values, "exteriorState");
			return this;
		}

		public Criteria andExteriorStateBetween(String value1, String value2) {
			addCriterion("EXTERIOR_STATE between", value1, value2,
					"exteriorState");
			return this;
		}

		public Criteria andExteriorStateNotBetween(String value1, String value2) {
			addCriterion("EXTERIOR_STATE not between", value1, value2,
					"exteriorState");
			return this;
		}

		public Criteria andPackageStateIsNull() {
			addCriterion("PACKAGE_STATE is null");
			return this;
		}

		public Criteria andPackageStateIsNotNull() {
			addCriterion("PACKAGE_STATE is not null");
			return this;
		}

		public Criteria andPackageStateEqualTo(String value) {
			addCriterion("PACKAGE_STATE =", value, "packageState");
			return this;
		}

		public Criteria andPackageStateNotEqualTo(String value) {
			addCriterion("PACKAGE_STATE <>", value, "packageState");
			return this;
		}

		public Criteria andPackageStateGreaterThan(String value) {
			addCriterion("PACKAGE_STATE >", value, "packageState");
			return this;
		}

		public Criteria andPackageStateGreaterThanOrEqualTo(String value) {
			addCriterion("PACKAGE_STATE >=", value, "packageState");
			return this;
		}

		public Criteria andPackageStateLessThan(String value) {
			addCriterion("PACKAGE_STATE <", value, "packageState");
			return this;
		}

		public Criteria andPackageStateLessThanOrEqualTo(String value) {
			addCriterion("PACKAGE_STATE <=", value, "packageState");
			return this;
		}

		public Criteria andPackageStateLike(String value) {
			addCriterion("PACKAGE_STATE like", value, "packageState");
			return this;
		}

		public Criteria andPackageStateNotLike(String value) {
			addCriterion("PACKAGE_STATE not like", value, "packageState");
			return this;
		}

		public Criteria andPackageStateIn(List values) {
			addCriterion("PACKAGE_STATE in", values, "packageState");
			return this;
		}

		public Criteria andPackageStateNotIn(List values) {
			addCriterion("PACKAGE_STATE not in", values, "packageState");
			return this;
		}

		public Criteria andPackageStateBetween(String value1, String value2) {
			addCriterion("PACKAGE_STATE between", value1, value2,
					"packageState");
			return this;
		}

		public Criteria andPackageStateNotBetween(String value1, String value2) {
			addCriterion("PACKAGE_STATE not between", value1, value2,
					"packageState");
			return this;
		}

		public Criteria andDetecthandleModeIsNull() {
			addCriterion("DETECTHANDLE_MODE is null");
			return this;
		}

		public Criteria andDetecthandleModeIsNotNull() {
			addCriterion("DETECTHANDLE_MODE is not null");
			return this;
		}

		public Criteria andDetecthandleModeEqualTo(Short value) {
			addCriterion("DETECTHANDLE_MODE =", value, "detecthandleMode");
			return this;
		}

		public Criteria andDetecthandleModeNotEqualTo(Short value) {
			addCriterion("DETECTHANDLE_MODE <>", value, "detecthandleMode");
			return this;
		}

		public Criteria andDetecthandleModeGreaterThan(Short value) {
			addCriterion("DETECTHANDLE_MODE >", value, "detecthandleMode");
			return this;
		}

		public Criteria andDetecthandleModeGreaterThanOrEqualTo(Short value) {
			addCriterion("DETECTHANDLE_MODE >=", value, "detecthandleMode");
			return this;
		}

		public Criteria andDetecthandleModeLessThan(Short value) {
			addCriterion("DETECTHANDLE_MODE <", value, "detecthandleMode");
			return this;
		}

		public Criteria andDetecthandleModeLessThanOrEqualTo(Short value) {
			addCriterion("DETECTHANDLE_MODE <=", value, "detecthandleMode");
			return this;
		}

		public Criteria andDetecthandleModeIn(List values) {
			addCriterion("DETECTHANDLE_MODE in", values, "detecthandleMode");
			return this;
		}

		public Criteria andDetecthandleModeNotIn(List values) {
			addCriterion("DETECTHANDLE_MODE not in", values, "detecthandleMode");
			return this;
		}

		public Criteria andDetecthandleModeBetween(Short value1, Short value2) {
			addCriterion("DETECTHANDLE_MODE between", value1, value2,
					"detecthandleMode");
			return this;
		}

		public Criteria andDetecthandleModeNotBetween(Short value1, Short value2) {
			addCriterion("DETECTHANDLE_MODE not between", value1, value2,
					"detecthandleMode");
			return this;
		}

		public Criteria andDetectisFaultIsNull() {
			addCriterion("DETECTIS_FAULT is null");
			return this;
		}

		public Criteria andDetectisFaultIsNotNull() {
			addCriterion("DETECTIS_FAULT is not null");
			return this;
		}

		public Criteria andDetectisFaultEqualTo(String value) {
			addCriterion("DETECTIS_FAULT =", value, "detectisFault");
			return this;
		}

		public Criteria andDetectisFaultNotEqualTo(String value) {
			addCriterion("DETECTIS_FAULT <>", value, "detectisFault");
			return this;
		}

		public Criteria andDetectisFaultGreaterThan(String value) {
			addCriterion("DETECTIS_FAULT >", value, "detectisFault");
			return this;
		}

		public Criteria andDetectisFaultGreaterThanOrEqualTo(String value) {
			addCriterion("DETECTIS_FAULT >=", value, "detectisFault");
			return this;
		}

		public Criteria andDetectisFaultLessThan(String value) {
			addCriterion("DETECTIS_FAULT <", value, "detectisFault");
			return this;
		}

		public Criteria andDetectisFaultLessThanOrEqualTo(String value) {
			addCriterion("DETECTIS_FAULT <=", value, "detectisFault");
			return this;
		}

		public Criteria andDetectisFaultLike(String value) {
			addCriterion("DETECTIS_FAULT like", value, "detectisFault");
			return this;
		}

		public Criteria andDetectisFaultNotLike(String value) {
			addCriterion("DETECTIS_FAULT not like", value, "detectisFault");
			return this;
		}

		public Criteria andDetectisFaultIn(List values) {
			addCriterion("DETECTIS_FAULT in", values, "detectisFault");
			return this;
		}

		public Criteria andDetectisFaultNotIn(List values) {
			addCriterion("DETECTIS_FAULT not in", values, "detectisFault");
			return this;
		}

		public Criteria andDetectisFaultBetween(String value1, String value2) {
			addCriterion("DETECTIS_FAULT between", value1, value2,
					"detectisFault");
			return this;
		}

		public Criteria andDetectisFaultNotBetween(String value1, String value2) {
			addCriterion("DETECTIS_FAULT not between", value1, value2,
					"detectisFault");
			return this;
		}

		public Criteria andFaultIspeopleIsNull() {
			addCriterion("FAULT_ISPEOPLE is null");
			return this;
		}

		public Criteria andFaultIspeopleIsNotNull() {
			addCriterion("FAULT_ISPEOPLE is not null");
			return this;
		}

		public Criteria andFaultIspeopleEqualTo(String value) {
			addCriterion("FAULT_ISPEOPLE =", value, "faultIspeople");
			return this;
		}

		public Criteria andFaultIspeopleNotEqualTo(String value) {
			addCriterion("FAULT_ISPEOPLE <>", value, "faultIspeople");
			return this;
		}

		public Criteria andFaultIspeopleGreaterThan(String value) {
			addCriterion("FAULT_ISPEOPLE >", value, "faultIspeople");
			return this;
		}

		public Criteria andFaultIspeopleGreaterThanOrEqualTo(String value) {
			addCriterion("FAULT_ISPEOPLE >=", value, "faultIspeople");
			return this;
		}

		public Criteria andFaultIspeopleLessThan(String value) {
			addCriterion("FAULT_ISPEOPLE <", value, "faultIspeople");
			return this;
		}

		public Criteria andFaultIspeopleLessThanOrEqualTo(String value) {
			addCriterion("FAULT_ISPEOPLE <=", value, "faultIspeople");
			return this;
		}

		public Criteria andFaultIspeopleLike(String value) {
			addCriterion("FAULT_ISPEOPLE like", value, "faultIspeople");
			return this;
		}

		public Criteria andFaultIspeopleNotLike(String value) {
			addCriterion("FAULT_ISPEOPLE not like", value, "faultIspeople");
			return this;
		}

		public Criteria andFaultIspeopleIn(List values) {
			addCriterion("FAULT_ISPEOPLE in", values, "faultIspeople");
			return this;
		}

		public Criteria andFaultIspeopleNotIn(List values) {
			addCriterion("FAULT_ISPEOPLE not in", values, "faultIspeople");
			return this;
		}

		public Criteria andFaultIspeopleBetween(String value1, String value2) {
			addCriterion("FAULT_ISPEOPLE between", value1, value2,
					"faultIspeople");
			return this;
		}

		public Criteria andFaultIspeopleNotBetween(String value1, String value2) {
			addCriterion("FAULT_ISPEOPLE not between", value1, value2,
					"faultIspeople");
			return this;
		}

		public Criteria andDetectResultIsNull() {
			addCriterion("DETECT_RESULT is null");
			return this;
		}

		public Criteria andDetectResultIsNotNull() {
			addCriterion("DETECT_RESULT is not null");
			return this;
		}

		public Criteria andDetectResultEqualTo(String value) {
			addCriterion("DETECT_RESULT =", value, "detectResult");
			return this;
		}

		public Criteria andDetectResultNotEqualTo(String value) {
			addCriterion("DETECT_RESULT <>", value, "detectResult");
			return this;
		}

		public Criteria andDetectResultGreaterThan(String value) {
			addCriterion("DETECT_RESULT >", value, "detectResult");
			return this;
		}

		public Criteria andDetectResultGreaterThanOrEqualTo(String value) {
			addCriterion("DETECT_RESULT >=", value, "detectResult");
			return this;
		}

		public Criteria andDetectResultLessThan(String value) {
			addCriterion("DETECT_RESULT <", value, "detectResult");
			return this;
		}

		public Criteria andDetectResultLessThanOrEqualTo(String value) {
			addCriterion("DETECT_RESULT <=", value, "detectResult");
			return this;
		}

		public Criteria andDetectResultLike(String value) {
			addCriterion("DETECT_RESULT like", value, "detectResult");
			return this;
		}

		public Criteria andDetectResultNotLike(String value) {
			addCriterion("DETECT_RESULT not like", value, "detectResult");
			return this;
		}

		public Criteria andDetectResultIn(List values) {
			addCriterion("DETECT_RESULT in", values, "detectResult");
			return this;
		}

		public Criteria andDetectResultNotIn(List values) {
			addCriterion("DETECT_RESULT not in", values, "detectResult");
			return this;
		}

		public Criteria andDetectResultBetween(String value1, String value2) {
			addCriterion("DETECT_RESULT between", value1, value2,
					"detectResult");
			return this;
		}

		public Criteria andDetectResultNotBetween(String value1, String value2) {
			addCriterion("DETECT_RESULT not between", value1, value2,
					"detectResult");
			return this;
		}

		public Criteria andMaintenanceCostIsNull() {
			addCriterion("MAINTENANCE_COST is null");
			return this;
		}

		public Criteria andMaintenanceCostIsNotNull() {
			addCriterion("MAINTENANCE_COST is not null");
			return this;
		}

		public Criteria andMaintenanceCostEqualTo(BigDecimal value) {
			addCriterion("MAINTENANCE_COST =", value, "maintenanceCost");
			return this;
		}

		public Criteria andMaintenanceCostNotEqualTo(BigDecimal value) {
			addCriterion("MAINTENANCE_COST <>", value, "maintenanceCost");
			return this;
		}

		public Criteria andMaintenanceCostGreaterThan(BigDecimal value) {
			addCriterion("MAINTENANCE_COST >", value, "maintenanceCost");
			return this;
		}

		public Criteria andMaintenanceCostGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("MAINTENANCE_COST >=", value, "maintenanceCost");
			return this;
		}

		public Criteria andMaintenanceCostLessThan(BigDecimal value) {
			addCriterion("MAINTENANCE_COST <", value, "maintenanceCost");
			return this;
		}

		public Criteria andMaintenanceCostLessThanOrEqualTo(BigDecimal value) {
			addCriterion("MAINTENANCE_COST <=", value, "maintenanceCost");
			return this;
		}

		public Criteria andMaintenanceCostIn(List values) {
			addCriterion("MAINTENANCE_COST in", values, "maintenanceCost");
			return this;
		}

		public Criteria andMaintenanceCostNotIn(List values) {
			addCriterion("MAINTENANCE_COST not in", values, "maintenanceCost");
			return this;
		}

		public Criteria andMaintenanceCostBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("MAINTENANCE_COST between", value1, value2,
					"maintenanceCost");
			return this;
		}

		public Criteria andMaintenanceCostNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("MAINTENANCE_COST not between", value1, value2,
					"maintenanceCost");
			return this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return this;
		}

		public Criteria andStatusIn(List values) {
			addCriterion("STATUS in", values, "status");
			return this;
		}

		public Criteria andStatusNotIn(List values) {
			addCriterion("STATUS not in", values, "status");
			return this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return this;
		}

		public Criteria andHandleResultIsNull() {
			addCriterion("HANDLE_RESULT is null");
			return this;
		}

		public Criteria andHandleResultIsNotNull() {
			addCriterion("HANDLE_RESULT is not null");
			return this;
		}

		public Criteria andHandleResultEqualTo(String value) {
			addCriterion("HANDLE_RESULT =", value, "handleResult");
			return this;
		}

		public Criteria andHandleResultNotEqualTo(String value) {
			addCriterion("HANDLE_RESULT <>", value, "handleResult");
			return this;
		}

		public Criteria andHandleResultGreaterThan(String value) {
			addCriterion("HANDLE_RESULT >", value, "handleResult");
			return this;
		}

		public Criteria andHandleResultGreaterThanOrEqualTo(String value) {
			addCriterion("HANDLE_RESULT >=", value, "handleResult");
			return this;
		}

		public Criteria andHandleResultLessThan(String value) {
			addCriterion("HANDLE_RESULT <", value, "handleResult");
			return this;
		}

		public Criteria andHandleResultLessThanOrEqualTo(String value) {
			addCriterion("HANDLE_RESULT <=", value, "handleResult");
			return this;
		}

		public Criteria andHandleResultLike(String value) {
			addCriterion("HANDLE_RESULT like", value, "handleResult");
			return this;
		}

		public Criteria andHandleResultNotLike(String value) {
			addCriterion("HANDLE_RESULT not like", value, "handleResult");
			return this;
		}

		public Criteria andHandleResultIn(List values) {
			addCriterion("HANDLE_RESULT in", values, "handleResult");
			return this;
		}

		public Criteria andHandleResultNotIn(List values) {
			addCriterion("HANDLE_RESULT not in", values, "handleResult");
			return this;
		}

		public Criteria andHandleResultBetween(String value1, String value2) {
			addCriterion("HANDLE_RESULT between", value1, value2,
					"handleResult");
			return this;
		}

		public Criteria andHandleResultNotBetween(String value1, String value2) {
			addCriterion("HANDLE_RESULT not between", value1, value2,
					"handleResult");
			return this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("REMARK is null");
			return this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("REMARK is not null");
			return this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("REMARK =", value, "remark");
			return this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("REMARK <>", value, "remark");
			return this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("REMARK >", value, "remark");
			return this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("REMARK >=", value, "remark");
			return this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("REMARK <", value, "remark");
			return this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("REMARK <=", value, "remark");
			return this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("REMARK like", value, "remark");
			return this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("REMARK not like", value, "remark");
			return this;
		}

		public Criteria andRemarkIn(List values) {
			addCriterion("REMARK in", values, "remark");
			return this;
		}

		public Criteria andRemarkNotIn(List values) {
			addCriterion("REMARK not in", values, "remark");
			return this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("REMARK between", value1, value2, "remark");
			return this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("REMARK not between", value1, value2, "remark");
			return this;
		}

		public Criteria andSpc1IsNull() {
			addCriterion("SPC_1 is null");
			return this;
		}

		public Criteria andSpc1IsNotNull() {
			addCriterion("SPC_1 is not null");
			return this;
		}

		public Criteria andSpc1EqualTo(String value) {
			addCriterion("SPC_1 =", value, "spc1");
			return this;
		}

		public Criteria andSpc1NotEqualTo(String value) {
			addCriterion("SPC_1 <>", value, "spc1");
			return this;
		}

		public Criteria andSpc1GreaterThan(String value) {
			addCriterion("SPC_1 >", value, "spc1");
			return this;
		}

		public Criteria andSpc1GreaterThanOrEqualTo(String value) {
			addCriterion("SPC_1 >=", value, "spc1");
			return this;
		}

		public Criteria andSpc1LessThan(String value) {
			addCriterion("SPC_1 <", value, "spc1");
			return this;
		}

		public Criteria andSpc1LessThanOrEqualTo(String value) {
			addCriterion("SPC_1 <=", value, "spc1");
			return this;
		}

		public Criteria andSpc1Like(String value) {
			addCriterion("SPC_1 like", value, "spc1");
			return this;
		}

		public Criteria andSpc1NotLike(String value) {
			addCriterion("SPC_1 not like", value, "spc1");
			return this;
		}

		public Criteria andSpc1In(List values) {
			addCriterion("SPC_1 in", values, "spc1");
			return this;
		}

		public Criteria andSpc1NotIn(List values) {
			addCriterion("SPC_1 not in", values, "spc1");
			return this;
		}

		public Criteria andSpc1Between(String value1, String value2) {
			addCriterion("SPC_1 between", value1, value2, "spc1");
			return this;
		}

		public Criteria andSpc1NotBetween(String value1, String value2) {
			addCriterion("SPC_1 not between", value1, value2, "spc1");
			return this;
		}

		public Criteria andSpc2IsNull() {
			addCriterion("SPC_2 is null");
			return this;
		}

		public Criteria andSpc2IsNotNull() {
			addCriterion("SPC_2 is not null");
			return this;
		}

		public Criteria andSpc2EqualTo(String value) {
			addCriterion("SPC_2 =", value, "spc2");
			return this;
		}

		public Criteria andSpc2NotEqualTo(String value) {
			addCriterion("SPC_2 <>", value, "spc2");
			return this;
		}

		public Criteria andSpc2GreaterThan(String value) {
			addCriterion("SPC_2 >", value, "spc2");
			return this;
		}

		public Criteria andSpc2GreaterThanOrEqualTo(String value) {
			addCriterion("SPC_2 >=", value, "spc2");
			return this;
		}

		public Criteria andSpc2LessThan(String value) {
			addCriterion("SPC_2 <", value, "spc2");
			return this;
		}

		public Criteria andSpc2LessThanOrEqualTo(String value) {
			addCriterion("SPC_2 <=", value, "spc2");
			return this;
		}

		public Criteria andSpc2Like(String value) {
			addCriterion("SPC_2 like", value, "spc2");
			return this;
		}

		public Criteria andSpc2NotLike(String value) {
			addCriterion("SPC_2 not like", value, "spc2");
			return this;
		}

		public Criteria andSpc2In(List values) {
			addCriterion("SPC_2 in", values, "spc2");
			return this;
		}

		public Criteria andSpc2NotIn(List values) {
			addCriterion("SPC_2 not in", values, "spc2");
			return this;
		}

		public Criteria andSpc2Between(String value1, String value2) {
			addCriterion("SPC_2 between", value1, value2, "spc2");
			return this;
		}

		public Criteria andSpc2NotBetween(String value1, String value2) {
			addCriterion("SPC_2 not between", value1, value2, "spc2");
			return this;
		}

		public Criteria andSpc3IsNull() {
			addCriterion("SPC_3 is null");
			return this;
		}

		public Criteria andSpc3IsNotNull() {
			addCriterion("SPC_3 is not null");
			return this;
		}

		public Criteria andSpc3EqualTo(String value) {
			addCriterion("SPC_3 =", value, "spc3");
			return this;
		}

		public Criteria andSpc3NotEqualTo(String value) {
			addCriterion("SPC_3 <>", value, "spc3");
			return this;
		}

		public Criteria andSpc3GreaterThan(String value) {
			addCriterion("SPC_3 >", value, "spc3");
			return this;
		}

		public Criteria andSpc3GreaterThanOrEqualTo(String value) {
			addCriterion("SPC_3 >=", value, "spc3");
			return this;
		}

		public Criteria andSpc3LessThan(String value) {
			addCriterion("SPC_3 <", value, "spc3");
			return this;
		}

		public Criteria andSpc3LessThanOrEqualTo(String value) {
			addCriterion("SPC_3 <=", value, "spc3");
			return this;
		}

		public Criteria andSpc3Like(String value) {
			addCriterion("SPC_3 like", value, "spc3");
			return this;
		}

		public Criteria andSpc3NotLike(String value) {
			addCriterion("SPC_3 not like", value, "spc3");
			return this;
		}

		public Criteria andSpc3In(List values) {
			addCriterion("SPC_3 in", values, "spc3");
			return this;
		}

		public Criteria andSpc3NotIn(List values) {
			addCriterion("SPC_3 not in", values, "spc3");
			return this;
		}

		public Criteria andSpc3Between(String value1, String value2) {
			addCriterion("SPC_3 between", value1, value2, "spc3");
			return this;
		}

		public Criteria andSpc3NotBetween(String value1, String value2) {
			addCriterion("SPC_3 not between", value1, value2, "spc3");
			return this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_TIME =", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_TIME <>", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("CREATE_TIME >", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_TIME >=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterionForJDBCDate("CREATE_TIME <", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATE_TIME <=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeIn(List values) {
			addCriterionForJDBCDate("CREATE_TIME in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotIn(List values) {
			addCriterionForJDBCDate("CREATE_TIME not in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_TIME between", value1, value2,
					"createTime");
			return this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATE_TIME not between", value1, value2,
					"createTime");
			return this;
		}
		
		public Criteria andWarehouseIdIsNull() {
            addCriterion("WAREHOUSE_ID is null");
            return this;
        }

        public Criteria andWarehouseIdIsNotNull() {
            addCriterion("WAREHOUSE_ID is not null");
            return this;
        }

        public Criteria andWarehouseIdEqualTo(Long value) {
            addCriterion("WAREHOUSE_ID =", value, "warehouseId");
            return this;
        }

        public Criteria andWarehouseIdNotEqualTo(Long value) {
            addCriterion("WAREHOUSE_ID <>", value, "warehouseId");
            return this;
        }

        public Criteria andWarehouseIdGreaterThan(Long value) {
            addCriterion("WAREHOUSE_ID >", value, "warehouseId");
            return this;
        }

        public Criteria andWarehouseIdGreaterThanOrEqualTo(Long value) {
            addCriterion("WAREHOUSE_ID >=", value, "warehouseId");
            return this;
        }

        public Criteria andWarehouseIdLessThan(Long value) {
            addCriterion("WAREHOUSE_ID <", value, "warehouseId");
            return this;
        }

        public Criteria andWarehouseIdLessThanOrEqualTo(Long value) {
            addCriterion("WAREHOUSE_ID <=", value, "warehouseId");
            return this;
        }

        public Criteria andWarehouseIdIn(List values) {
            addCriterion("WAREHOUSE_ID in", values, "warehouseId");
            return this;
        }

        public Criteria andWarehouseIdNotIn(List values) {
            addCriterion("WAREHOUSE_ID not in", values, "warehouseId");
            return this;
        }

        public Criteria andWarehouseIdBetween(Long value1, Long value2) {
            addCriterion("WAREHOUSE_ID between", value1, value2, "warehouseId");
            return this;
        }

        public Criteria andWarehouseIdNotBetween(Long value1, Long value2) {
            addCriterion("WAREHOUSE_ID not between", value1, value2, "warehouseId");
            return this;
        }
        
        public Criteria andShipAddressIsNull() {
			addCriterion("SHIP_ADDRESS is null");
			return this;
		}

		public Criteria andShipAddressIsNotNull() {
			addCriterion("SHIP_ADDRESS is not null");
			return this;
		}

		public Criteria andShipAddressEqualTo(String value) {
			addCriterion("SHIP_ADDRESS =", value, "shipAddress");
			return this;
		}

		public Criteria andShipAddressNotEqualTo(String value) {
			addCriterion("SHIP_ADDRESS <>", value, "shipAddress");
			return this;
		}

		public Criteria andShipAddressGreaterThan(String value) {
			addCriterion("SHIP_ADDRESS >", value, "shipAddress");
			return this;
		}

		public Criteria andShipAddressGreaterThanOrEqualTo(String value) {
			addCriterion("SHIP_ADDRESS >=", value, "shipAddress");
			return this;
		}

		public Criteria andShipAddressLessThan(String value) {
			addCriterion("SHIP_ADDRESS <", value, "shipAddress");
			return this;
		}

		public Criteria andShipAddressLessThanOrEqualTo(String value) {
			addCriterion("SHIP_ADDRESS <=", value, "shipAddress");
			return this;
		}

		public Criteria andShipAddressLike(String value) {
			addCriterion("SHIP_ADDRESS like", value, "shipAddress");
			return this;
		}

		public Criteria andShipAddressNotLike(String value) {
			addCriterion("SHIP_ADDRESS not like", value, "shipAddress");
			return this;
		}

		public Criteria andShipAddressIn(List values) {
			addCriterion("SHIP_ADDRESS in", values, "shipAddress");
			return this;
		}

		public Criteria andShipAddressNotIn(List values) {
			addCriterion("SHIP_ADDRESS not in", values, "shipAddress");
			return this;
		}

		public Criteria andShipAddressBetween(String value1, String value2) {
			addCriterion("SHIP_ADDRESS between", value1, value2, "shipAddress");
			return this;
		}

		public Criteria andShipAddressNotBetween(String value1, String value2) {
			addCriterion("SHIP_ADDRESS not between", value1, value2, "shipAddress");
			return this;
		}
		
		public Criteria andLinkPhoneIsNull() {
			addCriterion("LINK_PHONE is null");
			return this;
		}

		public Criteria andLinkPhoneIsNotNull() {
			addCriterion("LINK_PHONE is not null");
			return this;
		}

		public Criteria andLinkPhoneEqualTo(String value) {
			addCriterion("LINK_PHONE =", value, "linkPhone");
			return this;
		}

		public Criteria andLinkPhoneNotEqualTo(String value) {
			addCriterion("LINK_PHONE <>", value, "linkPhone");
			return this;
		}

		public Criteria andLinkPhoneGreaterThan(String value) {
			addCriterion("LINK_PHONE >", value, "linkPhone");
			return this;
		}

		public Criteria andLinkPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("LINK_PHONE >=", value, "linkPhone");
			return this;
		}

		public Criteria andLinkPhoneLessThan(String value) {
			addCriterion("LINK_PHONE <", value, "linkPhone");
			return this;
		}

		public Criteria andLinkPhoneLessThanOrEqualTo(String value) {
			addCriterion("LINK_PHONE <=", value, "linkPhone");
			return this;
		}

		public Criteria andLinkPhoneLike(String value) {
			addCriterion("LINK_PHONE like", value, "linkPhone");
			return this;
		}

		public Criteria andLinkPhoneNotLike(String value) {
			addCriterion("LINK_PHONE not like", value, "linkPhone");
			return this;
		}

		public Criteria andLinkPhoneIn(List values) {
			addCriterion("LINK_PHONE in", values, "linkPhone");
			return this;
		}

		public Criteria andLinkPhoneNotIn(List values) {
			addCriterion("LINK_PHONE not in", values, "linkPhone");
			return this;
		}

		public Criteria andLinkPhoneBetween(String value1, String value2) {
			addCriterion("LINK_PHONE between", value1, value2, "linkPhone");
			return this;
		}

		public Criteria andLinkPhoneNotBetween(String value1, String value2) {
			addCriterion("LINK_PHONE not between", value1, value2, "linkPhone");
			return this;
		}
		
		
		public Criteria andUnitPriceIsNull() {
			addCriterion("UNIT_PRICE is null");
			return this;
		}

		public Criteria andUnitPriceIsNotNull() {
			addCriterion("UNIT_PRICE is not null");
			return this;
		}

		public Criteria andUnitPriceEqualTo(BigDecimal value) {
			addCriterion("UNIT_PRICE =", value, "unitPrice");
			return this;
		}

		public Criteria andUnitPriceNotEqualTo(BigDecimal value) {
			addCriterion("UNIT_PRICE <>", value, "unitPrice");
			return this;
		}

		public Criteria andUnitPriceGreaterThan(BigDecimal value) {
			addCriterion("UNIT_PRICE >", value, "unitPrice");
			return this;
		}

		public Criteria andUnitPriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("UNIT_PRICE >=", value, "unitPrice");
			return this;
		}

		public Criteria andUnitPriceLessThan(BigDecimal value) {
			addCriterion("UNIT_PRICE <", value, "unitPrice");
			return this;
		}

		public Criteria andUnitPriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("UNIT_PRICE <=", value, "unitPrice");
			return this;
		}

		public Criteria andUnitPriceIn(List values) {
			addCriterion("UNIT_PRICE in", values, "unitPrice");
			return this;
		}

		public Criteria andUnitPriceNotIn(List values) {
			addCriterion("UNIT_PRICE not in", values, "unitPrice");
			return this;
		}

		public Criteria andUnitPriceBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("UNIT_PRICE between", value1, value2,
					"unitPrice");
			return this;
		}

		public Criteria andUnitPriceNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("UNIT_PRICE not between", value1, value2,
					"unitPrice");
			return this;
		}
		
		
		
		public Criteria andTotalPriceIsNull() {
			addCriterion("TOTAL_PRICE is null");
			return this;
		}

		public Criteria andTotalPriceIsNotNull() {
			addCriterion("TOTAL_PRICE is not null");
			return this;
		}

		public Criteria andTotalPriceEqualTo(BigDecimal value) {
			addCriterion("TOTAL_PRICE =", value, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceNotEqualTo(BigDecimal value) {
			addCriterion("TOTAL_PRICE <>", value, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceGreaterThan(BigDecimal value) {
			addCriterion("TOTAL_PRICE >", value, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("TOTAL_PRICE >=", value, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceLessThan(BigDecimal value) {
			addCriterion("TOTAL_PRICE <", value, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("TOTAL_PRICE <=", value, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceIn(List values) {
			addCriterion("TOTAL_PRICE in", values, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceNotIn(List values) {
			addCriterion("TOTAL_PRICE not in", values, "totalPrice");
			return this;
		}

		public Criteria andTotalPriceBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("TOTAL_PRICE between", value1, value2,
					"totalPrice");
			return this;
		}

		public Criteria andTotalPriceNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("TOTAL_PRICE not between", value1, value2,
					"totalPrice");
			return this;
		}
	}
}