package com.pltfm.app.dao.impl;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.pltfm.app.dao.OperationHistoryInfoDAO;
import com.pltfm.app.vobject.OperationHistoryInfo;
import com.pltfm.app.vobject.OperationHistoryInfoExample;

public class OperationHistoryInfoDAOImpl implements OperationHistoryInfoDAO {
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database table
   * OPERATION_HISTORY_INFO
   *
   * @ibatorgenerated Fri Jul 12 09:09:31 CST 2013
   */
  private SqlMapClient sqlMapClient;

  public SqlMapClient getSqlMapClient() {
    return sqlMapClient;
  }

  public void setSqlMapClient(SqlMapClient sqlMapClient) {
    this.sqlMapClient = sqlMapClient;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OPERATION_HISTORY_INFO
   *
   * @ibatorgenerated Fri Jul 12 09:09:31 CST 2013
   */
  public int countByExample(OperationHistoryInfoExample example) throws SQLException {
    Integer count = (Integer) sqlMapClient
        .queryForObject("OPERATION_HISTORY_INFO.ibatorgenerated_countByExample", example);
    return count.intValue();
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OPERATION_HISTORY_INFO
   *
   * @ibatorgenerated Fri Jul 12 09:09:31 CST 2013
   */
  public int deleteByExample(OperationHistoryInfoExample example) throws SQLException {
    int rows =
        sqlMapClient.delete("OPERATION_HISTORY_INFO.ibatorgenerated_deleteByExample", example);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OPERATION_HISTORY_INFO
   *
   * @ibatorgenerated Fri Jul 12 09:09:31 CST 2013
   */
  public int deleteByPrimaryKey(Integer nOperationHistoryId) throws SQLException {
    OperationHistoryInfo key = new OperationHistoryInfo();
    key.setnOperationHistoryId(nOperationHistoryId);
    int rows =
        sqlMapClient.delete("OPERATION_HISTORY_INFO.ibatorgenerated_deleteByPrimaryKey", key);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OPERATION_HISTORY_INFO
   *
   * @ibatorgenerated Fri Jul 12 09:09:31 CST 2013
   */
  public void insert(OperationHistoryInfo record) throws SQLException {
    sqlMapClient.insert("OPERATION_HISTORY_INFO.ibatorgenerated_insert", record);
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OPERATION_HISTORY_INFO
   *
   * @ibatorgenerated Fri Jul 12 09:09:31 CST 2013
   */
  public void insertSelective(OperationHistoryInfo record) throws SQLException {
    sqlMapClient.insert("OPERATION_HISTORY_INFO.ibatorgenerated_insertSelective", record);
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OPERATION_HISTORY_INFO
   *
   * @ibatorgenerated Fri Jul 12 09:09:31 CST 2013
   */
  public List selectByExample(OperationHistoryInfoExample example) throws SQLException {
    List list = sqlMapClient.queryForList("OPERATION_HISTORY_INFO.ibatorgenerated_selectByExample",
        example);
    return list;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OPERATION_HISTORY_INFO
   *
   * @ibatorgenerated Fri Jul 12 09:09:31 CST 2013
   */
  public OperationHistoryInfo selectByPrimaryKey(Integer nOperationHistoryId) throws SQLException {
    OperationHistoryInfo key = new OperationHistoryInfo();
    key.setnOperationHistoryId(nOperationHistoryId);
    OperationHistoryInfo record = (OperationHistoryInfo) sqlMapClient
        .queryForObject("OPERATION_HISTORY_INFO.ibatorgenerated_selectByPrimaryKey", key);
    return record;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OPERATION_HISTORY_INFO
   *
   * @ibatorgenerated Fri Jul 12 09:09:31 CST 2013
   */
  public int updateByExampleSelective(OperationHistoryInfo record,
      OperationHistoryInfoExample example) throws SQLException {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows = sqlMapClient
        .update("OPERATION_HISTORY_INFO.ibatorgenerated_updateByExampleSelective", parms);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OPERATION_HISTORY_INFO
   *
   * @ibatorgenerated Fri Jul 12 09:09:31 CST 2013
   */
  public int updateByExample(OperationHistoryInfo record, OperationHistoryInfoExample example)
      throws SQLException {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows = sqlMapClient.update("OPERATION_HISTORY_INFO.ibatorgenerated_updateByExample", parms);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OPERATION_HISTORY_INFO
   *
   * @ibatorgenerated Fri Jul 12 09:09:31 CST 2013
   */
  public int updateByPrimaryKeySelective(OperationHistoryInfo record) throws SQLException {
    int rows = sqlMapClient
        .update("OPERATION_HISTORY_INFO.ibatorgenerated_updateByPrimaryKeySelective", record);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OPERATION_HISTORY_INFO
   *
   * @ibatorgenerated Fri Jul 12 09:09:31 CST 2013
   */
  public int updateByPrimaryKey(OperationHistoryInfo record) throws SQLException {
    int rows =
        sqlMapClient.update("OPERATION_HISTORY_INFO.ibatorgenerated_updateByPrimaryKey", record);
    return rows;
  }

  /**
   * This class was generated by Apache iBATIS ibator. This class corresponds to the database table
   * OPERATION_HISTORY_INFO
   *
   * @ibatorgenerated Fri Jul 12 09:09:31 CST 2013
   */
  private static class UpdateByExampleParms extends OperationHistoryInfoExample {
    private Object record;

    public UpdateByExampleParms(Object record, OperationHistoryInfoExample example) {
      super(example);
      this.record = record;
    }

    public Object getRecord() {
      return record;
    }
  }
}
