package com.pltfm.app.dao.impl;

import java.sql.SQLException;
import java.util.List;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.pltfm.app.dao.OxygenMeasureInfoDAO;
import com.pltfm.app.vobject.OxygenMeasureInfo;
import com.pltfm.app.vobject.OxygenMeasureInfoExample;

public class OxygenMeasureInfoDAOImpl implements OxygenMeasureInfoDAO {
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database table
   * OXYGEN_MEASURE_INFO
   *
   * @ibatorgenerated Thu Jul 11 17:23:36 CST 2013
   */
  private SqlMapClient sqlMapClient;


  public SqlMapClient getSqlMapClient() {
    return sqlMapClient;
  }

  public void setSqlMapClient(SqlMapClient sqlMapClient) {
    this.sqlMapClient = sqlMapClient;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OXYGEN_MEASURE_INFO
   *
   * @ibatorgenerated Thu Jul 11 17:23:36 CST 2013
   */
  public int countByExample(OxygenMeasureInfoExample example) throws SQLException {
    Integer count = (Integer) sqlMapClient
        .queryForObject("OXYGEN_MEASURE_INFO.ibatorgenerated_countByExample", example);
    return count.intValue();
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OXYGEN_MEASURE_INFO
   *
   * @ibatorgenerated Thu Jul 11 17:23:36 CST 2013
   */
  public int deleteByExample(OxygenMeasureInfoExample example) throws SQLException {
    int rows = sqlMapClient.delete("OXYGEN_MEASURE_INFO.ibatorgenerated_deleteByExample", example);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OXYGEN_MEASURE_INFO
   *
   * @ibatorgenerated Thu Jul 11 17:23:36 CST 2013
   */
  public int deleteByPrimaryKey(Integer nOxygenMeasureId) throws SQLException {
    OxygenMeasureInfo key = new OxygenMeasureInfo();
    key.setnOxygenMeasureId(nOxygenMeasureId);
    int rows = sqlMapClient.delete("OXYGEN_MEASURE_INFO.ibatorgenerated_deleteByPrimaryKey", key);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OXYGEN_MEASURE_INFO
   *
   * @ibatorgenerated Thu Jul 11 17:23:36 CST 2013
   */
  public void insert(OxygenMeasureInfo record) throws SQLException {
    sqlMapClient.insert("OXYGEN_MEASURE_INFO.ibatorgenerated_insert", record);
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OXYGEN_MEASURE_INFO
   *
   * @ibatorgenerated Thu Jul 11 17:23:36 CST 2013
   */
  public void insertSelective(OxygenMeasureInfo record) throws SQLException {
    sqlMapClient.insert("OXYGEN_MEASURE_INFO.ibatorgenerated_insertSelective", record);
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OXYGEN_MEASURE_INFO
   *
   * @ibatorgenerated Thu Jul 11 17:23:36 CST 2013
   */
  public List selectByExample(OxygenMeasureInfoExample example) throws SQLException {
    List list =
        sqlMapClient.queryForList("OXYGEN_MEASURE_INFO.ibatorgenerated_selectByExample", example);
    return list;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OXYGEN_MEASURE_INFO
   *
   * @ibatorgenerated Thu Jul 11 17:23:36 CST 2013
   */
  public OxygenMeasureInfo selectByPrimaryKey(Integer nOxygenMeasureId) throws SQLException {
    OxygenMeasureInfo key = new OxygenMeasureInfo();
    key.setnOxygenMeasureId(nOxygenMeasureId);
    OxygenMeasureInfo record = (OxygenMeasureInfo) sqlMapClient
        .queryForObject("OXYGEN_MEASURE_INFO.ibatorgenerated_selectByPrimaryKey", key);
    return record;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OXYGEN_MEASURE_INFO
   *
   * @ibatorgenerated Thu Jul 11 17:23:36 CST 2013
   */
  public int updateByExampleSelective(OxygenMeasureInfo record, OxygenMeasureInfoExample example)
      throws SQLException {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows =
        sqlMapClient.update("OXYGEN_MEASURE_INFO.ibatorgenerated_updateByExampleSelective", parms);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OXYGEN_MEASURE_INFO
   *
   * @ibatorgenerated Thu Jul 11 17:23:36 CST 2013
   */
  public int updateByExample(OxygenMeasureInfo record, OxygenMeasureInfoExample example)
      throws SQLException {
    UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
    int rows = sqlMapClient.update("OXYGEN_MEASURE_INFO.ibatorgenerated_updateByExample", parms);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OXYGEN_MEASURE_INFO
   *
   * @ibatorgenerated Thu Jul 11 17:23:36 CST 2013
   */
  public int updateByPrimaryKeySelective(OxygenMeasureInfo record) throws SQLException {
    int rows = sqlMapClient
        .update("OXYGEN_MEASURE_INFO.ibatorgenerated_updateByPrimaryKeySelective", record);
    return rows;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table OXYGEN_MEASURE_INFO
   *
   * @ibatorgenerated Thu Jul 11 17:23:36 CST 2013
   */
  public int updateByPrimaryKey(OxygenMeasureInfo record) throws SQLException {
    int rows =
        sqlMapClient.update("OXYGEN_MEASURE_INFO.ibatorgenerated_updateByPrimaryKey", record);
    return rows;
  }

  /**
   * This class was generated by Apache iBATIS ibator. This class corresponds to the database table
   * OXYGEN_MEASURE_INFO
   *
   * @ibatorgenerated Thu Jul 11 17:23:36 CST 2013
   */
  private static class UpdateByExampleParms extends OxygenMeasureInfoExample {
    private Object record;

    public UpdateByExampleParms(Object record, OxygenMeasureInfoExample example) {
      super(example);
      this.record = record;
    }

    public Object getRecord() {
      return record;
    }
  }
}
