package com.kmzyc.promotion.app.dao;

import java.sql.SQLException;
import java.util.List;

import com.kmzyc.promotion.app.vobject.CategoryAttrValue;
import com.kmzyc.promotion.app.vobject.CategoryAttrValueExample;

@SuppressWarnings("unchecked")
public interface CategoryAttrValueDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table CATEGORY_ATTR_VALUE
	 * 
	 * @ibatorgenerated Thu Jul 25 17:31:28 CST 2013
	 */
	int countByExample(CategoryAttrValueExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table CATEGORY_ATTR_VALUE
	 * 
	 * @ibatorgenerated Thu Jul 25 17:31:28 CST 2013
	 */
	int deleteByExample(CategoryAttrValueExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table CATEGORY_ATTR_VALUE
	 * 
	 * @ibatorgenerated Thu Jul 25 17:31:28 CST 2013
	 */
	int deleteByPrimaryKey(Long categoryAttrValueId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table CATEGORY_ATTR_VALUE
	 * 
	 * @ibatorgenerated Thu Jul 25 17:31:28 CST 2013
	 */
	void insert(CategoryAttrValue record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table CATEGORY_ATTR_VALUE
	 * 
	 * @ibatorgenerated Thu Jul 25 17:31:28 CST 2013
	 */
	void insertSelective(CategoryAttrValue record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table CATEGORY_ATTR_VALUE
	 * 
	 * @ibatorgenerated Thu Jul 25 17:31:28 CST 2013
	 */
	List selectByExample(CategoryAttrValueExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table CATEGORY_ATTR_VALUE
	 * 
	 * @ibatorgenerated Thu Jul 25 17:31:28 CST 2013
	 */
	CategoryAttrValue selectByPrimaryKey(Long categoryAttrValueId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table CATEGORY_ATTR_VALUE
	 * 
	 * @ibatorgenerated Thu Jul 25 17:31:28 CST 2013
	 */
	int updateByExampleSelective(CategoryAttrValue record, CategoryAttrValueExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table CATEGORY_ATTR_VALUE
	 * 
	 * @ibatorgenerated Thu Jul 25 17:31:28 CST 2013
	 */
	int updateByExample(CategoryAttrValue record, CategoryAttrValueExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table CATEGORY_ATTR_VALUE
	 * 
	 * @ibatorgenerated Thu Jul 25 17:31:28 CST 2013
	 */
	int updateByPrimaryKeySelective(CategoryAttrValue record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table CATEGORY_ATTR_VALUE
	 * 
	 * @ibatorgenerated Thu Jul 25 17:31:28 CST 2013
	 */
	int updateByPrimaryKey(CategoryAttrValue record) throws SQLException;
}