package com.kmzyc.promotion.app.dao;

import java.sql.SQLException;
import java.util.List;

import com.kmzyc.promotion.app.vobject.ProductCertificate;
import com.kmzyc.promotion.app.vobject.ProductCertificateExample;

@SuppressWarnings("unchecked")
public interface ProductCertificateDAO {
	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_CERTIFICATE
	 * 
	 * @ibatorgenerated Wed Apr 09 15:13:38 CST 2014
	 */
	int countByExample(ProductCertificateExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_CERTIFICATE
	 * 
	 * @ibatorgenerated Wed Apr 09 15:13:38 CST 2014
	 */
	int deleteByExample(ProductCertificateExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_CERTIFICATE
	 * 
	 * @ibatorgenerated Wed Apr 09 15:13:38 CST 2014
	 */
	int deleteByPrimaryKey(Long pscId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_CERTIFICATE
	 * 
	 * @ibatorgenerated Wed Apr 09 15:13:38 CST 2014
	 */
	void insert(ProductCertificate record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_CERTIFICATE
	 * 
	 * @ibatorgenerated Wed Apr 09 15:13:38 CST 2014
	 */
	void insertSelective(ProductCertificate record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_CERTIFICATE
	 * 
	 * @ibatorgenerated Wed Apr 09 15:13:38 CST 2014
	 */
	List selectByExample(ProductCertificateExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_CERTIFICATE
	 * 
	 * @ibatorgenerated Wed Apr 09 15:13:38 CST 2014
	 */
	ProductCertificate selectByPrimaryKey(Long pscId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_CERTIFICATE
	 * 
	 * @ibatorgenerated Wed Apr 09 15:13:38 CST 2014
	 */
	int updateByExampleSelective(ProductCertificate record, ProductCertificateExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_CERTIFICATE
	 * 
	 * @ibatorgenerated Wed Apr 09 15:13:38 CST 2014
	 */
	int updateByExample(ProductCertificate record, ProductCertificateExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_CERTIFICATE
	 * 
	 * @ibatorgenerated Wed Apr 09 15:13:38 CST 2014
	 */
	int updateByPrimaryKeySelective(ProductCertificate record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_CERTIFICATE
	 * 
	 * @ibatorgenerated Wed Apr 09 15:13:38 CST 2014
	 */
	int updateByPrimaryKey(ProductCertificate record) throws SQLException;
}