package com.kmzyc.promotion.app.dao;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import com.kmzyc.promotion.app.vobject.ProductSkuQuantity;
import com.kmzyc.promotion.app.vobject.ProductSkuQuantityExample;

@SuppressWarnings("unchecked")
public interface ProductSkuQuantityDAO {
	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_SKU_QUANTITY
	 * 
	 * @ibatorgenerated Tue Nov 19 09:29:19 CST 2013
	 */
	int countByExample(ProductSkuQuantityExample example) throws SQLException;

	int countAll() throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_SKU_QUANTITY
	 * 
	 * @ibatorgenerated Tue Nov 19 09:29:19 CST 2013
	 */
	int deleteByExample(ProductSkuQuantityExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_SKU_QUANTITY
	 * 
	 * @ibatorgenerated Tue Nov 19 09:29:19 CST 2013
	 */
	int deleteByPrimaryKey(Long productSkuQuantityId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_SKU_QUANTITY
	 * 
	 * @ibatorgenerated Tue Nov 19 09:29:19 CST 2013
	 */
	void insert(ProductSkuQuantity record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_SKU_QUANTITY
	 * 
	 * @ibatorgenerated Tue Nov 19 09:29:19 CST 2013
	 */
	void insertSelective(ProductSkuQuantity record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_SKU_QUANTITY
	 * 
	 * @ibatorgenerated Tue Nov 19 09:29:19 CST 2013
	 */
	List selectByExample(ProductSkuQuantityExample example) throws SQLException;

	List selectByExample(ProductSkuQuantityExample example, int pageNo, int pageCount) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_SKU_QUANTITY
	 * 
	 * @ibatorgenerated Tue Nov 19 09:29:19 CST 2013
	 */
	ProductSkuQuantity selectByPrimaryKey(Long productSkuQuantityId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_SKU_QUANTITY
	 * 
	 * @ibatorgenerated Tue Nov 19 09:29:19 CST 2013
	 */
	int updateByExampleSelective(ProductSkuQuantity record, ProductSkuQuantityExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_SKU_QUANTITY
	 * 
	 * @ibatorgenerated Tue Nov 19 09:29:19 CST 2013
	 */
	int updateByExample(ProductSkuQuantity record, ProductSkuQuantityExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_SKU_QUANTITY
	 * 
	 * @ibatorgenerated Tue Nov 19 09:29:19 CST 2013
	 */
	int updateByPrimaryKeySelective(ProductSkuQuantity record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table PRODUCT_SKU_QUANTITY
	 * 
	 * @ibatorgenerated Tue Nov 19 09:29:19 CST 2013
	 */
	int updateByPrimaryKey(ProductSkuQuantity record) throws SQLException;

	int batchUpdateSaleQuantityBySkuCode(List<ProductSkuQuantity> quantityList) throws SQLException;

	int batchAddSaleQuantity(List<ProductSkuQuantity> quantityList) throws SQLException;

	// 查找最大的productQuantityId
	Long findMaxProductQuantityId() throws SQLException;

	public Map<Long, ProductSkuQuantity> getLastSaleSkuIdMap(List<Long> skuIdList) throws Exception;

}