package com.kmzyc.promotion.app.dao;

import java.sql.SQLException;
import java.util.List;

import com.kmzyc.commons.page.Page;
import com.kmzyc.promotion.app.vobject.PromotionRule;
import com.kmzyc.promotion.app.vobject.PromotionRuleExample;

@SuppressWarnings("unchecked")
public interface PromotionRuleDAO {
    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table PROMOTION_RULE
     * 
     * @ibatorgenerated Mon Aug 26 11:15:08 CST 2013
     */
    int countByExample(PromotionRuleExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table PROMOTION_RULE
     * 
     * @ibatorgenerated Mon Aug 26 11:15:08 CST 2013
     */
    int deleteByExample(PromotionRuleExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table PROMOTION_RULE
     * 
     * @ibatorgenerated Mon Aug 26 11:15:08 CST 2013
     */
    int deleteByPrimaryKey(Long promotionRuleId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table PROMOTION_RULE
     * 
     * @ibatorgenerated Mon Aug 26 11:15:08 CST 2013
     */
    Object insert(PromotionRule record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table PROMOTION_RULE
     * 
     * @ibatorgenerated Mon Aug 26 11:15:08 CST 2013
     */
    Object insertSelective(PromotionRule record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table PROMOTION_RULE
     * 
     * @ibatorgenerated Mon Aug 26 11:15:08 CST 2013
     */
    List selectByExample(PromotionRuleExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table PROMOTION_RULE
     * 
     * @ibatorgenerated Mon Aug 26 11:15:08 CST 2013
     */
    PromotionRule selectByPrimaryKey(Long promotionRuleId) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table PROMOTION_RULE
     * 
     * @ibatorgenerated Mon Aug 26 11:15:08 CST 2013
     */
    int updateByExampleSelective(PromotionRule record, PromotionRuleExample example)
            throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table PROMOTION_RULE
     * 
     * @ibatorgenerated Mon Aug 26 11:15:08 CST 2013
     */
    int updateByExample(PromotionRule record, PromotionRuleExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table PROMOTION_RULE
     * 
     * @ibatorgenerated Mon Aug 26 11:15:08 CST 2013
     */
    int updateByPrimaryKeySelective(PromotionRule record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database
     * table PROMOTION_RULE
     * 
     * @ibatorgenerated Mon Aug 26 11:15:08 CST 2013
     */
    int updateByPrimaryKey(PromotionRule record) throws SQLException;

    /**
     * 分页查询
     */
    Page selectPageByVo(Page page, PromotionRule record) throws SQLException;

    /**
     * 查询指定添加的数量
     * 
     * @param record
     * @return
     * @throws SQLException
     */
    public Integer selectCountByVo(PromotionRule record) throws SQLException;

    public Long getCouponId(Long ruleId) throws SQLException;

    public Long getIncreasePromotionRuleId();

}
