package com.kmzyc.promotion.app.dao;

import java.sql.SQLException;
import java.util.List;

import com.kmzyc.supplier.model.SuppliersCertificate;
import com.kmzyc.supplier.model.example.SuppliersCertificateExample;

@SuppressWarnings("unchecked")
public interface SuppliersCertificateDAO {
	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_CERTIFICATE
	 * 
	 * @ibatorgenerated Tue Jan 14 13:36:08 CST 2014
	 */
	int countByExample(SuppliersCertificateExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_CERTIFICATE
	 * 
	 * @ibatorgenerated Tue Jan 14 13:36:08 CST 2014
	 */
	int deleteByExample(SuppliersCertificateExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_CERTIFICATE
	 * 
	 * @ibatorgenerated Tue Jan 14 13:36:08 CST 2014
	 */
	int deleteByPrimaryKey(Long scId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_CERTIFICATE
	 * 
	 * @ibatorgenerated Tue Jan 14 13:36:08 CST 2014
	 */
	void insert(SuppliersCertificate record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_CERTIFICATE
	 * 
	 * @ibatorgenerated Tue Jan 14 13:36:08 CST 2014
	 */
	void insertSelective(SuppliersCertificate record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_CERTIFICATE
	 * 
	 * @ibatorgenerated Tue Jan 14 13:36:08 CST 2014
	 */
	List selectByExample(SuppliersCertificateExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_CERTIFICATE
	 * 
	 * @ibatorgenerated Tue Jan 14 13:36:08 CST 2014
	 */
	SuppliersCertificate selectByPrimaryKey(Long scId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_CERTIFICATE
	 * 
	 * @ibatorgenerated Tue Jan 14 13:36:08 CST 2014
	 */
	int updateByExampleSelective(SuppliersCertificate record, SuppliersCertificateExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_CERTIFICATE
	 * 
	 * @ibatorgenerated Tue Jan 14 13:36:08 CST 2014
	 */
	int updateByExample(SuppliersCertificate record, SuppliersCertificateExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_CERTIFICATE
	 * 
	 * @ibatorgenerated Tue Jan 14 13:36:08 CST 2014
	 */
	int updateByPrimaryKeySelective(SuppliersCertificate record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_CERTIFICATE
	 * 
	 * @ibatorgenerated Tue Jan 14 13:36:08 CST 2014
	 */
	int updateByPrimaryKey(SuppliersCertificate record) throws SQLException;

	List<SuppliersCertificate> selectSuppIdList(Long suppId) throws SQLException;

	int deleteBySuppId(Long suppId) throws SQLException;

	SuppliersCertificate selectSuppIdPath(String path) throws SQLException;
}