package com.kmzyc.promotion.app.dao;

import java.sql.SQLException;
import java.util.List;

import com.kmzyc.supplier.model.SuppliersWarehouse;
import com.kmzyc.supplier.model.example.SuppliersWarehouseExample;

@SuppressWarnings("unchecked")
public interface SuppliersWarehouseDAO {
	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_WAREHOUSE
	 * 
	 * @ibatorgenerated Mon Feb 10 14:19:34 CST 2014
	 */
	int countByExample(SuppliersWarehouseExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_WAREHOUSE
	 * 
	 * @ibatorgenerated Mon Feb 10 14:19:34 CST 2014
	 */
	int deleteByExample(SuppliersWarehouseExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_WAREHOUSE
	 * 
	 * @ibatorgenerated Mon Feb 10 14:19:34 CST 2014
	 */
	int deleteByPrimaryKey(Long supWarehouseId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_WAREHOUSE
	 * 
	 * @ibatorgenerated Mon Feb 10 14:19:34 CST 2014
	 */
	void insert(SuppliersWarehouse record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_WAREHOUSE
	 * 
	 * @ibatorgenerated Mon Feb 10 14:19:34 CST 2014
	 */
	void insertSelective(SuppliersWarehouse record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_WAREHOUSE
	 * 
	 * @ibatorgenerated Mon Feb 10 14:19:34 CST 2014
	 */
	List selectByExample(SuppliersWarehouseExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_WAREHOUSE
	 * 
	 * @ibatorgenerated Mon Feb 10 14:19:34 CST 2014
	 */
	SuppliersWarehouse selectByPrimaryKey(Long supWarehouseId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_WAREHOUSE
	 * 
	 * @ibatorgenerated Mon Feb 10 14:19:34 CST 2014
	 */
	int updateByExampleSelective(SuppliersWarehouse record, SuppliersWarehouseExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_WAREHOUSE
	 * 
	 * @ibatorgenerated Mon Feb 10 14:19:34 CST 2014
	 */
	int updateByExample(SuppliersWarehouse record, SuppliersWarehouseExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_WAREHOUSE
	 * 
	 * @ibatorgenerated Mon Feb 10 14:19:34 CST 2014
	 */
	int updateByPrimaryKeySelective(SuppliersWarehouse record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table SUPPLIERS_WAREHOUSE
	 * 
	 * @ibatorgenerated Mon Feb 10 14:19:34 CST 2014
	 */
	int updateByPrimaryKey(SuppliersWarehouse record) throws SQLException;

	List<SuppliersWarehouse> selectByPrimarySupplierId(Long supplierId) throws SQLException;
}