package com.pltfm.app.entities;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SuppressWarnings("unchecked")
public class OrderOutSideExtInfoExample implements Serializable {
  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database table
   * KMORDER.ORDER_OUT_SIDE_EXT_INFO
   * 
   * @ibatorgenerated Wed May 21 10:38:14 CST 2014
   */
  protected String orderByClause;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database table
   * KMORDER.ORDER_OUT_SIDE_EXT_INFO
   * 
   * @ibatorgenerated Wed May 21 10:38:14 CST 2014
   */
  protected List oredCriteria;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OUT_SIDE_EXT_INFO
   * 
   * @ibatorgenerated Wed May 21 10:38:14 CST 2014
   */
  public OrderOutSideExtInfoExample() {
    oredCriteria = new ArrayList();
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OUT_SIDE_EXT_INFO
   * 
   * @ibatorgenerated Wed May 21 10:38:14 CST 2014
   */
  protected OrderOutSideExtInfoExample(OrderOutSideExtInfoExample example) {
    this.orderByClause = example.orderByClause;
    this.oredCriteria = example.oredCriteria;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OUT_SIDE_EXT_INFO
   * 
   * @ibatorgenerated Wed May 21 10:38:14 CST 2014
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OUT_SIDE_EXT_INFO
   * 
   * @ibatorgenerated Wed May 21 10:38:14 CST 2014
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OUT_SIDE_EXT_INFO
   * 
   * @ibatorgenerated Wed May 21 10:38:14 CST 2014
   */
  public List getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OUT_SIDE_EXT_INFO
   * 
   * @ibatorgenerated Wed May 21 10:38:14 CST 2014
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OUT_SIDE_EXT_INFO
   * 
   * @ibatorgenerated Wed May 21 10:38:14 CST 2014
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OUT_SIDE_EXT_INFO
   * 
   * @ibatorgenerated Wed May 21 10:38:14 CST 2014
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_OUT_SIDE_EXT_INFO
   * 
   * @ibatorgenerated Wed May 21 10:38:14 CST 2014
   */
  public void clear() {
    oredCriteria.clear();
  }

  /**
   * This class was generated by Apache iBATIS ibator. This class corresponds to the database table
   * KMORDER.ORDER_OUT_SIDE_EXT_INFO
   * 
   * @ibatorgenerated Wed May 21 10:38:14 CST 2014
   */
  public static class Criteria {
    protected List criteriaWithoutValue;

    protected List criteriaWithSingleValue;

    protected List criteriaWithListValue;

    protected List criteriaWithBetweenValue;

    protected Criteria() {
      super();
      criteriaWithoutValue = new ArrayList();
      criteriaWithSingleValue = new ArrayList();
      criteriaWithListValue = new ArrayList();
      criteriaWithBetweenValue = new ArrayList();
    }

    public boolean isValid() {
      return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
          || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
    }

    public List getCriteriaWithoutValue() {
      return criteriaWithoutValue;
    }

    public List getCriteriaWithSingleValue() {
      return criteriaWithSingleValue;
    }

    public List getCriteriaWithListValue() {
      return criteriaWithListValue;
    }

    public List getCriteriaWithBetweenValue() {
      return criteriaWithBetweenValue;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteriaWithoutValue.add(condition);
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("value", value);
      criteriaWithSingleValue.add(map);
    }

    protected void addCriterion(String condition, List values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", values);
      criteriaWithListValue.add(map);
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      List list = new ArrayList();
      list.add(value1);
      list.add(value2);
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", list);
      criteriaWithBetweenValue.add(map);
    }

    public Criteria andOidIsNull() {
      addCriterion("OID is null");
      return this;
    }

    public Criteria andOidIsNotNull() {
      addCriterion("OID is not null");
      return this;
    }

    public Criteria andOidEqualTo(Long value) {
      addCriterion("OID =", value, "oid");
      return this;
    }

    public Criteria andOidNotEqualTo(Long value) {
      addCriterion("OID <>", value, "oid");
      return this;
    }

    public Criteria andOidGreaterThan(Long value) {
      addCriterion("OID >", value, "oid");
      return this;
    }

    public Criteria andOidGreaterThanOrEqualTo(Long value) {
      addCriterion("OID >=", value, "oid");
      return this;
    }

    public Criteria andOidLessThan(Long value) {
      addCriterion("OID <", value, "oid");
      return this;
    }

    public Criteria andOidLessThanOrEqualTo(Long value) {
      addCriterion("OID <=", value, "oid");
      return this;
    }

    public Criteria andOidIn(List values) {
      addCriterion("OID in", values, "oid");
      return this;
    }

    public Criteria andOidNotIn(List values) {
      addCriterion("OID not in", values, "oid");
      return this;
    }

    public Criteria andOidBetween(Long value1, Long value2) {
      addCriterion("OID between", value1, value2, "oid");
      return this;
    }

    public Criteria andOidNotBetween(Long value1, Long value2) {
      addCriterion("OID not between", value1, value2, "oid");
      return this;
    }

    public Criteria andOrderCodeIsNull() {
      addCriterion("ORDER_CODE is null");
      return this;
    }

    public Criteria andOrderCodeIsNotNull() {
      addCriterion("ORDER_CODE is not null");
      return this;
    }

    public Criteria andOrderCodeEqualTo(String value) {
      addCriterion("ORDER_CODE =", value, "orderCode");
      return this;
    }

    public Criteria andOrderCodeNotEqualTo(String value) {
      addCriterion("ORDER_CODE <>", value, "orderCode");
      return this;
    }

    public Criteria andOrderCodeGreaterThan(String value) {
      addCriterion("ORDER_CODE >", value, "orderCode");
      return this;
    }

    public Criteria andOrderCodeGreaterThanOrEqualTo(String value) {
      addCriterion("ORDER_CODE >=", value, "orderCode");
      return this;
    }

    public Criteria andOrderCodeLessThan(String value) {
      addCriterion("ORDER_CODE <", value, "orderCode");
      return this;
    }

    public Criteria andOrderCodeLessThanOrEqualTo(String value) {
      addCriterion("ORDER_CODE <=", value, "orderCode");
      return this;
    }

    public Criteria andOrderCodeLike(String value) {
      addCriterion("ORDER_CODE like", value, "orderCode");
      return this;
    }

    public Criteria andOrderCodeNotLike(String value) {
      addCriterion("ORDER_CODE not like", value, "orderCode");
      return this;
    }

    public Criteria andOrderCodeIn(List values) {
      addCriterion("ORDER_CODE in", values, "orderCode");
      return this;
    }

    public Criteria andOrderCodeNotIn(List values) {
      addCriterion("ORDER_CODE not in", values, "orderCode");
      return this;
    }

    public Criteria andOrderCodeBetween(String value1, String value2) {
      addCriterion("ORDER_CODE between", value1, value2, "orderCode");
      return this;
    }

    public Criteria andOrderCodeNotBetween(String value1, String value2) {
      addCriterion("ORDER_CODE not between", value1, value2, "orderCode");
      return this;
    }

    public Criteria andCampaignidIsNull() {
      addCriterion("CAMPAIGNID is null");
      return this;
    }

    public Criteria andCampaignidIsNotNull() {
      addCriterion("CAMPAIGNID is not null");
      return this;
    }

    public Criteria andCampaignidEqualTo(String value) {
      addCriterion("CAMPAIGNID =", value, "campaignid");
      return this;
    }

    public Criteria andCampaignidNotEqualTo(String value) {
      addCriterion("CAMPAIGNID <>", value, "campaignid");
      return this;
    }

    public Criteria andCampaignidGreaterThan(String value) {
      addCriterion("CAMPAIGNID >", value, "campaignid");
      return this;
    }

    public Criteria andCampaignidGreaterThanOrEqualTo(String value) {
      addCriterion("CAMPAIGNID >=", value, "campaignid");
      return this;
    }

    public Criteria andCampaignidLessThan(String value) {
      addCriterion("CAMPAIGNID <", value, "campaignid");
      return this;
    }

    public Criteria andCampaignidLessThanOrEqualTo(String value) {
      addCriterion("CAMPAIGNID <=", value, "campaignid");
      return this;
    }

    public Criteria andCampaignidLike(String value) {
      addCriterion("CAMPAIGNID like", value, "campaignid");
      return this;
    }

    public Criteria andCampaignidNotLike(String value) {
      addCriterion("CAMPAIGNID not like", value, "campaignid");
      return this;
    }

    public Criteria andCampaignidIn(List values) {
      addCriterion("CAMPAIGNID in", values, "campaignid");
      return this;
    }

    public Criteria andCampaignidNotIn(List values) {
      addCriterion("CAMPAIGNID not in", values, "campaignid");
      return this;
    }

    public Criteria andCampaignidBetween(String value1, String value2) {
      addCriterion("CAMPAIGNID between", value1, value2, "campaignid");
      return this;
    }

    public Criteria andCampaignidNotBetween(String value1, String value2) {
      addCriterion("CAMPAIGNID not between", value1, value2, "campaignid");
      return this;
    }

    public Criteria andFeedbackIsNull() {
      addCriterion("FEEDBACK is null");
      return this;
    }

    public Criteria andFeedbackIsNotNull() {
      addCriterion("FEEDBACK is not null");
      return this;
    }

    public Criteria andFeedbackEqualTo(String value) {
      addCriterion("FEEDBACK =", value, "feedback");
      return this;
    }

    public Criteria andFeedbackNotEqualTo(String value) {
      addCriterion("FEEDBACK <>", value, "feedback");
      return this;
    }

    public Criteria andFeedbackGreaterThan(String value) {
      addCriterion("FEEDBACK >", value, "feedback");
      return this;
    }

    public Criteria andFeedbackGreaterThanOrEqualTo(String value) {
      addCriterion("FEEDBACK >=", value, "feedback");
      return this;
    }

    public Criteria andFeedbackLessThan(String value) {
      addCriterion("FEEDBACK <", value, "feedback");
      return this;
    }

    public Criteria andFeedbackLessThanOrEqualTo(String value) {
      addCriterion("FEEDBACK <=", value, "feedback");
      return this;
    }

    public Criteria andFeedbackLike(String value) {
      addCriterion("FEEDBACK like", value, "feedback");
      return this;
    }

    public Criteria andFeedbackNotLike(String value) {
      addCriterion("FEEDBACK not like", value, "feedback");
      return this;
    }

    public Criteria andFeedbackIn(List values) {
      addCriterion("FEEDBACK in", values, "feedback");
      return this;
    }

    public Criteria andFeedbackNotIn(List values) {
      addCriterion("FEEDBACK not in", values, "feedback");
      return this;
    }

    public Criteria andFeedbackBetween(String value1, String value2) {
      addCriterion("FEEDBACK between", value1, value2, "feedback");
      return this;
    }

    public Criteria andFeedbackNotBetween(String value1, String value2) {
      addCriterion("FEEDBACK not between", value1, value2, "feedback");
      return this;
    }

    public Criteria andSourceIsNull() {
      addCriterion("SOURCE is null");
      return this;
    }

    public Criteria andSourceIsNotNull() {
      addCriterion("SOURCE is not null");
      return this;
    }

    public Criteria andSourceEqualTo(String value) {
      addCriterion("SOURCE =", value, "source");
      return this;
    }

    public Criteria andSourceNotEqualTo(String value) {
      addCriterion("SOURCE <>", value, "source");
      return this;
    }

    public Criteria andSourceGreaterThan(String value) {
      addCriterion("SOURCE >", value, "source");
      return this;
    }

    public Criteria andSourceGreaterThanOrEqualTo(String value) {
      addCriterion("SOURCE >=", value, "source");
      return this;
    }

    public Criteria andSourceLessThan(String value) {
      addCriterion("SOURCE <", value, "source");
      return this;
    }

    public Criteria andSourceLessThanOrEqualTo(String value) {
      addCriterion("SOURCE <=", value, "source");
      return this;
    }

    public Criteria andSourceLike(String value) {
      addCriterion("SOURCE like", value, "source");
      return this;
    }

    public Criteria andSourceNotLike(String value) {
      addCriterion("SOURCE not like", value, "source");
      return this;
    }

    public Criteria andSourceIn(List values) {
      addCriterion("SOURCE in", values, "source");
      return this;
    }

    public Criteria andSourceNotIn(List values) {
      addCriterion("SOURCE not in", values, "source");
      return this;
    }

    public Criteria andSourceBetween(String value1, String value2) {
      addCriterion("SOURCE between", value1, value2, "source");
      return this;
    }

    public Criteria andSourceNotBetween(String value1, String value2) {
      addCriterion("SOURCE not between", value1, value2, "source");
      return this;
    }

    public Criteria andChannelIsNull() {
      addCriterion("CHANNEL is null");
      return this;
    }

    public Criteria andChannelIsNotNull() {
      addCriterion("CHANNEL is not null");
      return this;
    }

    public Criteria andChannelEqualTo(String value) {
      addCriterion("CHANNEL =", value, "channel");
      return this;
    }

    public Criteria andChannelNotEqualTo(String value) {
      addCriterion("CHANNEL <>", value, "channel");
      return this;
    }

    public Criteria andChannelGreaterThan(String value) {
      addCriterion("CHANNEL >", value, "channel");
      return this;
    }

    public Criteria andChannelGreaterThanOrEqualTo(String value) {
      addCriterion("CHANNEL >=", value, "channel");
      return this;
    }

    public Criteria andChannelLessThan(String value) {
      addCriterion("CHANNEL <", value, "channel");
      return this;
    }

    public Criteria andChannelLessThanOrEqualTo(String value) {
      addCriterion("CHANNEL <=", value, "channel");
      return this;
    }

    public Criteria andChannelLike(String value) {
      addCriterion("CHANNEL like", value, "channel");
      return this;
    }

    public Criteria andChannelNotLike(String value) {
      addCriterion("CHANNEL not like", value, "channel");
      return this;
    }

    public Criteria andChannelIn(List values) {
      addCriterion("CHANNEL in", values, "channel");
      return this;
    }

    public Criteria andChannelNotIn(List values) {
      addCriterion("CHANNEL not in", values, "channel");
      return this;
    }

    public Criteria andChannelBetween(String value1, String value2) {
      addCriterion("CHANNEL between", value1, value2, "channel");
      return this;
    }

    public Criteria andChannelNotBetween(String value1, String value2) {
      addCriterion("CHANNEL not between", value1, value2, "channel");
      return this;
    }

    public Criteria andCommissionTypeIsNull() {
      addCriterion("COMMISSION_TYPE is null");
      return this;
    }

    public Criteria andCommissionTypeIsNotNull() {
      addCriterion("COMMISSION_TYPE is not null");
      return this;
    }

    public Criteria andCommissionTypeEqualTo(String value) {
      addCriterion("COMMISSION_TYPE =", value, "commissionType");
      return this;
    }

    public Criteria andCommissionTypeNotEqualTo(String value) {
      addCriterion("COMMISSION_TYPE <>", value, "commissionType");
      return this;
    }

    public Criteria andCommissionTypeGreaterThan(String value) {
      addCriterion("COMMISSION_TYPE >", value, "commissionType");
      return this;
    }

    public Criteria andCommissionTypeGreaterThanOrEqualTo(String value) {
      addCriterion("COMMISSION_TYPE >=", value, "commissionType");
      return this;
    }

    public Criteria andCommissionTypeLessThan(String value) {
      addCriterion("COMMISSION_TYPE <", value, "commissionType");
      return this;
    }

    public Criteria andCommissionTypeLessThanOrEqualTo(String value) {
      addCriterion("COMMISSION_TYPE <=", value, "commissionType");
      return this;
    }

    public Criteria andCommissionTypeLike(String value) {
      addCriterion("COMMISSION_TYPE like", value, "commissionType");
      return this;
    }

    public Criteria andCommissionTypeNotLike(String value) {
      addCriterion("COMMISSION_TYPE not like", value, "commissionType");
      return this;
    }

    public Criteria andCommissionTypeIn(List values) {
      addCriterion("COMMISSION_TYPE in", values, "commissionType");
      return this;
    }

    public Criteria andCommissionTypeNotIn(List values) {
      addCriterion("COMMISSION_TYPE not in", values, "commissionType");
      return this;
    }

    public Criteria andCommissionTypeBetween(String value1, String value2) {
      addCriterion("COMMISSION_TYPE between", value1, value2, "commissionType");
      return this;
    }

    public Criteria andCommissionTypeNotBetween(String value1, String value2) {
      addCriterion("COMMISSION_TYPE not between", value1, value2, "commissionType");
      return this;
    }

    public Criteria andCreatedateIsNull() {
      addCriterion("CREATEDATE is null");
      return this;
    }

    public Criteria andCreatedateIsNotNull() {
      addCriterion("CREATEDATE is not null");
      return this;
    }

    public Criteria andCreatedateEqualTo(Date value) {
      addCriterion("CREATEDATE =", value, "createdate");
      return this;
    }

    public Criteria andCreatedateNotEqualTo(Date value) {
      addCriterion("CREATEDATE <>", value, "createdate");
      return this;
    }

    public Criteria andCreatedateGreaterThan(Date value) {
      addCriterion("CREATEDATE >", value, "createdate");
      return this;
    }

    public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
      addCriterion("CREATEDATE >=", value, "createdate");
      return this;
    }

    public Criteria andCreatedateLessThan(Date value) {
      addCriterion("CREATEDATE <", value, "createdate");
      return this;
    }

    public Criteria andCreatedateLessThanOrEqualTo(Date value) {
      addCriterion("CREATEDATE <=", value, "createdate");
      return this;
    }

    public Criteria andCreatedateIn(List values) {
      addCriterion("CREATEDATE in", values, "createdate");
      return this;
    }

    public Criteria andCreatedateNotIn(List values) {
      addCriterion("CREATEDATE not in", values, "createdate");
      return this;
    }

    public Criteria andCreatedateBetween(Date value1, Date value2) {
      addCriterion("CREATEDATE between", value1, value2, "createdate");
      return this;
    }

    public Criteria andCreatedateNotBetween(Date value1, Date value2) {
      addCriterion("CREATEDATE not between", value1, value2, "createdate");
      return this;
    }
  }
}
