package com.pltfm.app.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SuppressWarnings("unchecked")
public class OrderAlterExample implements Serializable {
  /**
	 * 
	 */
  private static final long serialVersionUID = 1L;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database table
   * KMORDER.ORDER_ALTER
   * 
   * @ibatorgenerated Fri Apr 18 16:17:33 CST 2014
   */
  protected String orderByClause;

  /**
   * This field was generated by Apache iBATIS ibator. This field corresponds to the database table
   * KMORDER.ORDER_ALTER
   * 
   * @ibatorgenerated Fri Apr 18 16:17:33 CST 2014
   */
  protected List oredCriteria;

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_ALTER
   * 
   * @ibatorgenerated Fri Apr 18 16:17:33 CST 2014
   */
  public OrderAlterExample() {
    oredCriteria = new ArrayList();
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_ALTER
   * 
   * @ibatorgenerated Fri Apr 18 16:17:33 CST 2014
   */
  protected OrderAlterExample(OrderAlterExample example) {
    this.orderByClause = example.orderByClause;
    this.oredCriteria = example.oredCriteria;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_ALTER
   * 
   * @ibatorgenerated Fri Apr 18 16:17:33 CST 2014
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_ALTER
   * 
   * @ibatorgenerated Fri Apr 18 16:17:33 CST 2014
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_ALTER
   * 
   * @ibatorgenerated Fri Apr 18 16:17:33 CST 2014
   */
  public List getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_ALTER
   * 
   * @ibatorgenerated Fri Apr 18 16:17:33 CST 2014
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_ALTER
   * 
   * @ibatorgenerated Fri Apr 18 16:17:33 CST 2014
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_ALTER
   * 
   * @ibatorgenerated Fri Apr 18 16:17:33 CST 2014
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by Apache iBATIS ibator. This method corresponds to the database
   * table KMORDER.ORDER_ALTER
   * 
   * @ibatorgenerated Fri Apr 18 16:17:33 CST 2014
   */
  public void clear() {
    oredCriteria.clear();
  }

  /**
   * This class was generated by Apache iBATIS ibator. This class corresponds to the database table
   * KMORDER.ORDER_ALTER
   * 
   * @ibatorgenerated Fri Apr 18 16:17:33 CST 2014
   */
  public static class Criteria {
    protected List criteriaWithoutValue;

    protected List criteriaWithSingleValue;

    protected List criteriaWithListValue;

    protected List criteriaWithBetweenValue;

    protected Criteria() {
      super();
      criteriaWithoutValue = new ArrayList();
      criteriaWithSingleValue = new ArrayList();
      criteriaWithListValue = new ArrayList();
      criteriaWithBetweenValue = new ArrayList();
    }

    public boolean isValid() {
      return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
          || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
    }

    public List getCriteriaWithoutValue() {
      return criteriaWithoutValue;
    }

    public List getCriteriaWithSingleValue() {
      return criteriaWithSingleValue;
    }

    public List getCriteriaWithListValue() {
      return criteriaWithListValue;
    }

    public List getCriteriaWithBetweenValue() {
      return criteriaWithBetweenValue;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteriaWithoutValue.add(condition);
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("value", value);
      criteriaWithSingleValue.add(map);
    }

    protected void addCriterion(String condition, List values, String property) {
      if (values == null || values.size() == 0) {
        throw new RuntimeException("Value list for " + property + " cannot be null or empty");
      }
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", values);
      criteriaWithListValue.add(map);
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      List list = new ArrayList();
      list.add(value1);
      list.add(value2);
      Map map = new HashMap();
      map.put("condition", condition);
      map.put("values", list);
      criteriaWithBetweenValue.add(map);
    }

    public Criteria andOrderAlterIdIsNull() {
      addCriterion("ORDER_ALTER_ID is null");
      return this;
    }

    public Criteria andOrderAlterIdIsNotNull() {
      addCriterion("ORDER_ALTER_ID is not null");
      return this;
    }

    public Criteria andOrderAlterIdEqualTo(Long value) {
      addCriterion("ORDER_ALTER_ID =", value, "orderAlterId");
      return this;
    }

    public Criteria andOrderAlterIdNotEqualTo(Long value) {
      addCriterion("ORDER_ALTER_ID <>", value, "orderAlterId");
      return this;
    }

    public Criteria andOrderAlterIdGreaterThan(Long value) {
      addCriterion("ORDER_ALTER_ID >", value, "orderAlterId");
      return this;
    }

    public Criteria andOrderAlterIdGreaterThanOrEqualTo(Long value) {
      addCriterion("ORDER_ALTER_ID >=", value, "orderAlterId");
      return this;
    }

    public Criteria andOrderAlterIdLessThan(Long value) {
      addCriterion("ORDER_ALTER_ID <", value, "orderAlterId");
      return this;
    }

    public Criteria andOrderAlterIdLessThanOrEqualTo(Long value) {
      addCriterion("ORDER_ALTER_ID <=", value, "orderAlterId");
      return this;
    }

    public Criteria andOrderAlterIdIn(List values) {
      addCriterion("ORDER_ALTER_ID in", values, "orderAlterId");
      return this;
    }

    public Criteria andOrderAlterIdNotIn(List values) {
      addCriterion("ORDER_ALTER_ID not in", values, "orderAlterId");
      return this;
    }

    public Criteria andOrderAlterIdBetween(Long value1, Long value2) {
      addCriterion("ORDER_ALTER_ID between", value1, value2, "orderAlterId");
      return this;
    }

    public Criteria andOrderAlterIdNotBetween(Long value1, Long value2) {
      addCriterion("ORDER_ALTER_ID not between", value1, value2, "orderAlterId");
      return this;
    }

    public Criteria andOrderCodeIsNull() {
      addCriterion("ORDER_CODE is null");
      return this;
    }

    public Criteria andOrderCodeIsNotNull() {
      addCriterion("ORDER_CODE is not null");
      return this;
    }

    public Criteria andOrderCodeEqualTo(String value) {
      addCriterion("ORDER_CODE =", value, "orderCode");
      return this;
    }

    public Criteria andOrderCodeNotEqualTo(String value) {
      addCriterion("ORDER_CODE <>", value, "orderCode");
      return this;
    }

    public Criteria andOrderCodeGreaterThan(String value) {
      addCriterion("ORDER_CODE >", value, "orderCode");
      return this;
    }

    public Criteria andOrderCodeGreaterThanOrEqualTo(String value) {
      addCriterion("ORDER_CODE >=", value, "orderCode");
      return this;
    }

    public Criteria andOrderCodeLessThan(String value) {
      addCriterion("ORDER_CODE <", value, "orderCode");
      return this;
    }

    public Criteria andOrderCodeLessThanOrEqualTo(String value) {
      addCriterion("ORDER_CODE <=", value, "orderCode");
      return this;
    }

    public Criteria andOrderCodeLike(String value) {
      addCriterion("ORDER_CODE like", value, "orderCode");
      return this;
    }

    public Criteria andOrderCodeNotLike(String value) {
      addCriterion("ORDER_CODE not like", value, "orderCode");
      return this;
    }

    public Criteria andOrderCodeIn(List values) {
      addCriterion("ORDER_CODE in", values, "orderCode");
      return this;
    }

    public Criteria andOrderCodeNotIn(List values) {
      addCriterion("ORDER_CODE not in", values, "orderCode");
      return this;
    }

    public Criteria andOrderCodeBetween(String value1, String value2) {
      addCriterion("ORDER_CODE between", value1, value2, "orderCode");
      return this;
    }

    public Criteria andOrderCodeNotBetween(String value1, String value2) {
      addCriterion("ORDER_CODE not between", value1, value2, "orderCode");
      return this;
    }

    public Criteria andProposerIsNull() {
      addCriterion("PROPOSER is null");
      return this;
    }

    public Criteria andProposerIsNotNull() {
      addCriterion("PROPOSER is not null");
      return this;
    }

    public Criteria andProposerEqualTo(String value) {
      addCriterion("PROPOSER =", value, "proposer");
      return this;
    }

    public Criteria andProposerNotEqualTo(String value) {
      addCriterion("PROPOSER <>", value, "proposer");
      return this;
    }

    public Criteria andProposerGreaterThan(String value) {
      addCriterion("PROPOSER >", value, "proposer");
      return this;
    }

    public Criteria andProposerGreaterThanOrEqualTo(String value) {
      addCriterion("PROPOSER >=", value, "proposer");
      return this;
    }

    public Criteria andProposerLessThan(String value) {
      addCriterion("PROPOSER <", value, "proposer");
      return this;
    }

    public Criteria andProposerLessThanOrEqualTo(String value) {
      addCriterion("PROPOSER <=", value, "proposer");
      return this;
    }

    public Criteria andProposerLike(String value) {
      addCriterion("PROPOSER like", value, "proposer");
      return this;
    }

    public Criteria andProposerNotLike(String value) {
      addCriterion("PROPOSER not like", value, "proposer");
      return this;
    }

    public Criteria andProposerIn(List values) {
      addCriterion("PROPOSER in", values, "proposer");
      return this;
    }

    public Criteria andProposerNotIn(List values) {
      addCriterion("PROPOSER not in", values, "proposer");
      return this;
    }

    public Criteria andProposerBetween(String value1, String value2) {
      addCriterion("PROPOSER between", value1, value2, "proposer");
      return this;
    }

    public Criteria andProposerNotBetween(String value1, String value2) {
      addCriterion("PROPOSER not between", value1, value2, "proposer");
      return this;
    }

    public Criteria andCheckerIsNull() {
      addCriterion("CHECKER is null");
      return this;
    }

    public Criteria andCheckerIsNotNull() {
      addCriterion("CHECKER is not null");
      return this;
    }

    public Criteria andCheckerEqualTo(String value) {
      addCriterion("CHECKER =", value, "checker");
      return this;
    }

    public Criteria andCheckerNotEqualTo(String value) {
      addCriterion("CHECKER <>", value, "checker");
      return this;
    }

    public Criteria andCheckerGreaterThan(String value) {
      addCriterion("CHECKER >", value, "checker");
      return this;
    }

    public Criteria andCheckerGreaterThanOrEqualTo(String value) {
      addCriterion("CHECKER >=", value, "checker");
      return this;
    }

    public Criteria andCheckerLessThan(String value) {
      addCriterion("CHECKER <", value, "checker");
      return this;
    }

    public Criteria andCheckerLessThanOrEqualTo(String value) {
      addCriterion("CHECKER <=", value, "checker");
      return this;
    }

    public Criteria andCheckerLike(String value) {
      addCriterion("CHECKER like", value, "checker");
      return this;
    }

    public Criteria andCheckerNotLike(String value) {
      addCriterion("CHECKER not like", value, "checker");
      return this;
    }

    public Criteria andCheckerIn(List values) {
      addCriterion("CHECKER in", values, "checker");
      return this;
    }

    public Criteria andCheckerNotIn(List values) {
      addCriterion("CHECKER not in", values, "checker");
      return this;
    }

    public Criteria andCheckerBetween(String value1, String value2) {
      addCriterion("CHECKER between", value1, value2, "checker");
      return this;
    }

    public Criteria andCheckerNotBetween(String value1, String value2) {
      addCriterion("CHECKER not between", value1, value2, "checker");
      return this;
    }

    public Criteria andProposeStatusIsNull() {
      addCriterion("PROPOSE_STATUS is null");
      return this;
    }

    public Criteria andProposeStatusIsNotNull() {
      addCriterion("PROPOSE_STATUS is not null");
      return this;
    }

    public Criteria andProposeStatusEqualTo(Short value) {
      addCriterion("PROPOSE_STATUS =", value, "proposeStatus");
      return this;
    }

    public Criteria andProposeStatusNotEqualTo(Short value) {
      addCriterion("PROPOSE_STATUS <>", value, "proposeStatus");
      return this;
    }

    public Criteria andProposeStatusGreaterThan(Short value) {
      addCriterion("PROPOSE_STATUS >", value, "proposeStatus");
      return this;
    }

    public Criteria andProposeStatusGreaterThanOrEqualTo(Short value) {
      addCriterion("PROPOSE_STATUS >=", value, "proposeStatus");
      return this;
    }

    public Criteria andProposeStatusLessThan(Short value) {
      addCriterion("PROPOSE_STATUS <", value, "proposeStatus");
      return this;
    }

    public Criteria andProposeStatusLessThanOrEqualTo(Short value) {
      addCriterion("PROPOSE_STATUS <=", value, "proposeStatus");
      return this;
    }

    public Criteria andProposeStatusIn(List values) {
      addCriterion("PROPOSE_STATUS in", values, "proposeStatus");
      return this;
    }

    public Criteria andProposeStatusNotIn(List values) {
      addCriterion("PROPOSE_STATUS not in", values, "proposeStatus");
      return this;
    }

    public Criteria andProposeStatusBetween(Short value1, Short value2) {
      addCriterion("PROPOSE_STATUS between", value1, value2, "proposeStatus");
      return this;
    }

    public Criteria andProposeStatusNotBetween(Short value1, Short value2) {
      addCriterion("PROPOSE_STATUS not between", value1, value2, "proposeStatus");
      return this;
    }

    public Criteria andCreateDateIsNull() {
      addCriterion("CREATE_DATE is null");
      return this;
    }

    public Criteria andCreateDateIsNotNull() {
      addCriterion("CREATE_DATE is not null");
      return this;
    }

    public Criteria andCreateDateEqualTo(Date value) {
      addCriterion("CREATE_DATE =", value, "createDate");
      return this;
    }

    public Criteria andCreateDateNotEqualTo(Date value) {
      addCriterion("CREATE_DATE <>", value, "createDate");
      return this;
    }

    public Criteria andCreateDateGreaterThan(Date value) {
      addCriterion("CREATE_DATE >", value, "createDate");
      return this;
    }

    public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
      addCriterion("CREATE_DATE >=", value, "createDate");
      return this;
    }

    public Criteria andCreateDateLessThan(Date value) {
      addCriterion("CREATE_DATE <", value, "createDate");
      return this;
    }

    public Criteria andCreateDateLessThanOrEqualTo(Date value) {
      addCriterion("CREATE_DATE <=", value, "createDate");
      return this;
    }

    public Criteria andCreateDateIn(List values) {
      addCriterion("CREATE_DATE in", values, "createDate");
      return this;
    }

    public Criteria andCreateDateNotIn(List values) {
      addCriterion("CREATE_DATE not in", values, "createDate");
      return this;
    }

    public Criteria andCreateDateBetween(Date value1, Date value2) {
      addCriterion("CREATE_DATE between", value1, value2, "createDate");
      return this;
    }

    public Criteria andCreateDateNotBetween(Date value1, Date value2) {
      addCriterion("CREATE_DATE not between", value1, value2, "createDate");
      return this;
    }

    public Criteria andCheckDateIsNull() {
      addCriterion("CHECK_DATE is null");
      return this;
    }

    public Criteria andCheckDateIsNotNull() {
      addCriterion("CHECK_DATE is not null");
      return this;
    }

    public Criteria andCheckDateEqualTo(Date value) {
      addCriterion("CHECK_DATE =", value, "checkDate");
      return this;
    }

    public Criteria andCheckDateNotEqualTo(Date value) {
      addCriterion("CHECK_DATE <>", value, "checkDate");
      return this;
    }

    public Criteria andCheckDateGreaterThan(Date value) {
      addCriterion("CHECK_DATE >", value, "checkDate");
      return this;
    }

    public Criteria andCheckDateGreaterThanOrEqualTo(Date value) {
      addCriterion("CHECK_DATE >=", value, "checkDate");
      return this;
    }

    public Criteria andCheckDateLessThan(Date value) {
      addCriterion("CHECK_DATE <", value, "checkDate");
      return this;
    }

    public Criteria andCheckDateLessThanOrEqualTo(Date value) {
      addCriterion("CHECK_DATE <=", value, "checkDate");
      return this;
    }

    public Criteria andCheckDateIn(List values) {
      addCriterion("CHECK_DATE in", values, "checkDate");
      return this;
    }

    public Criteria andCheckDateNotIn(List values) {
      addCriterion("CHECK_DATE not in", values, "checkDate");
      return this;
    }

    public Criteria andCheckDateBetween(Date value1, Date value2) {
      addCriterion("CHECK_DATE between", value1, value2, "checkDate");
      return this;
    }

    public Criteria andCheckDateNotBetween(Date value1, Date value2) {
      addCriterion("CHECK_DATE not between", value1, value2, "checkDate");
      return this;
    }

    public Criteria andAlterCommentIsNull() {
      addCriterion("ALTER_COMMENT is null");
      return this;
    }

    public Criteria andAlterCommentIsNotNull() {
      addCriterion("ALTER_COMMENT is not null");
      return this;
    }

    public Criteria andAlterCommentEqualTo(String value) {
      addCriterion("ALTER_COMMENT =", value, "alterComment");
      return this;
    }

    public Criteria andAlterCommentNotEqualTo(String value) {
      addCriterion("ALTER_COMMENT <>", value, "alterComment");
      return this;
    }

    public Criteria andAlterCommentGreaterThan(String value) {
      addCriterion("ALTER_COMMENT >", value, "alterComment");
      return this;
    }

    public Criteria andAlterCommentGreaterThanOrEqualTo(String value) {
      addCriterion("ALTER_COMMENT >=", value, "alterComment");
      return this;
    }

    public Criteria andAlterCommentLessThan(String value) {
      addCriterion("ALTER_COMMENT <", value, "alterComment");
      return this;
    }

    public Criteria andAlterCommentLessThanOrEqualTo(String value) {
      addCriterion("ALTER_COMMENT <=", value, "alterComment");
      return this;
    }

    public Criteria andAlterCommentLike(String value) {
      addCriterion("ALTER_COMMENT like", value, "alterComment");
      return this;
    }

    public Criteria andAlterCommentNotLike(String value) {
      addCriterion("ALTER_COMMENT not like", value, "alterComment");
      return this;
    }

    public Criteria andAlterCommentIn(List values) {
      addCriterion("ALTER_COMMENT in", values, "alterComment");
      return this;
    }

    public Criteria andAlterCommentNotIn(List values) {
      addCriterion("ALTER_COMMENT not in", values, "alterComment");
      return this;
    }

    public Criteria andAlterCommentBetween(String value1, String value2) {
      addCriterion("ALTER_COMMENT between", value1, value2, "alterComment");
      return this;
    }

    public Criteria andAlterCommentNotBetween(String value1, String value2) {
      addCriterion("ALTER_COMMENT not between", value1, value2, "alterComment");
      return this;
    }

    public Criteria andBackTypeIsNull() {
      addCriterion("BACK_TYPE is null");
      return this;
    }

    public Criteria andBackTypeIsNotNull() {
      addCriterion("BACK_TYPE is not null");
      return this;
    }

    public Criteria andBackTypeEqualTo(Short value) {
      addCriterion("BACK_TYPE =", value, "backType");
      return this;
    }

    public Criteria andBackTypeNotEqualTo(Short value) {
      addCriterion("BACK_TYPE <>", value, "backType");
      return this;
    }

    public Criteria andBackTypeGreaterThan(Short value) {
      addCriterion("BACK_TYPE >", value, "backType");
      return this;
    }

    public Criteria andBackTypeGreaterThanOrEqualTo(Short value) {
      addCriterion("BACK_TYPE >=", value, "backType");
      return this;
    }

    public Criteria andBackTypeLessThan(Short value) {
      addCriterion("BACK_TYPE <", value, "backType");
      return this;
    }

    public Criteria andBackTypeLessThanOrEqualTo(Short value) {
      addCriterion("BACK_TYPE <=", value, "backType");
      return this;
    }

    public Criteria andBackTypeIn(List values) {
      addCriterion("BACK_TYPE in", values, "backType");
      return this;
    }

    public Criteria andBackTypeNotIn(List values) {
      addCriterion("BACK_TYPE not in", values, "backType");
      return this;
    }

    public Criteria andBackTypeBetween(Short value1, Short value2) {
      addCriterion("BACK_TYPE between", value1, value2, "backType");
      return this;
    }

    public Criteria andBackTypeNotBetween(Short value1, Short value2) {
      addCriterion("BACK_TYPE not between", value1, value2, "backType");
      return this;
    }

    public Criteria andAddressIsNull() {
      addCriterion("ADDRESS is null");
      return this;
    }

    public Criteria andAddressIsNotNull() {
      addCriterion("ADDRESS is not null");
      return this;
    }

    public Criteria andAddressEqualTo(String value) {
      addCriterion("ADDRESS =", value, "address");
      return this;
    }

    public Criteria andAddressNotEqualTo(String value) {
      addCriterion("ADDRESS <>", value, "address");
      return this;
    }

    public Criteria andAddressGreaterThan(String value) {
      addCriterion("ADDRESS >", value, "address");
      return this;
    }

    public Criteria andAddressGreaterThanOrEqualTo(String value) {
      addCriterion("ADDRESS >=", value, "address");
      return this;
    }

    public Criteria andAddressLessThan(String value) {
      addCriterion("ADDRESS <", value, "address");
      return this;
    }

    public Criteria andAddressLessThanOrEqualTo(String value) {
      addCriterion("ADDRESS <=", value, "address");
      return this;
    }

    public Criteria andAddressLike(String value) {
      addCriterion("ADDRESS like", value, "address");
      return this;
    }

    public Criteria andAddressNotLike(String value) {
      addCriterion("ADDRESS not like", value, "address");
      return this;
    }

    public Criteria andAddressIn(List values) {
      addCriterion("ADDRESS in", values, "address");
      return this;
    }

    public Criteria andAddressNotIn(List values) {
      addCriterion("ADDRESS not in", values, "address");
      return this;
    }

    public Criteria andAddressBetween(String value1, String value2) {
      addCriterion("ADDRESS between", value1, value2, "address");
      return this;
    }

    public Criteria andAddressNotBetween(String value1, String value2) {
      addCriterion("ADDRESS not between", value1, value2, "address");
      return this;
    }

    public Criteria andNameIsNull() {
      addCriterion("NAME is null");
      return this;
    }

    public Criteria andNameIsNotNull() {
      addCriterion("NAME is not null");
      return this;
    }

    public Criteria andNameEqualTo(String value) {
      addCriterion("NAME =", value, "name");
      return this;
    }

    public Criteria andNameNotEqualTo(String value) {
      addCriterion("NAME <>", value, "name");
      return this;
    }

    public Criteria andNameGreaterThan(String value) {
      addCriterion("NAME >", value, "name");
      return this;
    }

    public Criteria andNameGreaterThanOrEqualTo(String value) {
      addCriterion("NAME >=", value, "name");
      return this;
    }

    public Criteria andNameLessThan(String value) {
      addCriterion("NAME <", value, "name");
      return this;
    }

    public Criteria andNameLessThanOrEqualTo(String value) {
      addCriterion("NAME <=", value, "name");
      return this;
    }

    public Criteria andNameLike(String value) {
      addCriterion("NAME like", value, "name");
      return this;
    }

    public Criteria andNameNotLike(String value) {
      addCriterion("NAME not like", value, "name");
      return this;
    }

    public Criteria andNameIn(List values) {
      addCriterion("NAME in", values, "name");
      return this;
    }

    public Criteria andNameNotIn(List values) {
      addCriterion("NAME not in", values, "name");
      return this;
    }

    public Criteria andNameBetween(String value1, String value2) {
      addCriterion("NAME between", value1, value2, "name");
      return this;
    }

    public Criteria andNameNotBetween(String value1, String value2) {
      addCriterion("NAME not between", value1, value2, "name");
      return this;
    }

    public Criteria andPhoneIsNull() {
      addCriterion("PHONE is null");
      return this;
    }

    public Criteria andPhoneIsNotNull() {
      addCriterion("PHONE is not null");
      return this;
    }

    public Criteria andPhoneEqualTo(String value) {
      addCriterion("PHONE =", value, "phone");
      return this;
    }

    public Criteria andPhoneNotEqualTo(String value) {
      addCriterion("PHONE <>", value, "phone");
      return this;
    }

    public Criteria andPhoneGreaterThan(String value) {
      addCriterion("PHONE >", value, "phone");
      return this;
    }

    public Criteria andPhoneGreaterThanOrEqualTo(String value) {
      addCriterion("PHONE >=", value, "phone");
      return this;
    }

    public Criteria andPhoneLessThan(String value) {
      addCriterion("PHONE <", value, "phone");
      return this;
    }

    public Criteria andPhoneLessThanOrEqualTo(String value) {
      addCriterion("PHONE <=", value, "phone");
      return this;
    }

    public Criteria andPhoneLike(String value) {
      addCriterion("PHONE like", value, "phone");
      return this;
    }

    public Criteria andPhoneNotLike(String value) {
      addCriterion("PHONE not like", value, "phone");
      return this;
    }

    public Criteria andPhoneIn(List values) {
      addCriterion("PHONE in", values, "phone");
      return this;
    }

    public Criteria andPhoneNotIn(List values) {
      addCriterion("PHONE not in", values, "phone");
      return this;
    }

    public Criteria andPhoneBetween(String value1, String value2) {
      addCriterion("PHONE between", value1, value2, "phone");
      return this;
    }

    public Criteria andPhoneNotBetween(String value1, String value2) {
      addCriterion("PHONE not between", value1, value2, "phone");
      return this;
    }

    public Criteria andFinishDateIsNull() {
      addCriterion("FINISH_DATE is null");
      return this;
    }

    public Criteria andFinishDateIsNotNull() {
      addCriterion("FINISH_DATE is not null");
      return this;
    }

    public Criteria andFinishDateEqualTo(Date value) {
      addCriterion("FINISH_DATE =", value, "finishDate");
      return this;
    }

    public Criteria andFinishDateNotEqualTo(Date value) {
      addCriterion("FINISH_DATE <>", value, "finishDate");
      return this;
    }

    public Criteria andFinishDateGreaterThan(Date value) {
      addCriterion("FINISH_DATE >", value, "finishDate");
      return this;
    }

    public Criteria andFinishDateGreaterThanOrEqualTo(Date value) {
      addCriterion("FINISH_DATE >=", value, "finishDate");
      return this;
    }

    public Criteria andFinishDateLessThan(Date value) {
      addCriterion("FINISH_DATE <", value, "finishDate");
      return this;
    }

    public Criteria andFinishDateLessThanOrEqualTo(Date value) {
      addCriterion("FINISH_DATE <=", value, "finishDate");
      return this;
    }

    public Criteria andFinishDateIn(List values) {
      addCriterion("FINISH_DATE in", values, "finishDate");
      return this;
    }

    public Criteria andFinishDateNotIn(List values) {
      addCriterion("FINISH_DATE not in", values, "finishDate");
      return this;
    }

    public Criteria andFinishDateBetween(Date value1, Date value2) {
      addCriterion("FINISH_DATE between", value1, value2, "finishDate");
      return this;
    }

    public Criteria andFinishDateNotBetween(Date value1, Date value2) {
      addCriterion("FINISH_DATE not between", value1, value2, "finishDate");
      return this;
    }

    public Criteria andRuturnMoneyIsNull() {
      addCriterion("RUTURN_MONEY is null");
      return this;
    }

    public Criteria andRuturnMoneyIsNotNull() {
      addCriterion("RUTURN_MONEY is not null");
      return this;
    }

    public Criteria andRuturnMoneyEqualTo(BigDecimal value) {
      addCriterion("RUTURN_MONEY =", value, "ruturnMoney");
      return this;
    }

    public Criteria andRuturnMoneyNotEqualTo(BigDecimal value) {
      addCriterion("RUTURN_MONEY <>", value, "ruturnMoney");
      return this;
    }

    public Criteria andRuturnMoneyGreaterThan(BigDecimal value) {
      addCriterion("RUTURN_MONEY >", value, "ruturnMoney");
      return this;
    }

    public Criteria andRuturnMoneyGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("RUTURN_MONEY >=", value, "ruturnMoney");
      return this;
    }

    public Criteria andRuturnMoneyLessThan(BigDecimal value) {
      addCriterion("RUTURN_MONEY <", value, "ruturnMoney");
      return this;
    }

    public Criteria andRuturnMoneyLessThanOrEqualTo(BigDecimal value) {
      addCriterion("RUTURN_MONEY <=", value, "ruturnMoney");
      return this;
    }

    public Criteria andRuturnMoneyIn(List values) {
      addCriterion("RUTURN_MONEY in", values, "ruturnMoney");
      return this;
    }

    public Criteria andRuturnMoneyNotIn(List values) {
      addCriterion("RUTURN_MONEY not in", values, "ruturnMoney");
      return this;
    }

    public Criteria andRuturnMoneyBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("RUTURN_MONEY between", value1, value2, "ruturnMoney");
      return this;
    }

    public Criteria andRuturnMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("RUTURN_MONEY not between", value1, value2, "ruturnMoney");
      return this;
    }

    public Criteria andFareSubsidyIsNull() {
      addCriterion("FARE_SUBSIDY is null");
      return this;
    }

    public Criteria andFareSubsidyIsNotNull() {
      addCriterion("FARE_SUBSIDY is not null");
      return this;
    }

    public Criteria andFareSubsidyEqualTo(BigDecimal value) {
      addCriterion("FARE_SUBSIDY =", value, "fareSubsidy");
      return this;
    }

    public Criteria andFareSubsidyNotEqualTo(BigDecimal value) {
      addCriterion("FARE_SUBSIDY <>", value, "fareSubsidy");
      return this;
    }

    public Criteria andFareSubsidyGreaterThan(BigDecimal value) {
      addCriterion("FARE_SUBSIDY >", value, "fareSubsidy");
      return this;
    }

    public Criteria andFareSubsidyGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("FARE_SUBSIDY >=", value, "fareSubsidy");
      return this;
    }

    public Criteria andFareSubsidyLessThan(BigDecimal value) {
      addCriterion("FARE_SUBSIDY <", value, "fareSubsidy");
      return this;
    }

    public Criteria andFareSubsidyLessThanOrEqualTo(BigDecimal value) {
      addCriterion("FARE_SUBSIDY <=", value, "fareSubsidy");
      return this;
    }

    public Criteria andFareSubsidyIn(List values) {
      addCriterion("FARE_SUBSIDY in", values, "fareSubsidy");
      return this;
    }

    public Criteria andFareSubsidyNotIn(List values) {
      addCriterion("FARE_SUBSIDY not in", values, "fareSubsidy");
      return this;
    }

    public Criteria andFareSubsidyBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("FARE_SUBSIDY between", value1, value2, "fareSubsidy");
      return this;
    }

    public Criteria andFareSubsidyNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("FARE_SUBSIDY not between", value1, value2, "fareSubsidy");
      return this;
    }

    public Criteria andRuturnSumIsNull() {
      addCriterion("RUTURN_SUM is null");
      return this;
    }

    public Criteria andRuturnSumIsNotNull() {
      addCriterion("RUTURN_SUM is not null");
      return this;
    }

    public Criteria andRuturnSumEqualTo(BigDecimal value) {
      addCriterion("RUTURN_SUM =", value, "ruturnSum");
      return this;
    }

    public Criteria andRuturnSumNotEqualTo(BigDecimal value) {
      addCriterion("RUTURN_SUM <>", value, "ruturnSum");
      return this;
    }

    public Criteria andRuturnSumGreaterThan(BigDecimal value) {
      addCriterion("RUTURN_SUM >", value, "ruturnSum");
      return this;
    }

    public Criteria andRuturnSumGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("RUTURN_SUM >=", value, "ruturnSum");
      return this;
    }

    public Criteria andRuturnSumLessThan(BigDecimal value) {
      addCriterion("RUTURN_SUM <", value, "ruturnSum");
      return this;
    }

    public Criteria andRuturnSumLessThanOrEqualTo(BigDecimal value) {
      addCriterion("RUTURN_SUM <=", value, "ruturnSum");
      return this;
    }

    public Criteria andRuturnSumIn(List values) {
      addCriterion("RUTURN_SUM in", values, "ruturnSum");
      return this;
    }

    public Criteria andRuturnSumNotIn(List values) {
      addCriterion("RUTURN_SUM not in", values, "ruturnSum");
      return this;
    }

    public Criteria andRuturnSumBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("RUTURN_SUM between", value1, value2, "ruturnSum");
      return this;
    }

    public Criteria andRuturnSumNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("RUTURN_SUM not between", value1, value2, "ruturnSum");
      return this;
    }

    public Criteria andOrderAlterCodeIsNull() {
      addCriterion("ORDER_ALTER_CODE is null");
      return this;
    }

    public Criteria andOrderAlterCodeIsNotNull() {
      addCriterion("ORDER_ALTER_CODE is not null");
      return this;
    }

    public Criteria andOrderAlterCodeEqualTo(String value) {
      addCriterion("ORDER_ALTER_CODE =", value, "orderAlterCode");
      return this;
    }

    public Criteria andOrderAlterCodeNotEqualTo(String value) {
      addCriterion("ORDER_ALTER_CODE <>", value, "orderAlterCode");
      return this;
    }

    public Criteria andOrderAlterCodeGreaterThan(String value) {
      addCriterion("ORDER_ALTER_CODE >", value, "orderAlterCode");
      return this;
    }

    public Criteria andOrderAlterCodeGreaterThanOrEqualTo(String value) {
      addCriterion("ORDER_ALTER_CODE >=", value, "orderAlterCode");
      return this;
    }

    public Criteria andOrderAlterCodeLessThan(String value) {
      addCriterion("ORDER_ALTER_CODE <", value, "orderAlterCode");
      return this;
    }

    public Criteria andOrderAlterCodeLessThanOrEqualTo(String value) {
      addCriterion("ORDER_ALTER_CODE <=", value, "orderAlterCode");
      return this;
    }

    public Criteria andOrderAlterCodeLike(String value) {
      addCriterion("ORDER_ALTER_CODE like", value, "orderAlterCode");
      return this;
    }

    public Criteria andOrderAlterCodeNotLike(String value) {
      addCriterion("ORDER_ALTER_CODE not like", value, "orderAlterCode");
      return this;
    }

    public Criteria andOrderAlterCodeIn(List values) {
      addCriterion("ORDER_ALTER_CODE in", values, "orderAlterCode");
      return this;
    }

    public Criteria andOrderAlterCodeNotIn(List values) {
      addCriterion("ORDER_ALTER_CODE not in", values, "orderAlterCode");
      return this;
    }

    public Criteria andOrderAlterCodeBetween(String value1, String value2) {
      addCriterion("ORDER_ALTER_CODE between", value1, value2, "orderAlterCode");
      return this;
    }

    public Criteria andOrderAlterCodeNotBetween(String value1, String value2) {
      addCriterion("ORDER_ALTER_CODE not between", value1, value2, "orderAlterCode");
      return this;
    }

    public Criteria andStockOutIdIsNull() {
      addCriterion("STOCK_OUT_ID is null");
      return this;
    }

    public Criteria andStockOutIdIsNotNull() {
      addCriterion("STOCK_OUT_ID is not null");
      return this;
    }

    public Criteria andStockOutIdEqualTo(BigDecimal value) {
      addCriterion("STOCK_OUT_ID =", value, "stockOutId");
      return this;
    }

    public Criteria andStockOutIdNotEqualTo(BigDecimal value) {
      addCriterion("STOCK_OUT_ID <>", value, "stockOutId");
      return this;
    }

    public Criteria andStockOutIdGreaterThan(BigDecimal value) {
      addCriterion("STOCK_OUT_ID >", value, "stockOutId");
      return this;
    }

    public Criteria andStockOutIdGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("STOCK_OUT_ID >=", value, "stockOutId");
      return this;
    }

    public Criteria andStockOutIdLessThan(BigDecimal value) {
      addCriterion("STOCK_OUT_ID <", value, "stockOutId");
      return this;
    }

    public Criteria andStockOutIdLessThanOrEqualTo(BigDecimal value) {
      addCriterion("STOCK_OUT_ID <=", value, "stockOutId");
      return this;
    }

    public Criteria andStockOutIdIn(List values) {
      addCriterion("STOCK_OUT_ID in", values, "stockOutId");
      return this;
    }

    public Criteria andStockOutIdNotIn(List values) {
      addCriterion("STOCK_OUT_ID not in", values, "stockOutId");
      return this;
    }

    public Criteria andStockOutIdBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("STOCK_OUT_ID between", value1, value2, "stockOutId");
      return this;
    }

    public Criteria andStockOutIdNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("STOCK_OUT_ID not between", value1, value2, "stockOutId");
      return this;
    }

    public Criteria andDistributionIdIsNull() {
      addCriterion("DISTRIBUTION_ID is null");
      return this;
    }

    public Criteria andDistributionIdIsNotNull() {
      addCriterion("DISTRIBUTION_ID is not null");
      return this;
    }

    public Criteria andDistributionIdEqualTo(BigDecimal value) {
      addCriterion("DISTRIBUTION_ID =", value, "distributionId");
      return this;
    }

    public Criteria andDistributionIdNotEqualTo(BigDecimal value) {
      addCriterion("DISTRIBUTION_ID <>", value, "distributionId");
      return this;
    }

    public Criteria andDistributionIdGreaterThan(BigDecimal value) {
      addCriterion("DISTRIBUTION_ID >", value, "distributionId");
      return this;
    }

    public Criteria andDistributionIdGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("DISTRIBUTION_ID >=", value, "distributionId");
      return this;
    }

    public Criteria andDistributionIdLessThan(BigDecimal value) {
      addCriterion("DISTRIBUTION_ID <", value, "distributionId");
      return this;
    }

    public Criteria andDistributionIdLessThanOrEqualTo(BigDecimal value) {
      addCriterion("DISTRIBUTION_ID <=", value, "distributionId");
      return this;
    }

    public Criteria andDistributionIdIn(List values) {
      addCriterion("DISTRIBUTION_ID in", values, "distributionId");
      return this;
    }

    public Criteria andDistributionIdNotIn(List values) {
      addCriterion("DISTRIBUTION_ID not in", values, "distributionId");
      return this;
    }

    public Criteria andDistributionIdBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("DISTRIBUTION_ID between", value1, value2, "distributionId");
      return this;
    }

    public Criteria andDistributionIdNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("DISTRIBUTION_ID not between", value1, value2, "distributionId");
      return this;
    }

    public Criteria andLogisticsOrderNoIsNull() {
      addCriterion("LOGISTICS_ORDER_NO is null");
      return this;
    }

    public Criteria andLogisticsOrderNoIsNotNull() {
      addCriterion("LOGISTICS_ORDER_NO is not null");
      return this;
    }

    public Criteria andLogisticsOrderNoEqualTo(String value) {
      addCriterion("LOGISTICS_ORDER_NO =", value, "logisticsOrderNo");
      return this;
    }

    public Criteria andLogisticsOrderNoNotEqualTo(String value) {
      addCriterion("LOGISTICS_ORDER_NO <>", value, "logisticsOrderNo");
      return this;
    }

    public Criteria andLogisticsOrderNoGreaterThan(String value) {
      addCriterion("LOGISTICS_ORDER_NO >", value, "logisticsOrderNo");
      return this;
    }

    public Criteria andLogisticsOrderNoGreaterThanOrEqualTo(String value) {
      addCriterion("LOGISTICS_ORDER_NO >=", value, "logisticsOrderNo");
      return this;
    }

    public Criteria andLogisticsOrderNoLessThan(String value) {
      addCriterion("LOGISTICS_ORDER_NO <", value, "logisticsOrderNo");
      return this;
    }

    public Criteria andLogisticsOrderNoLessThanOrEqualTo(String value) {
      addCriterion("LOGISTICS_ORDER_NO <=", value, "logisticsOrderNo");
      return this;
    }

    public Criteria andLogisticsOrderNoLike(String value) {
      addCriterion("LOGISTICS_ORDER_NO like", value, "logisticsOrderNo");
      return this;
    }

    public Criteria andLogisticsOrderNoNotLike(String value) {
      addCriterion("LOGISTICS_ORDER_NO not like", value, "logisticsOrderNo");
      return this;
    }

    public Criteria andLogisticsOrderNoIn(List values) {
      addCriterion("LOGISTICS_ORDER_NO in", values, "logisticsOrderNo");
      return this;
    }

    public Criteria andLogisticsOrderNoNotIn(List values) {
      addCriterion("LOGISTICS_ORDER_NO not in", values, "logisticsOrderNo");
      return this;
    }

    public Criteria andLogisticsOrderNoBetween(String value1, String value2) {
      addCriterion("LOGISTICS_ORDER_NO between", value1, value2, "logisticsOrderNo");
      return this;
    }

    public Criteria andLogisticsOrderNoNotBetween(String value1, String value2) {
      addCriterion("LOGISTICS_ORDER_NO not between", value1, value2, "logisticsOrderNo");
      return this;
    }

    public Criteria andCustomerLogisticsNoIsNull() {
      addCriterion("CUSTOMER_LOGISTICS_NO is null");
      return this;
    }

    public Criteria andCustomerLogisticsNoIsNotNull() {
      addCriterion("CUSTOMER_LOGISTICS_NO is not null");
      return this;
    }

    public Criteria andCustomerLogisticsNoEqualTo(String value) {
      addCriterion("CUSTOMER_LOGISTICS_NO =", value, "customerLogisticsNo");
      return this;
    }

    public Criteria andCustomerLogisticsNoNotEqualTo(String value) {
      addCriterion("CUSTOMER_LOGISTICS_NO <>", value, "customerLogisticsNo");
      return this;
    }

    public Criteria andCustomerLogisticsNoGreaterThan(String value) {
      addCriterion("CUSTOMER_LOGISTICS_NO >", value, "customerLogisticsNo");
      return this;
    }

    public Criteria andCustomerLogisticsNoGreaterThanOrEqualTo(String value) {
      addCriterion("CUSTOMER_LOGISTICS_NO >=", value, "customerLogisticsNo");
      return this;
    }

    public Criteria andCustomerLogisticsNoLessThan(String value) {
      addCriterion("CUSTOMER_LOGISTICS_NO <", value, "customerLogisticsNo");
      return this;
    }

    public Criteria andCustomerLogisticsNoLessThanOrEqualTo(String value) {
      addCriterion("CUSTOMER_LOGISTICS_NO <=", value, "customerLogisticsNo");
      return this;
    }

    public Criteria andCustomerLogisticsNoLike(String value) {
      addCriterion("CUSTOMER_LOGISTICS_NO like", value, "customerLogisticsNo");
      return this;
    }

    public Criteria andCustomerLogisticsNoNotLike(String value) {
      addCriterion("CUSTOMER_LOGISTICS_NO not like", value, "customerLogisticsNo");
      return this;
    }

    public Criteria andCustomerLogisticsNoIn(List values) {
      addCriterion("CUSTOMER_LOGISTICS_NO in", values, "customerLogisticsNo");
      return this;
    }

    public Criteria andCustomerLogisticsNoNotIn(List values) {
      addCriterion("CUSTOMER_LOGISTICS_NO not in", values, "customerLogisticsNo");
      return this;
    }

    public Criteria andCustomerLogisticsNoBetween(String value1, String value2) {
      addCriterion("CUSTOMER_LOGISTICS_NO between", value1, value2, "customerLogisticsNo");
      return this;
    }

    public Criteria andCustomerLogisticsNoNotBetween(String value1, String value2) {
      addCriterion("CUSTOMER_LOGISTICS_NO not between", value1, value2, "customerLogisticsNo");
      return this;
    }

    public Criteria andOrderItemIdIsNull() {
      addCriterion("ORDER_ITEM_ID is null");
      return this;
    }

    public Criteria andOrderItemIdIsNotNull() {
      addCriterion("ORDER_ITEM_ID is not null");
      return this;
    }

    public Criteria andOrderItemIdEqualTo(Long value) {
      addCriterion("ORDER_ITEM_ID =", value, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdNotEqualTo(Long value) {
      addCriterion("ORDER_ITEM_ID <>", value, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdGreaterThan(Long value) {
      addCriterion("ORDER_ITEM_ID >", value, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdGreaterThanOrEqualTo(Long value) {
      addCriterion("ORDER_ITEM_ID >=", value, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdLessThan(Long value) {
      addCriterion("ORDER_ITEM_ID <", value, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdLessThanOrEqualTo(Long value) {
      addCriterion("ORDER_ITEM_ID <=", value, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdIn(List values) {
      addCriterion("ORDER_ITEM_ID in", values, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdNotIn(List values) {
      addCriterion("ORDER_ITEM_ID not in", values, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdBetween(Long value1, Long value2) {
      addCriterion("ORDER_ITEM_ID between", value1, value2, "orderItemId");
      return this;
    }

    public Criteria andOrderItemIdNotBetween(Long value1, Long value2) {
      addCriterion("ORDER_ITEM_ID not between", value1, value2, "orderItemId");
      return this;
    }

    public Criteria andAlterTypeIsNull() {
      addCriterion("ALTER_TYPE is null");
      return this;
    }

    public Criteria andAlterTypeIsNotNull() {
      addCriterion("ALTER_TYPE is not null");
      return this;
    }

    public Criteria andAlterTypeEqualTo(Short value) {
      addCriterion("ALTER_TYPE =", value, "alterType");
      return this;
    }

    public Criteria andAlterTypeNotEqualTo(Short value) {
      addCriterion("ALTER_TYPE <>", value, "alterType");
      return this;
    }

    public Criteria andAlterTypeGreaterThan(Short value) {
      addCriterion("ALTER_TYPE >", value, "alterType");
      return this;
    }

    public Criteria andAlterTypeGreaterThanOrEqualTo(Short value) {
      addCriterion("ALTER_TYPE >=", value, "alterType");
      return this;
    }

    public Criteria andAlterTypeLessThan(Short value) {
      addCriterion("ALTER_TYPE <", value, "alterType");
      return this;
    }

    public Criteria andAlterTypeLessThanOrEqualTo(Short value) {
      addCriterion("ALTER_TYPE <=", value, "alterType");
      return this;
    }

    public Criteria andAlterTypeIn(List values) {
      addCriterion("ALTER_TYPE in", values, "alterType");
      return this;
    }

    public Criteria andAlterTypeNotIn(List values) {
      addCriterion("ALTER_TYPE not in", values, "alterType");
      return this;
    }

    public Criteria andAlterTypeBetween(Short value1, Short value2) {
      addCriterion("ALTER_TYPE between", value1, value2, "alterType");
      return this;
    }

    public Criteria andAlterTypeNotBetween(Short value1, Short value2) {
      addCriterion("ALTER_TYPE not between", value1, value2, "alterType");
      return this;
    }

    public Criteria andAlterNumIsNull() {
      addCriterion("ALTER_NUM is null");
      return this;
    }

    public Criteria andAlterNumIsNotNull() {
      addCriterion("ALTER_NUM is not null");
      return this;
    }

    public Criteria andAlterNumEqualTo(Long value) {
      addCriterion("ALTER_NUM =", value, "alterNum");
      return this;
    }

    public Criteria andAlterNumNotEqualTo(Long value) {
      addCriterion("ALTER_NUM <>", value, "alterNum");
      return this;
    }

    public Criteria andAlterNumGreaterThan(Long value) {
      addCriterion("ALTER_NUM >", value, "alterNum");
      return this;
    }

    public Criteria andAlterNumGreaterThanOrEqualTo(Long value) {
      addCriterion("ALTER_NUM >=", value, "alterNum");
      return this;
    }

    public Criteria andAlterNumLessThan(Long value) {
      addCriterion("ALTER_NUM <", value, "alterNum");
      return this;
    }

    public Criteria andAlterNumLessThanOrEqualTo(Long value) {
      addCriterion("ALTER_NUM <=", value, "alterNum");
      return this;
    }

    public Criteria andAlterNumIn(List values) {
      addCriterion("ALTER_NUM in", values, "alterNum");
      return this;
    }

    public Criteria andAlterNumNotIn(List values) {
      addCriterion("ALTER_NUM not in", values, "alterNum");
      return this;
    }

    public Criteria andAlterNumBetween(Long value1, Long value2) {
      addCriterion("ALTER_NUM between", value1, value2, "alterNum");
      return this;
    }

    public Criteria andAlterNumNotBetween(Long value1, Long value2) {
      addCriterion("ALTER_NUM not between", value1, value2, "alterNum");
      return this;
    }

    public Criteria andPhotoBatchNoIsNull() {
      addCriterion("PHOTO_BATCH_NO is null");
      return this;
    }

    public Criteria andPhotoBatchNoIsNotNull() {
      addCriterion("PHOTO_BATCH_NO is not null");
      return this;
    }

    public Criteria andPhotoBatchNoEqualTo(String value) {
      addCriterion("PHOTO_BATCH_NO =", value, "photoBatchNo");
      return this;
    }

    public Criteria andPhotoBatchNoNotEqualTo(String value) {
      addCriterion("PHOTO_BATCH_NO <>", value, "photoBatchNo");
      return this;
    }

    public Criteria andPhotoBatchNoGreaterThan(String value) {
      addCriterion("PHOTO_BATCH_NO >", value, "photoBatchNo");
      return this;
    }

    public Criteria andPhotoBatchNoGreaterThanOrEqualTo(String value) {
      addCriterion("PHOTO_BATCH_NO >=", value, "photoBatchNo");
      return this;
    }

    public Criteria andPhotoBatchNoLessThan(String value) {
      addCriterion("PHOTO_BATCH_NO <", value, "photoBatchNo");
      return this;
    }

    public Criteria andPhotoBatchNoLessThanOrEqualTo(String value) {
      addCriterion("PHOTO_BATCH_NO <=", value, "photoBatchNo");
      return this;
    }

    public Criteria andPhotoBatchNoLike(String value) {
      addCriterion("PHOTO_BATCH_NO like", value, "photoBatchNo");
      return this;
    }

    public Criteria andPhotoBatchNoNotLike(String value) {
      addCriterion("PHOTO_BATCH_NO not like", value, "photoBatchNo");
      return this;
    }

    public Criteria andPhotoBatchNoIn(List values) {
      addCriterion("PHOTO_BATCH_NO in", values, "photoBatchNo");
      return this;
    }

    public Criteria andPhotoBatchNoNotIn(List values) {
      addCriterion("PHOTO_BATCH_NO not in", values, "photoBatchNo");
      return this;
    }

    public Criteria andPhotoBatchNoBetween(String value1, String value2) {
      addCriterion("PHOTO_BATCH_NO between", value1, value2, "photoBatchNo");
      return this;
    }

    public Criteria andPhotoBatchNoNotBetween(String value1, String value2) {
      addCriterion("PHOTO_BATCH_NO not between", value1, value2, "photoBatchNo");
      return this;
    }

    public Criteria andEvidenceIsNull() {
      addCriterion("EVIDENCE is null");
      return this;
    }

    public Criteria andEvidenceIsNotNull() {
      addCriterion("EVIDENCE is not null");
      return this;
    }

    public Criteria andEvidenceEqualTo(Long value) {
      addCriterion("EVIDENCE =", value, "evidence");
      return this;
    }

    public Criteria andEvidenceNotEqualTo(Long value) {
      addCriterion("EVIDENCE <>", value, "evidence");
      return this;
    }

    public Criteria andEvidenceGreaterThan(Long value) {
      addCriterion("EVIDENCE >", value, "evidence");
      return this;
    }

    public Criteria andEvidenceGreaterThanOrEqualTo(Long value) {
      addCriterion("EVIDENCE >=", value, "evidence");
      return this;
    }

    public Criteria andEvidenceLessThan(Long value) {
      addCriterion("EVIDENCE <", value, "evidence");
      return this;
    }

    public Criteria andEvidenceLessThanOrEqualTo(Long value) {
      addCriterion("EVIDENCE <=", value, "evidence");
      return this;
    }

    public Criteria andEvidenceIn(List values) {
      addCriterion("EVIDENCE in", values, "evidence");
      return this;
    }

    public Criteria andEvidenceNotIn(List values) {
      addCriterion("EVIDENCE not in", values, "evidence");
      return this;
    }

    public Criteria andEvidenceBetween(Long value1, Long value2) {
      addCriterion("EVIDENCE between", value1, value2, "evidence");
      return this;
    }

    public Criteria andEvidenceNotBetween(Long value1, Long value2) {
      addCriterion("EVIDENCE not between", value1, value2, "evidence");
      return this;
    }

    public Criteria andLogisticsCodeIsNull() {
      addCriterion("LOGISTICS_CODE is null");
      return this;
    }

    public Criteria andLogisticsCodeIsNotNull() {
      addCriterion("LOGISTICS_CODE is not null");
      return this;
    }

    public Criteria andLogisticsCodeEqualTo(String value) {
      addCriterion("LOGISTICS_CODE =", value, "logisticsCode");
      return this;
    }

    public Criteria andLogisticsCodeNotEqualTo(String value) {
      addCriterion("LOGISTICS_CODE <>", value, "logisticsCode");
      return this;
    }

    public Criteria andLogisticsCodeGreaterThan(String value) {
      addCriterion("LOGISTICS_CODE >", value, "logisticsCode");
      return this;
    }

    public Criteria andLogisticsCodeGreaterThanOrEqualTo(String value) {
      addCriterion("LOGISTICS_CODE >=", value, "logisticsCode");
      return this;
    }

    public Criteria andLogisticsCodeLessThan(String value) {
      addCriterion("LOGISTICS_CODE <", value, "logisticsCode");
      return this;
    }

    public Criteria andLogisticsCodeLessThanOrEqualTo(String value) {
      addCriterion("LOGISTICS_CODE <=", value, "logisticsCode");
      return this;
    }

    public Criteria andLogisticsCodeLike(String value) {
      addCriterion("LOGISTICS_CODE like", value, "logisticsCode");
      return this;
    }

    public Criteria andLogisticsCodeNotLike(String value) {
      addCriterion("LOGISTICS_CODE not like", value, "logisticsCode");
      return this;
    }

    public Criteria andLogisticsCodeIn(List values) {
      addCriterion("LOGISTICS_CODE in", values, "logisticsCode");
      return this;
    }

    public Criteria andLogisticsCodeNotIn(List values) {
      addCriterion("LOGISTICS_CODE not in", values, "logisticsCode");
      return this;
    }

    public Criteria andLogisticsCodeBetween(String value1, String value2) {
      addCriterion("LOGISTICS_CODE between", value1, value2, "logisticsCode");
      return this;
    }

    public Criteria andLogisticsCodeNotBetween(String value1, String value2) {
      addCriterion("LOGISTICS_CODE not between", value1, value2, "logisticsCode");
      return this;
    }

    public Criteria andAddressIdIsNull() {
      addCriterion("ADDRESS_ID is null");
      return this;
    }

    public Criteria andAddressIdIsNotNull() {
      addCriterion("ADDRESS_ID is not null");
      return this;
    }

    public Criteria andAddressIdEqualTo(BigDecimal value) {
      addCriterion("ADDRESS_ID =", value, "addressId");
      return this;
    }

    public Criteria andAddressIdNotEqualTo(BigDecimal value) {
      addCriterion("ADDRESS_ID <>", value, "addressId");
      return this;
    }

    public Criteria andAddressIdGreaterThan(BigDecimal value) {
      addCriterion("ADDRESS_ID >", value, "addressId");
      return this;
    }

    public Criteria andAddressIdGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("ADDRESS_ID >=", value, "addressId");
      return this;
    }

    public Criteria andAddressIdLessThan(BigDecimal value) {
      addCriterion("ADDRESS_ID <", value, "addressId");
      return this;
    }

    public Criteria andAddressIdLessThanOrEqualTo(BigDecimal value) {
      addCriterion("ADDRESS_ID <=", value, "addressId");
      return this;
    }

    public Criteria andAddressIdIn(List values) {
      addCriterion("ADDRESS_ID in", values, "addressId");
      return this;
    }

    public Criteria andAddressIdNotIn(List values) {
      addCriterion("ADDRESS_ID not in", values, "addressId");
      return this;
    }

    public Criteria andAddressIdBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("ADDRESS_ID between", value1, value2, "addressId");
      return this;
    }

    public Criteria andAddressIdNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("ADDRESS_ID not between", value1, value2, "addressId");
      return this;
    }

    public Criteria andEmailIsNull() {
      addCriterion("EMAIL is null");
      return this;
    }

    public Criteria andEmailIsNotNull() {
      addCriterion("EMAIL is not null");
      return this;
    }

    public Criteria andEmailEqualTo(String value) {
      addCriterion("EMAIL =", value, "email");
      return this;
    }

    public Criteria andEmailNotEqualTo(String value) {
      addCriterion("EMAIL <>", value, "email");
      return this;
    }

    public Criteria andEmailGreaterThan(String value) {
      addCriterion("EMAIL >", value, "email");
      return this;
    }

    public Criteria andEmailGreaterThanOrEqualTo(String value) {
      addCriterion("EMAIL >=", value, "email");
      return this;
    }

    public Criteria andEmailLessThan(String value) {
      addCriterion("EMAIL <", value, "email");
      return this;
    }

    public Criteria andEmailLessThanOrEqualTo(String value) {
      addCriterion("EMAIL <=", value, "email");
      return this;
    }

    public Criteria andEmailLike(String value) {
      addCriterion("EMAIL like", value, "email");
      return this;
    }

    public Criteria andEmailNotLike(String value) {
      addCriterion("EMAIL not like", value, "email");
      return this;
    }

    public Criteria andEmailIn(List values) {
      addCriterion("EMAIL in", values, "email");
      return this;
    }

    public Criteria andEmailNotIn(List values) {
      addCriterion("EMAIL not in", values, "email");
      return this;
    }

    public Criteria andEmailBetween(String value1, String value2) {
      addCriterion("EMAIL between", value1, value2, "email");
      return this;
    }

    public Criteria andEmailNotBetween(String value1, String value2) {
      addCriterion("EMAIL not between", value1, value2, "email");
      return this;
    }

    public Criteria andDiscountAmountIsNull() {
      addCriterion("DISCOUNT_AMOUNT is null");
      return this;
    }

    public Criteria andDiscountAmountIsNotNull() {
      addCriterion("DISCOUNT_AMOUNT is not null");
      return this;
    }

    public Criteria andDiscountAmountEqualTo(BigDecimal value) {
      addCriterion("DISCOUNT_AMOUNT =", value, "discountAmount");
      return this;
    }

    public Criteria andDiscountAmountNotEqualTo(BigDecimal value) {
      addCriterion("DISCOUNT_AMOUNT <>", value, "discountAmount");
      return this;
    }

    public Criteria andDiscountAmountGreaterThan(BigDecimal value) {
      addCriterion("DISCOUNT_AMOUNT >", value, "discountAmount");
      return this;
    }

    public Criteria andDiscountAmountGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("DISCOUNT_AMOUNT >=", value, "discountAmount");
      return this;
    }

    public Criteria andDiscountAmountLessThan(BigDecimal value) {
      addCriterion("DISCOUNT_AMOUNT <", value, "discountAmount");
      return this;
    }

    public Criteria andDiscountAmountLessThanOrEqualTo(BigDecimal value) {
      addCriterion("DISCOUNT_AMOUNT <=", value, "discountAmount");
      return this;
    }

    public Criteria andDiscountAmountIn(List values) {
      addCriterion("DISCOUNT_AMOUNT in", values, "discountAmount");
      return this;
    }

    public Criteria andDiscountAmountNotIn(List values) {
      addCriterion("DISCOUNT_AMOUNT not in", values, "discountAmount");
      return this;
    }

    public Criteria andDiscountAmountBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("DISCOUNT_AMOUNT between", value1, value2, "discountAmount");
      return this;
    }

    public Criteria andDiscountAmountNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("DISCOUNT_AMOUNT not between", value1, value2, "discountAmount");
      return this;
    }

    public Criteria andFareAdditionalIsNull() {
      addCriterion("FARE_ADDITIONAL is null");
      return this;
    }

    public Criteria andFareAdditionalIsNotNull() {
      addCriterion("FARE_ADDITIONAL is not null");
      return this;
    }

    public Criteria andFareAdditionalEqualTo(Short value) {
      addCriterion("FARE_ADDITIONAL =", value, "fareAdditional");
      return this;
    }

    public Criteria andFareAdditionalNotEqualTo(Short value) {
      addCriterion("FARE_ADDITIONAL <>", value, "fareAdditional");
      return this;
    }

    public Criteria andFareAdditionalGreaterThan(Short value) {
      addCriterion("FARE_ADDITIONAL >", value, "fareAdditional");
      return this;
    }

    public Criteria andFareAdditionalGreaterThanOrEqualTo(Short value) {
      addCriterion("FARE_ADDITIONAL >=", value, "fareAdditional");
      return this;
    }

    public Criteria andFareAdditionalLessThan(Short value) {
      addCriterion("FARE_ADDITIONAL <", value, "fareAdditional");
      return this;
    }

    public Criteria andFareAdditionalLessThanOrEqualTo(Short value) {
      addCriterion("FARE_ADDITIONAL <=", value, "fareAdditional");
      return this;
    }

    public Criteria andFareAdditionalIn(List values) {
      addCriterion("FARE_ADDITIONAL in", values, "fareAdditional");
      return this;
    }

    public Criteria andFareAdditionalNotIn(List values) {
      addCriterion("FARE_ADDITIONAL not in", values, "fareAdditional");
      return this;
    }

    public Criteria andFareAdditionalBetween(Short value1, Short value2) {
      addCriterion("FARE_ADDITIONAL between", value1, value2, "fareAdditional");
      return this;
    }

    public Criteria andFareAdditionalNotBetween(Short value1, Short value2) {
      addCriterion("FARE_ADDITIONAL not between", value1, value2, "fareAdditional");
      return this;
    }

    public Criteria andPreferentialAmountIsNull() {
      addCriterion("PREFERENTIAL_AMOUNT is null");
      return this;
    }

    public Criteria andPreferentialAmountIsNotNull() {
      addCriterion("PREFERENTIAL_AMOUNT is not null");
      return this;
    }

    public Criteria andPreferentialAmountEqualTo(BigDecimal value) {
      addCriterion("PREFERENTIAL_AMOUNT =", value, "preferentialAmount");
      return this;
    }

    public Criteria andPreferentialAmountNotEqualTo(BigDecimal value) {
      addCriterion("PREFERENTIAL_AMOUNT <>", value, "preferentialAmount");
      return this;
    }

    public Criteria andPreferentialAmountGreaterThan(BigDecimal value) {
      addCriterion("PREFERENTIAL_AMOUNT >", value, "preferentialAmount");
      return this;
    }

    public Criteria andPreferentialAmountGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("PREFERENTIAL_AMOUNT >=", value, "preferentialAmount");
      return this;
    }

    public Criteria andPreferentialAmountLessThan(BigDecimal value) {
      addCriterion("PREFERENTIAL_AMOUNT <", value, "preferentialAmount");
      return this;
    }

    public Criteria andPreferentialAmountLessThanOrEqualTo(BigDecimal value) {
      addCriterion("PREFERENTIAL_AMOUNT <=", value, "preferentialAmount");
      return this;
    }

    public Criteria andPreferentialAmountIn(List values) {
      addCriterion("PREFERENTIAL_AMOUNT in", values, "preferentialAmount");
      return this;
    }

    public Criteria andPreferentialAmountNotIn(List values) {
      addCriterion("PREFERENTIAL_AMOUNT not in", values, "preferentialAmount");
      return this;
    }

    public Criteria andPreferentialAmountBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PREFERENTIAL_AMOUNT between", value1, value2, "preferentialAmount");
      return this;
    }

    public Criteria andPreferentialAmountNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("PREFERENTIAL_AMOUNT not between", value1, value2, "preferentialAmount");
      return this;
    }

    public Criteria andCustomerLogisticsCodeIsNull() {
      addCriterion("CUSTOMER_LOGISTICS_CODE is null");
      return this;
    }

    public Criteria andCustomerLogisticsCodeIsNotNull() {
      addCriterion("CUSTOMER_LOGISTICS_CODE is not null");
      return this;
    }

    public Criteria andCustomerLogisticsCodeEqualTo(String value) {
      addCriterion("CUSTOMER_LOGISTICS_CODE =", value, "customerLogisticsCode");
      return this;
    }

    public Criteria andCustomerLogisticsCodeNotEqualTo(String value) {
      addCriterion("CUSTOMER_LOGISTICS_CODE <>", value, "customerLogisticsCode");
      return this;
    }

    public Criteria andCustomerLogisticsCodeGreaterThan(String value) {
      addCriterion("CUSTOMER_LOGISTICS_CODE >", value, "customerLogisticsCode");
      return this;
    }

    public Criteria andCustomerLogisticsCodeGreaterThanOrEqualTo(String value) {
      addCriterion("CUSTOMER_LOGISTICS_CODE >=", value, "customerLogisticsCode");
      return this;
    }

    public Criteria andCustomerLogisticsCodeLessThan(String value) {
      addCriterion("CUSTOMER_LOGISTICS_CODE <", value, "customerLogisticsCode");
      return this;
    }

    public Criteria andCustomerLogisticsCodeLessThanOrEqualTo(String value) {
      addCriterion("CUSTOMER_LOGISTICS_CODE <=", value, "customerLogisticsCode");
      return this;
    }

    public Criteria andCustomerLogisticsCodeLike(String value) {
      addCriterion("CUSTOMER_LOGISTICS_CODE like", value, "customerLogisticsCode");
      return this;
    }

    public Criteria andCustomerLogisticsCodeNotLike(String value) {
      addCriterion("CUSTOMER_LOGISTICS_CODE not like", value, "customerLogisticsCode");
      return this;
    }

    public Criteria andCustomerLogisticsCodeIn(List values) {
      addCriterion("CUSTOMER_LOGISTICS_CODE in", values, "customerLogisticsCode");
      return this;
    }

    public Criteria andCustomerLogisticsCodeNotIn(List values) {
      addCriterion("CUSTOMER_LOGISTICS_CODE not in", values, "customerLogisticsCode");
      return this;
    }

    public Criteria andCustomerLogisticsCodeBetween(String value1, String value2) {
      addCriterion("CUSTOMER_LOGISTICS_CODE between", value1, value2, "customerLogisticsCode");
      return this;
    }

    public Criteria andCustomerLogisticsCodeNotBetween(String value1, String value2) {
      addCriterion("CUSTOMER_LOGISTICS_CODE not between", value1, value2, "customerLogisticsCode");
      return this;
    }

    public Criteria andAuditCommentIsNull() {
      addCriterion("AUDIT_COMMENT is null");
      return this;
    }

    public Criteria andAuditCommentIsNotNull() {
      addCriterion("AUDIT_COMMENT is not null");
      return this;
    }

    public Criteria andAuditCommentEqualTo(String value) {
      addCriterion("AUDIT_COMMENT =", value, "auditComment");
      return this;
    }

    public Criteria andAuditCommentNotEqualTo(String value) {
      addCriterion("AUDIT_COMMENT <>", value, "auditComment");
      return this;
    }

    public Criteria andAuditCommentGreaterThan(String value) {
      addCriterion("AUDIT_COMMENT >", value, "auditComment");
      return this;
    }

    public Criteria andAuditCommentGreaterThanOrEqualTo(String value) {
      addCriterion("AUDIT_COMMENT >=", value, "auditComment");
      return this;
    }

    public Criteria andAuditCommentLessThan(String value) {
      addCriterion("AUDIT_COMMENT <", value, "auditComment");
      return this;
    }

    public Criteria andAuditCommentLessThanOrEqualTo(String value) {
      addCriterion("AUDIT_COMMENT <=", value, "auditComment");
      return this;
    }

    public Criteria andAuditCommentLike(String value) {
      addCriterion("AUDIT_COMMENT like", value, "auditComment");
      return this;
    }

    public Criteria andAuditCommentNotLike(String value) {
      addCriterion("AUDIT_COMMENT not like", value, "auditComment");
      return this;
    }

    public Criteria andAuditCommentIn(List values) {
      addCriterion("AUDIT_COMMENT in", values, "auditComment");
      return this;
    }

    public Criteria andAuditCommentNotIn(List values) {
      addCriterion("AUDIT_COMMENT not in", values, "auditComment");
      return this;
    }

    public Criteria andAuditCommentBetween(String value1, String value2) {
      addCriterion("AUDIT_COMMENT between", value1, value2, "auditComment");
      return this;
    }

    public Criteria andAuditCommentNotBetween(String value1, String value2) {
      addCriterion("AUDIT_COMMENT not between", value1, value2, "auditComment");
      return this;
    }

    public Criteria andQualityCommentIsNull() {
      addCriterion("QUALITY_COMMENT is null");
      return this;
    }

    public Criteria andQualityCommentIsNotNull() {
      addCriterion("QUALITY_COMMENT is not null");
      return this;
    }

    public Criteria andQualityCommentEqualTo(String value) {
      addCriterion("QUALITY_COMMENT =", value, "qualityComment");
      return this;
    }

    public Criteria andQualityCommentNotEqualTo(String value) {
      addCriterion("QUALITY_COMMENT <>", value, "qualityComment");
      return this;
    }

    public Criteria andQualityCommentGreaterThan(String value) {
      addCriterion("QUALITY_COMMENT >", value, "qualityComment");
      return this;
    }

    public Criteria andQualityCommentGreaterThanOrEqualTo(String value) {
      addCriterion("QUALITY_COMMENT >=", value, "qualityComment");
      return this;
    }

    public Criteria andQualityCommentLessThan(String value) {
      addCriterion("QUALITY_COMMENT <", value, "qualityComment");
      return this;
    }

    public Criteria andQualityCommentLessThanOrEqualTo(String value) {
      addCriterion("QUALITY_COMMENT <=", value, "qualityComment");
      return this;
    }

    public Criteria andQualityCommentLike(String value) {
      addCriterion("QUALITY_COMMENT like", value, "qualityComment");
      return this;
    }

    public Criteria andQualityCommentNotLike(String value) {
      addCriterion("QUALITY_COMMENT not like", value, "qualityComment");
      return this;
    }

    public Criteria andQualityCommentIn(List values) {
      addCriterion("QUALITY_COMMENT in", values, "qualityComment");
      return this;
    }

    public Criteria andQualityCommentNotIn(List values) {
      addCriterion("QUALITY_COMMENT not in", values, "qualityComment");
      return this;
    }

    public Criteria andQualityCommentBetween(String value1, String value2) {
      addCriterion("QUALITY_COMMENT between", value1, value2, "qualityComment");
      return this;
    }

    public Criteria andQualityCommentNotBetween(String value1, String value2) {
      addCriterion("QUALITY_COMMENT not between", value1, value2, "qualityComment");
      return this;
    }

    public Criteria andCustomerLogisticsNameIsNull() {
      addCriterion("CUSTOMER_LOGISTICS_NAME is null");
      return this;
    }

    public Criteria andCustomerLogisticsNameIsNotNull() {
      addCriterion("CUSTOMER_LOGISTICS_NAME is not null");
      return this;
    }

    public Criteria andCustomerLogisticsNameEqualTo(String value) {
      addCriterion("CUSTOMER_LOGISTICS_NAME =", value, "customerLogisticsName");
      return this;
    }

    public Criteria andCustomerLogisticsNameNotEqualTo(String value) {
      addCriterion("CUSTOMER_LOGISTICS_NAME <>", value, "customerLogisticsName");
      return this;
    }

    public Criteria andCustomerLogisticsNameGreaterThan(String value) {
      addCriterion("CUSTOMER_LOGISTICS_NAME >", value, "customerLogisticsName");
      return this;
    }

    public Criteria andCustomerLogisticsNameGreaterThanOrEqualTo(String value) {
      addCriterion("CUSTOMER_LOGISTICS_NAME >=", value, "customerLogisticsName");
      return this;
    }

    public Criteria andCustomerLogisticsNameLessThan(String value) {
      addCriterion("CUSTOMER_LOGISTICS_NAME <", value, "customerLogisticsName");
      return this;
    }

    public Criteria andCustomerLogisticsNameLessThanOrEqualTo(String value) {
      addCriterion("CUSTOMER_LOGISTICS_NAME <=", value, "customerLogisticsName");
      return this;
    }

    public Criteria andCustomerLogisticsNameLike(String value) {
      addCriterion("CUSTOMER_LOGISTICS_NAME like", value, "customerLogisticsName");
      return this;
    }

    public Criteria andCustomerLogisticsNameNotLike(String value) {
      addCriterion("CUSTOMER_LOGISTICS_NAME not like", value, "customerLogisticsName");
      return this;
    }

    public Criteria andCustomerLogisticsNameIn(List values) {
      addCriterion("CUSTOMER_LOGISTICS_NAME in", values, "customerLogisticsName");
      return this;
    }

    public Criteria andCustomerLogisticsNameNotIn(List values) {
      addCriterion("CUSTOMER_LOGISTICS_NAME not in", values, "customerLogisticsName");
      return this;
    }

    public Criteria andCustomerLogisticsNameBetween(String value1, String value2) {
      addCriterion("CUSTOMER_LOGISTICS_NAME between", value1, value2, "customerLogisticsName");
      return this;
    }

    public Criteria andCustomerLogisticsNameNotBetween(String value1, String value2) {
      addCriterion("CUSTOMER_LOGISTICS_NAME not between", value1, value2, "customerLogisticsName");
      return this;
    }

    public Criteria andLogisticsNameIsNull() {
      addCriterion("LOGISTICS_NAME is null");
      return this;
    }

    public Criteria andLogisticsNameIsNotNull() {
      addCriterion("LOGISTICS_NAME is not null");
      return this;
    }

    public Criteria andLogisticsNameEqualTo(String value) {
      addCriterion("LOGISTICS_NAME =", value, "logisticsName");
      return this;
    }

    public Criteria andLogisticsNameNotEqualTo(String value) {
      addCriterion("LOGISTICS_NAME <>", value, "logisticsName");
      return this;
    }

    public Criteria andLogisticsNameGreaterThan(String value) {
      addCriterion("LOGISTICS_NAME >", value, "logisticsName");
      return this;
    }

    public Criteria andLogisticsNameGreaterThanOrEqualTo(String value) {
      addCriterion("LOGISTICS_NAME >=", value, "logisticsName");
      return this;
    }

    public Criteria andLogisticsNameLessThan(String value) {
      addCriterion("LOGISTICS_NAME <", value, "logisticsName");
      return this;
    }

    public Criteria andLogisticsNameLessThanOrEqualTo(String value) {
      addCriterion("LOGISTICS_NAME <=", value, "logisticsName");
      return this;
    }

    public Criteria andLogisticsNameLike(String value) {
      addCriterion("LOGISTICS_NAME like", value, "logisticsName");
      return this;
    }

    public Criteria andLogisticsNameNotLike(String value) {
      addCriterion("LOGISTICS_NAME not like", value, "logisticsName");
      return this;
    }

    public Criteria andLogisticsNameIn(List values) {
      addCriterion("LOGISTICS_NAME in", values, "logisticsName");
      return this;
    }

    public Criteria andLogisticsNameNotIn(List values) {
      addCriterion("LOGISTICS_NAME not in", values, "logisticsName");
      return this;
    }

    public Criteria andLogisticsNameBetween(String value1, String value2) {
      addCriterion("LOGISTICS_NAME between", value1, value2, "logisticsName");
      return this;
    }

    public Criteria andLogisticsNameNotBetween(String value1, String value2) {
      addCriterion("LOGISTICS_NAME not between", value1, value2, "logisticsName");
      return this;
    }

    public Criteria andProvinceIsNull() {
      addCriterion("PROVINCE is null");
      return this;
    }

    public Criteria andProvinceIsNotNull() {
      addCriterion("PROVINCE is not null");
      return this;
    }

    public Criteria andProvinceEqualTo(String value) {
      addCriterion("PROVINCE =", value, "province");
      return this;
    }

    public Criteria andProvinceNotEqualTo(String value) {
      addCriterion("PROVINCE <>", value, "province");
      return this;
    }

    public Criteria andProvinceGreaterThan(String value) {
      addCriterion("PROVINCE >", value, "province");
      return this;
    }

    public Criteria andProvinceGreaterThanOrEqualTo(String value) {
      addCriterion("PROVINCE >=", value, "province");
      return this;
    }

    public Criteria andProvinceLessThan(String value) {
      addCriterion("PROVINCE <", value, "province");
      return this;
    }

    public Criteria andProvinceLessThanOrEqualTo(String value) {
      addCriterion("PROVINCE <=", value, "province");
      return this;
    }

    public Criteria andProvinceLike(String value) {
      addCriterion("PROVINCE like", value, "province");
      return this;
    }

    public Criteria andProvinceNotLike(String value) {
      addCriterion("PROVINCE not like", value, "province");
      return this;
    }

    public Criteria andProvinceIn(List values) {
      addCriterion("PROVINCE in", values, "province");
      return this;
    }

    public Criteria andProvinceNotIn(List values) {
      addCriterion("PROVINCE not in", values, "province");
      return this;
    }

    public Criteria andProvinceBetween(String value1, String value2) {
      addCriterion("PROVINCE between", value1, value2, "province");
      return this;
    }

    public Criteria andProvinceNotBetween(String value1, String value2) {
      addCriterion("PROVINCE not between", value1, value2, "province");
      return this;
    }

    public Criteria andCityIsNull() {
      addCriterion("CITY is null");
      return this;
    }

    public Criteria andCityIsNotNull() {
      addCriterion("CITY is not null");
      return this;
    }

    public Criteria andCityEqualTo(String value) {
      addCriterion("CITY =", value, "city");
      return this;
    }

    public Criteria andCityNotEqualTo(String value) {
      addCriterion("CITY <>", value, "city");
      return this;
    }

    public Criteria andCityGreaterThan(String value) {
      addCriterion("CITY >", value, "city");
      return this;
    }

    public Criteria andCityGreaterThanOrEqualTo(String value) {
      addCriterion("CITY >=", value, "city");
      return this;
    }

    public Criteria andCityLessThan(String value) {
      addCriterion("CITY <", value, "city");
      return this;
    }

    public Criteria andCityLessThanOrEqualTo(String value) {
      addCriterion("CITY <=", value, "city");
      return this;
    }

    public Criteria andCityLike(String value) {
      addCriterion("CITY like", value, "city");
      return this;
    }

    public Criteria andCityNotLike(String value) {
      addCriterion("CITY not like", value, "city");
      return this;
    }

    public Criteria andCityIn(List values) {
      addCriterion("CITY in", values, "city");
      return this;
    }

    public Criteria andCityNotIn(List values) {
      addCriterion("CITY not in", values, "city");
      return this;
    }

    public Criteria andCityBetween(String value1, String value2) {
      addCriterion("CITY between", value1, value2, "city");
      return this;
    }

    public Criteria andCityNotBetween(String value1, String value2) {
      addCriterion("CITY not between", value1, value2, "city");
      return this;
    }

    public Criteria andAreaIsNull() {
      addCriterion("AREA is null");
      return this;
    }

    public Criteria andAreaIsNotNull() {
      addCriterion("AREA is not null");
      return this;
    }

    public Criteria andAreaEqualTo(String value) {
      addCriterion("AREA =", value, "area");
      return this;
    }

    public Criteria andAreaNotEqualTo(String value) {
      addCriterion("AREA <>", value, "area");
      return this;
    }

    public Criteria andAreaGreaterThan(String value) {
      addCriterion("AREA >", value, "area");
      return this;
    }

    public Criteria andAreaGreaterThanOrEqualTo(String value) {
      addCriterion("AREA >=", value, "area");
      return this;
    }

    public Criteria andAreaLessThan(String value) {
      addCriterion("AREA <", value, "area");
      return this;
    }

    public Criteria andAreaLessThanOrEqualTo(String value) {
      addCriterion("AREA <=", value, "area");
      return this;
    }

    public Criteria andAreaLike(String value) {
      addCriterion("AREA like", value, "area");
      return this;
    }

    public Criteria andAreaNotLike(String value) {
      addCriterion("AREA not like", value, "area");
      return this;
    }

    public Criteria andAreaIn(List values) {
      addCriterion("AREA in", values, "area");
      return this;
    }

    public Criteria andAreaNotIn(List values) {
      addCriterion("AREA not in", values, "area");
      return this;
    }

    public Criteria andAreaBetween(String value1, String value2) {
      addCriterion("AREA between", value1, value2, "area");
      return this;
    }

    public Criteria andAreaNotBetween(String value1, String value2) {
      addCriterion("AREA not between", value1, value2, "area");
      return this;
    }

    public Criteria andZipcodeIsNull() {
      addCriterion("ZIPCODE is null");
      return this;
    }

    public Criteria andZipcodeIsNotNull() {
      addCriterion("ZIPCODE is not null");
      return this;
    }

    public Criteria andZipcodeEqualTo(Integer value) {
      addCriterion("ZIPCODE =", value, "zipcode");
      return this;
    }

    public Criteria andZipcodeNotEqualTo(Integer value) {
      addCriterion("ZIPCODE <>", value, "zipcode");
      return this;
    }

    public Criteria andZipcodeGreaterThan(Integer value) {
      addCriterion("ZIPCODE >", value, "zipcode");
      return this;
    }

    public Criteria andZipcodeGreaterThanOrEqualTo(Integer value) {
      addCriterion("ZIPCODE >=", value, "zipcode");
      return this;
    }

    public Criteria andZipcodeLessThan(Integer value) {
      addCriterion("ZIPCODE <", value, "zipcode");
      return this;
    }

    public Criteria andZipcodeLessThanOrEqualTo(Integer value) {
      addCriterion("ZIPCODE <=", value, "zipcode");
      return this;
    }

    public Criteria andZipcodeIn(List values) {
      addCriterion("ZIPCODE in", values, "zipcode");
      return this;
    }

    public Criteria andZipcodeNotIn(List values) {
      addCriterion("ZIPCODE not in", values, "zipcode");
      return this;
    }

    public Criteria andZipcodeBetween(Integer value1, Integer value2) {
      addCriterion("ZIPCODE between", value1, value2, "zipcode");
      return this;
    }

    public Criteria andZipcodeNotBetween(Integer value1, Integer value2) {
      addCriterion("ZIPCODE not between", value1, value2, "zipcode");
      return this;
    }

    public Criteria andCommodityBatchNumberIsNull() {
      addCriterion("COMMODITY_BATCH_NUMBER is null");
      return this;
    }

    public Criteria andCommodityBatchNumberIsNotNull() {
      addCriterion("COMMODITY_BATCH_NUMBER is not null");
      return this;
    }

    public Criteria andCommodityBatchNumberEqualTo(String value) {
      addCriterion("COMMODITY_BATCH_NUMBER =", value, "commodityBatchNumber");
      return this;
    }

    public Criteria andCommodityBatchNumberNotEqualTo(String value) {
      addCriterion("COMMODITY_BATCH_NUMBER <>", value, "commodityBatchNumber");
      return this;
    }

    public Criteria andCommodityBatchNumberGreaterThan(String value) {
      addCriterion("COMMODITY_BATCH_NUMBER >", value, "commodityBatchNumber");
      return this;
    }

    public Criteria andCommodityBatchNumberGreaterThanOrEqualTo(String value) {
      addCriterion("COMMODITY_BATCH_NUMBER >=", value, "commodityBatchNumber");
      return this;
    }

    public Criteria andCommodityBatchNumberLessThan(String value) {
      addCriterion("COMMODITY_BATCH_NUMBER <", value, "commodityBatchNumber");
      return this;
    }

    public Criteria andCommodityBatchNumberLessThanOrEqualTo(String value) {
      addCriterion("COMMODITY_BATCH_NUMBER <=", value, "commodityBatchNumber");
      return this;
    }

    public Criteria andCommodityBatchNumberLike(String value) {
      addCriterion("COMMODITY_BATCH_NUMBER like", value, "commodityBatchNumber");
      return this;
    }

    public Criteria andCommodityBatchNumberNotLike(String value) {
      addCriterion("COMMODITY_BATCH_NUMBER not like", value, "commodityBatchNumber");
      return this;
    }

    public Criteria andCommodityBatchNumberIn(List values) {
      addCriterion("COMMODITY_BATCH_NUMBER in", values, "commodityBatchNumber");
      return this;
    }

    public Criteria andCommodityBatchNumberNotIn(List values) {
      addCriterion("COMMODITY_BATCH_NUMBER not in", values, "commodityBatchNumber");
      return this;
    }

    public Criteria andCommodityBatchNumberBetween(String value1, String value2) {
      addCriterion("COMMODITY_BATCH_NUMBER between", value1, value2, "commodityBatchNumber");
      return this;
    }

    public Criteria andCommodityBatchNumberNotBetween(String value1, String value2) {
      addCriterion("COMMODITY_BATCH_NUMBER not between", value1, value2, "commodityBatchNumber");
      return this;
    }

    public Criteria andAlterBatchNumberIsNull() {
      addCriterion("ALTER_BATCH_NUMBER is null");
      return this;
    }

    public Criteria andAlterBatchNumberIsNotNull() {
      addCriterion("ALTER_BATCH_NUMBER is not null");
      return this;
    }

    public Criteria andAlterBatchNumberEqualTo(String value) {
      addCriterion("ALTER_BATCH_NUMBER =", value, "alterBatchNumber");
      return this;
    }

    public Criteria andAlterBatchNumberNotEqualTo(String value) {
      addCriterion("ALTER_BATCH_NUMBER <>", value, "alterBatchNumber");
      return this;
    }

    public Criteria andAlterBatchNumberGreaterThan(String value) {
      addCriterion("ALTER_BATCH_NUMBER >", value, "alterBatchNumber");
      return this;
    }

    public Criteria andAlterBatchNumberGreaterThanOrEqualTo(String value) {
      addCriterion("ALTER_BATCH_NUMBER >=", value, "alterBatchNumber");
      return this;
    }

    public Criteria andAlterBatchNumberLessThan(String value) {
      addCriterion("ALTER_BATCH_NUMBER <", value, "alterBatchNumber");
      return this;
    }

    public Criteria andAlterBatchNumberLessThanOrEqualTo(String value) {
      addCriterion("ALTER_BATCH_NUMBER <=", value, "alterBatchNumber");
      return this;
    }

    public Criteria andAlterBatchNumberLike(String value) {
      addCriterion("ALTER_BATCH_NUMBER like", value, "alterBatchNumber");
      return this;
    }

    public Criteria andAlterBatchNumberNotLike(String value) {
      addCriterion("ALTER_BATCH_NUMBER not like", value, "alterBatchNumber");
      return this;
    }

    public Criteria andAlterBatchNumberIn(List values) {
      addCriterion("ALTER_BATCH_NUMBER in", values, "alterBatchNumber");
      return this;
    }

    public Criteria andAlterBatchNumberNotIn(List values) {
      addCriterion("ALTER_BATCH_NUMBER not in", values, "alterBatchNumber");
      return this;
    }

    public Criteria andAlterBatchNumberBetween(String value1, String value2) {
      addCriterion("ALTER_BATCH_NUMBER between", value1, value2, "alterBatchNumber");
      return this;
    }

    public Criteria andAlterBatchNumberNotBetween(String value1, String value2) {
      addCriterion("ALTER_BATCH_NUMBER not between", value1, value2, "alterBatchNumber");
      return this;
    }
  }
}
